### ISSUE TITLE
TypeError: 'ellipsis' object is not iterable

### ISSUE THREAD

**Issue by calfcamel** [ethereum/web3.py#1012]
* Version: 4.5.0
* Python: 3.5
* OS: linux

### What was wrong?

```
$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from web3 import HTTPProvider, Web3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/EotAccounts/env/lib/python3.5/site-packages/web3/__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "/home/ubuntu/EotAccounts/env/lib/python3.5/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/home/ubuntu/EotAccounts/env/lib/python3.5/site-packages/eth_account/account.py", line 10, in <module>
    from eth_keyfile import (
  File "/home/ubuntu/EotAccounts/env/lib/python3.5/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/home/ubuntu/EotAccounts/env/lib/python3.5/site-packages/eth_keyfile/keyfile.py", line 10, in <module>
    from eth_keys import keys
  File "/home/ubuntu/EotAccounts/env/lib/python3.5/site-packages/eth_keys/__init__.py", line 15, in <module>
    from .main import (  # noqa: F401
  File "/home/ubuntu/EotAccounts/env/lib/python3.5/site-packages/eth_keys/main.py", line 3, in <module>
    from eth_keys.datatypes import (
  File "/home/ubuntu/EotAccounts/env/lib/python3.5/site-packages/eth_keys/datatypes.py", line 8, in <module>
    from eth_utils import (
  File "/home/ubuntu/EotAccounts/env/lib/python3.5/site-packages/eth_utils/__init__.py", line 24, in <module>
    from .applicators import (  # noqa: F401
  File "/home/ubuntu/EotAccounts/env/lib/python3.5/site-packages/eth_utils/applicators.py", line 43, in <module>
    def combine_argument_formatters(*formatters: List[Callable[..., Any]]) -> Formatters:
  File "/usr/lib/python3.5/typing.py", line 1025, in __getitem__
    tvars = _type_vars(params)
  File "/usr/lib/python3.5/typing.py", line 284, in _type_vars
    _get_type_vars(types, tvars)
  File "/usr/lib/python3.5/typing.py", line 279, in _get_type_vars
    t._get_type_vars(tvars)
  File "/usr/lib/python3.5/typing.py", line 786, in _get_type_vars
    _get_type_vars(self.__args__, tvars)
  File "/usr/lib/python3.5/typing.py", line 277, in _get_type_vars
    for t in types:
TypeError: 'ellipsis' object is not iterable
```

**Comment by carver** [comment]
https://github.com/python/typing/issues/259 implies that you need to upgrade the python version to `3.5.3`+

Leaving this open, because maybe we should have a check/constraint in eth-utils that complains on 3.5.2 (it looks like this bug is *only* in 3.5.2, not in 3.5.1).

**Comment by pipermerriam** [comment]
https://github.com/ethereum/eth-utils/issues/125
