### ISSUE TITLE
Can't deploy contract with PyEVM

### ISSUE THREAD

**Issue by paymog** [ethereum/web3.py#1013]
* Version: 4.3.0
* Python: 3.6.5
* OS: osx/

### What was wrong?

I recently switched from `pyethereum` to `PyEvm` and I'm having trouble reading the state of contracts deployed in a test environment. I'm also finding that during contract deployment, I *need* to specify the `gas` where I didn't need to before when I used `pyethereum`. Is there a way around this?

```python
from web3 import Web3
from web3.providers.eth_tester import EthereumTesterProvider
from eth_tester import PyEVMBackend
from backend.server.utils.contract_compiler import ContractCompiler
import unittest
from web3.contract import ConciseContract
from eth_tester import EthereumTester
W3 = Web3(EthereumTesterProvider(EthereumTester(PyEVMBackend())))


class TestMyERC20Contract(unittest.TestCase):

    def test(self):
        # compiler is a class I wrote which performs contract compilation
        compiler = ContractCompiler()
        contract_interface = compiler.get_contract_interface("mycro.sol", "MycroCoin")
        contract = W3.eth.contract(abi=contract_interface['abi'], bytecode=contract_interface['bin'])

        tx_hash = contract.constructor().transact(transaction={'from': W3.eth.accounts[0], 'gas': 3100000})
        tx_receipt = W3.eth.waitForTransactionReceipt(tx_hash)
        contract_address = tx_receipt['contractAddress']

        abi = contract_interface['abi']
        contract_instance = W3.eth.contract(address=contract_address, abi=abi,
                                            ContractFactoryClass=ConciseContract)

        # need to recreate the contract now that we've successfully deployed and have a contract address
        contract = W3.eth.contract(address=contract_address, abi=contract_interface['abi'])

        # seems to succeed
        contract_instance.transfer(W3.eth.accounts[1], 10, transact={'from': W3.eth.accounts[0]})

        # fails
        contract.functions.totalSupply().call()

        # also fails
        contract_instance.totalSupply()
```

The full output of the error is below. I get the same error for both of the failing lines.

```
Testing started at 9:28 AM ...
/Users/paymahn/mycro/backend/venv/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_unittest_runner.py --target backend.tests.test_fake
Launching unittests with arguments python -m unittest backend.tests.test_fake in /Users/paymahn/mycro/backend/tests


Ran 1 test in 0.907s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/contract.py", line 1363, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_abi/abi.py", line 96, in decode_abi
    return decoder(stream)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 164, in decode
    yield decoder(stream)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 186, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 279, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/paymahn/mycro/backend/tests/test_fake.py", line 34, in test
    contract.functions.totalSupply().call()
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/contract.py", line 1106, in call
    **self.kwargs
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/contract.py", line 1385, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
```

**Comment by paymog** [comment]
After some debugging I found that `print(W3.eth.getCode(contract_address))` results int `b''` which is odd because `waitForTransactionReceipt` seems to complete successfully.

**Comment by carver** [comment]
Maybe you're running out of gas. Have you looked at the receipt status?

---
Closing, since this is not likely a Web3.py issue. Feel free to continue the discussion here.

**Comment by paymog** [comment]
Ah, I think you're right @carver. I tried increasing the gas used for the contract deployment and now I'm getting `evm.exceptions.ValidationError: Transaction exceeds gas limit: using 3200000, bringing total to 3200000, but limit is 3144659`. Do you know how I can increase the limit on the `EthereumTesterProvider`/`EthereumTester`/`PyEVMBackend`? When I used `pyethereum` I found I didn't have to worry about gas during testing and never had to specify gas for transactions. Is that possible with `PyEVMBackend`?

**Comment by paymog** [comment]
Nevermind, figured it out: https://gitter.im/ethereum/py-evm?at=5b7eb68c4be56c5918854337
