### ISSUE TITLE
whisper: The method shh_<methodName> does not exist/is not available

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#1029]
* Web3.py version: 4.4.1
* Python: 3.7.0
* OS: linux
* geth version: `1.8.15-unstable`
* I am running `geth` with `--shh` flag and `--rpcapi "admin,eth,net,web3,debug,shh"`

---------

My code:

```
from web3 import Web3, HTTPProvider
web3 = Web3(HTTPProvider('http://localhost:8545'))
from web3.shh import Shh
Shh.attach(web3, "shh")

print ("web3 =", web3.version.api)
print(web3.shh)      # Works !!!
keyPair =  '0xa82ff6abcf75393084edb06d100e53268c5e118884d59282ef9d3396c8537011';
kId = web3.shh.addPrivateKey(keyPair) # Does not work !!!
```

Error I am having:

```
<web3.shh.Shh object at 0x7f9a25a320f0>
Traceback (most recent call last):
  File "whisper.py", line 15, in <module>
    kId = web3.shh.addPrivateKey(keyPair)
  File "/home/alper/eBlocBroker/venv/lib/python3.5/site-packages/web3/shh.py", line 31, in addPrivateKey
    return self.web3.manager.request_blocking("shh_addPrivateKey", [key])
  File "/home/alper/eBlocBroker/venv/lib/python3.5/site-packages/web3/manager.py", line 110, in request_blocking
    raise ValueError(response["error"])
ValueError: {'message': 'The method shh_addPrivateKey does not exist/is not available', 'code': -32601}
```

**=>** Please note that this error is generated for `web3.shh` 's methods. `web3.ssh.<methodName>` returns following error: `The method shh_<methodName> does not exist/is not available`

**Comment by avatar-lavventura** [comment]
I am sorry I was not able to delete this issue. I started `geth` with `--shh` flag and the problem is solved.
