### ISSUE TITLE
"OSError: [WinError 1] Incorrect function" when using IPCProvider on Windows

### ISSUE THREAD

**Issue by ArchFrosty** [ethereum/web3.py#1087]
* Version: 4.7.2
* Python: 3.6
* OS: win

### What was wrong?

After update IPCProvider on windows doesn't work.
```
web3 = Web3(Web3.IPCProvider('\\\.\pipe\geth.ipc', timeout=100))
```
Errors with:
```
Traceback (most recent call last):
  File "C:/Users/username/PycharmProjects/dp/getTransactions.py", line 19, in <module>
    web3 = Web3(Web3.IPCProvider('\\\.\pipe\geth.ipc', timeout=100))
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\providers\ipc.py", line 192, in __init__
    self.ipc_path = str(pathlib.Path(ipc_path).expanduser().resolve())
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\pathlib.py", line 1119, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\pathlib.py", line 193, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 1] Incorrect function: '\\\\.\\pipe\\geth.ipc'
```

### How can it be fixed?

Downgrading to version 4.7.1 fixes this issue.

**Comment by voith** [comment]
could this be related to my comment in gitter: https://gitter.im/ethereum/web3.py?at=5bba94d1c7bf7c3662cfef68

**Comment by voith** [comment]
Indeed a bug in python: https://bugs.python.org/issue31842

**Comment by pipermerriam** [comment]
closing as this isn't a bug in our library.

**Comment by KiraToms** [comment]
remove the first backslash
web3 = Web3(Web3.IPCProvider('\\.\pipe\geth.ipc', timeout=100))

**Comment by its5Q** [comment]
This is still a problem on windows, and the issue with python wasn't fixed. As a workaround, I just removed path resolving.
