### ISSUE TITLE
ImportError: cannot import name 'NewType'

### ISSUE THREAD

**Issue by Lynaj** [ethereum/web3.py#1091]
* Version: 4.7.2
* Python: 3.5.1
* OS: osx/

* The code which produced the error
import web3

* The full output of the error
```

Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import web3
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/web3/__init__.py", line 7, in
 <module>
    from eth_account import Account  # noqa: E402
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_account/__init__.py", lin
e 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_account/account.py", line
 10, in <module>
    from eth_keyfile import (
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_keyfile/__init__.py", lin
e 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_keyfile/keyfile.py", line
 10, in <module>
    from eth_keys import keys
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_keys/__init__.py", line 1
5, in <module>
    from .main import (  # noqa: F401
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_keys/main.py", line 3, in
 <module>
    from eth_keys.datatypes import (
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_keys/datatypes.py", line 
8, in <module>
    from eth_utils import (
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_utils/__init__.py", line 
5, in <module>
    from .abi import (  # noqa: F401
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_utils/abi.py", line 3, in
 <module>
    from .crypto import keccak
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_utils/crypto.py", line 5,
 in <module>
    from .conversions import to_bytes
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_utils/conversions.py", li
ne 7, in <module>
    from .typing import HexStr, Primitives, T
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_utils/typing/__init__.py"
, line 1, in <module>
    from .misc import (  # noqa: F401
  File "/Users/macbook/Desktop/projects/env351/lib/python3.5/site-packages/eth_utils/typing/misc.py", li
ne 1, in <module>
    from typing import NewType, TypeVar, Union
ImportError: cannot import name 'NewType
```

**Comment by pipermerriam** [comment]
Likely due to using older `python 3.5.1`, consider updating to newer version of python `3.5`, I've confirmed the import is available in python `3.5.5`
