### ISSUE TITLE
when sending a str, it must be a hex string

### ISSUE THREAD

**Issue by icrazymob** [ethereum/web3.py#1105]
* Version: x.x.x
* Python: /3.6
* OS: centos7
* `pip freeze` output

```
attrdict==2.0.0                                                                                                                                                                 
certifi==2018.8.24                                                                                                                                                              
chardet==3.0.4                                                                                                                                                                  
cytoolz==0.9.0.1                                                                                                                                                                
eth-abi==1.2.0                                                                                                                                                                  
eth-account==0.3.0                                                                                                                                                              
eth-hash==0.2.0                                                                                                                                                                 
eth-keyfile==0.5.1                                                                                                                                                              
eth-keys==0.2.0b3                                                                                                                                                               
eth-rlp==0.1.2                                                                                                                                                                  
eth-typing==1.3.0                                                                                                                                                               
eth-utils==1.2.2                                                                                                                                                                
hexbytes==0.1.0                                                                                                                                                                 
idna==2.7                                                                                                                                                                       
lru-dict==1.1.6                                                                                                                                                                 
parsimonious==0.8.0                                                                                                                                                             
pycryptodome==3.6.6                                                                                                                                                             
requests==2.19.1                                                                                                                                                                
rlp==1.0.3                                                                                                                                                                      
six==1.11.0                                                                                                                                                                     
toolz==0.9.0                                                                                                                                                                    
urllib3==1.23                                                                                                                                                                   
web3==4.7.2                                                                                                                                                                     
websockets==6.0                                                                                                                                                                 
```

### What was wrong?
```
from web3 import *

etherscan_provider = Web3.HTTPProvider( 'https://api.etherscan.io/api')
w3 = Web3(Web3.HTTPProvider( 'https://api.etherscan.io/api'))


signed_txn = w3.eth.account.signTransaction(dict(
    gas = 2000000,
    gasPrice= 234567897654321,
    nonce=0,
    to='0xABA024480E6B9e92B7e3332a2a3eb104F183D18C',
    value= 100000,
    chainId = 1
),
'0x2850d0xxxxxxxxxxxxxxxxxxxxxxxxxx')


w3.eth.sendRawTransaction(signed_txn.rawTransaction)

File "/root/eth/lib/python3.6/site-packages/eth_utils/conversions.py", line 142, in hexstr_if_str                                                                             
hexstr_or_primitive                                                                                                                                                         
ValueError: when sending a str, it must be a hex string. Got: 'Error! Missing Or invalid Module name'   
```
What's the problem?

**Comment by pipermerriam** [comment]
can you provide the value of `signed_txn.rawTransaction` and/or it's type `type(signed_txn.rawTransaction)`

**Comment by pipermerriam** [comment]
Also, the full stacktrace would be helpful.

**Comment by icrazymob** [comment]
ofc

`
Traceback (most recent call last):                                                                                                                                              
  File "/var/www/www-root/data/www/eth-gateway/test.py", line 18, in <module>                                                                                                   
    w3.eth.sendRawTransaction(signed_txn.rawTransaction)                                                                                                                        
  File "/root/eth/lib/python3.6/site-packages/web3/eth.py", line 274, in sendRawTransaction                                                                                     
    [raw_transaction],                                                                                                                                                          
  File "/root/eth/lib/python3.6/site-packages/web3/manager.py", line 109, in request_blocking                                                                                   
    response = self._make_request(method, params)                                                                                                                               
  File "/root/eth/lib/python3.6/site-packages/web3/manager.py", line 92, in _make_request                                                                                       
    return request_func(method, params)                                                                                                                                         
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__                                                                                                   
  File "/root/eth/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters                                                                      
    response = make_request(method, params)                                                                                                                                     
  File "/root/eth/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware                                                                    
    return make_request(method, params)                                                                                                                                         
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__                                                                                                   
  File "/root/eth/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters                                                                      
    response = make_request(method, formatted_params)                                                                                                                           
  File "/root/eth/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware                                                                              
    response = make_request(method, params)                                                                                                                                     
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__                                                                                                   
  File "/root/eth/lib/python3.6/site-packages/web3/middleware/formatting.py", line 57, in apply_formatters                                                                      
    formatter(response['result']),                                                                                                                                              
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__                                                                                                   
  File "/root/eth/lib/python3.6/site-packages/web3/middleware/pythonic.py", line 69, in to_hexbytes                                                                             
    result = HexBytes(val)                                                                                                                                                      
  File "/root/eth/lib/python3.6/site-packages/hexbytes/main.py", line 17, in __new__                                                                                            
    bytesval = hexstr_if_str(to_bytes, val)                                                                                                                                     
  File "/root/eth/lib/python3.6/site-packages/eth_utils/conversions.py", line 143, in hexstr_if_str                                                                             
    hexstr_or_primitive                                                                                                                                                         
ValueError: when sending a str, it must be a hex string. Got: 'Error! Missing Or invalid Module name'                                                                           
`
`b"\xf8i\x80\x86\xd5V\x987$1\x83\x1e\x84\x80\x94\xab\xa0$H\x0ek\x9e\x92\xb7\xe33**>\xb1\x04\xf1\x83\xd1\x8c\x83\x01\x86\xa0\x80%\xa0l\x89\xe9^\x86.\x98%2\xe2\xd2\xbd\xea\x15\xa8
\x7fO\xb0\xd7.\x1b\xe8F\xa8S\xa3\xee\x98=\xad\x80E\xa0E\xf7\xec\xf2\xaa,\xacI\xcc\x11\x16\xb3\x1d\x82\x17a\x1a\xe6~7\x15o\xe9\xf6xF2'x\xbdl\x93" 

                               
<class 'hexbytes.main.HexBytes'>                                                                                                                                                `

**Comment by icrazymob** [comment]
Any ideas?

**Comment by pipermerriam** [comment]
It looks like etherscan isn't returning a valid JSON-RPC response:

Here's the full JSON of their response:

```
{'status': '0', 'message': 'NOTOK', 'result': 'Error! Missing Or invalid Module name'}
```

You should double check that etherscan supports sending raw transactions.  I know that infura does.

**Comment by carver** [comment]
As I mentioned in https://ethereum.stackexchange.com/questions/60421/web3-python-sendtransaction-error the etherscan API is not a JSON-RPC API, which web3.py needs.

I expanded with more explanation there.
