### ISSUE TITLE
Cannot decode logs. eth_abi.exceptions.InsufficientDataBytes: Tried to read 96 bytes. Only got 74 bytes

### ISSUE THREAD

**Issue by porobov** [ethereum/web3.py#1106]
* Version: 4.7.2
* Python: 3.6.6
* OS: linux
* `pip freeze` output

```
asn1crypto==0.24.0
atomicwrites==1.2.1
attrdict==2.0.0
attrs==18.2.0
bitcoin==1.1.42
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
coincurve==9.0.0
coverage==4.5.1
cytoolz==0.9.0.1
eth-abi==1.2.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.3.0
eth-utils==1.2.2
ethereum==1.0.8
ethjsonrpc==0.3.0
future==0.16.0
hexbytes==0.1.0
idna==2.7
imgurpython==1.1.7
lru-dict==1.1.6
-e git+https://github.com/porobov/mlneth-backend.git@dff8f5d7b41237274a2a52e5b10a77e7b8e20e24#egg=mlneth_backend
more-itertools==4.3.0
parsimonious==0.8.0
pbkdf2==1.3
peewee==3.7.0
Pillow==5.3.0
pluggy==0.7.1
py==1.6.0
py-ecc==1.4.3
pycparser==2.19
pycryptodome==3.6.6
pyethash==0.1.27
PyScaffold==3.1
pysha3==1.0.2
pytest==3.8.2
pytest-cov==2.6.0
PyYAML==3.13
repoze.lru==0.7
requests==2.9.1
rlp==0.4.4
scrypt==0.8.6
six==1.11.0
toolz==0.9.0
urllib3==1.23
web3==4.7.2
websockets==6.0
```

### What was wrong?
**get_event_data** works fine with contract_a, but throws exception with contract_b. Events to be decoded have the same parameters (uint256, uint8, uint8, uint8, uint8, string, string, string, address), except that the last parameter in contract_b is indexed. The function firing the event is public in contract_a and external in contract_b. 

* The code which produced the error (real contracts on main net)
```
from eth_utils.abi import event_abi_to_log_topic
from web3.utils.events import get_event_data
from web3 import Web3, HTTPProvider, IPCProvider
from web3.auto import w3
from config import *

web3 = Web3(HTTPProvider('https://mainnet.infura.io/your-api-key'))

contract_a_address = u'0x15dbdB25f870f21eaf9105e68e249E0426DaE916'
contract_a_abi = [{"constant": False, "inputs": [{"name": "newDelayInSeconds", "type": "uint32"}, {"name": "newCharityAddress", "type": "address"},{"name":"newImagePlacementPriceInWei","type":"uint256"}],"name":"adminContractSettings","outputs":[],"payable":False,"type":"function"},{"constant":False,"inputs":[],"name":"emergencyRefund","outputs":[],"payable":False,"type":"function"},{"constant":False,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"},{"name":"priceForEachBlockInWei","type":"uint256"}],"name":"sellBlocks","outputs":[{"name":"","type":"bool"}],"payable":False,"type":"function"},{"constant":True,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"}],"name":"getAreaPrice","outputs":[{"name":"","type":"uint256"}],"payable":False,"type":"function"},{"constant":True,"inputs":[{"name":"x","type":"uint8"},{"name":"y","type":"uint8"}],"name":"getBlockInfo","outputs":[{"name":"landlord","type":"address"},{"name":"imageID","type":"uint256"},{"name":"sellPrice","type":"uint256"}],"payable":False,"type":"function"},{"constant":False,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"},{"name":"imageSourceUrl","type":"string"},{"name":"adUrl","type":"string"},{"name":"adText","type":"string"}],"name":"placeImage","outputs":[{"name":"","type":"uint256"}],"payable":True,"type":"function"},{"constant":False,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"}],"name":"buyBlocks","outputs":[{"name":"","type":"uint256"}],"payable":True,"type":"function"},{"constant":True,"inputs":[{"name":"userAddress","type":"address"}],"name":"getUserInfo","outputs":[{"name":"referal","type":"address"},{"name":"handshakes","type":"uint8"},{"name":"balance","type":"uint256"},{"name":"activationTime","type":"uint32"},{"name":"banned","type":"bool"},{"name":"userID","type":"uint256"},{"name":"refunded","type":"bool"},{"name":"investments","type":"uint256"}],"payable":False,"type":"function"},{"constant":True,"inputs":[{"name":"userID","type":"uint256"}],"name":"getUserAddressByID","outputs":[{"name":"userAddress","type":"address"}],"payable":False,"type":"function"},{"constant":True,"inputs":[],"name":"getMyInfo","outputs":[{"name":"balance","type":"uint256"},{"name":"activationTime","type":"uint32"}],"payable":False,"type":"function"},{"constant":True,"inputs":[],"name":"getStateInfo","outputs":[{"name":"_numUsers","type":"uint256"},{"name":"_blocksSold","type":"uint16"},{"name":"_totalWeiInvested","type":"uint256"},{"name":"_numImages","type":"uint256"},{"name":"_setting_imagePlacementPriceInWei","type":"uint256"},{"name":"_numNewStatus","type":"uint256"},{"name":"_setting_delay","type":"uint32"}],"payable":False,"type":"function"},{"constant":False,"inputs":[],"name":"withdrawAll","outputs":[],"payable":False,"type":"function"},{"constant":False,"inputs":[{"name":"referal","type":"address"}],"name":"signIn","outputs":[{"name":"","type":"uint256"}],"payable":False,"type":"function"},{"constant":True,"inputs":[{"name":"imageID","type":"uint256"}],"name":"getImageInfo","outputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"},{"name":"imageSourceUrl","type":"string"},{"name":"adUrl","type":"string"},{"name":"adText","type":"string"}],"payable":False,"type":"function"},{"constant":True,"inputs":[],"name":"charityBalance","outputs":[{"name":"","type":"uint256"}],"payable":False,"type":"function"},{"constant":True,"inputs":[],"name":"charityAddress","outputs":[{"name":"","type":"address"}],"payable":False,"type":"function"},{"constant":False,"inputs":[{"name":"violator","type":"address"},{"name":"banViolator","type":"bool"},{"name":"pauseContract","type":"bool"},{"name":"refundInvestments","type":"bool"}],"name":"adminContractSecurity","outputs":[],"payable":False,"type":"function"},{"inputs":[],"type":"constructor"},{"payable":False,"type":"fallback"},{"anonymous":False,"inputs":[{"indexed":False,"name":"ID","type":"uint256"},{"indexed":False,"name":"newUser","type":"address"},{"indexed":False,"name":"invitedBy","type":"address"},{"indexed":False,"name":"activationTime","type":"uint32"}],"name":"NewUser","type":"event"},{"anonymous":False,"inputs":[{"indexed":False,"name":"ID","type":"uint256"},{"indexed":False,"name":"fromX","type":"uint8"},{"indexed":False,"name":"fromY","type":"uint8"},{"indexed":False,"name":"toX","type":"uint8"},{"indexed":False,"name":"toY","type":"uint8"},{"indexed":False,"name":"price","type":"uint256"}],"name":"NewAreaStatus","type":"event"},{"anonymous":False,"inputs":[{"indexed":False,"name":"ID","type":"uint256"},{"indexed":False,"name":"fromX","type":"uint8"},{"indexed":False,"name":"fromY","type":"uint8"},{"indexed":False,"name":"toX","type":"uint8"},{"indexed":False,"name":"toY","type":"uint8"},{"indexed":False,"name":"imageSourceUrl","type":"string"},{"indexed":False,"name":"adUrl","type":"string"},{"indexed":False,"name":"adText","type":"string"}],"name":"NewImage","type":"event"}]
contract_a = web3.eth.contract(address=contract_a_address, abi=contract_a_abi)
contract_a_event_abi = contract_a.events.NewImage().abi
contract_a_event_signature = web3.toHex(event_abi_to_log_topic(contract_a_event_abi))
found_logs = web3.eth.getLogs(
        {
            'address': contract_a_address,
            'fromBlock': 4315137,
            'toBlock': 4315137,
            'topics': [contract_a_event_signature,]
        })
# works fine
print(get_event_data(contract_a_event_abi, found_logs[0]))


contract_b_address = u'0xCEf41878Db032586C835eE0890484399402A64f6'
contract_b_abi = [{"constant":True,"inputs":[{"name":"_interfaceId","type":"bytes4"}],"name":"supportsInterface","outputs":[{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_address","type":"address"}],"name":"adminSetMarket","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[{"name":"x","type":"uint8"},{"name":"y","type":"uint8"}],"name":"getBlockOwner","outputs":[{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[{"name":"_tokenId","type":"uint256"}],"name":"getApproved","outputs":[{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_to","type":"address"},{"name":"_tokenId","type":"uint256"}],"name":"approve","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"}],"name":"areaPrice","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[],"name":"InterfaceId_ERC165","outputs":[{"name":"","type":"bytes4"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_tokenId","type":"uint256"}],"name":"transferFrom","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[{"name":"","type":"address"}],"name":"balances","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[{"name":"_owner","type":"address"},{"name":"_index","type":"uint256"}],"name":"tokenOfOwnerByIndex","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_address","type":"address"}],"name":"adminSetAds","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[],"name":"withdraw","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[{"name":"_payer","type":"address"},{"name":"_recipient","type":"address"},{"name":"_amount","type":"uint256"}],"name":"operatorTransferFunds","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[],"name":"unpause","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_tokenId","type":"uint256"}],"name":"safeTransferFrom","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"rentals","outputs":[{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[{"name":"_tokenId","type":"uint256"}],"name":"exists","outputs":[{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[{"name":"_index","type":"uint256"}],"name":"tokenByIndex","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"x","type":"uint8"},{"name":"y","type":"uint8"}],"name":"adminImportOldMEBlock","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"paused","outputs":[{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"},{"name":"priceForEachBlockWei","type":"uint256"}],"name":"sellArea","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[{"name":"_tokenId","type":"uint256"}],"name":"ownerOf","outputs":[{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_to","type":"address"},{"name":"_blockId","type":"uint16"}],"name":"_mintCrowdsaleBlock","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"},{"name":"imageSource","type":"string"},{"name":"link","type":"string"},{"name":"text","type":"string"}],"name":"placeAds","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[],"name":"renounceOwnership","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"market","outputs":[{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"},{"name":"rentPricePerPeriodWei","type":"uint256"}],"name":"rentOutArea","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[{"name":"x","type":"uint8"},{"name":"y","type":"uint8"}],"name":"blockID","outputs":[{"name":"","type":"uint16"}],"payable":False,"stateMutability":"pure","type":"function"},{"constant":False,"inputs":[],"name":"pause","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[{"name":"_address","type":"address"}],"name":"adminSetRentals","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"}],"name":"buyArea","outputs":[],"payable":True,"stateMutability":"payable","type":"function"},{"constant":True,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[],"name":"adminRescueFunds","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":False,"inputs":[{"name":"_to","type":"address"},{"name":"_approved","type":"bool"}],"name":"setApprovalForAll","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[{"name":"advertiser","type":"address"},{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"}],"name":"canAdvertise","outputs":[{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"},{"name":"numberOfPeriods","type":"uint256"}],"name":"areaRentPrice","outputs":[{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[],"name":"ads","outputs":[{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_tokenId","type":"uint256"},{"name":"_data","type":"bytes"}],"name":"safeTransferFrom","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[{"name":"_tokenId","type":"uint256"}],"name":"tokenURI","outputs":[{"name":"","type":"string"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":True,"inputs":[{"name":"_owner","type":"address"},{"name":"_operator","type":"address"}],"name":"isApprovedForAll","outputs":[{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function"},{"constant":False,"inputs":[{"name":"fromX","type":"uint8"},{"name":"fromY","type":"uint8"},{"name":"toX","type":"uint8"},{"name":"toY","type":"uint8"},{"name":"numberOfPeriods","type":"uint256"}],"name":"rentArea","outputs":[],"payable":True,"stateMutability":"payable","type":"function"},{"constant":False,"inputs":[{"name":"_newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function"},{"constant":True,"inputs":[],"name":"isMEH","outputs":[{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function"},{"anonymous":False,"inputs":[{"indexed":False,"name":"ID","type":"uint256"},{"indexed":False,"name":"fromX","type":"uint8"},{"indexed":False,"name":"fromY","type":"uint8"},{"indexed":False,"name":"toX","type":"uint8"},{"indexed":False,"name":"toY","type":"uint8"},{"indexed":False,"name":"newLandlord","type":"address"}],"name":"LogBuys","type":"event"},{"anonymous":False,"inputs":[{"indexed":False,"name":"ID","type":"uint256"},{"indexed":False,"name":"fromX","type":"uint8"},{"indexed":False,"name":"fromY","type":"uint8"},{"indexed":False,"name":"toX","type":"uint8"},{"indexed":False,"name":"toY","type":"uint8"},{"indexed":False,"name":"sellPrice","type":"uint256"}],"name":"LogSells","type":"event"},{"anonymous":False,"inputs":[{"indexed":False,"name":"ID","type":"uint256"},{"indexed":False,"name":"fromX","type":"uint8"},{"indexed":False,"name":"fromY","type":"uint8"},{"indexed":False,"name":"toX","type":"uint8"},{"indexed":False,"name":"toY","type":"uint8"},{"indexed":False,"name":"rentPricePerPeriodWei","type":"uint256"}],"name":"LogRentsOut","type":"event"},{"anonymous":False,"inputs":[{"indexed":False,"name":"ID","type":"uint256"},{"indexed":False,"name":"fromX","type":"uint8"},{"indexed":False,"name":"fromY","type":"uint8"},{"indexed":False,"name":"toX","type":"uint8"},{"indexed":False,"name":"toY","type":"uint8"},{"indexed":False,"name":"numberOfPeriods","type":"uint256"},{"indexed":False,"name":"rentedFrom","type":"uint256"}],"name":"LogRents","type":"event"},{"anonymous":False,"inputs":[{"indexed":False,"name":"ID","type":"uint256"},{"indexed":False,"name":"fromX","type":"uint8"},{"indexed":False,"name":"fromY","type":"uint8"},{"indexed":False,"name":"toX","type":"uint8"},{"indexed":False,"name":"toY","type":"uint8"},{"indexed":False,"name":"imageSourceUrl","type":"string"},{"indexed":False,"name":"adUrl","type":"string"},{"indexed":False,"name":"adText","type":"string"},{"indexed":True,"name":"advertiser","type":"address"}],"name":"LogAds","type":"event"},{"anonymous":False,"inputs":[{"indexed":False,"name":"payerOrPayee","type":"address"},{"indexed":False,"name":"balanceChange","type":"int256"}],"name":"LogContractBalance","type":"event"},{"anonymous":False,"inputs":[{"indexed":False,"name":"newAddress","type":"address"},{"indexed":False,"name":"moduleName","type":"string"}],"name":"LogModuleUpgrade","type":"event"},{"anonymous":False,"inputs":[],"name":"Pause","type":"event"},{"anonymous":False,"inputs":[],"name":"Unpause","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"previousOwner","type":"address"}],"name":"OwnershipRenounced","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"previousOwner","type":"address"},{"indexed":True,"name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"_from","type":"address"},{"indexed":True,"name":"_to","type":"address"},{"indexed":True,"name":"_tokenId","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"_owner","type":"address"},{"indexed":True,"name":"_approved","type":"address"},{"indexed":True,"name":"_tokenId","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":False,"inputs":[{"indexed":True,"name":"_owner","type":"address"},{"indexed":True,"name":"_operator","type":"address"},{"indexed":False,"name":"_approved","type":"bool"}],"name":"ApprovalForAll","type":"event"}]
contract_b = web3.eth.contract(address=contract_b_address, abi=contract_b_abi)
contract_b_event_abi = contract_b.events.LogAds().abi
contract_b_event_signature = web3.toHex(event_abi_to_log_topic(contract_b_event_abi))
found_logs = web3.eth.getLogs(
        {
            'address': contract_b_address,
            'fromBlock': 6275796,
            'toBlock': 6287707,
            'topics': [contract_b_event_signature,]
        })
# returns error: eth_abi.exceptions.InsufficientDataBytes: Tried to read 96 bytes.  Only got 74 bytes
print(get_event_data(contract_b_event_abi, found_logs[0]))
```

* The full output of the error
```
Traceback (most recent call last):
  File "sandbox.py", line 43, in <module>
    print(get_event_data(contract_b_event_abi, found_logs[0]))
  File "/home/petr/Projects/2018-03-02-million-ether-2/mlneth-backend/vvenv/lib/python3.6/site-packages/web3/utils/events.py", line 189, in get_event_data
    decoded_log_data = decode_abi(log_data_types, log_data)
  File "/home/petr/Projects/2018-03-02-million-ether-2/mlneth-backend/vvenv/lib/python3.6/site-packages/eth_abi/abi.py", line 96, in decode_abi
    return decoder(stream)
  File "/home/petr/Projects/2018-03-02-million-ether-2/mlneth-backend/vvenv/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/home/petr/Projects/2018-03-02-million-ether-2/mlneth-backend/vvenv/lib/python3.6/site-packages/eth_utils/functional.py", line 20, in inner
    return callback(fn(*args, **kwargs))
  File "/home/petr/Projects/2018-03-02-million-ether-2/mlneth-backend/vvenv/lib/python3.6/site-packages/eth_abi/decoding.py", line 164, in decode
    yield decoder(stream)
  File "/home/petr/Projects/2018-03-02-million-ether-2/mlneth-backend/vvenv/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/home/petr/Projects/2018-03-02-million-ether-2/mlneth-backend/vvenv/lib/python3.6/site-packages/eth_abi/decoding.py", line 136, in decode
    value = self.tail_decoder(stream)
  File "/home/petr/Projects/2018-03-02-million-ether-2/mlneth-backend/vvenv/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/home/petr/Projects/2018-03-02-million-ether-2/mlneth-backend/vvenv/lib/python3.6/site-packages/eth_abi/decoding.py", line 186, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/petr/Projects/2018-03-02-million-ether-2/mlneth-backend/vvenv/lib/python3.6/site-packages/eth_abi/decoding.py", line 589, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 96 bytes.  Only got 74 bytes
```
* What type of node you were connecting to.
Infura

### How can it be fixed?

Related issues:
https://github.com/ethereum/web3.py/issues/928
https://github.com/ethereum/solidity/issues/3493

**Comment by pipermerriam** [comment]
I think this is a long standing bug.

The event API in web3 is built such that it *assumes* that an event which matches the appropriate topic will also have a data field which can be decoded.  This is in no way guaranteed.  In fact, at some point, someone is likely to grief the network by issuing events who's topics match known commonly used events, but who's data fields are not decodable.  In this case, it's likely just a bug with solidity.

Either way, a decision needs to be made with respect to what web3 should do in this case.  Obvious choices to me are:

The best solution I can think of is to add a fallback which handles this when decoding logs, leaves the log as-is without exposing the decoded arguments.  This however raises another problem which is that then you cannot *blindly* iterate over logs since some of them may not contain the decoded log data.

That leads me to think that it should be configurable at the filter level, where the user can specify a *handler* of sorts.  The default handler might be to raise an exception, and we could provide alternate handlers to 1) exclude malformed logs and 2) expose them in their unparsed format.

I think some of this issue has to be dealt with in documentation since users will need to be educated on how to use this error handling API.

Also, not 100% sure I've diagnosed this correctly, but on the surface it seems to match.

**Comment by carver** [comment]
This is likely the solidity bug mentioned here: https://github.com/ethereum/web3.py/issues/928#issuecomment-401505197

Solidity 0.5.0 is supposed to include the fix: https://github.com/ethereum/solidity/issues/3493

I'm not convinced we should do anything about this, but am not inherently opposed to adding a hack to fix it. As long as we can figure out a way that doesn't limit/break other valid scenarios.

**Comment by pipermerriam** [comment]
@carver not exactly proposing a hack to fix this, but rather to handle the general case where there are logs that legitimately cannot be decoded because their data field isn't valid ABI for the expected log args.  Agreed this is probably low priority, I'll try to write up an issue tomorrow to capture the idea.

**Comment by porobov** [comment]
@pipermerriam if it helps... currently I'm getting contract events through ethereum.abi.decode_abi(event_abi, logdata) from ethereum package with this hack https://github.com/ethereum/pyethereum/issues/342#issuecomment-219023147

**Comment by kclowes** [comment]
There is a flag in eth-abi that can be toggled: `eth_abi.decode(..., ..., strict=False)` that might help in this case. There is also a way in web3.py to ignore malformed logs. Docs [here](https://web3py.readthedocs.io/en/stable/web3.contract.html#events).
