### ISSUE TITLE
How to invoke a payable function in solidity by web3py use local accounts and infura

### ISSUE THREAD

**Issue by BowenXiao1999** [ethereum/web3.py#1174]
* Version: latest web3py
* Python: 3.6
* OS: osx
* `pip freeze` output

```
<put the output from running pip freeze here>
absl-py==0.5.0
appnope==0.1.0
astor==0.7.1
astroid==2.0.4
attrdict==2.0.0
backcall==0.1.0
beautifulsoup4==4.6.3
bleach==3.0.0
certifi==2018.10.15
chardet==3.0.4
comtypes==1.1.7
cycler==0.10.0
cytoolz==0.9.0.1
decorator==4.3.0
defusedxml==0.5.0
Django==2.1.3
entrypoints==0.2.3
eth-abi==1.2.2
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.3.0
eth-utils==1.3.0
future==0.17.1
gast==0.2.0
get==2018.11.19
grpcio==1.15.0
gym==0.10.9
h5py==2.8.0
hexbytes==0.1.0
idna==2.7
ipykernel==5.1.0
ipython==7.1.1
ipython-genutils==0.2.0
ipywidgets==7.4.2
isort==4.3.4
jedi==0.13.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-console==6.0.0
jupyter-core==4.4.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
lru-dict==1.1.6
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==3.0.0
mccabe==0.6.1
mistune==0.8.3
nbconvert==5.4.0
nbformat==4.4.0
notebook==5.7.2
notedown==1.5.1
numpy==1.15.4
opencv-python==3.4.3.18
pandas==0.23.4
pandoc-attributes==0.1.7
pandocfilters==1.4.2
parsimonious==0.8.1
parso==0.3.1
pbkdf2==1.3
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.3.0
post==2018.11.20
prometheus-client==0.4.2
prompt-toolkit==2.0.7
protobuf==3.6.1
ptyprocess==0.6.0
public==2018.11.20
pycryptodome==3.7.2
pyglet==1.3.2
Pygments==2.2.0
pylint==2.1.1
pyparsing==2.2.2
python-dateutil==2.7.3
pytz==2018.7
pywifi==1.1.10
PyYAML==4.2b4
pyzmq==17.1.2
qtconsole==4.4.3
query-string==2018.11.20
request==2018.11.20
requests==2.20.1
rlp==1.0.3
scikit-learn==0.20.1
scipy==1.1.0
Send2Trash==1.5.0
six==1.11.0
sklearn==0.0
tensorboard==1.11.0
tensorflow==1.11.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
toolz==0.9.0
tornado==5.1.1
traitlets==4.3.2
typed-ast==1.1.0
typing==3.6.6
urllib3==1.24.1
wcwidth==0.1.7
web3==4.8.2
webencodings==0.5.1
websockets==6.0
Werkzeug==0.14.1
wget==3.2
widgetsnbextension==3.4.2
wifi==0.3.8
wrapt==1.10.11
```
connecting to infura, i want to invoke a solidity function like this:

`
function openChannel(address recipient) public payable {
    //perform some validation first
    if (msg.value == 0) {
      revert();
    }

    if (recipient == msg.sender) { 
        revert(); 
    }

    if (channels[msg.sender][recipient].collateral > 0) {
        revert();
    }

    channels[msg.sender][recipient] = Channel({
        sender:msg.sender,
        recipient: recipient,
        collateral: uint(msg.value)
    });
}`

if i use local network like ganache, i can use below to invoke it:
`contract_instance.functions.openChannel(recipientAddress).transact({'from': web3.eth.accounts[0], 'value': 5})`
but if i use infura, it can not work because i don't have any accounts in the accounts list, and according to infura, i can not import my local accounts into it.
do it in infura, exception:
```
Traceback (most recent call last):
  File "/Users/a931759898/Desktop/Desktop/BlockChain/edgePricingSystem/edgePricingSystem/pricingSystem/test/4.py", line 51, in <module>
    contract_instance.functions.openChannel(proxy).transact({'from':user, 'value':1, 'gas':600000})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/contract.py", line 1151, in transact
    **self.kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/contract.py", line 1454, in transact_with_contract_function
    txn_hash = web3.eth.sendTransaction(transact_transaction)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/eth.py", line 268, in sendTransaction
    [transaction],
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/manager.py", line 92, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/middleware/exception_retry_request.py", line 87, in middleware
    return make_request(method, params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/providers/rpc.py", line 68, in make_request
    **self.get_request_kwargs()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/web3/utils/request.py", line 27, in make_post_request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://rinkeby.infura.io/v3/5590c756ce4d47269bcc0a2d462f8215
```

 **So how can i use my local accounts to invoke the payable function?**
i search it in docs i find sth, and i did below:

`
contract_instance = web3.eth.contract(address=configForRinkeby["address"],abi=configForRinkeby['abi'])

tx = contract_instance.functions.openChannel(user).buildTransaction({'value':1, 'gas':600000, 'nonce': web3.eth.getTransactionCount(proxy)})

signed_txn = web3.eth.account.signTransaction(tx, private_key=accounts['proxy']['pass'])

web3.eth.sendRawTransaction(signed_txn.rawTransaction)
`

when i check the balance of my accounts, it does not change after this procedure means it does not work.
so are there any methds to do it? Really appreciate!!!!

**Comment by fselmo** [comment]
stale
