### ISSUE TITLE
Multiple providers with Infura URI at top breaks Web3 Cache generation

### ISSUE THREAD

**Issue by hernandp** [ethereum/web3.py#1180]
* Version: 4.8.2
* Python: 3.6
* OS: OSX Mojave and Linux
* `pip freeze` output

```astroid==2.0.4
attrdict==2.0.0
autopep8==1.4
boto3==1.9.49
botocore==1.12.49
certifi==2018.10.15
chardet==3.0.4
Click==7.0
clickclick==1.2.2
connexion==1.1.15
cytoolz==0.9.0.1
dnspython==1.15.0
docutils==0.14
eth-abi==1.3.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==2.0.0
eth-utils==1.4.1
eventlet==0.24.1
filelock==3.0.9
Flask==1.0.2
greenlet==0.4.15
gunicorn==19.9.0
hexbytes==0.1.0
idna==2.7
inflection==0.3.1
isort==4.3.4
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
lazy-object-proxy==1.3.1
lru-dict==1.1.6
MarkupSafe==1.1.0
mccabe==0.6.1
monotonic==1.5
parsimonious==0.8.1
pluggy==0.7.1
py==1.7.0
pycodestyle==2.4.0
pycryptodome==3.7.2
pyethereum==1.0.0
pylint==2.2.2
pymongo==3.7.2
python-dateutil==2.6.0
python-decouple==3.1
PyYAML==3.13
requests==2.20.0
rlp==1.0.3
rope==0.11.0
s3transfer==0.1.13
six==1.11.0
swagger-spec-validator==2.4.1
toml==0.10.0
toolz==0.9.0
tox==3.5.2
urllib3==1.24.1
virtualenv==16.0.0
web3==4.8.2
websockets==6.0
Werkzeug==0.14.1
wrapt==1.10.11
```

### What was wrong?

In a project I'm developing with the Multiple-providers feature of Web3, there is an option to use Infura and put it as the primary provider.  So if I find this feature is requested, I use ```insert``` at index 0 to put the Infura HTTPProvider at first entry (this of course at Web3 initialization).

Here's a sample code that reproduces the error:

```
import web3

providers = []
providers.append(web3.HTTPProvider("http://localhost:8545"))

# Get alternate node list

ALT_NODES = ["http://althost:8000", "http://althost:8001"]

for nodeURI in ALT_NODES:
    providers.append(web3.HTTPProvider(nodeURI))

# Check if we have Infura and if should be used as primary

INFURA_NODE = "https://ropsten.infura.io/v3/770f6f0cd4cc44878fd2e6907a086ade"

INFURA_PROVIDER = web3.HTTPProvider(INFURA_NODE)
providers.insert(0, web3.HTTPProvider(INFURA_PROVIDER))

w3 = web3.Web3(providers)

print(w3.eth.getTransactionCount('0x8ae47CAD4b76d75810Ba91A22E9c12207e1cc19d'))

```

getTransactionCount fails with the following stack trace:

```
Traceback (most recent call last):  File "infuratest.py", line 22, in <module>    print(w3.eth.getTransactionCount('0x8ae47CAD4b76d75810Ba91A22E9c12207e1cc19d'))  File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 238, in getTransactionCount    block_identifier,  File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 109, in request_blocking    response = self._make_request(method, params)  File "/usr/local/lib/python3.7/site-packages/web3/manager.py", line 92, in _make_request    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.7/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.7/site-packages/web3/middleware/exception_retry_request.py", line 80, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.7/site-packages/web3/providers/rpc.py", line 68, in make_request
    **self.get_request_kwargs()
  File "/usr/local/lib/python3.7/site-packages/web3/utils/request.py", line 25, in make_post_request
    session = _get_session(endpoint_uri)
  File "/usr/local/lib/python3.7/site-packages/web3/utils/request.py", line 17, in _get_session
    cache_key = generate_cache_key((args, kwargs))
  File "/usr/local/lib/python3.7/site-packages/web3/utils/caching.py", line 39, in generate_cache_key
    in value
  File "/usr/local/lib/python3.7/site-packages/web3/utils/caching.py", line 38, in <genexpr>
    for item
  File "/usr/local/lib/python3.7/site-packages/web3/utils/caching.py", line 39, in generate_cache_key
    in value
  File "/usr/local/lib/python3.7/site-packages/web3/utils/caching.py", line 38, in <genexpr>
    for item
  File "/usr/local/lib/python3.7/site-packages/web3/utils/caching.py", line 44, in generate_cache_key
    type(value),
TypeError: Cannot generate cache key for value RPC connection https://ropsten.infura.io/v3/770f6f0cd4cc44878fd2e6907a086ade of type <class 'web3.providers.rpc.HTTPProvider'>
```

**Comment by pipermerriam** [comment]
Making note that multi-provider API is being deprecated in `v5`.  The culprit seems to be the `endpoint_uri` variable here:

```
  File "/usr/local/lib/python3.7/site-packages/web3/utils/request.py", line 25, in make_post_request
    session = _get_session(endpoint_uri)
```

It *should* be a string but instead it is getting an instance of the `HTTPProvider`.

**Comment by hernandp** [comment]
> 
> 
> Making note that multi-provider API is being deprecated in `v5`.

Didn't know about this.  Will v5 drop any "multiprovider" scheme? It's a useful feature (e.g: rotating between local enterprise nodes and Infura.io as fallback).
Thanks.

**Comment by pipermerriam** [comment]
@hernandp yes, it's not us abandoning it entirely as I know this is still a feature that is useful for people, however, the current approach is broken/wrong.  

- The **only** thing you can do is fall back across multiple providers.
- You cannot round robin
- You cannot dynamically choose provider based on request
- You cannot control how/which provider is chosen...

Our thought is that this API belongs at the `Manager` level and that we need to expand the `Manager` API to support injecting custom logic into the provider selection process.  After that we can provide some additional managers that do common things like round-robin or provider selection based on request type.

**Comment by adricu** [comment]
You have a bug in your code:
```
INFURA_PROVIDER = web3.HTTPProvider(INFURA_NODE)
providers.insert(0, web3.HTTPProvider(INFURA_PROVIDER))
```

It should be:
```
INFURA_PROVIDER = web3.HTTPProvider(INFURA_NODE)
providers.insert(0, INFURA_PROVIDER)
```

Regards

**Comment by kclowes** [comment]
Closing - allowing only a single provider has been released in v5a3.
