### ISSUE TITLE
Error with local_filter_middleware block filters with "latest" option, no new blocks

### ISSUE THREAD

**Issue by dylanjw** [ethereum/web3.py#1254]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

```
Python 3.6.4 (default, Jun  5 2018, 18:04:05)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.                 
>>> from web3 import Web3, EthereumTesterProvider
>>> from web3.middleware import local_filter_middleware
>>> w3 = Web3(EthereumTesterProvider())
>>> w3.middleware_onion.add(local_filter_middleware)
>>> filter = w3.eth.filter('latest')
>>> filter.get_new_entries()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/_utils/filters.py", line 124, in get_new_entries
    log_entries = self._filter_valid_entries(self.web3.eth.getFilterChanges(self.filter_id))
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/eth.py", line 363, in getFilterChanges
    "eth_getFilterChanges", [filter_id],
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/manager.py", line 94, in request_blocking
    response = self._make_request(method, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/manager.py", line 81, in _make_request
    return request_func(method, params)
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/filter.py", line 312, in middleware
    return {'result': next(_filter.filter_changes)}
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/filter.py", line 274, in get_filter_changes
    yield(block_hashes_in_range(self.w3, block_range))
  File "/home/dwilson/.pyenv/versions/web3/lib/python3.6/site-packages/eth_utils/functional.py", line 46, in inner
    return callback(fn(*args, **kwargs))
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/middleware/filter.py", line 280, in block_hashes_in_range
    for block_number in range(from_block, to_block + 1):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
>>> 
```

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

...

**Comment by fselmo** [comment]
stale / not currently reproducible
