### ISSUE TITLE
Error when deploying app in  ubuntu server

### ISSUE THREAD

**Issue by BhumikaB** [ethereum/web3.py#1258]
* Version: ubuntu 16.04
* Python: python 3.6.7
* OS:linux

 **pip3 freeze**
attrdict==2.0.1
blinker==1.3
certifi==2018.11.29
chardet==3.0.4
Click==7.0
cloud-init==18.4
command-not-found==0.3
configobj==5.0.6
cryptography==1.2.3
cytoolz==0.9.0.1
eth-abi==1.3.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.1
eth-rlp==0.1.2
eth-typing==2.0.0
eth-utils==1.4.1
Flask==1.0.2
hexbytes==0.1.0
hibagent==1.0.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
jsonpatch==1.10
jsonpointer==1.9
language-selector==0.1
lru-dict==1.1.6
MarkupSafe==1.1.0
oauthlib==1.0.3
parsimonious==0.8.1
prettytable==0.7.2
pyasn1==0.1.9
pycryptodome==3.7.3
pycurl==7.43.0
pygobject==3.20.0
PyJWT==1.3.0
pyserial==3.0.1
python-apt==1.1.0b1+ubuntu0.16.4.2
python-debian==0.1.27
python-systemd==231
PyYAML==3.11
requests==2.21.0
rlp==1.1.0
six==1.12.0
ssh-import-id==5.5
toolz==0.9.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.24.1
virtualenv==16.4.0
web3==4.8.3
websockets==6.0
Werkzeug==0.14.1
 
**I am using web3 api with flask  and deploying it in ubuntu server it gives me the following error in error.log:**

```
[Tue Feb 26 08:33:40.990205 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192] bhumika, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.990266 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192] hello, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993157 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192] ERROR:flask.app:Exception on /address_generate [POST], referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993183 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192] Traceback (most recent call last):, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993188 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993192 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     response = self.full_dispatch_request(), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993195 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993198 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     rv = self.handle_user_exception(e), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993201 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993205 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     reraise(exc_type, exc_value, tb), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993208 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993211 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     raise value, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993225 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993229 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     rv = self.dispatch_request(), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993232 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993235 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993238 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/__init__.py", line 45, in address_generate, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993241 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     new_address = my_provider.personal.newAccount(name), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993244 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/personal.py", line 18, in newAccount, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993247 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     "personal_newAccount", [password],, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993250 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/manager.py", line 109, in request_blocking, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993254 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     response = self._make_request(method, params), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993257 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/manager.py", line 92, in _make_request, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993260 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     return request_func(method, params), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993263 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993266 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993269 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     response = make_request(method, params), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993272 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993276 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     return make_request(method, params), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993279 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993291 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993295 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     response = make_request(method, params), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993297 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993301 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     response = make_request(method, params), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993304 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993306 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993309 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     response = make_request(method, params), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993312 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993315 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     result = make_request(method, params), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993318 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993321 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993325 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     response = make_request(method, params), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993328 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993331 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993334 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     response = make_request(method, params), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993337 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/providers/ipc.py", line 220, in make_request, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993341 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     with self._lock, self._socket as sock:, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993344 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/providers/ipc.py", line 48, in __enter__, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993351 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     self.sock = self._open(), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993354 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/providers/ipc.py", line 61, in _open, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993358 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     return get_ipc_socket(self.ipc_path), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993361 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]   File "/var/www/EthApp/EthApp/venv/lib/python3.6/site-packages/web3/providers/ipc.py", line 32, in get_ipc_socket, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993364 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192]     sock.connect(ipc_path), referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993369 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192] PermissionError: [Errno 13] Permission denied, referer: http://18.219.48.7/address.html
[Tue Feb 26 08:33:40.993376 2019] [wsgi:error] [pid 18223:tid 139892973623040] [client 116.72.55.92:60192] , referer: http://18.219.48.7/address.html

```
**My abc.wsgi is:**

```
#!/usr/bin/python3.6
import sys
import logging
logging.basicConfig(stream=sys.stderr)
print(sys.version)
sys.path.insert(0,"/var/www/EthApp/")
sys.path.append("/var/www/EthApp/EthApp/venv/lib64/python3.6/site-packages/")
print(sys.path)

from EthApp import app as application
application.secret_key = 'add key'
```

**Comment by pipermerriam** [comment]
This is going to be beyond our ability to debug for you but I suspect a problem with how you're configuring your `sys.path`.  If you activate your `venv` manually does that import work?  If not, then it might be a problem with your actual install of `cytoolz` at which point I'd recommend nuking your venv and reinstalling, paying attention to any errors during the install.

**Comment by BhumikaB** [comment]
yes it was error  with my sys.path,got solved thank you so much
