### ISSUE TITLE
Cannot connect to IPC socket path : None

### ISSUE THREAD

**Issue by warkechetan** [ethereum/web3.py#1327]
* Version: x.x.x
* Python:3.6.5
* OS: win 10 
* w3.eth.blockNumber() output

```
<put the output from running pip freeze here>
```Web3(HTTPProvider('http://localhost:8545'))
<web3.main.Web3 object at 0x00000261149D0470>
>>> web3.eth.blockNumber()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\eth.py", line 102, in blockNumber
    return self.web3.manager.request_blocking("eth_blockNumber", [])
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\manager.py", line 92, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\providers\ipc.py", line 220, in make_request
    with self._lock, self._socket as sock:
  File "C:\Users\Chetan\AppData\Local\Programs\Python\Python36\lib\site-packages\web3\providers\ipc.py", line 45, in __enter__
    raise FileNotFoundError("cannot connect to IPC socket at path: %r" % self.ipc_path)
FileNotFoundError: cannot connect to IPC socket at path: None
>>>

**Comment by kclowes** [comment]
I can't tell for sure, but it looks like you set `web3 = Web3(IPCProvider())` earlier (outside of what you pasted) and then didn't reset the variable to use the `HTTPProvider` `web3 = Web3(HTTPProvider('http://localhost:8545'))`. If you are trying to use the `HTTPProvider`, you should be able to say:

```
web3 = Web3(HTTPProvider('http://localhost:8545'))
web3.eth.blockNumber()
```

Feel free to reopen if that doesn't fix your problem!
