### ISSUE TITLE
Could not handle interface? Error: return data b'' for output_types ['bool']

### ISSUE THREAD

**Issue by aRooooooba** [ethereum/web3.py#1328]
* Web3 Version: 4.9.1
* Python: 3.7
* OS: win10
* `pip freeze` output

```
astroid==2.2.5
attrdict==2.0.1
beautifulsoup4==4.7.1
certifi==2019.3.9
chardet==3.0.4
colorama==0.4.1
cytoolz==0.9.0.1
eth-abi==1.3.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.1
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.4.1
hexbytes==0.1.0
idna==2.8
isort==4.3.16
lazy-object-proxy==1.3.1
lru-dict==1.1.6
mccabe==0.6.1
numpy==1.16.2
pandas==0.24.2
parsimonious==0.8.1
pycodestyle==2.5.0
pycryptodome==3.8.1
pylint==2.3.1
pypiwin32==223
python-dateutil==2.8.0
pytz==2019.1
pywin32==224
requests==2.21.0
rlp==1.1.0
semantic-version==2.6.0
six==1.12.0
soupsieve==1.9
toolz==0.9.0
typed-ast==1.3.1
urllib3==1.24.1
web3==4.9.1
websockets==6.0
wrapt==1.11.1
```

### What was wrong?
I was trying interface in solidity. It works well in remix. Because I have some trouble using local solc compiler, I used remix to compile (version: 0.5.1+commit.c8a2cb62.Emscripten.clang) and saved the abi and bytecode to local files. But it can't work properly using web3.py.

The two solidity files are as follows:

<interfaceTest1.sol>
```solidity
pragma solidity >=0.4.22 <0.6.0;

contract T1 {
    uint validRange = 10;

    function validate(uint input) external view returns(bool) {
        return input < validRange;
    }
}
```

<interfaceTest2.sol>
```solidity
pragma solidity >=0.4.22 <0.6.0;

import "./interfaceTest1.sol";


contract ValidInterface {
    function validate(uint input) public view returns(bool);
}

contract T2 {
    ValidInterface public validInterface;
    function setValidInterfaceAddress(address addr) external {
        validInterface = ValidInterface(addr);
    }

    function test(uint input) external view returns(bool) {
        return validInterface.validate(input);
    }
}
```
The python file is as follows:
```python
import pdb
import json
from web3 import Web3

# pdb.set_trace()
web3 = Web3(Web3.IPCProvider())
acc = web3.eth.accounts[0]
web3.personal.unlockAccount(acc, '111', 0)
with open('solidity/T1ABI.json', 'r') as T1ABIFile, \
     open('solidity/T1Bytecode.json', 'r') as T1BytecodeFile, \
     open('solidity/T2ABI.json', 'r') as T2ABIFile, \
     open('solidity/T2Bytecode.json', 'r') as T2BytecodeFile:
    t1ABI = json.load(T1ABIFile)
    t1Bytecode = json.load(T1BytecodeFile)
    t2ABI = json.load(T2ABIFile)
    t2Bytecode = json.load(T2BytecodeFile)

web3.eth.defaultAccount = acc
web3.miner.setEtherBase(acc)
web3.miner.start(1)

T1 = web3.eth.contract(abi=t1ABI, bytecode=t1Bytecode['object'])
t1TxHash = T1.constructor().transact()
T2 = web3.eth.contract(abi=t2ABI, bytecode=t2Bytecode['object'])
t2TxHash = T2.constructor().transact()

t1Receipt = web3.eth.waitForTransactionReceipt(t1TxHash)
t2Receipt = web3.eth.waitForTransactionReceipt(t2TxHash)
t1Addr = t1Receipt.contractAddress
t2Addr = t2Receipt.contractAddress

t1 = web3.eth.contract(address=t1Addr, abi=t1ABI)
t2 = web3.eth.contract(address=t2Addr, abi=t2ABI)

# preparation complete

t2.functions.setValidInterfaceAddress(t1Addr).transact()
print(t2.functions.test(4).call())
```
The error message is as follows:
```
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\web3\contract.py", line 1372, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "D:\Python37\lib\site-packages\eth_abi\abi.py", line 96, in decode_abi
    return decoder(stream)
  File "D:\Python37\lib\site-packages\eth_abi\decoding.py", line 118, in __call__
    return self.decode(stream)
  File "D:\Python37\lib\site-packages\eth_utils\functional.py", line 46, in inner
    return callback(fn(*args, **kwargs))
  File "D:\Python37\lib\site-packages\eth_abi\decoding.py", line 164, in decode
    yield decoder(stream)
  File "D:\Python37\lib\site-packages\eth_abi\decoding.py", line 118, in __call__
    return self.decode(stream)
  File "D:\Python37\lib\site-packages\eth_abi\decoding.py", line 186, in decode
    raw_data = self.read_data_from_stream(stream)
  File "D:\Python37\lib\site-packages\eth_abi\decoding.py", line 296, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\aRooba\documents\code\GraduationProject\back-end\web3_test.py", line 36, in <module>
    print(t2.functions.test(4).call())
  File "D:\Python37\lib\site-packages\web3\contract.py", line 1115, in call
    **self.kwargs
  File "D:\Python37\lib\site-packages\web3\contract.py", line 1394, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call test return data b'' for output_types ['bool']
```
Again, it works well on remix, and I was using remix compiled output. I used `web3.eth.getCode(t1Addr)` and `web3.eth.getCode(t2Addr)` , and both of them work well. Moreover, `t2.functions.validInterface().call() == t1.address` outputs `True`.

I was wondering if web3.py cannot handle interface?

### How can it be fixed?

I have no idea.

**Comment by aRooooooba** [comment]
Can anyone help me please?
Although actually it's not that serious to me :), I can realize the function from above the smart contract. But it does matters, doesn't it?

**Comment by kclowes** [comment]
That error indicates that your ABI defines that the output type of `test` should be a boolean, but a bytestring is being returned instead. So it looks like somehow `test` is returning a bytestring. My guess is that there is an error in your Solidity code somewhere, but there is nothing obviously wrong that jumps out at me. Sorry that's not more help!

**Comment by kclowes** [comment]
I was wrong earlier. @pipermerriam pointed out that the error is actually saying that decoding a boolean requires `\x00` or` \x01` but it's getting an empty byte string. However, this is likely related to [this](https://github.com/ethereum/go-ethereum/issues/19186) go-ethereum bug. There are also some more details on [this thread](https://github.com/ethereum/web3.py/issues/1257). Sorry for the confusion! Closing since this doesn't appear to be a web3 bug.
