### ISSUE TITLE
Error in installation (fresh venv): Cannot import name `scrypt`

### ISSUE THREAD

**Issue by yrdeboer** [ethereum/web3.py#1375]
* Version: 4.9.2
* Python: 3.6
* OS: Ubuntu 16.04 LTS (Linux 4.18.0-21-generic #22-Ubuntu SMP Wed May 15 13:13:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)
* `pip freeze` output

```
apt-xapian-index==0.47
apturl==0.5.2
asn1crypto==0.24.0
attrdict==2.0.1
awscli==1.16.26
beautifulsoup4==4.6.3
blinker==1.4
Brlapi==0.6.7
cached-property==1.4.0
certifi==2018.8.24
chardet==3.0.4
checkbox-support==0.22
colorama==0.3.7
command-not-found==0.3
cryptography==2.3
cupshelpers==1.0
cytoolz==0.9.0.1
defer==1.0.6
distro==1.3.0
distro-info===0.18ubuntu0.18.10.2
docker==3.4.1
docker-compose==1.21.0
docker-pycreds==0.2.2
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
elpy==1.23.0
entrypoints==0.2.3.post3
eth-abi==1.3.0
eth-account==0.3.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.6.1
feedparser==5.2.1
flake8==3.5.0
graphviz==0.8.4
guacamole==0.9.2
hexbytes==0.2.0
html5lib==1.0.1
httplib2==0.11.3
idna==2.6
jedi==0.12.0
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
keyring==15.1.0
keyrings.alt==3.1
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.14.0
lazr.uri==1.0.3
louis==3.6.0
lru-dict==1.1.6
lxml==4.2.5
Mako==1.0.7
MarkupSafe==1.0
mccabe==0.6.1
netifaces==0.10.4
oauthlib==2.0.6
olefile==0.46
onboard==1.4.1
oneconf==0.3.9
padme==1.1.1
parsimonious==0.8.1
parso==0.2.1
pexpect==4.6.0
Pillow==5.2.0
piston-mini-client==0.7.5
pkg-resources==0.0.0
plainbox==0.25
pyasn1==0.4.2
pycairo==1.16.2
pycodestyle==2.4.0
pycrypto==2.6.1
pycryptodome==3.8.2
pycups==1.9.73
pycurl==7.43.0.1
pyflakes==1.6.0
Pygments==2.2.0
PyGObject==3.30.1
PyJWT==1.6.4
pyparsing==2.2.0
python-apt==1.7.1
python-dateutil==2.6.1
python-debian==0.1.33
pyxdg==0.25
PyYAML==3.12
reportlab==3.5.6
requests==2.18.4
requests-unixsocket==0.1.5
rlp==1.1.0
roman==2.0.0
rsa==3.4.2
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
simplejson==3.15.0
six==1.11.0
software-center-aptd-plugins==0.0.0
ssh-import-id==5.7
system-service==0.3
systemd-python==234
texttable==1.4.0
toolz==0.9.0
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
urllib3==1.22
usb-creator==0.3.3
virtualenv==15.1.0
wadllib==1.3.3
web3==4.9.2
webencodings==0.5
websocket-client==0.53.0
websockets==6.0
xdiagnose==3.8.8
xdot==0.9
xkit==0.0.0
XlsxWriter==0.9.6


```

### What was wrong?

I carefully followed the instructions here: https://web3py.readthedocs.io/en/stable/troubleshooting.html#setup-environment

Then I try to import web3, and I get an error:

```
ImportError: cannot import name 'scrypt'
```

There is another ticket with the same issue, but that fix does not work for me: https://github.com/ethereum/web3.py/issues/751

Included:
* The code which produced the error
* The full output of the error

```
myname@mydevice:/ntfs/projects/gsmg$ echo $PYTHONPATH
/usr/lib/python3/dist-packages
myname@mydevice:/ntfs/projects/gsmg$ echo $PATH
/home/myname/bin:/home/myname/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/go/bin:/ntfs/projects/fabric/fabric-samples/bin:/usr/local/go/bin:/ntfs/projects/fabric/fabric-samples/bin
myname@mydevice:/ntfs/projects/gsmg$ virtualenv -p `which python3.6` venv4web3
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /ntfs/projects/gsmg/venv4web3/bin/python3.6
Also creating executable in /ntfs/projects/gsmg/venv4web3/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
myname@mydevice:/ntfs/projects/gsmg$ source venv4web3/bin/activate
(venv4web3) myname@mydevice:/ntfs/projects/gsmg$ pip install --upgrade pip setuptools
Requirement already up-to-date: pip in ./venv4web3/lib/python3.6/site-packages (19.1.1)
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
ERROR: launchpadlib 1.10.6 requires testresources, which is not installed.
Installing collected packages: setuptools
  Found existing installation: setuptools 40.2.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /ntfs/projects/gsmg/venv4web3
    Can't uninstall 'setuptools'. No files were found to uninstall.
Successfully installed setuptools-41.0.1
(venv4web3) myname@mydevice:/ntfs/projects/gsmg$ pip install --no-cache-dir --upgrade   web3
Collecting web3
  Downloading https://files.pythonhosted.org/packages/24/f5/3d6e3ac1ec98dc736084a8f821b922517d5492714889bf29460d9d97bda0/web3-4.9.2-py3-none-any.whl (124kB)
     |████████████████████████████████| 133kB 1.7MB/s 
Collecting eth-utils<2.0.0,>=1.2.0 (from web3)
  Downloading https://files.pythonhosted.org/packages/f4/cd/2aa6cc8acd3837aafa4f0763213be4b48bae93f68b042decac9a07e58d65/eth_utils-1.6.1-py3-none-any.whl
Collecting lru-dict<2.0.0,>=1.1.6 (from web3)
  Downloading https://files.pythonhosted.org/packages/00/a5/32ed6e10246cd341ca8cc205acea5d208e4053f48a4dced2b1b31d45ba3f/lru-dict-1.1.6.tar.gz
Collecting hexbytes<1.0.0,>=0.1.0 (from web3)
  Downloading https://files.pythonhosted.org/packages/4e/99/7e0c9a2f74f2a0b4512bd4491334537f4a3418a4daec6ae90ed5cd8d6b89/hexbytes-0.2.0-py3-none-any.whl
Collecting eth-hash[pycryptodome]<1.0.0,>=0.2.0 (from web3)
  Downloading https://files.pythonhosted.org/packages/0d/d8/0f0c8d4ccaa4c8d25524fd1ed9f5c6d9551b52b74b973f338de3f0a23111/eth_hash-0.2.0-py3-none-any.whl
Collecting websockets<7.0.0,>=6.0.0 (from web3)
  Downloading https://files.pythonhosted.org/packages/5c/fe/99aeaf97985585baefca8d56125ec828ef5549276324ec319b63a4da686d/websockets-6.0-cp36-cp36m-manylinux1_x86_64.whl (88kB)
     |████████████████████████████████| 92kB 9.7MB/s 
Collecting eth-abi<2.0.0,>=1.2.0 (from web3)
  Downloading https://files.pythonhosted.org/packages/e9/ef/5af786a32ae7ac3aece6489400ea2cee6b2ede7a7b3955e6f55a59442d12/eth_abi-1.3.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: requests<3.0.0,>=2.16.0 in /usr/lib/python3/dist-packages (from web3) (2.18.4)
Collecting eth-account<0.4.0,>=0.2.1 (from web3)
  Downloading https://files.pythonhosted.org/packages/a3/d8/6118bc0e00d6ec092bb02b012989d1018893755eb84da53266412ac359e3/eth_account-0.3.0-py3-none-any.whl
Collecting cytoolz<1.0.0,>=0.9.0; implementation_name == "cpython" (from web3)
  Downloading https://files.pythonhosted.org/packages/36/f4/9728ba01ccb2f55df9a5af029b48ba0aaca1081bbd7823ea2ee223ba7a42/cytoolz-0.9.0.1.tar.gz (443kB)
     |████████████████████████████████| 450kB 8.8MB/s 
Collecting eth-typing<3.0.0,>=1.0.0 (from eth-utils<2.0.0,>=1.2.0->web3)
  Downloading https://files.pythonhosted.org/packages/3e/8e/45c4779d98e43c166738a606b021f32a7a70c4c0d8c524c28f0703325409/eth_typing-2.1.0-py3-none-any.whl
Collecting pycryptodome<4,>=3.6.6; extra == "pycryptodome" (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3)
  Downloading https://files.pythonhosted.org/packages/9f/2a/d4f6b8802cc9b428f285cad6ff486ecacc8d3ae7c8cdccaae26359ccac4e/pycryptodome-3.8.2-cp36-cp36m-manylinux1_x86_64.whl (9.6MB)
     |████████████████████████████████| 9.6MB 7.5MB/s 
Collecting parsimonious<0.9.0,>=0.8.0 (from eth-abi<2.0.0,>=1.2.0->web3)
  Downloading https://files.pythonhosted.org/packages/02/fc/067a3f89869a41009e1a7cdfb14725f8ddd246f30f63c645e8ef8a1c56f4/parsimonious-0.8.1.tar.gz (45kB)
     |████████████████████████████████| 51kB 13.9MB/s 
Collecting eth-keyfile<0.6.0,>=0.5.0 (from eth-account<0.4.0,>=0.2.1->web3)
  Downloading https://files.pythonhosted.org/packages/eb/a5/3615d100b62fbf20fe5d5c0d1d4d7326eac861d260b0cd2a36af2bf8ccb1/eth_keyfile-0.5.1-py3-none-any.whl
Collecting eth-keys<0.3.0,>=0.2.0b3 (from eth-account<0.4.0,>=0.2.1->web3)
  Downloading https://files.pythonhosted.org/packages/61/4f/d8e778e377e0b9287b5ffc7ecc4e3b1e9d3045030d391acc7328e23708f2/eth_keys-0.2.4-py3-none-any.whl
Collecting attrdict<3,>=2.0.0 (from eth-account<0.4.0,>=0.2.1->web3)
  Downloading https://files.pythonhosted.org/packages/ef/97/28fe7e68bc7adfce67d4339756e85e9fcf3c6fd7f0c0781695352b70472c/attrdict-2.0.1-py2.py3-none-any.whl
Collecting eth-rlp<1,>=0.1.2 (from eth-account<0.4.0,>=0.2.1->web3)
  Downloading https://files.pythonhosted.org/packages/56/4b/b309fb44dd9bb975e84f3d626392eec1eeed0108e55a51cd7dd8956a73ad/eth_rlp-0.1.2-py3-none-any.whl
Collecting toolz>=0.8.0 (from cytoolz<1.0.0,>=0.9.0; implementation_name == "cpython"->web3)
  Downloading https://files.pythonhosted.org/packages/14/d0/a73c15bbeda3d2e7b381a36afb0d9cd770a9f4adc5d1532691013ba881db/toolz-0.9.0.tar.gz (45kB)
     |████████████████████████████████| 51kB 15.0MB/s 
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /usr/lib/python3/dist-packages (from parsimonious<0.9.0,>=0.8.0->eth-abi<2.0.0,>=1.2.0->web3) (1.11.0)
Collecting rlp<2,>=0.6.0 (from eth-rlp<1,>=0.1.2->eth-account<0.4.0,>=0.2.1->web3)
  Downloading https://files.pythonhosted.org/packages/54/d4/3013691b8c4702cb1c3253be643f2cef12e9bee93e134694e6dab83f41e2/rlp-1.1.0-py2.py3-none-any.whl
Building wheels for collected packages: lru-dict, cytoolz, parsimonious, toolz
  Building wheel for lru-dict (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-dnyk7z9x/wheels/b7/ef/06/fbdd555907a7d438fb33e4c8675f771ff1cf41917284c51ebf
  Building wheel for cytoolz (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-dnyk7z9x/wheels/88/f3/11/9817b001e59ab04889e8cffcbd9087e2e2155b9ebecfc8dd38
  Building wheel for parsimonious (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-dnyk7z9x/wheels/b7/8d/e7/a0e74217da5caeb3c1c7689639b6d28ddbf9985b840bc96a9a
  Building wheel for toolz (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-dnyk7z9x/wheels/f4/0c/f6/ce6b2d1aa459ee97cc3c0f82236302bd62d89c86c700219463
Successfully built lru-dict cytoolz parsimonious toolz
Installing collected packages: toolz, cytoolz, eth-typing, pycryptodome, eth-hash, eth-utils, lru-dict, hexbytes, websockets, parsimonious, eth-abi, eth-keys, eth-keyfile, attrdict, rlp, eth-rlp, eth-account, web3
Successfully installed attrdict-2.0.1 cytoolz-0.9.0.1 eth-abi-1.3.0 eth-account-0.3.0 eth-hash-0.2.0 eth-keyfile-0.5.1 eth-keys-0.2.4 eth-rlp-0.1.2 eth-typing-2.1.0 eth-utils-1.6.1 hexbytes-0.2.0 lru-dict-1.1.6 parsimonious-0.8.1 pycryptodome-3.8.2 rlp-1.1.0 toolz-0.9.0 web3-4.9.2 websockets-6.0
(venv4web3) myname@mydevice:/ntfs/projects/gsmg$ python
Python 3.6.8 (default, Apr  9 2019, 04:59:38) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import web3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ntfs/projects/gsmg/venv4web3/lib/python3.6/site-packages/web3/__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "/ntfs/projects/gsmg/venv4web3/lib/python3.6/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/ntfs/projects/gsmg/venv4web3/lib/python3.6/site-packages/eth_account/account.py", line 10, in <module>
    from eth_keyfile import (
  File "/ntfs/projects/gsmg/venv4web3/lib/python3.6/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/ntfs/projects/gsmg/venv4web3/lib/python3.6/site-packages/eth_keyfile/keyfile.py", line 7, in <module>
    from Crypto.Protocol.KDF import scrypt
ImportError: cannot import name 'scrypt'

```

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by yrdeboer** [comment]
Finally, (not sure how I did it), I got it to run.
Because I am not sure whether it had something to do with my PYTHONPATH, I will close the issue.
