### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by tycooperaow** [ethereum/web3.py#1377]
* Version: latest
* Python: 3.7.0
* OS: win
* `pip freeze` output

### What was wrong?
I consistently receive this error with my dapp regardless that I have web3 and pycryptodome installed on my computer and virtual environment. 

```
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from api import app
  File "C:\Users\Ty Cooper\Desktop\Coding\Projects\streamline\server\api\__init__.py", line 46, in <module>
    from api import endpoints, block, admin
  File "C:\Users\Ty Cooper\Desktop\Coding\Projects\streamline\server\api\endpoints.py", line 9, in <module>
    from web3 import Web3
  File "C:\Users\Ty Cooper\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "C:\Users\Ty Cooper\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_account\__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "C:\Users\Ty Cooper\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_account\account.py", line 10, in <module>
    from eth_keyfile import (
  File "C:\Users\Ty Cooper\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_keyfile\__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "C:\Users\Ty Cooper\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_keyfile\keyfile.py", line 5, in <module>
    from Crypto import Random
ModuleNotFoundError: No module named 'Crypto'

```

Please include any of the following that are applicable:

* The code which produced the error
The code occurs in my routes file when I am importing web3 then onward it is tracing back through the library. For some reason the file states it could not find the 'Crypto' module and I have no control over finding out how this could occurred. It happened out of nowhere.

* What type of node you were connecting to.

I was connected to Ganache, but the connection to the blockchain isn't the issue.

**Comment by tycooperaow** [comment]
I have solved it! 

The folders in the crypto site packages were all lowercase and python is case sensitive! Changing 'crypto' to 'Crypto' and along with all of the other sub-folders in 'Crypto' worked!
