### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R

### ISSUE THREAD

**Issue by tyyen** [ethereum/web3.py#1448]
* Version: 1.8.11-stable
* Go Version: go1.10
* Python: 3.6
* OS: linux

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/test/flask_web.py", line 144, in verify
    tx_hash = w3.eth.sendRawTransaction(RawTx)
  File "/usr/local/lib/python3.6/dist-packages/web3/eth.py", line 275, in sendRawTransaction
    [raw_transaction],
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R'}
```

I form the raw transaction and send it. Most of the times it succeeds, but sometime it shows this error. It seems that the problem is the transaction signature in which R is 0x0003....
Sorry that the raw transaction hex string including signature is lost. I only remember that the signature R starts with 0x0003.... and S starts with non-zero digits.

**Comment by kclowes** [comment]
Any chance you can send a code snippet that reproduces the error, even if it doesn't happen every time?

**Comment by tyyen** [comment]
The error happened when 

- the private key is: 0x3A5703FD7C90E76E3EA34D08B0EC102E50EB97BE7AFA508CEDD7B7CC8B1FC6BB

- the transaction is as below

```
nonce: 25
gasPrice: 0x23cace
gas: 0x47b760
to: 0xedfd839d99d4af368698bab3b88a576ec7088c49
value: 0
data: 0x64c02b4400000000000000000000000000000000000000000000000000000000000000600000000000000000000000003e4f577d594841536ca8ffe90da79d69b8b24f83000000000000000000000000000000000000000000000000000000005ce5fea5000000000000000000000000000000000000000000000000000000000000000a6e756d4465766963653300000000000000000000000000000000000000000000
```

I use RLP, keccak hash and ecc signature of nodejs package to make ethereum raw transaction
```
let result = RLP.encode([nonce, gasPrice, gas, address, value, data]);
let hash_result = keccak256(Buffer.from(result));
let sig_result = secp256k1.sign(hash_result, privKey)

let v = Buffer.from((27 + sig_result.recovery).toString(16), 'hex');
let r = sig_result.signature.slice(0,32);
let s = sig_result.signature.slice(32,64);
console.log('sig (v): ', v.toString('hex'));
console.log('sig (r): ', r.toString('hex'));
console.log('sig (s): ', s.toString('hex'));

let result_final = RLP.encode([nonce, gasPrice, gas, address, value, data, v, r, s]);
console.log('rawtx: ', result_final.toString('hex'));
```
And the running result is
```
sig (v):  1b
sig (r):  398ba5b2a8537ba8a867e806455da60507c25653d793fb160438d7af373bdf45
sig (s):  00b86e90705a0d2b72ed7f74e8cc9de2da4a6508bd5cf2b4ad8f3c79ede3b366

rawtx: f90108198323cace8347b76094edfd839d99d4af368698bab3b88a576ec7088c4980b8a464c02b4400000000000000000000000000000000000000000000000000000000000000600000000000000000000000003e4f577d594841536ca8ffe90da79d69b8b24f83000000000000000000000000000000000000000000000000000000005ce5fea5000000000000000000000000000000000000000000000000000000000000000a6e756d44657669636533000000000000000000000000000000000000000000001ba0398ba5b2a8537ba8a867e806455da60507c25653d793fb160438d7af373bdf45a000b86e90705a0d2b72ed7f74e8cc9de2da4a6508bd5cf2b4ad8f3c79ede3b366
```

Then use web3.py to sendRawTransaction
```
tx_hash = w3.eth.sendRawTransaction(RawTx)
w3.eth.waitForTransactionReceipt(tx_hash)
```

Error happened
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/test/flask_web.py", line 144, in verify
    tx_hash = w3.eth.sendRawTransaction(RawTx)
  File "/usr/local/lib/python3.6/dist-packages/web3/eth.py", line 275, in sendRawTransaction
    [raw_transaction],
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R'}
```

It seems that it's due to the leading zeros of signature R-part

**Comment by anysoft** [comment]
> * Version: 1.8.11-stable
> * Go Version: go1.10
> * Python: 3.6
> * OS: linux
> 
> ```
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
>     response = self.handle_exception(e)
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/ubuntu/test/flask_web.py", line 144, in verify
>     tx_hash = w3.eth.sendRawTransaction(RawTx)
>   File "/usr/local/lib/python3.6/dist-packages/web3/eth.py", line 275, in sendRawTransaction
>     [raw_transaction],
>   File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 112, in request_blocking
>     raise ValueError(response["error"])
> ValueError: {'code': -32000, 'message': 'rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R'}
> ```
> 
> I form the raw transaction and send it. Most of the times it succeeds, but sometime it shows this error. It seems that the problem is the transaction signature in which R is 0x0003....
> Sorry that the raw transaction hex string including signature is lost. I only remember that the signature R starts with 0x0003.... and S starts with non-zero digits.

you can  see this issue https://github.com/MOACChain/moac-core/issues/24

**Comment by kclowes** [comment]
Closing, related downstream issue is closed.
