### ISSUE TITLE
websocket is not stable

### ISSUE THREAD

**Issue by NateYan** [ethereum/web3.py#1458]
* Version: 5.0.2
* Python: 3.7.4
* OS: win
* `pip freeze` output
```
attrdict==2.0.1
base58==1.0.3
certifi==2019.9.11
chardet==3.0.4
Click==7.0
cytoolz==0.10.0
eth-abi==2.0.0
eth-account==0.4.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.7.0
Flask==1.1.1
Flask-SQLAlchemy==2.4.0
hexbytes==0.2.0
idna==2.8
ipfshttpclient==0.4.12
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==2.6.0
lru-dict==1.1.6
MarkupSafe==1.1.1
multiaddr==0.0.8
netaddr==0.7.19
parsimonious==0.8.1
protobuf==3.9.1
pycryptodome==3.9.0
pypiwin32==223
pywin32==224
requests==2.22.0
rlp==1.1.0
six==1.12.0
SQLAlchemy==1.3.8
toolz==0.10.0
urllib3==1.25.3
varint==1.0.2
web3==5.0.2
websockets==7.0
Werkzeug==0.15.6
```

### What was wrong?
```
When I run the following code, like 2 out 10 times, it will be OK, but other times it will fail with error.

`from web3 import Web3

if __name__ == '__main__':

    infura_url_http = 'https://mainnet.infura.io/v3/my-project-id'
    infura_url_ws = 'wss://mainnet.infura.io/ws/v3/my-project-id'

    ws3 = Web3(Web3.WebsocketProvider(infura_url_ws))
    wh3 = Web3(Web3.HTTPProvider(infura_url_http))

    abi = [{"name": "NewExchange", "inputs": [{"type": "address", "name": "token", "indexed": True}, {"type": "address", "name": "exchange", "indexed": True}], "anonymous": False, "type": "event"}]

    uniswap = ws3.eth.contract('0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95', abi=abi)
    events = uniswap.events.NewExchange.createFilter(fromBlock = 8575500).get_all_entries()#8585567
    print(event)`
```
Error message:
Traceback (most recent call last):
  File "D:\defi\web3\uniswap.py", line 14, in <module>
    events = uniswap.events.NewExchange.createFilter(fromBlock = 8575500).get_all_entries()#8585567
  File "D:\defi\lib\site-packages\web3\_utils\decorators.py", line 16, in _wrapper
    return self.method(objtype, *args, **kwargs)
  File "D:\defi\lib\site-packages\web3\contract.py", line 1092, in createFilter
    log_filter = filter_builder.deploy(self.web3)
  File "D:\defi\lib\site-packages\web3\_utils\events.py", line 364, in deploy
    log_filter = w3.eth.filter(self.filter_params)
  File "D:\defi\lib\site-packages\web3\eth.py", line 390, in filter
    [filter_params],
  File "D:\defi\lib\site-packages\web3\manager.py", line 94, in request_blocking
    response = self._make_request(method, params)
  File "D:\defi\lib\site-packages\web3\manager.py", line 81, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "D:\defi\lib\site-packages\web3\middleware\formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "D:\defi\lib\site-packages\web3\middleware\gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "D:\defi\lib\site-packages\web3\middleware\formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "D:\defi\lib\site-packages\web3\middleware\attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "D:\defi\lib\site-packages\web3\middleware\formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "D:\defi\lib\site-packages\web3\middleware\normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "D:\defi\lib\site-packages\web3\middleware\formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "D:\defi\lib\site-packages\web3\middleware\formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "D:\defi\lib\site-packages\web3\providers\websocket.py", line 119, in make_request
    return future.result()
  File "d:\python37_32\Lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "d:\python37_32\Lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\defi\lib\site-packages\web3\providers\websocket.py", line 107, in coro_make_request
    timeout=self.websocket_timeout
  File "d:\python37_32\Lib\asyncio\tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[Finished in 44.0s with exit code 1]

### How can it be fixed?

I tried to add request_kwargs={'timeout':60} when initiating provider, but it did not work.

**Comment by voith** [comment]
> createFilter(fromBlock = 8575500).get_all_entries()

You seem to be requesting all entries from block `8575500`. Infura barfs if you request a lot of data. I've had similar problems in the past and I solved them by requesting data in batches instead of getting them in one go.  In my case, I fetch data for 50 blocks at a time. You could do this by using a combination of `fromBlock` and `toBlock`  such that the requested blocks are not more than 50.

**Comment by NateYan** [comment]
Thanks!
Several days ago, it works when I use the method as you said. But now it does not work.

**Comment by khssnv** [comment]
I have an issue the same.

* web3py version: `5.0.2`

```console
$ python -V
Python 3.7.4rc1

$ cat /etc/lsb-release | grep DESCRIPTION
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```

<details>
  <summary>$ pip freeze</summary>

```console
attrdict==2.0.1
backcall==0.1.0
base58==1.0.3
certifi==2019.6.16
chardet==3.0.4
Click==7.0
cytoolz==0.10.0
decorator==4.4.0
dnspython==1.16.0
email-validator==1.0.4
et-xmlfile==1.0.1
eth-abi==2.0.0
eth-account==0.4.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.6.4
fancycompleter==0.8
fastapi==0.36.0
h11==0.8.1
hexbytes==0.2.0
httptools==0.0.13
idna==2.8
ipfshttpclient==0.4.12
ipython==7.8.0
ipython-genutils==0.2.0
jdcal==1.4.1
jedi==0.15.1
jsonschema==2.6.0
lru-dict==1.1.6
morphys==1.0
motor==2.0.0
multiaddr==0.0.8
netaddr==0.7.19
numpy==1.17.2
openpyxl==2.6.3
pandas==0.25.1
parsimonious==0.8.1
parso==0.5.1
pdbpp==0.10.0
pexpect==4.7.0
pickleshare==0.7.5
prompt-toolkit==2.0.9
protobuf==3.9.1
ptyprocess==0.6.0
py-multihash==0.2.3
pycryptodome==3.9.0
pydantic==0.30
Pygments==2.4.2
pymongo==3.9.0
python-dateutil==2.8.0
pytz==2019.2
requests==2.22.0
rlp==1.1.0
six==1.12.0
starlette==0.12.7
toolz==0.10.0
traitlets==4.3.2
urllib3==1.25.3
uvicorn==0.8.6
uvloop==0.12.2
varint==1.0.2
wcwidth==0.1.7
web3==5.0.2
websockets==7.0
wmctrl==0.3
xlrd==1.2.0
```
</details>


<details>
  <summary>exec log</summary>

```console
khassanov@32vd $ python ipci.py
Starting IPCI poller
Starting burn operations updater
Task exception was never retrieved
future: <Task finished coro=<carbon_units_burn_operations_updater() done, defined at ipci.py:90> exception=TimeoutError()>
Traceback (most recent call last):
  File "ipci.py", line 105, in carbon_units_burn_operations_updater
    fromBlock=FROM_BLOCK
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/_utils/decorators.py", line 14, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/contract.py", line 1092, in createFilter
    log_filter = filter_builder.deploy(self.web3)
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/_utils/events.py", line 364, in deploy
    log_filter = w3.eth.filter(self.filter_params)
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/eth.py", line 390, in filter
    [filter_params],
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/manager.py", line 94, in request_blocking
    response = self._make_request(method, params)
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/manager.py", line 81, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/providers/websocket.py", line 119, in make_request
    return future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/khassanov/Workspace/NU_DAO/server/venv-py37/lib/python3.7/site-packages/web3/providers/websocket.py", line 107, in coro_make_request
    timeout=self.websocket_timeout
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```
</details>

**Comment by voith** [comment]
from my past experience, I can tell that this happens because infura barfs occasionally. Try playing with any other websocket tool to check if infura still works fine. I usually use [wscat](https://www.npmjs.com/package/wscat) to test.
Here's an example to test filters on ifura using wscat: https://github.com/ethereum/web3.py/issues/1062#issuecomment-422166278
If infura works fine with any other websocket library then we can say that this a bug in the `WebsocketProvider` else file a bug report to infura.

**Comment by khssnv** [comment]
I've used to test with `wscat` like `npx wscat -c wss://mainnet.infura.io/ws/v3/{myid}` and it opens connection while `.get_all_entries()` fails with `TimeoutError`.

**Comment by kclowes** [comment]
@khssnv I am consistently getting events back using web3 via websockets when trying to replicate the original issue, do you have another snippet I can try? Maybe even this one: 

> sometimes even a call to read contract variable like ERC20 decimals

**Comment by fselmo** [comment]
Closing due to staleness and doesn't seem to be a `web3.py` bug 🐛 🤔 ... please feel free to re-open / restart the conversation if this is still relevant as a library issue
