### ISSUE TITLE
Event().createFilter() doesn't work(w3.eth.filter)

### ISSUE THREAD

**Issue by Leekyungun** [ethereum/web3.py#1466]
* Version: 5.0.2
* Python: 3.7
* OS: linux
* `pip freeze` output

```
asn1crypto==0.24.0
attrdict==2.0.1
base58==1.0.3
bcrypt==3.1.7
boto==2.49.0
boto3==1.9.234
botocore==1.12.234
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
cryptography==2.7
cytoolz==0.10.0
Django==2.2.3
django-cors-headers==3.0.2
docutils==0.15.2
eth-abi==2.0.0
eth-account==0.4.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.1.0
eth-utils==1.7.0
hexbytes==0.2.0
idna==2.8
ipfshttpclient==0.4.12
jmespath==0.9.4
jsonschema==2.6.0
jwt==0.6.1
lru-dict==1.1.6
multiaddr==0.0.8
netaddr==0.7.19
parsimonious==0.8.1
protobuf==3.9.1
pycparser==2.19
pycryptodome==3.9.0
PyJWT==1.7.1
python-dateutil==2.8.0
pytz==2019.1
redis==3.2.1
requests==2.22.0
rlp==1.1.0
s3transfer==0.2.1
simple-websocket-server==0.4.0
six==1.12.0
sqlparse==0.3.0
toolz==0.10.0
urllib3==1.25.3
varint==1.0.2
web3==5.0.2
websocket-client==0.56.0
websockets==7.0
```

### What was wrong?
What is the reason for the error below?

> source code:
``` python
w3 = Web3(Web3.HTTPProvider('https://kovan.infura.io/v3/{PRIVATE_ID}'))

contract = w3.eth.contract(address=CONTROLLERADDRESS, abi=abi)
    event_filter = contract.events.Deposit.createFilter(fromBlock=1, toBlock='latest')
    while True:
        print(event_filter.get_all_entries())
        time.sleep(2)
```

> Result:
```
Traceback (most recent call last):
  File "contract_event_test.py", line 15, in <module>
    contract_instance = w3.eth.contract(contract_abi, contract_address, ContractFactoryClass=ConciseContract)
TypeError: contract() takes from 1 to 2 positional arguments but 3 were given
(python3) [centos@localhost wallet_test]$ python web3_contract_test.py 
Traceback (most recent call last):
  File "web3_contract_test.py", line 53, in <module>
    detect_deposit()
  File "web3_contract_test.py", line 47, in detect_deposit
    event_filter = contract.events.Deposit.createFilter(fromBlock=1, toBlock='latest')
  File "/data/venv/python3/lib/python3.7/site-packages/web3/_utils/decorators.py", line 16, in _wrapper
    return self.method(objtype, *args, **kwargs)
  File "/data/venv/python3/lib/python3.7/site-packages/web3/contract.py", line 1092, in createFilter
    log_filter = filter_builder.deploy(self.web3)
  File "/data/venv/python3/lib/python3.7/site-packages/web3/_utils/events.py", line 364, in deploy
    log_filter = w3.eth.filter(self.filter_params)
  File "/data/venv/python3/lib/python3.7/site-packages/web3/eth.py", line 390, in filter
    [filter_params],
  File "/data/venv/python3/lib/python3.7/site-packages/web3/manager.py", line 97, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'The method eth_newFilter does not exist/is not available'}
```

**Comment by pipermerriam** [comment]
This is because infura doesn't support event filters.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Leekyungun** [comment]
Thank you. 
I'm designing with a WebSocket.
