### ISSUE TITLE
timeout when listening to events from Infura Ropsten websocket (works in web3.js though)

### ISSUE THREAD

**Issue by jerryji** [ethereum/web3.py#1523]
* Version: 5.3.0
* Python: 3.6.8
* OS: Linux (Ubuntu 18.04)
* `pip freeze` output

```
web3==5.3.0
...
```

### What was wrong?

Timeout when listening to events from Infura Ropsten via websocket, but the same implementation works in web3.js

The code can be found at  https://github.com/jerryji/ropsten_wss_timeout_demo.git  (instructions in README.md) --

```
$ python ropsten_wss_timeout_demo.py 
fromBlock=6807400, BrickTransfer succeeds, but EthUpdate will timeout
^CTraceback (most recent call last):
  File "ropsten_wss_timeout_demo.py", line 43, in <module>
    all_entries = event_filter.get_all_entries()
  File "/usr/local/lib/python3.6/dist-packages/web3/_utils/filters.py", line 125, in get_all_entries
    log_entries = self._filter_valid_entries(self.web3.eth.getFilterLogs(self.filter_id))
  File "/usr/local/lib/python3.6/dist-packages/web3/eth.py", line 407, in getFilterLogs
    "eth_getFilterLogs", [filter_id],
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 96, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 51, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 51, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 51, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 51, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 51, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/providers/websocket.py", line 122, in make_request
    return future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 427, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
```

### How can it be fixed?

IDK, why does the same implementation work in web3.js but not in web3.py? Can any polyglot wizard please shed some light?

**Comment by kclowes** [comment]
Thank you for such a detailed report @jerryji! I should be able to look into it next week, unless someone gets there ahead of me :)

**Comment by kclowes** [comment]
Closing, this issue is stale. We have a new WebsocketProvider coming in v7. Docs can be found [here](https://web3py.readthedocs.io/en/stable/providers.html#websocketproviderv2-beta).
