### ISSUE TITLE
Could not decode contract function call GetTask return data b'' for output_types ['(string[3],string[2],int256[3],string[2],string)']

### ISSUE THREAD

**Issue by R31N3** [ethereum/web3.py#1604]
* Version: 5.4.0
* Python: 3.8
* OS: osx/linux/win
* `pip freeze` output

```
adal==1.2.2
aiocontextvars==0.2.2
aiofiles==0.4.0
aiohttp==3.6.2
aiosmtplib==1.1.2
APScheduler==3.6.3
apt-clone==0.2.1
apturl==0.5.2
async-lru==1.0.2
async-timeout==3.0.1
asyncpg==0.20.1
attrdict==2.0.1
attrs==19.3.0
base58==2.0.0
beautifulsoup4==4.6.0
Brlapi==0.6.6
catfish==1.4.10
certifi==2018.1.18
cffi==1.14.0
chardet==3.0.4
click==7.1.1
command-not-found==0.3
configobj==5.0.6
coverage==5.0.3
cryptography==2.8
cupshelpers==1.0
CurrencyConverter==0.14.1
cytoolz==0.10.1
defer==1.0.6
et-xmlfile==1.0.1
eth-abi==2.1.1
eth-account==0.4.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.2.1
eth-utils==1.8.4
Faker==4.0.0
fastapi==0.52.0
gino==0.8.6
gunicorn==20.0.4
h11==0.9.0
h2==3.2.0
hexbytes==0.2.0
hpack==3.0.0
hstspreload==2020.3.12
httplib2==0.9.2
httptools==0.0.13
httpx==0.11.1
hyperframe==5.2.0
idna==2.6
ipfshttpclient==0.4.12
jdcal==1.4.1
Jinja2==2.11.1
jsonschema==3.2.0
louis==3.5.0
lru-dict==1.1.6
lxml==4.4.1
Mako==1.0.7
MarkupSafe==1.0
menulibre==2.2.1
more-itertools==8.2.0
mugshot==0.4.2
multiaddr==0.0.9
multidict==4.7.5
mypy-extensions==0.4.3
netaddr==0.7.19
netifaces==0.10.4
Office365-REST-Python-Client==2.1.5
onboard==1.4.1
openpyxl==3.0.3
packaging==20.3
parsimonious==0.8.1
passlib==1.7.2
pexpect==4.2.1
Pillow==5.1.0
pluggy==0.13.1
protobuf==3.11.3
psutil==5.4.2
py==1.8.1
pycairo==1.16.2
pycparser==2.20
pycrypto==2.6.1
pycryptodome==3.9.7
pycups==1.9.73
pycurl==7.43.0.1
pydantic==1.4
pygobject==3.26.1
PyICU==1.9.8
PyJWT==1.7.1
pyparsing==2.4.6
pyparted==3.11.1
pyrsistent==0.15.7
pytest==5.3.2
pytest-cov==2.8.1
python-apt==1.6.5+ubuntu0.2
python-dateutil==2.8.1
python-debian==0.1.32
python-xapp==1.8.1
pytz==2019.3
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.22.0
requests-unixsocket==0.1.5
rfc3986==1.3.2
rlp==1.2.0
sessioninstaller==0.0.0
setproctitle==1.1.10
six==1.11.0
sniffio==1.1.0
SQLAlchemy==1.3.15
starlette==0.13.2
system-service==0.3
systemd-python==234
text-unidecode==1.3
toolz==0.10.0
trafaret==1.2.0
trafaret-config==2.0.2
typing-extensions==3.7.4.1
tzlocal==2.0.0
ubuntu-drivers-common==0.0.0
ufw==0.36
urllib3==1.22
uvicorn==0.11.1
uvloop==0.14.0
varint==1.0.2
wcwidth==0.1.8
web3==5.4.0
websockets==8.1
xkit==0.0.0
XlsxWriter==1.2.7
yarl==1.4.2
```

### What was wrong?

I tried to call one of my functions, but over and over get traceback and problems with decoding, when from Remix IDE function works fine. I can't even just call mapping structure from my contract using ```contract.functions.tasks("project_id").call(transaction={"from": w3.eth.accounts[0], "gas": 4700000}))``` , getting the same problem. What could it be?

The code which produced the error:
```python
w3 = Web3(Web3.HTTPProvider("...")) # URL contains basic auth, that's why I wouldn't show it.


Contract = w3.eth.contract(abi=ABI, bytecode=BYTECODE)

tx_hash = Contract.constructor().transact(
    transaction={
        "from": w3.eth.accounts[0],
        "gas": 4700000,
    }
)

tx_receipt = w3.eth.waitForTransactionReceipt(tx_hash, poll_latency=0.5).contractAddress

# noinspection PyTypeChecker
contract = w3.eth.contract(abi=ABI, address=tx_receipt)

tx_hash = contract.functions.CreateProject(
    "project_id",
    "user_id",
    "title",
    "description",
    "created_at",
    "planned_completion_date",
    "addictionalData"
).transact(transaction={"from": w3.eth.accounts[0], "gas": 4700000})

tx_receipt = w3.eth.waitForTransactionReceipt(tx_hash, poll_latency=0.5)

print(contract.functions.GetTask("project_id").call(transaction={"from": w3.eth.accounts[0], "gas": 4700000}))
```
Contract code:
```
pragma solidity ^0.6.4;
pragma experimental ABIEncoderV2;

contract StrackerTask {   
    struct Task {
        string[3] IDs; // projectID, taskID, userID
        string[2] taskDetails; // taskTitle, taskDescription
        int[3] workData; // state, work_time, task_current_cost
        string[2] dates; // created_at, complete_date
        string addictionalData; // external_source, external_id
    }
    
    mapping(string  => Task) public tasks; //tasks to project
    

    function CreateTask(
        string memory projectID, string memory taskID, string memory userID, string memory taskTitle,  string memory taskDescription, int state,  int work_time, int task_current_cost,
        string memory createDate, string memory planned_completion_date, string memory addictionalData
    ) public returns (bool success)
    {
        Task memory task;
        
        task.IDs = [projectID, taskID, userID];
        task.taskDetails = [taskTitle, taskDescription];
        task.workData = [state, work_time, task_current_cost];
        task.dates = [createDate, planned_completion_date];
        task.addictionalData = addictionalData;
        
        tasks[taskID] = task;
        
        return true;
    }
    
    function GetTask(string memory taskID) public returns (Task memory)
    {
        return tasks[taskID];   
    }
   
```

The full output of the error:
```
Traceback (most recent call last):
  File "/home/r31n3/.local/lib/python3.8/site-packages/web3/contract.py", line 1432, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/home/r31n3/.local/lib/python3.8/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/home/r31n3/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/r31n3/.local/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/r31n3/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/home/r31n3/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/r31n3/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 142, in decode
    start_pos = decode_uint_256(stream)
  File "/home/r31n3/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/r31n3/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/r31n3/.local/lib/python3.8/site-packages/eth_abi/decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/r31n3/.../.../.../.../sas.py", line 46, in <module>
    print(contract.functions.GetTask("project_id").call(transaction={"from": w3.eth.accounts[0], "gas": 4700000}))
  File "/home/r31n3/.local/lib/python3.8/site-packages/web3/contract.py", line 894, in call
    return call_contract_function(
  File "/home/r31n3/.local/lib/python3.8/site-packages/web3/contract.py", line 1454, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call GetTask return data b'' for output_types ['(string[3],string[2],int256[3],string[2],string)']

```

Type of node I was connecting to: Last Version of Quorum

**Comment by R31N3** [comment]
I don't actually understand how it works, but after I had enable compiler optimization, everything started working correctly fine!
