### ISSUE TITLE
DeprecationWarning: This library has been renamed to `eth-abi`.  The `ethereum-abi-utils` package will no longer recieve updates.  Please update your dependencies accordingly.

### ISSUE THREAD

**Issue by esraa95mahmoud** [ethereum/web3.py#1693]
when i run

`python 1_accounts.py `
I get the following error
```
Traceback (most recent call last):
  File "1_accounts.py", line 2, in <module>
    from web3 import Web3 
  File "/home/esraa/.local/lib/python2.7/site-packages/web3/__init__.py", line 6, in <module>
    from web3.main import Web3
  File "/home/esraa/.local/lib/python2.7/site-packages/web3/main.py", line 5, in <module>
    from web3.eth import Eth
  File "/home/esraa/.local/lib/python2.7/site-packages/web3/eth.py", line 18, in <module>
    from web3.utils.filters import (
  File "/home/esraa/.local/lib/python2.7/site-packages/web3/utils/filters.py", line 9, in <module>
    from .events import (
  File "/home/esraa/.local/lib/python2.7/site-packages/web3/utils/events.py", line 3, in <module>
    from eth_abi import (
  File "/home/esraa/.local/lib/python2.7/site-packages/eth_abi/__init__.py", line 2, in <module>
    "This library has been renamed to `eth-abi`.  The `ethereum-abi-utils` "
DeprecationWarning: This library has been renamed to `eth-abi`.  The `ethereum-abi-utils` package will no longer recieve updates.  Please update your dependencies accordingly.
```

**Comment by pipermerriam** [comment]
You very likely are using a very old version of the library.  Check `pip freeze | grep web3` and see about updating to a new version which should fix this problem.

**Comment by esraa95mahmoud** [comment]
i get this error
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by pipermerriam** [comment]
Web3.py no longer supports python version 2.  You'll have to upgrade to a more modern version of python.
