### ISSUE TITLE
The issue with web3.eth.getBalance()

### ISSUE THREAD

**Issue by nikitapodga** [ethereum/web3.py#1697]
* Version: 5.12.0
* Python: 3.8.5
* OS: win
* `pip freeze` output

### What was wrong?
The issue is when doing `balance = web3.eth.getBalance(k)`
```
import web3
from web3 import Web3
w3 = Web3(Web3.IPCProvider())
balance = web3.eth.getBalance(k)
```

```
Traceback (most recent call last):
  File "C:/Users/user/Desktop/storage.py", line 26, in <module>
    class check():
  File "C:/Users/user/Desktop/storage.py", line 54, in check
    balance = web3.eth.getBalance(k)
AttributeError: module 'web3.eth' has no attribute 'getBalance'
```

**Comment by pipermerriam** [comment]
In your code `web3` is the python module.  You should be calling `w3.eth.getBalance(k)`
