### ISSUE TITLE
raise DeprecationWarning( DeprecationWarning: This library has been renamed to `eth-utils`.  The `ethereum-utils` package will no longer recieve updates.  Please update your dependencies accordingly.

### ISSUE THREAD

**Issue by esraa95mahmoud** [ethereum/web3.py#1698]
when i run` python3 1_accounts.py` command 
i get the error 
```
Traceback (most recent call last):
  File "1_accounts.py", line 2, in <module>
    from web3 import Web3 
  File "/home/esraa/.local/lib/python3.8/site-packages/web3/__init__.py", line 6, in <module>
    from eth_account import (
  File "/home/esraa/.local/lib/python3.8/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (  # noqa: F401
  File "/home/esraa/.local/lib/python3.8/site-packages/eth_account/account.py", line 11, in <module>
    from eth_keyfile import (
  File "/home/esraa/.local/lib/python3.8/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/home/esraa/.local/lib/python3.8/site-packages/eth_keyfile/keyfile.py", line 10, in <module>
    from eth_keys import keys
  File "/home/esraa/.local/lib/python3.8/site-packages/eth_keys/__init__.py", line 15, in <module>
    from .main import (  # noqa: F401
  File "/home/esraa/.local/lib/python3.8/site-packages/eth_keys/main.py", line 3, in <module>
    from eth_utils import (
  File "/home/esraa/.local/lib/python3.8/site-packages/eth_utils/__init__.py", line 1, in <module>
    raise DeprecationWarning(
DeprecationWarning: This library has been renamed to `eth-utils`.  The `ethereum-utils` package will no longer recieve updates.  Please update your dependencies accordingly.

```

**Comment by pipermerriam** [comment]
can you provide the output of `pip freeze` so we can see what dependencies you have installed.

**Comment by esraa95mahmoud** [comment]
when i run `sudo pip freeze | grep web3` 
i get
```
 web3==3.11.1
web3utils==0.1.3
```
i dont understand

**Comment by esraa95mahmoud** [comment]
the output of `pip freeze`
```
absl-py==0.9.0
alabaster==0.7.12
appdirs==1.4.4
apturl==0.5.2
arrow==0.15.8
asn1crypto==1.4.0
astunparse==1.6.3
atomicwrites==1.4.0
attrs==19.3.0
Babel==2.8.0
base58==2.0.1
bcrypt==3.1.7
binaryornot==0.4.4
bitarray==1.2.2
blinker==1.4
bottle==0.12.18
Brlapi==0.7.0
bump2version==1.0.0
cached-property==1.5.1
cachetools==4.1.1
cattrs==1.0.0
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
cliapp==1.20180812.1
click==7.1.2
cloudpickle==1.5.0
cmdtest==0.32+git
coincurve==13.0.0
colorama==0.4.3
command-not-found==0.3
conan==1.28.0
cookiecutter==1.7.2
couchbase==3.0.3
cryptography==3.0
cupshelpers==1.0
cytoolz==0.10.1
dbus-python==1.2.16
decorator==4.4.2
deepdiff==5.0.2
defer==1.0.6
Deprecated==1.2.10
deprecation==2.1.0
distlib==0.3.1
distro==1.5.0
distro-info==0.0.0
docutils==0.16
duplicity==0.8.12.0
entrypoints==0.3
eth-abi==2.1.1
eth-account==0.5.2
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.1.2
eth-tester==0.5.0b1
eth-typing==2.2.1
eth-utils==1.9.0
ethereum==2.3.2
ethereum-abi-utils==0.4.7
ethereum-utils==0.6.2
fasteners==0.15
filelock==3.0.12
future==0.18.2
gast==0.3.3
Geohash==1.0
google-auth==1.20.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.31.0
h5py==2.10.0
hexbytes==0.2.1
httplib2==0.18.1
idna==2.10
imagesize==1.2.0
importlib-metadata==1.7.0
iniconfig==1.0.1
ipfshttpclient==0.6.0.post1
jeepney==0.4.3
Jinja2==2.11.2
jinja2-time==0.2.0
jsonschema==3.2.0
Keras-Preprocessing==1.1.2
keyring==21.3.0
keyrings.alt==3.4.0
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.3
lazr.uri==1.0.5
linecache2==1.0.0
lockfile==0.12.2
louis==3.12.0
lru-dict==1.1.6
macaroonbakery==1.3.1
Mako==1.1.3
Markdown==3.2.2
MarkupSafe==1.1.1
Mesa @ file:///home/esraa/private-ethereum/mesa_repo
mlagents==0.18.1
mlagents-envs==0.18.1
monotonic==1.5
more-itertools==8.4.0
multiaddr==0.0.9
mypy-extensions==0.4.3
netaddr==0.8.0
netifaces==0.10.9
networkx==2.4
node-semver==0.8.0
numpy==1.18.5
oauthlib==3.1.0
olefile==0.46
opt-einsum==3.3.0
ordered-set==4.0.2
packaging==20.4
pandas==1.1.0
paramiko==2.7.1
parsimonious==0.8.1
patch-ng==1.17.4
pbkdf2==1.3
pbr==5.4.5
pexpect==4.8.0
Pillow==7.2.0
pipdeptree==1.0.0
pipenv==2020.6.2
pluggy==0.13.1
pluginbase==1.0.0
poyo==0.5.0
protobuf==3.12.4
ptyprocess==0.6.0
py==1.9.0
py-ecc==4.0.0
py-solc==3.2.0
py-solc-x==0.10.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pycparser==2.20
pycrypto==2.6.1
pycryptodome==3.9.8
pycups==1.9.73
pyes==0.99.6
pyethash==0.1.27
PyGithub==1.52
Pygments==2.6.1
PyGObject==3.36.0
PyJWT==1.7.1
pylru==1.2.0
pymacaroons==0.13.0
PyNaCl==1.4.0
pyparsing==2.4.7
pyRFC3339==1.1
pyrsistent==0.16.0
pysha3==1.0.2
pytest==6.0.1
python-apt==2.0.0+ubuntu0.20.4.1
python-dateutil==2.8.1
python-debian==0.1.37
python-geohash==0.8.5
python-slugify==4.0.1
pytz==2020.1
pyxdg==0.26
PyYAML==5.3.1
reportlab==3.5.46
repoze.lru==0.7
requests==2.24.0
requests-oauthlib==1.3.0
requests-unixsocket==0.2.0
rlp==1.2.0
rsa==4.6
scipy==1.4.1
scrypt==0.8.15
SecretStorage==3.1.2
selenium==3.141.0
semantic-version==2.8.5
sgmllib3k==1.0.0
simplejson==3.17.2
six==1.15.0
smartplugctl==0.0.5
snowballstemmer==2.0.0
Sphinx==3.1.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport==1.2.3
systemd-python==234
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.3.0
tensorflow-estimator==2.3.0
termcolor==1.1.0
testresources==2.0.1
text-unidecode==1.3
toml==0.10.1
toolz==0.10.0
tornado==6.0.4
tqdm==4.48.2
traceback2==1.4.0
ttystatus==0.38
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
unittest2==1.1.0
urllib3==1.25.10
usb-creator==0.3.7
varint==1.0.2
virtualenv==20.0.30
virtualenv-clone==0.5.4
wadllib==1.3.4
wcwidth==0.2.5
web3==3.11.1
web3utils==0.1.3
websockets==8.1
Werkzeug==1.0.1
wrapt==1.12.1
xkit==0.0.0
zipp==3.1.0
```

**Comment by kclowes** [comment]
@esraa95mahmoud It looks like you have web3 v3.11 installed. We currently only support v5+. Try upgrading your web3 version and feel free to reopen this issue if you're still having problems!

**Comment by esraa95mahmoud** [comment]
i have this error i can not solve it `ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/esraa/private-ethereum`
