### ISSUE TITLE
TypeError: Address <eth_account.signers.local.LocalAccount object at 0x7ffaa4c4adc0> must be provided as a string

### ISSUE THREAD

**Issue by ShubhamKarala** [ethereum/web3.py#1714]
* Version: 5.12.0
* Python: 3.8
* OS: linux
* `pip freeze` output

```
attrs==19.3.0
base58==2.0.1
bitarray==1.2.2
blake2b-py==0.1.3
cached-property==1.5.1
certifi==2020.6.20
chardet==3.0.4
cytoolz==0.10.1
eth-abi==2.1.1
eth-account==0.5.2
eth-bloom==1.0.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.1.2
eth-tester==0.5.0b1
eth-typing==2.2.1
eth-utils==1.9.3
hexbytes==0.2.1
idna==2.10
ipfshttpclient==0.6.0.post1
jsonschema==3.2.0
lru-dict==1.1.6
multiaddr==0.0.9
mypy-extensions==0.4.3
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.13.0
py-ecc==1.7.1
py-evm==0.3.0a15
py-geth==2.4.0
py-solc==3.2.0
pycryptodome==3.9.8
pyethash==0.1.27
pyrsistent==0.16.0
requests==2.24.0
rlp==1.2.0
semantic-version==2.8.5
six==1.15.0
toolz==0.10.0
trie==1.4.0
urllib3==1.25.10
varint==1.0.2
web3==5.12.0
websockets==8.1
```

### What was wrong?
When I try to deploy the smart contract I constantly got same errot.
```Traceback (most recent call last):
  File "script.py", line 71, in <module>
    tx_hash = CertificateStore.constructor().transact()
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/contract.py", line 662, in transact
    return self.web3.eth.sendTransaction(transact_transaction)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/eth.py", line 384, in sendTransaction
    get_buffered_gas_estimate(self.web3, transaction),
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/transactions.py", line 127, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/eth.py", line 448, in estimateGas
    return self.web3.manager.request_blocking(
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 73, in apply_formatters
    formatted_params = formatter(params)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/eth_utils/decorators.py", line 91, in wrapper
    return ReturnType(result)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/eth_utils/applicators.py", line 22, in apply_formatter_at_index
    yield formatter(item)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/rpc_abi.py", line 238, in apply_abi_formatters_to_dict
    formatted_values = map_abi_data(
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/abi.py", line 799, in map_abi_data
    return pipe(data, *pipeline)
  File "cytoolz/functoolz.pyx", line 669, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 644, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/abi.py", line 833, in data_tree_map
    return recursive_map(map_to_typed_data, data_tree)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/decorators.py", line 30, in wrapped
    wrapped_val = to_wrap(*args)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/formatters.py", line 89, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/formatters.py", line 76, in map_collection
    return datatype(map(func, collection))
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/formatters.py", line 88, in recurse
    return recursive_map(func, item)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/decorators.py", line 30, in wrapped
    wrapped_val = to_wrap(*args)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/formatters.py", line 90, in recursive_map
    return func(items_mapped)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/abi.py", line 830, in map_to_typed_data
    return ABITypedData(func(*elements))
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/normalizers.py", line 78, in wrapper
    modified = to_wrap(type_str, data)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/normalizers.py", line 196, in abi_address_to_hex
    validate_address(data)
  File "/home/helium/Desktop/dada_works/python-test/venv/lib/python3.8/site-packages/web3/_utils/validation.py", line 165, in validate_address
    raise TypeError('Address {} must be provided as a string'.format(value))
TypeError: Address <eth_account.signers.local.LocalAccount object at 0x7ffaa4c4adc0> must be provided as a string
```

* The code which produced the error

```import json
from web3 import Web3
from solc import compile_standard


compiled_sol = compile_standard({
    "language": "Solidity",
    "sources": {
        "certificates.sol": {
            "content": '''
                pragma solidity >=0.5.0;

                contract CertificateStore {

                    event NewCertificate(uint certificateId, string name, uint id);

                    struct Certificate {
                        string name;
                        uint id;
                    }

                    Certificate[] public certificates;


                    function _createCertificate(string memory _name, uint _id) private {
                        certificates.push(Certificate(_name, _id));
                        uint MainID = certificates.length -1;
                        emit NewCertificate(MainID, _name, _id);
                    } 

                    function _generateRandomId(string memory _str) private pure returns (uint) {
                        uint rand = uint(keccak256(abi.encodePacked(_str)));
                        return rand ;
                    }

                    function createRandomCertificate(string memory _name) public {
                        uint randID= _generateRandomId(_name);
                        _createCertificate(_name, randID);
                    }

                }
                '''
        }
    },
    "settings":
        {
            "outputSelection": {
                "*": {
                    "*": [
                        "metadata", "evm.bytecode"
                        , "evm.bytecode.sourceMap"
                    ]
                }
            }
        }
})

w3 = Web3(Web3.HTTPProvider('http://127.0.0.1:8545'))

print(w3.isConnected())

w3.eth.defaultAccount = w3.eth.account.privateKeyToAccount("8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63")


bytecode = compiled_sol['contracts']['certificates.sol']['CertificateStore']['evm']['bytecode']['object']

abi = json.loads(compiled_sol['contracts']['certificates.sol']['CertificateStore']['metadata'])['output']['abi']

CertificateStore = w3.eth.contract(abi=abi, bytecode=bytecode)

tx_hash = CertificateStore.constructor().transact()

tx_receipt = w3.eth.waitForTransactionReceipt(tx_hash)

certificatestore = w3.eth.contract(
    address = tx_receipt.contractAddress,
    abi=abi
)


tx_hash = certificatestore.functions.createRandomCertificate("Shubham Karala").transact()

tx_receipt = w3.eth.waitForTransactionReceipt(tx_hash)

print(certificatestore.functions.certificates(0).call())
```

**Comment by ShubhamKarala** [comment]
nevermind, I got it. I was storing object in w3.eth.defaultAccount instead of the account address.

**Comment by shellwhale** [comment]
> nevermind, I got it. I was storing object in w3.eth.defaultAccount instead of the account address.

Could you please share the code with your problem solved?

**Comment by TheAsouka** [comment]
Hey @ShubhamKarala be carefull you are exposing a privatekey here. Someone could have stolen your funds ;)
