### ISSUE TITLE
 raise ValueError(response["error"]) ValueError: {'message': 'VM Exception while processing transaction: invalid opcode', 'code': -32000, 'data': {'stack': 'RuntimeError: VM Exception while processing transaction: invalid opcode\n 

### ISSUE THREAD

**Issue by duaa99** [ethereum/web3.py#1717]
```
ganache_url = "HTTP://127.0.0.1:7545"

web3 = Web3(Web3.HTTPProvider(ganache_url))



abi =json.loads('')

bytecode=''




print(web3.isConnected())

web3.eth.defaultAccount = web3.eth.accounts[0]
Courses = web3.eth.contract(abi=abi, bytecode=bytecode)


rusalt = Courses.constructor().transact()
rusalt_receipt = web3.eth.waitForTransactionReceipt(rusalt)
contract = web3.eth.contract(address=rusalt_receipt.contractAddress,abi=abi,)
```
   `web3.eth.waitForTransactionReceipt(contract.functions.set_data(1,i,lis1[i]).transact({'from':'0x343A55f7792f6a355CD8f9109C869F9c6DA7b3a8'}))`

Gives me an error on this
``web3.eth.waitForTransactionReceipt(contract.functions.set_data(1,i,lis1[i]).transact({'from':'0x343A55f7792f6a355CD8f9109C869F9c6DA7b3a8'})`)`
```
  raise ValueError(response["error"])
ValueError: {'message': 'VM Exception while processing transaction: invalid opcode', 'code': -32000, 'data': {'stack': 'RuntimeError: VM Exception while processing transaction: invalid opcode\n    at Function.RuntimeError.fromResults (/tmp/.mount_ganachTA7rCW/resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:89:13)\n    at module.exports (/tmp/.mount_ganachTA7rCW/resources/static/node/node_modules/ganache-core/lib/utils/gas/guestimation.js:142:32)', 'name': 'RuntimeError'}}
```

can help me .....

**Comment by kclowes** [comment]
@duaa99 my first guess is that it might be your bytecode. Is your bytecode correct?
