### ISSUE TITLE
_parse_logs() missing 1 required positional argument: 'errors'

### ISSUE THREAD

**Issue by mikeshultz** [ethereum/web3.py#1738]
* Version: 5.12.1
* Python: 3.8.3
* OS: linux
* `pip freeze` output

```
attrs==20.2.0
base58==2.0.1
bitarray==1.2.2
certifi==2020.6.20
chardet==3.0.4
cytoolz==0.10.1
eth-abi==2.1.1
eth-account==0.5.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.0
eth-typing==2.2.2
eth-utils==1.9.5
hexbytes==0.2.1
idna==2.10
ipfshttpclient==0.6.1
jsonschema==3.2.0
lru-dict==1.1.6
multiaddr==0.0.9
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.13.0
pycryptodome==3.9.8
pyrsistent==0.16.0
requests==2.24.0
rlp==2.0.0a1
rusty-rlp==0.1.15
six==1.15.0
toolz==0.10.0
urllib3==1.25.10
varint==1.0.2
web3==5.12.1
websockets==8.1
```

### What was wrong?

When trying to use an event without initializing the Event instance, methods may throw errors like this:

    Traceback (most recent call last):
      File "main2.py", line 9, in <module>
        contract.events['AddressEvent'].processReceipt(EVENT_RECEIPT, STRICT)
      File "/home/mike/.venvs/web3test/lib/python3.8/site-packages/eth_utils/decorators.py", line 20, in _wrapper
        return self.method(objtype, *args, **kwargs)
      File "/home/mike/dev/web3.py/web3/contract.py", line 1139, in processReceipt
        return self._parse_logs(txn_receipt, errors)
      File "/home/mike/.venvs/web3test/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
        return callback(fn(*args, **kwargs))
    TypeError: _parse_logs() missing 1 required positional argument: 'errors'

Example test case:

https://gist.github.com/mikeshultz/811e72a82beccdccc6e3ee8fcbefbb66

The test case works fine if you execute it with an initialized event instance:

    contract.events['AddressEvent']().processReceipt(EVENT_RECEIPT, STRICT)

I assume this is intended functionality because of the `@combomethod` decorator and [it's documented in some of the examples](https://web3py.readthedocs.io/en/stable/contracts.html#events) in the docs.

### How can it be fixed?

Guessing this has to do with `@to_tuple` decorator(or `eth_utils.functional.apply_to_return_value()`) but don't have the time right now to get setup and pull `eth_utils` apart.

https://github.com/ethereum/web3.py/blob/e2b5bcb19c6a7f833b3482e5bcd9b761ae4ec223/web3/contract.py#L1139

**Comment by kclowes** [comment]
Thanks for this report @mikeshultz. It does indeed look like a bug. I'll dig in as soon as I can!

**Comment by KaiRo-at** [comment]
Hrm, I'm running into this now, has that never been actually looked into?

**Comment by kclowes** [comment]
@KaiRo-at that's right, this has not been looked into yet. It's pretty low priority right now, since there is a workaround. I'd happily review a PR if you feel like putting one up!

**Comment by moda20** [comment]
@kclowes i am having the same error and i can't find a workaround. what is the workaround you mentioned?

**Comment by SeanMGonzalez** [comment]
a slight tangent, but not perpendicular. I came across this issue thread while researching contract events on Polygon/Mumbai. Turns out Polygon does not support eth_newFilter, which was causing similar problems for me. This fixed the problem: https://ethereum.stackexchange.com/questions/106868/listen-to-events-in-the-polygon-network-using-web3-py
