### ISSUE TITLE
Python int too large to convert to C ssize_t in w3.eth.contract.functions.symbol()

### ISSUE THREAD

**Issue by fathomson** [ethereum/web3.py#1739]
Issue similar to: [1699](https://github.com/ethereum/web3.py/issues/1699)

* Version: 5.21.1
* Python: 3.7.7
* OS: win
* `pip freeze` output

```
argon2-cffi==20.1.0
async-generator==1.10
attrdict==2.0.1
attrs==20.2.0
backcall==0.2.0
base58==2.0.1
bitarray==1.2.2
bleach==3.1.5
certifi==2020.6.20
cffi==1.14.2
chardet==3.0.4
colorama==0.4.3
cycler==0.10.0
cytoolz==0.10.1
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
eth-abi==2.1.1
eth-account==0.5.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.0
eth-typing==2.2.2
eth-utils==1.9.5
hexbytes==0.2.1
idna==2.10
importlib-metadata==1.7.0
ipfshttpclient==0.6.1
ipykernel==5.3.4
ipython==7.18.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.2
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.6.3
jupyterlab==2.2.7
jupyterlab-pygments==0.1.1
jupyterlab-server==1.2.0
kiwisolver==1.2.0
lab==6.0
lru-dict==1.1.6
MarkupSafe==1.1.1
matplotlib==3.3.1
mistune==0.8.4
multiaddr==0.0.9
nbclient==0.5.0
nbconvert==6.0.0
nbformat==5.0.7
nest-asyncio==1.4.0
netaddr==0.8.0
notebook==6.1.4
numpy==1.19.1
packaging==20.4
pandocfilters==1.4.2
parsimonious==0.8.1
parso==0.7.1
pickleshare==0.7.5
Pillow==7.2.0
prometheus-client==0.8.0
prompt-toolkit==3.0.7
protobuf==3.13.0
pycparser==2.20
pycryptodome==3.9.8
Pygments==2.6.1
pyparsing==2.4.7
pypiwin32==223
pyrsistent==0.16.0
python-dateutil==2.8.1
python-firebase==1.2.1
pywin32==228
pywinpty==0.5.7
pyzmq==19.0.2
qtconsole==4.7.7
QtPy==1.9.0
requests==2.24.0
rlp==2.0.0a1
rusty-rlp==0.1.15
Send2Trash==1.5.0
simplejson==3.17.2
six==1.15.0
terminado==0.8.3
testpath==0.4.4
toolz==0.10.0
tornado==6.0.4
tqdm==4.48.2
traitlets==5.0.4
txt2tags==3.7
typing-extensions==3.7.4.3
urllib3==1.25.10
varint==1.0.2
wcwidth==0.2.5
web3==5.12.1
webencodings==0.5.1
websockets==8.1
widgetsnbextension==3.5.1
zipp==3.1.0
```
### What was wrong?

The w3.eth.contract.functions.symbol() throws an error on certain contract addresses, thus not being able to load the contract details.

* The code which produced the error

```
import json
from web3 import Web3

w3 = Web3(Web3.IPCProvider())
erc20 = json.loads('[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"}]')
adr = "0x08A2E41FB99A7599725190B9C970Ad3893fa33CF"  # also: 0xE54f9E6Ab80ebc28515aF8b8233c1aeE6506a15E, 0x4Ddc2D193948926D02f9B1fE9e1daa0718270ED5
erc20_contract = w3.eth.contract(address=adr, abi=erc20)
symbol = erc20_contract.functions.symbol().call()
```

* The full output of the error

```
Traceback (most recent call last):
  File "C:/Users/un/PycharmProjects/ethpending/test.py", line 12, in <module>
    symbol = erc20_contract.functions.symbol().call()
  File "C:\Users\un\PycharmProjects\ethpending\venv\lib\site-packages\web3\contract.py", line 964, in call
    **self.kwargs
  File "C:\Users\un\PycharmProjects\ethpending\venv\lib\site-packages\web3\contract.py", line 1507, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "C:\Users\un\PycharmProjects\ethpending\venv\lib\site-packages\eth_abi\codec.py", line 181, in decode_abi
    return decoder(stream)
  File "C:\Users\un\PycharmProjects\ethpending\venv\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\Users\un\PycharmProjects\ethpending\venv\lib\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "C:\Users\un\PycharmProjects\ethpending\venv\lib\site-packages\eth_abi\decoding.py", line 173, in decode
    yield decoder(stream)
  File "C:\Users\un\PycharmProjects\ethpending\venv\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\Users\un\PycharmProjects\ethpending\venv\lib\site-packages\eth_abi\decoding.py", line 144, in decode
    stream.push_frame(start_pos)
  File "C:\Users\un\PycharmProjects\ethpending\venv\lib\site-packages\eth_abi\decoding.py", line 95, in push_frame
    self.seek_in_frame(0)
  File "C:\Users\un\PycharmProjects\ethpending\venv\lib\site-packages\eth_abi\decoding.py", line 84, in seek_in_frame
    self.seek(self._total_offset + pos, *args, **kwargs)
OverflowError: Python int too large to convert to C ssize_t
```

* What type of node you were connecting to.
local full node

### How can it be fixed?
datatype change?

**Comment by kclowes** [comment]
I suspect this is the same as https://github.com/ethereum/eth-abi/issues/142 - i.e. just a really confusing error message. 

To troubleshoot, make sure your ABI is correct. When I pull the ABI from the contract at "0x08A2E41FB99A7599725190B9C970Ad3893fa33CF" I get the below results: 
```
In [5]: import json
   ...: from web3.auto.infura import w3
   ...:
   ...: erc20 = json.loads('[{    "constant": true,    "inputs": [],    "name": "symbol",     "outputs": [     {        "internalType": "bytes32",        "name": "",        "type": "bytes32"      }    ],    "payable": false,    "stateMutability": "view",    "type": "function"  }]')
   ...: adr = "0x08A2E41FB99A7599725190B9C970Ad3893fa33CF"  # also: 0xE54f9E6Ab80ebc28515aF8b8233c1aeE6506a15E, 0x4Ddc2D193948926D02f9B1fE9e1daa0718270ED5
   ...: erc20_contract = w3.eth.contract(address=adr, abi=erc20)
   ...: erc20_contract.functions.symbol().call()
Out[5]: b'PASTA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

I'm going to close, but if this doesn't fix your issue, please re-open because this has come up a bunch!

**Comment by pipermerriam** [comment]
@kclowes this previously was happening due to the JSON-RPC response returning the revert reason instead of the function call output.  I documented that in #1699

**Comment by kclowes** [comment]
Yeah, I saw that one, but the symbol that they're calling above is just a state variable, which wouldn't trigger any revert, right? So it seems like there are two separate issues that could cause this OverflowError: 1) bad ABI, and 2) `revert`?

**Comment by pipermerriam** [comment]
I'm trying to avoid making assumptions about what what the raw JSON-RPC response is that is coming back.  You are correct though that in general, this is caused by the return value not being well formed with respect to the provided ABI.  We just can't necessarily diagnose it until someone inspects the raw response.
