### ISSUE TITLE
web3 import issues

### ISSUE THREAD

**Issue by blockchainOSINT** [ethereum/web3.py#1785]
* Version: web3==5.12.3
* Python: 3.9
* OS: Windows 10

```
from web3 import Web3

File "C:\Users\User\Desktop\Misc Python Scripts\ssethereum_final.py", line 2, in <module>
  from web3 import Web3
File "C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\web3\__init__.py", line 9, in <module>
  from web3.main import (
File "C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\web3\main.py", line 69, in <module>
  from web3.manager import (
File "C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\web3\manager.py", line 31, in <module>
  from web3.middleware import (
File "C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\web3\middleware\__init__.py", line 20, in <module>
  from .cache import ( # noqa: F401
File "C:\Users\User\AppData\Local\Programs\Python\Python39\Lib\site-packages\web3\middleware\cache.py", line 15, in <module>
  import lru

builtins.ModuleNotFoundError: No module named 'lru'
```
I updated all of my Python packages (including web3) to latest version, which I thought would install all of the dependencies such as this `lru `module, however I’m still getting this error. I tried manually install `lru `but I'm getting errors there also:

```
pip install lru

Collecting lru
  Using cached lru-0.1.tar.gz (1.1 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\User\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-lh01ruki\\lru\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-lh01ruki\\lru\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-aa9l4age'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-lh01ruki\lru\
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-lh01ruki\lru\setup.py", line 2, in <module>
        from lru import __version__ as version
      File "C:\Users\User\AppData\Local\Temp\pip-install-lh01ruki\lru\lru.py", line 18
        raise KeyError, key
                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

My web3 code worked with previous versions of Python and I’d rather not have to downgrade -- don't understand why upgrading would affect importing modules? Any suggestions on how to fix?

**Comment by kclowes** [comment]
@blockchainOSINT We don't yet support Python 3.9 (see #1774), but it's on the docket. I'd try downgrading your python and installing web3 in a new virtual environment to see if that is the problem. If it's still not working, feel free to reopen!
