### ISSUE TITLE
Estimate Gas Value Error

### ISSUE THREAD

**Issue by kaleb-keny** [ethereum/web3.py#1789]
* Version:  5.13.0
* Python: 3.7.9
* OS: win
* `pip freeze` output

```
aiohttp @ file:///C:/ci/aiohttp_1603893481584/work
alabaster==0.7.12
argh==0.26.2
astroid @ file:///C:/ci/astroid_1592481955828/work
async-generator==1.10
async-timeout==3.0.1
atomicwrites==1.4.0
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1596578164842/work
Babel==2.8.0
backcall==0.2.0
base58 @ file:///home/conda/feedstock_root/build_artifacts/base58_1591738914578/work
bcrypt @ file:///C:/ci/bcrypt_1597918112552/work
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1601924105527/work
bitarray @ file:///D:/bld/bitarray_1589849383176/work
bleach @ file:///tmp/build/80754af9/bleach_1600439572647/work
brotlipy==0.7.0
certifi==2020.6.20
cffi @ file:///C:/ci/cffi_1600699250966/work
chardet==3.0.4
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1598884132938/work
colorama @ file:///tmp/build/80754af9/colorama_1603211150991/work
cryptography @ file:///C:/ci/cryptography_1601046913206/work
cytoolz==0.11.0
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch @ file:///tmp/build/80754af9/diff-match-patch_1594828741838/work
docutils==0.16
entrypoints==0.3
eth-abi @ file:///home/conda/feedstock_root/build_artifacts/eth-abi_1603547879440/work
eth-account @ file:///home/conda/feedstock_root/build_artifacts/eth-account_1602701711300/work
eth-hash @ file:///home/conda/feedstock_root/build_artifacts/eth-hash_1598382387998/work
eth-keyfile @ file:///home/conda/feedstock_root/build_artifacts/eth-keyfile_1598795122692/work
eth-keys @ file:///home/conda/feedstock_root/build_artifacts/eth-keys_1598719634616/work
eth-rlp @ file:///home/conda/feedstock_root/build_artifacts/eth-rlp_1602701686634/work
eth-typing @ file:///home/conda/feedstock_root/build_artifacts/eth-typing_1599130010743/work
eth-utils @ file:///D:/bld/eth-utils_1602415227529/work
flake8 @ file:///tmp/build/80754af9/flake8_1601911421857/work
funcy @ file:///home/conda/feedstock_root/build_artifacts/funcy_1601143499053/work
future==0.18.2
h11 @ file:///tmp/build/80754af9/h11_1594058940538/work
h2==3.2.0
hexbytes @ file:///home/conda/feedstock_root/build_artifacts/hexbytes_1598376847189/work
hpack==3.0.0
httpcore @ file:///tmp/build/80754af9/httpcore_1601996039936/work
httpx @ file:///tmp/build/80754af9/httpx_1602258256207/work
hyperframe==5.1.0
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
imagesize==1.2.0
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1602276842396/work
intervaltree @ file:///tmp/build/80754af9/intervaltree_1598376443606/work
ipfshttpclient @ file:///home/conda/feedstock_root/build_artifacts/ipfshttpclient_1598794283395/work
ipykernel @ file:///C:/ci/ipykernel_1596208728219/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///C:/ci/ipython_1604101327119/work
ipython-genutils==0.2.0
isort @ file:///tmp/build/80754af9/isort_1602603989581/work
jedi @ file:///C:/ci/jedi_1592833832328/work
Jinja2==2.11.2
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1601311786391/work
jupyter-core==4.6.3
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
keyring @ file:///C:/ci/keyring_1601488971022/work
knockknock==0.1.8.1
lazy-object-proxy==1.4.3
lru-dict @ file:///D:/bld/lru-dict_1602336430664/work
lxml @ file:///C:/ci/lxml_1603216364379/work
MarkupSafe @ file:///C:/ci/markupsafe_1594405949945/work
matrix-client==0.3.2
mccabe==0.6.1
mistune @ file:///C:/ci/mistune_1594373272338/work
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
multiaddr @ file:///home/conda/feedstock_root/build_artifacts/multiaddr_1598720134323/work
multidict @ file:///C:/ci/multidict_1600456486794/work
nbclient @ file:///tmp/build/80754af9/nbclient_1602783176460/work
nbconvert @ file:///C:/ci/nbconvert_1601914921407/work
nbformat @ file:///tmp/build/80754af9/nbformat_1602783287752/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1601499549014/work
netaddr==0.7.19
numpy @ file:///C:/ci/numpy_and_numpy_base_1603468620949/work
numpydoc @ file:///tmp/build/80754af9/numpydoc_1594166760263/work
packaging==20.4
pandas @ file:///C:/ci/pandas_1602088205210/work
pandocfilters==1.4.2
paramiko @ file:///tmp/build/80754af9/paramiko_1598886428689/work
parsimonious==0.8.1
parso==0.7.0
pathtools==0.1.2
pexpect @ file:///C:/ci/pexpect_1594383465186/work
pickleshare @ file:///C:/ci/pickleshare_1594374056827/work
pluggy==0.13.1
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
protobuf==3.13.0
psutil @ file:///C:/ci/psutil_1598352273540/work
pycodestyle==2.6.0
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pycryptodome @ file:///C:/ci/pycryptodome_1599214675409/work
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1598885001695/work
pyflakes==2.2.0
Pygments @ file:///tmp/build/80754af9/pygments_1604103097372/work
PyJWT==1.7.1
pylint @ file:///C:/ci/pylint_1598605958085/work
PyMySQL @ file:///C:/ci/pymysql_1601577445570/work
PyNaCl @ file:///C:/ci/pynacl_1595009241355/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
pyparsing==2.4.7
pyrsistent @ file:///C:/ci/pyrsistent_1600123688363/work
PySocks @ file:///C:/ci/pysocks_1594394709107/work
python-dateutil==2.8.1
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1600278539111/work
python-language-server @ file:///tmp/build/80754af9/python-language-server_1600454544709/work
python-telegram-bot @ file:///home/conda/feedstock_root/build_artifacts/python-telegram-bot_1594075855617/work
pytz==2020.1
pywin32==227
pywin32-ctypes @ file:///C:/ci/pywin32-ctypes_1594392691209/work
PyYAML==5.3.1
pyzmq==19.0.2
QDarkStyle==2.8.1
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1602272867890/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1600870028330/work
QtPy==1.9.0
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
rfc3986 @ file:///tmp/build/80754af9/rfc3986_1594058972433/work
rlp @ file:///home/conda/feedstock_root/build_artifacts/rlp_1598494850535/work
rope @ file:///tmp/build/80754af9/rope_1602264064449/work
Rtree==0.9.4
six==1.15.0
sniffio @ file:///C:/ci/sniffio_1594059074984/work
snowballstemmer==2.0.0
sortedcontainers==2.2.2
soupsieve==2.0.1
Sphinx @ file:///tmp/build/80754af9/sphinx_1597428793432/work
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
spyder @ file:///C:/ci/spyder_1599052032150/work
spyder-kernels @ file:///C:/ci/spyder-kernels_1599051798778/work
SQLAlchemy @ file:///C:/ci/sqlalchemy_1603818968375/work
tabulate==0.8.7
testpath==0.4.4
toml @ file:///tmp/build/80754af9/toml_1592853716807/work
toolz @ file:///tmp/build/80754af9/toolz_1601054250827/work
tornado==6.0.4
tqdm @ file:///tmp/build/80754af9/tqdm_1602185206534/work
traitlets @ file:///tmp/build/80754af9/traitlets_1602787416690/work
twilio @ file:///home/conda/feedstock_root/build_artifacts/twilio_1602712058208/work
typed-ast==1.4.1
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1598376058250/work
ujson @ file:///C:/ci/ujson_1602523369547/work
urllib3 @ file:///tmp/build/80754af9/urllib3_1603305693037/work
varint @ file:///home/conda/feedstock_root/build_artifacts/varint_1591731592842/work
watchdog @ file:///C:/ci/watchdog_1593446515400/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
web3 @ file:///D:/bld/web3_1604009788517/work
webencodings==0.5.1
websockets @ file:///D:/bld/websockets_1602327186949/work
win-inet-pton==1.1.0
wincertstore==0.2
wrapt==1.11.2
yagmail @ file:///home/conda/feedstock_root/build_artifacts/yagmail_1602166136512/work
yapf @ file:///tmp/build/80754af9/yapf_1593528177422/work
yarl @ file:///C:/ci/yarl_1598045271760/work
zipp @ file:///tmp/build/80754af9/zipp_1604001098328/work

```

### What was wrong?

Trying to estimate gas with ganache, I setup the mainnet fork using:

- ganache-cli -f https://mainnet.infura.io/v3/XXXXXXXXXXXXXXXXXXXXXX --chainId 1 --verbose -u 0xeF4818607B34A3159e8FFc2C4B4C3492A1901812 
- Then I run the below code which estimates the gas of doing a exchange on 1inch from ETH to sUSD token

```
import web3 as w3

def estimateGas(web3):
    address='0xeF4818607B34A3159e8FFc2C4B4C3492A1901812'
    contractAddress= '0xC586BeF4a0992C495Cf22e1aeEE4E446CECDee0E'
    abi = '''[{"inputs":[{"internalType":"contract IOneSplit","name":"impl","type":"address"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"newImpl","type":"address"}],"name":"ImplementationUpdated","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_AAVE","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_BANCOR","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_BDAI","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_CHAI","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_COMPOUND","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_CURVE_BINANCE","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_CURVE_COMPOUND","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_CURVE_SYNTHETIX","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_CURVE_USDT","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_CURVE_Y","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_FULCRUM","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_IEARN","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_KYBER","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_OASIS","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_SMART_TOKEN","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_UNISWAP","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_DISABLE_WETH","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_ENABLE_KYBER_BANCOR_RESERVE","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_ENABLE_KYBER_OASIS_RESERVE","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_ENABLE_KYBER_UNISWAP_RESERVE","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_ENABLE_MULTI_PATH_DAI","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_ENABLE_MULTI_PATH_ETH","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_ENABLE_MULTI_PATH_USDC","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"FLAG_ENABLE_UNISWAP_COMPOUND","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"internalType":"contract IERC20","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"claimAsset","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"internalType":"contract IERC20","name":"fromToken","type":"address"},{"internalType":"contract IERC20","name":"toToken","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"uint256","name":"parts","type":"uint256"},{"internalType":"uint256","name":"featureFlags","type":"uint256"}],"name":"getExpectedReturn","outputs":[{"internalType":"uint256","name":"returnAmount","type":"uint256"},{"internalType":"uint256[]","name":"distribution","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"isOwner","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"oneSplitImpl","outputs":[{"internalType":"contract IOneSplit","name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[],"name":"renounceOwnership","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"internalType":"contract IOneSplit","name":"impl","type":"address"}],"name":"setNewImpl","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"internalType":"contract IERC20","name":"fromToken","type":"address"},{"internalType":"contract IERC20","name":"toToken","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"uint256","name":"minReturn","type":"uint256"},{"internalType":"uint256[]","name":"distribution","type":"uint256[]"},{"internalType":"uint256","name":"featureFlags","type":"uint256"}],"name":"swap","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"}]'''
    amount = 10000000
    contract = web3.eth.contract(address=contractAddress,
                                 abi=abi)
    
    minReturn, distribution  = contract.functions.getExpectedReturn(fromToken='0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
                                                                    toToken='0x57Ab1ec28D129707052df4dF418D58a2D46d5f51',
                                                                    amount=amount,
                                                                    parts=5,
                                                                    featureFlags=0).call({'from':'0x0000000000000000000000000000000000000000'})

    print(minReturn,distribution)

    txPrep = contract.functions.swap(fromToken='0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
                                     toToken='0x57Ab1ec28D129707052df4dF418D58a2D46d5f51',
                                     amount=amount,
                                     minReturn=minReturn,
                                     distribution=distribution,
                                     featureFlags=0)

    gasEstimate =   txPrep.estimateGas({'from':address,
                                        'value':amount})
    
    print(gasEstimate)


#%%Test Mainnet
infuraLink='https://mainnet.infura.io/v3/XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
web3Mainnet=w3.Web3(w3.HTTPProvider(infuraLink))    
estimateGas(web3Mainnet)


#%%Test Mainnet Fork
ganacheCLI='http://127.0.0.1:8545'
web3MainnetFork=w3.Web3(w3.HTTPProvider(ganacheCLI,request_kwargs={'timeout': 600}))
estimateGas(web3MainnetFork)
```

The output is as follows:
```
In [20]: runcell('Test Mainnet', 'C:/kaleb/1inch/test.py')
4535120411 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0]
568618
```

```
In [21]: runcell('Test Mainnet Fork', 'C:/kaleb/1inch/test.py')
4535120411 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0]
Traceback (most recent call last):

  File "C:\kaleb\1inch\test.py", line 41, in <module>
    estimateGas(web3MainnetFork)

  File "C:\kaleb\1inch\test.py", line 27, in estimateGas
    'value':amount})

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\contract.py", line 1044, in estimateGas
    **self.kwargs

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\contract.py", line 1618, in estimate_gas_for_function
    return web3.eth.estimateGas(estimate_transaction, block_identifier)

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\module.py", line 44, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\manager.py", line 154, in request_blocking
    response = self._make_request(method, params)

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\manager.py", line 133, in _make_request
    return request_func(method, params)

  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\middleware\formatting.py", line 76, in apply_formatters
    response = make_request(method, params)

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\middleware\gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)

  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\middleware\formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\middleware\attrdict.py", line 33, in middleware
    response = make_request(method, params)

  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\middleware\formatting.py", line 83, in apply_formatters
    formatter(response["result"]),

  File "cytoolz\functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\eth_utils\applicators.py", line 72, in apply_formatter_if
    return formatter(value)

  File "C:\kaleb\miniconda\envs\keeper\lib\site-packages\web3\_utils\formatters.py", line 42, in hex_to_integer
    return int(value, 16)

ValueError: invalid literal for int() with base 16: '0x-8410410323c3'
```

Not sure what the issue is, as I tested the same code with ETH to DAI swap, and seems to work fine.
The verbose of the ganache cli shows this at the end
![image](https://user-images.githubusercontent.com/62237347/98470678-9cfe3700-21e7-11eb-987b-77221e59a388.png)

**Comment by kclowes** [comment]
@kaleb-keny it looks like web3 is trying to format the response on the way back, but the formatter (`int()`) doesn't know what to do with the dash. You may be able to add some middleware to strip out the dash ([docs here](https://web3py.readthedocs.io/en/stable/internals.html#internals-middlewares)), or you could extend the `Method` class and put in your own custom response formatter, but that's not currently documented. You can see an example of how it is done in another one of our libraries [here](https://github.com/ethereum/ddht/pull/94/files#diff-a055f2e00f32dbb2b313cc95e0524458ae9e053dbcb2075291b38a446001ae85R148-R152). It's on my list to document, so that should be coming up soon.

**Comment by kaleb-keny** [comment]
hey, thanks for the answer, should I raise this issue with ganache devs? As I don't think the gasEstimate is correct even without the dash ... As it exceeds the max gas in a block  think?

**Comment by kclowes** [comment]
Yeah, I'd raise it with them and see what they say. I'm going to close this issue, but feel free to reopen if there's something else going on!

**Comment by kaleb-keny** [comment]
Just wanted to post here a solution to the issue, in case someone stumbles upon it, using estimate transaction as per the below configuration seems to work fine on ganache and mainnet, where txPrep is the variable generated as per the above code
```

        tx = txPrep.buildTransaction({'chainId': self.chainId,
                                      'gas': self.inchGas,
                                      'gasPrice': gasPrice,
                                      'nonce': nonce})

        w3.eth.estimateGas(transaction={'to':contractAddress,
                                                              from':address,
                                                               value':int(msgValue),
                                                               data':tx["data"]})
```

**Comment by kclowes** [comment]
Ah, thanks for the update @kaleb-keny. Looks like the key was that `data` field encoding?

**Comment by kaleb-keny** [comment]
yeah definitely, using the `data encoding` instead of wrapping estimateGas with the tx seems to work, although both approaches are equivalent on mainnet but not on forked ganachian-mainnet.
