### ISSUE TITLE
Allow longer timeouts then 10 seconds

### ISSUE THREAD

**Issue by owodunni** [ethereum/web3.py#1798]
* Version: 5.12.1
* Python: 3.8.6
* OS: linux
* `pip freeze` output

```
pip freeze
....                                                                                                                                                                                                  
requests==2.24.0
urllib3==1.25.10
web3==5.12.1
```

### What was wrong?

* Connections timeout after 10 seconds. I am doing a lot event filtering of smart contracts. Which results in me choking my Geth Node. Leading to longer respons times and eventually timeouts.
* Error output:
```
11-21 15:40 [MainThread  ] [ERROR]  HTTPConnectionPool(host='gluteus', port=8545): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='gluteus', port=8545): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/owodunni/.local/venv/bin/Arbie", line 11, in <module>
    load_entry_point('Arbie', 'console_scripts', 'Arbie')()
  File "/home/owodunni/Prog/arbie/Arbie/__main__.py", line 66, in main
    raise ex
  File "/home/owodunni/Prog/arbie/Arbie/__main__.py", line 63, in main
    asyncio.run(app.run())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/owodunni/Prog/arbie/Arbie/arbie.py", line 20, in run
    await self.action_tree.run()
  File "/home/owodunni/Prog/arbie/Arbie/Actions/action_tree.py", line 56, in run
    await self._run_once()
  File "/home/owodunni/Prog/arbie/Arbie/Actions/action_tree.py", line 73, in _run_once
    await action.on_next(data)
  File "/home/owodunni/Prog/arbie/Arbie/Actions/pool_finder.py", line 108, in on_next
    *await self._get_results(uni_coro, bal_coro),
  File "/home/owodunni/Prog/arbie/Arbie/Actions/pool_finder.py", line 124, in _get_results
    results = await asyncio.gather(uni_coro, bal_coro)
  File "/home/owodunni/Prog/arbie/Arbie/Contracts/balancer.py", line 120, in all_pools
    return self._create_pools(await bf.find_events())
  File "/home/owodunni/Prog/arbie/Arbie/Contracts/event_filter.py", line 17, in find_events
    results = await async_map(self._get_entries, range(nmb_event_chunks))
  File "/home/owodunni/Prog/arbie/Arbie/async_helpers.py", line 8, in async_map
    return await asyncio.gather(*tasks)
  File "/home/owodunni/Prog/arbie/Arbie/Contracts/event_filter.py", line 32, in _get_entries
    return await self._get_entries_range(from_block, to_block)
  File "/home/owodunni/Prog/arbie/Arbie/Contracts/event_filter.py", line 40, in _get_entries_range
    return await loop.run_in_executor(None, event_filter.get_all_entries)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/_utils/filters.py", line 163, in get_all_entries
    log_entries = self._filter_valid_entries(self.web3.eth.getFilterLogs(self.filter_id))
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/eth.py", line 497, in getFilterLogs
    return self.web3.manager.request_blocking(
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/providers/rpc.py", line 92, in make_request
    raw_response = make_post_request(
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/web3/_utils/request.py", line 39, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/owodunni/.local/venv/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='gluteus', port=8545): Read timed out. (read timeout=10)

```

* Node: 

ethereum/client-go:stable@sha256:8009eca8f4a768e76582a14b4cce0e2e0dd5044e5f963ed9e0e6e4ac435804dd
* Connection Http

### How can it be fixed?

In line 36 in file https://github.com/ethereum/web3.py/blob/e176ce0793dafdd0573acc8d4b76425b6eb604ca/web3/_utils/request.py

there is a hardcoded timeout of 10 seconds. I think allowing this to be larger would fix the issue.

**Comment by kclowes** [comment]
@owodunni At a quick glance, it looks like you should be able to pass in timeout as a keyword argument. Did you try that already?

**Comment by owodunni** [comment]
Hi @kclowes, I think I missed that. I thought it looked pretty hard coded..
I tried setting other parameters in this manner: https://github.com/ethereum/web3.py/commit/55297bc9df44a032e7ea223aa12229d72de5ef5a

But as far as I could see I cannot set the timeout that way.

**Comment by kclowes** [comment]
I just tested it out, and you are able to pass it in with the request_kwargs. So:
`w3 = Web3(HTTPProvider('http://localhost:8545', request_kwargs={'timeout': 60}))`
But that could definitely be documented better, so I'll leave this issue open to add it to the docs. Let me know if that doesn't work for you. Thanks for the report!

**Comment by marcgarreau** [comment]
IMO, this is a fringe use case and is sufficiently documented [here](https://web3py.readthedocs.io/en/stable/providers.html#httpprovider), so closing this issue. If we want to document other/all tweakable args, lets open a new issue.
