### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=7545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccac7ca5f8>: Failed to establish a new connection: [Errno 111] Connection refused',))

### ISSUE THREAD

**Issue by esraa95mahmoud** [ethereum/web3.py#1800]
I created a blockchain app using Ethereum, I downloaded a virtual box. I activated the smart contract on the virtual box and connected it to the Python file on the original device. When the application is executed I get this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 144, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 153, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fccac7ca5f8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=7545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccac7ca5f8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "final.py", line 18, in <module>
    web3.eth.defaultAccount = web3.eth.accounts[0]
  File "/usr/local/lib/python3.6/dist-packages/web3/eth.py", line 182, in accounts
    return self.get_accounts()
  File "/usr/local/lib/python3.6/dist-packages/web3/module.py", line 44, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 154, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 133, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/providers/rpc.py", line 95, in make_request
    **self.get_request_kwargs()
  File "/usr/local/lib/python3.6/dist-packages/web3/_utils/request.py", line 39, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 567, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=7545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccac7ca5f8>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by kclowes** [comment]
@esraa95mahmoud I'll need some more detail to help you troubleshoot. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) please?

**Comment by esraa95mahmoud** [comment]
@kclowes I have a smart contract that was linked to web3.py through the Python file. I want to do a test to apply Ethereum. I ran the smart contract and 127.0.1.1.7545 on my Eppento device, and I linked them with the Python file on the virtual box, when running them it gives me the previous error.
Do you want to put the code here ??

**Comment by kclowes** [comment]
Yes please!

**Comment by Naheel-Azawy** [comment]
Hello, I'm having a similar error. Here's a minimal example:

```py
from web3 import Web3
url1 = "http://127.0.0.1:8545"
url2 = "http://192.168.2.158:8545"
w3 = Web3(Web3.HTTPProvider(url1))
print(w3.eth.accounts)
```

Using `url1` everything works nicely for me. But `url2` results to a similar error as OP's error. Note that this is my actual private IP. I was wondering why I'm getting this error on my raspberry pi. But when I tested the same on my local machine, weirdly enough, I got the same error. I'm using ganache and truffle. I guess I'm doing something wrong, any ideas?

**Comment by kclowes** [comment]
Hmm, I'm not sure. Could be a firewall?

**Comment by Naheel-Azawy** [comment]
I don't think so. I didn't add any special rules to it. But anyway, I always use my machine to deploy all sorts of services for development and access it from different devices with no issues.

**Comment by Naheel-Azawy** [comment]
Ok I guess I found it. As mentioned in https://github.com/simolus3/web3dart/issues/32, ganache uses 127.0.0.0 by default. It needs to be set to 0.0.0.0. Problem solved for me. I hope this helped @esraa95mahmoud?

**Comment by kclowes** [comment]
Awesome, thanks for the update @Naheel-Azawy! I'm going to close since you solved your issue and I never got a response from @esraa95mahmoud back in December.

**Comment by robinportigliatti** [comment]
Found myself here as I used Docker and had the same error.

Just run the `ganache-cli` inside your docker with this command :
```
ganache-cli -h 0.0.0.0 -p 8545
```
And then you can access ganache via `http://0.0.0.0:8545"`
Or just use another docker with this `Dockerfile` and `docker-compose`:
```
FROM node:alpine
# Set the /app directory as working directory
WORKDIR /app
# Install ganache-cli globally
RUN npm install -g ganache-cli
RUN apk add --no-cache bash
# Set the default command for the image
CMD ["ganache-cli", "-h", "0.0.0.0", "--port", "8545"]
```
In `docker-compose.yml` you should have something like this:
```
  ganache:
    build: ./ganache
    command: bash -c "ganache-cli -h 0.0.0.0 --port 8545"
    env_file:
      - ganache.env
```

And access it via `http://ganache:8545`  from your application
