### ISSUE TITLE
web3.exceptions.BadFunctionCallOutput on ens.name call

### ISSUE THREAD

**Issue by zinootje** [ethereum/web3.py#1802]
* Version:5.12.2
* Python: 3.7
* OS: win
* `pip freeze` output
```
absl-py==0.10.0
adanet==0.8.0
astunparse==1.6.3
attrdict==2.0.1
attrs==20.2.0
autobahn==20.7.1
Automat==20.2.0
base58==2.0.0
bitarray==1.2.2
cachetools==4.1.0
certifi==2019.11.28
cffi==1.14.3
chardet==3.0.4
click==7.1.2
colorama==0.4.3
commando==1.0.0
constantly==15.1.0
coverage==5.3
cryptography==3.2.1
Cython==0.29.21
cytoolz==0.10.1
deap==1.3.1
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.2.1
eth-typing==2.2.1
eth-utils==1.9.5
fswrap==1.0.0
gast==0.4.0
gevent==1.4.0
google-auth==1.14.3
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
greenlet==0.4.15
grpcio==1.28.1
guppy3==3.1.0
gviz-api==1.9.0
h5py==2.10.0
hexbytes==0.2.1
hkdf==0.0.3
humanize==3.1.0
hyde==0.8.9
hyperlink==20.0.1
idna==2.8
importlib-metadata==1.5.0
incremental==17.5.0
ipfshttpclient==0.7.0a1
Jinja2==2.11.2
joblib==0.17.0
jsonpickle==1.4.1
jsonschema==3.2.0
Keras-Preprocessing==1.1.2
lru-dict==1.1.6
magic-wormhole==0.12.0
Markdown==2.6.11
MarkupSafe==0.23
minify-html==0.3.8
mock==3.0.5
multiaddr==0.0.9
mypy-extensions==0.4.3
netaddr==0.8.0
nose==1.3.7
numpy==1.18.4
oauthlib==3.1.0
opt-einsum==3.3.0
pandas==1.0.3
parsimonious==0.8.1
profilehooks==1.11.2
protobuf==3.11.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.19
pycryptodome==3.9.4
Pygments==2.7.1
PyHamcrest==2.0.2
PyNaCl==1.4.0
pyOpenSSL==19.1.0
pypiwin32==223
pyrsistent==0.15.7
python-dateutil==2.8.1
pytz==2020.1
pywin32==227
PyYAML==3.13
rednose==1.3.0
requests==2.22.0
requests-oauthlib==1.3.0
rlp==1.2.0
rsa==4.0
scikit-learn==0.23.0
scipy==1.4.1
service-identity==18.1.0
six==1.13.0
sklearn==0.0
smartypants==1.8.6
spake2==0.8
stopit==1.1.2
tensorboard==2.2.1
tensorboard-plugin-profile==2.2.0
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
termstyle==0.1.11
threadpoolctl==2.0.0
toolz==0.10.0
TPOT==0.11.2
tqdm==4.46.0
Twisted==20.3.0
txaio==20.4.1
txtorcon==20.0.0
typing-extensions==3.7.4.1
typogrify==2.0.7
ujson==4.0.1
uniswap-python==0.3.4
update-checker==0.17
urllib3==1.25.7
varint==1.0.2
web3==5.12.2
websocket==0.2.1
websocket-client==0.57.0
websockets==8.1
Werkzeug==1.0.1
wrapt==1.12.1
xgboost==1.0.2
yappi==1.2.3
yattag==1.14.0
zipp==2.1.0
zope.interface==5.1.2

```

### What was wrong?
```
import web3
w3 = web3.Web3(web3.WebsocketProvider("wss://mainnet.infura.io/ws/*******"))
import ens
ns = ens.ENS.fromWeb3(w3)
adress = ns.name("0x6ED8CD17EE5453E17eb731a6B2004aF53eA1f26a")
print(adress)
```

running this gives the error
```
`Traceback (most recent call last):
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\contract.py", line 1507, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_abi\codec.py", line 181, in decode_abi
    return decoder(stream)
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_abi\decoding.py", line 173, in decode
    yield decoder(stream)
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_abi\decoding.py", line 142, in decode
    start_pos = decode_uint_256(stream)
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_abi\decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\eth_abi\decoding.py", line 308, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/**/***/errrr.py", line 5, in <module>
    adress = ns.name("0x6ED8CD17EE5453E17eb731a6B2004aF53eA1f26a")
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\ens\main.py", line 122, in name
    return self.resolve(reversed_domain, get='name')
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\ens\main.py", line 217, in resolve
    address = lookup_function(namehash).call()
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\contract.py", line 964, in call
    **self.kwargs
  File "C:\Users\**\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\contract.py", line 1529, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?` 
```
it should return the eth name or null if there isn't one if i understand correctly

**Comment by kclowes** [comment]
@zinootje Sorry for the long response time. You are right, it usually does return either the name or `None` if there is no name. I _think_ what's happening in this case is that the contract uses a custom resolver that either doesn't implement reverse resolution, or the ABI for reverse resolution doesn't match the ABI that web3py expects. I can't see the ABI for the contract at "0x6ED8CD17EE5453E17eb731a6B2004aF53eA1f26a" on Etherscan, so I'm not 100% sure. AFAIK, we don't support custom resolvers. However, if the resolver implements the standard functionality (like [here](https://docs.ens.domains/contract-api-reference/publicresolver)), web3 should be able to handle it. 

On first glance, it seems like it would be straightforward to support a custom resolver by passing it in to the ENS class on initialization, but I'm not sure if there is a historical reason why we didn't add that or why it may be more complicated than it seems. @carver - do you know? And please correct me if any of that is wrong!

**Comment by carver** [comment]
Right, if the ENS entry points to an invalid resolver, or to a resolver that doesn't offer a reverse resolution function, then the resolution attempt would crash.

**Comment by fselmo** [comment]
stale
