### ISSUE TITLE
ipc socket timeout unrecoverable doing unlock_account on a local node

### ISSUE THREAD

**Issue by joseluu** [ethereum/web3.py#1842]
* Version: 5.15.0
* Python: 3.6
* OS: linux
* `pip freeze` output

```
attrdict==2.0.1
attrs==20.3.0
base58==2.1.0
bitarray==1.2.2
certifi==2020.11.8
chardet==3.0.4
click==7.1.2
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.9.5
Flask==1.1.2
hexbytes==0.2.1
idna==2.10
importlib-metadata==3.4.0
importlib-resources==5.1.0
ipfshttpclient==0.7.0a1
itsdangerous==1.1.0
Jinja2==2.11.2
jsonschema==3.2.0
lru-dict==1.1.6
MarkupSafe==1.1.1
multiaddr==0.0.9
netaddr==0.8.0
numpy==1.19.5
pandas==1.1.5
parsimonious==0.8.1
pkg-resources==0.0.0
protobuf==3.14.0
pycryptodome==3.9.9
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2020.5
requests==2.24.0
rlp==2.0.0
six==1.15.0
toolz==0.11.1
typing-extensions==3.7.4.3
urllib3==1.25.11
varint==1.0.2
web3==5.15.0
websockets==8.1
Werkzeug==1.0.1
zipp==3.4.0
```

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
*w3.geth.personal.unlockAccount(QAXH_ADDRESS, QAXH_PASSWORD)
* The full output of the error
Traceback (most recent call last):
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/providers/ipc.py", line 246, in make_request
    raw_response += sock.recv(4096)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/flask/app.py", line 2464, in _call_
    return self.wsgi_app(environ, start_response)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/test_id/plateform/authentification.py", line 729, in mobile_connect_test
    return authenticate(address, customerId, deadline, money, provider, hatch_address, dico_response)
  File "/var/www/test_id/plateform/authentification.py", line 945, in authenticate
    safe, tx_hash1 = deploy_diamond_user_safe(gasPrice_in_gwei, owner_hash, saltQI, saltQE, customerId, provider, diamond_constructor_args, hatch_address)
  File "/var/www/test_id/plateform/qaxh_packages/deployment/deployProxies.py", line 189, in deploy_diamond_user_safe
    w3.geth.personal.unlockAccount(QAXH_ADDRESS, QAXH_PASSWORD)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/manager.py", line 154, in request_blocking
    response = self._make_request(method, params)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/manager.py", line 133, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry._call_
    
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry._call_
    
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry._call_
    
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry._call_
    
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry._call_
    
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry._call_
    
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/providers/ipc.py", line 248, in make_request
    timeout.sleep(0)
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/_utils/threads.py", line 89, in sleep
    self.check()
  File "/var/www/test_id/plateform/venv/lib/python3.6/site-packages/web3/_utils/threads.py", line 82, in check
    raise self
web3._utils.threads.Timeout: True seconds
* What type of node you were connecting to:
connecting to local node via IPC

### How can it be fixed?

I have a pull request to fix it

**Comment by pipermerriam** [comment]
Can you expand on why this is "unrecoverable"?

**Comment by joseluu** [comment]
> Can you expand on why this is "unrecoverable"?
There is an uncatched exception within an exception handler, so it escapes the initial exception handler and the program flow is not consistent anymore, in this case, the call to unlock_account is not done and subsequent transaction signing fails.

**Comment by pacrob** [comment]
New `AsyncIPCProvider` and deprecation of `geth.personal` render this moot. Closing.
