### ISSUE TITLE
Installation of web3[tester] fails because of netaddr-0.7.3

### ISSUE THREAD

**Issue by jbirnick** [ethereum/web3.py#1873]
* Version: Newest?
* Python: 3.9.1
* OS: Arch Linux
* `pip freeze` output

```
alabaster==0.7.12
anki @ file:///build/anki/src/anki/dist/anki-2.1.35-py3-none-any.whl
ankirspy @ file:///build/anki/src/anki/dist/ankirspy-2.1.35-cp39-cp39-manylinux1_x86_64.whl
anyio==2.0.2
anytree==2.8.0
appdirs==1.4.4
apsw==3.34.0.post1
aqt @ file:///build/anki/src/anki/dist/aqt-2.1.35-py3-none-any.whl
arandr==0.1.10
argon2-cffi==20.1.0
asn1crypto==1.4.0
async-generator==1.10
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
base58==2.1.0
Beaker==1.11.0
beautifulsoup4==4.9.3
bitarray==1.2.2
bleach==3.3.0
borgbackup==1.1.14
btrfsutil==5.10
CacheControl==0.12.6
cffi==1.14.4
chardet==3.0.4
click==7.1.2
colorama==0.4.4
contextlib2==0.6.0.post1
cryptography==3.3.1
css-parser==1.0.6
cssselect==1.1.0
cvxopt==1.2.5
cycler==0.10.0
cypari2==2.1.2
cysignals==1.10.2
Cython==0.29.21
cytoolz==0.11.0
decorator==4.4.2
defusedxml==0.6.0
distlib==0.3.1
distro==1.5.0
dnspython==1.16.0
docutils==0.16
entrypoints==0.3
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
feedparser==5.2.1
Flask==1.1.2
Flask-Cors==3.0.9
fpylll==0.5.5
gmpy2==2.1.0b5
gpg==1.15.1
hexbytes==0.2.1
html2text==2020.1.16
html5-parser==0.4.9
html5lib==1.1
idna==2.10
ifaddr==0.1.7
imagesize==1.2.0
importlib-metadata==3.4.0
ipfshttpclient==0.7.0a1
ipykernel==5.4.2
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.6.2
itsdangerous==1.1.0
jedi==0.17.2
Jinja2==2.11.3
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.6.3
jupyter-server==1.3.0
jupyterlab==3.0.7
jupyterlab-pygments==0.1.2
jupyterlab-server==2.2.0
kiwisolver==1.3.1
lensfun==0.3.95
lightdm-gtk-greeter-settings==1.2.2
louis==3.16.0
lru-dict==1.1.7
lxml==4.6.2
Mako==1.1.4
mallard-ducktype==1.0.2
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib==3.3.4
mechanize==0.4.5
mistune==0.8.4
mpmath==1.1.0
msgpack==1.0.2
multiaddr==0.0.9
nbclassic==0.2.6
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nest-asyncio==1.4.3
netaddr==0.8.0
netifaces==0.10.9
networkx==2.5
notebook==6.2.0
numpy==1.20.0
ordered-set==4.0.2
orjson @ file:///build/python-orjson/src/python-orjson-3.4.8/target/wheels/orjson-3.4.8-cp39-cp39-manylinux2010_x86_64.whl
packaging==20.9
pandocfilters==1.4.3
parsimonious==0.8.1
parso==0.7.1
pdfarranger==1.7.0
pep517==0.9.1
pexpect==4.8.0
pickleshare==0.7.5
pikepdf==2.5.2
Pillow==8.1.0
ply==3.11
pplpy==0.8.7
progress==1.5
prometheus-client==0.9.0
prompt-toolkit==3.0.14
protobuf==3.12.4
psutil==5.8.0
ptyprocess==0.7.0
pwquality==1.4.4
py7zr==0.11.3
PyAudio==0.2.11
pycairo==1.20.0
pychm==0.8.6
pycparser==2.20
pycryptodome==3.9.9
pyfiglet==0.8.post1
Pygments==2.7.4
PyGObject==3.38.0
PyOpenGL==3.1.5
pyOpenSSL==20.0.1
pyparsing==2.4.7
PyQt5==5.15.2
PyQt5-sip==12.8.1
PyQtWebEngine==5.15.2
pyrsistent==0.17.3
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2021.1
pyzmq==20.0.0
regex==2020.11.13
requests==2.25.1
resolvelib==0.5.4
retrying==1.3.3
rlp==2.0.1
rpy2==3.4.2
sage==9.2
sagetex==3.5
scipy==1.6.0
Send2Trash==1.5.0
six==1.15.0
sniffio==1.2.0
snowballstemmer==2.1.0
soupsieve==2.1
Sphinx==3.4.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sympy==1.7.1
team==1.0
termdown==1.17.0
terminado==0.9.2
testpath==0.4.4
texttable==1.6.3
todoist-python==8.1.2
toml==0.10.2
toolz==0.11.1
torbrowser-launcher==0.3.3
tornado==6.1
traitlets==5.0.5
typing==3.7.4.3
tzlocal==2.1
unrardll==0.1.4
urllib3==1.26.3
varint==1.0.2
waitress==1.4.4
wcwidth==0.2.5
web3==5.16.0
webencodings==0.5.1
websockets==8.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
youtube-dl==2021.2.4.1
zeroconf==0.28.8
zipp==3.4.0
```

### The problem

The installation of web3[tester] fails with the following error:
```
$ pip install 'web3[tester]'
...
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in ./.local/lib/python3.9/site-packages (from web3[tester]) (2.2.2)
Requirement already satisfied: eth-utils<2.0.0,>=1.9.5 in ./.local/lib/python3.9/site-packages (from web3[tester]) (1.10.0)
  Downloading netaddr-0.7.3.zip (1.2 MB)
     |████████████████████████████████| 1.2 MB 27.0 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pxwvxzet/netaddr_594172a6e3a5462a8090952ac3c4b2ba/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pxwvxzet/netaddr_594172a6e3a5462a8090952ac3c4b2ba/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mzp42oy1
         cwd: /tmp/pip-install-pxwvxzet/netaddr_594172a6e3a5462a8090952ac3c4b2ba/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pxwvxzet/netaddr_594172a6e3a5462a8090952ac3c4b2ba/setup.py", line 23
        print "netaddr requires Python version 2.4.x or higher."
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("netaddr requires Python version 2.4.x or higher.")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

How can this be fixed?

**Comment by kclowes** [comment]
It looks like you're using python 3.9 which we don't support yet. Try using python 3.8, and if that doesn't work, feel free to reopen this issue!
