### ISSUE TITLE
AttributeError: 'Contract' object has no attribute 'transact'

### ISSUE THREAD

**Issue by JuanDavidG1997** [ethereum/web3.py#1922]
* Version: 5.17.0
* Python: 3.69
* OS: linux*
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?
For some wierd reason I can't call the funcion transact of web3._utils.datatypes.Contract.
I am trying to add a participant to my test blockchain

Please include any of the following that are applicable:

* The code which produced the error
for i in range(num):
            # Transact to the blockchain to add a participant
            temp = {'from': self.accounts[i], 'to': self.contract_addr, 'gas': 900000}
            trans_hash = self.contract.transact(temp).add_participant()
            self._wait_until_trans_receipt(trans_hash)
* The full output of the error
* Starting "PyPower" as "PyPower-0" ...
Starting "HouseholdSim" as "HouseholdSim-0" ...
Starting "CSV" as "CSV-0" ...
Starting "Ethereum" as "Ethereum-0" ...
<class 'web3._utils.datatypes.Contract'>
Traceback (most recent call last):
  File "demo.py", line 165, in <module>
    main()
  File "demo.py", line 44, in main
    create_scenario(world)
  File "demo.py", line 65, in create_scenario
    ethereum = ethereum_sim.Ethereum.create(10)
  File "/home/juan/mosaik/Mosaik/lib/python3.6/site-packages/mosaik/scenario.py", line 418, in create
    model_params)
  File "/home/juan/mosaik/Mosaik/lib/python3.6/site-packages/mosaik/util.py", line 68, in sync_call
    return sync_process(proc(), sim._world)
  File "/home/juan/mosaik/Mosaik/lib/python3.6/site-packages/mosaik/util.py", line 26, in sync_process
    return world.env.run(until=world.env.process(generator))
  File "/home/juan/mosaik/Mosaik/lib/python3.6/site-packages/simpy/core.py", line 138, in run
    self.step()
  File "/home/juan/mosaik/Mosaik/lib/python3.6/site-packages/simpy/io/base.py", line 77, in step
    callback(event)
  File "/home/juan/mosaik/Mosaik/lib/python3.6/site-packages/simpy/core.py", line 60, in callback
    raise event.value
  File "/home/juan/mosaik/Mosaik/lib/python3.6/site-packages/mosaik/util.py", line 61, in proc
    ret = yield func(*args, **kwargs)
  File "/home/juan/mosaik/Mosaik/lib/python3.6/site-packages/mosaik_api.py", line 393, in wrapper
    ret = func(*args, **kwargs)
  File "/home/juan/mosaik/mosaik_ethereum_demo/model/mosaik_ethereum.py", line 51, in create
    trans_hash = self.contract.transact(temp).add_participant()
AttributeError: 'Contract' object has no attribute 'transact'

**Comment by kclowes** [comment]
@JuanDavidG1997 It's hard to tell without more details, but my best guess is your ABI is wrong. Can you post how you're setting up the contract instance?

**Comment by marcgarreau** [comment]
Closing due to inactivity; please reopen if necessary. I suspect the [contract example docs](https://web3py.readthedocs.io/en/latest/examples.html#working-with-contracts) are enough to resolve this either way.
