### ISSUE TITLE
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call getAmountsOut return data b'' for output_types ['uint256[]']

### ISSUE THREAD

**Issue by FCaimi** [ethereum/web3.py#1959]
* Version: web3==5.18.0
* Python: 3.9.4
* OS: osx
* `pip freeze` output

```
attrs==20.3.0
base58==2.1.0
bitarray==1.2.2
certifi==2020.12.5
chardet==4.0.0
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.1
idna==2.10
ipfshttpclient==0.7.0a1
jsonschema==3.2.0
lru-dict==1.1.7
multiaddr==0.0.9
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.15.8
pyaes==1.6.1
pyasn1==0.4.8
pycryptodome==3.10.1
pyrsistent==0.17.3
requests==2.25.1
rlp==2.0.1
rsa==4.7.2
six==1.15.0
Telethon==1.21.1
toolz==0.11.1
urllib3==1.26.4
varint==1.0.2
web3==5.18.0
websockets==8.1
```

### What was wrong?

I'm trying to call a smartcontract function deployed on BSC mainnet (pancakeswap router) to read token prices :

```from web3 import Web3
import json

BSC_URL = 'https://bsc-dataseed1.binance.org:443/'

PANCAKE_ROUTER_ADDRESS = '0x05fF2B0DB69458A0750badebc4f9e13aDd608C7F'

w3 = Web3(Web3.HTTPProvider(BSC_URL))

TOKEN_1 = '0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82'
TOKEN_2 = '0x4Fabb145d64652a948d72533023f6E7A623C7C53'

pancakeRouter_abi = json.load(open('abi/pancakeRouter.json', 'r'))

pancake_contract = w3.eth.contract(address=PANCAKE_ROUTER_ADDRESS, abi=pancakeRouter_abi)

total = pancake_contract.functions.getAmountsOut(10000000000000000000, [TOKEN_1, TOKEN_2]).call()
```

But I have the following error :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/web3/contract.py", line 1507, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 142, in decode
    start_pos = decode_uint_256(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/usr/local/lib/python3.9/site-packages/eth_abi/decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Federico/Documents/Progetti/Crypto/dapp-bot/vigilante.py", line 31, in <module>
    total_token2 = pancake_contract.functions.getAmountsOut(10000000000000000000, [TOKEN_1, TOKEN_2]).call()
  File "/usr/local/lib/python3.9/site-packages/web3/contract.py", line 954, in call
    return call_contract_function(
  File "/usr/local/lib/python3.9/site-packages/web3/contract.py", line 1528, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call getAmountsOut return data b'' for output_types ['uint256[]']
```

The strange thing is that if a call another function on the smart contract everything works fine, for example:

```
weth = pancake_contract.functions.WETH().call()
print(weth)
```

Can anyone help with this problem ? 

Thanks

**Comment by stevencoveta** [comment]
Your router contract is not correct
