### ISSUE TITLE
web3.exceptions.LogTopicError: Expected 3 log topics.  Got 2

### ISSUE THREAD

**Issue by clanstyles** [ethereum/web3.py#1974]
* Version: 0.8.0
* Python: 3.8
* OS: linux
* `pip freeze` output

```amqp==2.6.1
asgiref==3.3.4
attrs==20.3.0
base58==2.1.0
billiard==3.6.4.0
bitarray==1.2.2
celery==4.4.7
certifi==2020.12.5
chardet==4.0.0
cytoolz==0.11.0
Django==3.2
django-crispy-forms==1.11.2
django-formtools==2.3
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.1
idna==2.10
importlib-metadata==4.0.1
ipfshttpclient==0.7.0a1
jsonschema==3.2.0
kombu==4.6.11
lru-dict==1.1.7
multiaddr==0.0.9
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.15.8
pycryptodome==3.10.1
pyrsistent==0.17.3
pytz==2021.1
redis==3.5.3
requests==2.25.1
rlp==2.0.1
six==1.15.0
sqlparse==0.4.1
toolz==0.11.1
typing-extensions==3.10.0.0
urllib3==1.26.4
varint==1.0.2
vine==1.3.0
web3==5.19.0
websockets==8.1
zipp==3.4.1
```

### What was wrong?
We are trying to listen on the event "transfer" and are having an issue where the topics aren't aligned. 

env variables to reproduce it:
MARKETPLACE_ADDRESS=0xE9d84aa46C621b159eB6118aC8774F5E630B58e8 
NODE=https://data-seed-prebsc-1-s1.binance.org:8545

```
Traceback (most recent call last):
  File "__init__.py", line 470, in <module>
    main()
  File "__init__.py", line 459, in main
    loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "__init__.py", line 17, in log_loop
    for event in event_filter.get_new_entries():
  File "/home/styles/work/bsc/env/lib/python3.8/site-packages/web3/_utils/filters.py", line 161, in get_new_entries
    return self._format_log_entries(log_entries)
  File "/home/styles/work/bsc/env/lib/python3.8/site-packages/web3/_utils/filters.py", line 172, in _format_log_entries
    formatted_log_entries = [
  File "/home/styles/work/bsc/env/lib/python3.8/site-packages/web3/_utils/filters.py", line 173, in <listcomp>
    self.format_entry(log_entry) for log_entry in log_entries
  File "/home/styles/work/bsc/env/lib/python3.8/site-packages/web3/_utils/filters.py", line 204, in format_entry
    return self.log_entry_formatter(entry)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/styles/work/bsc/env/lib/python3.8/site-packages/web3/_utils/events.py", line 225, in get_event_data
    raise LogTopicError("Expected {0} log topics.  Got {1}".format(
web3.exceptions.LogTopicError: Expected 3 log topics.  Got 2
```
Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.
```
import os
import asyncio
from web3 import Web3

def handle_transfer_event(event):
    print('transfer: ',handle_peter_event,  event)

async def log_loop(event_filter, name, handle_event, poll_interval):
    while True:
        print('name:', name)
        for event in event_filter.get_new_entries():
            handle_event(event)

        await asyncio.sleep(poll_interval)

def main():
    node = os.getenv('NODE')
    nft_address = os.getenv('NFT_ADDRESS')

    '''
    Marketplace Demo
    '''
    abi = '''[
{
"anonymous": false,
"inputs": [
{
"indexed": true,
"internalType": "address",
"name": "owner",
"type": "address"
},
{
"indexed": true,
"internalType": "address",
"name": "approved",
"type": "address"
},
{
"indexed": true,
"internalType": "uint256",
"name": "tokenId",
"type": "uint256"
}
],
"name": "Approval",
"type": "event"
},
{
"anonymous": false,
"inputs": [
{
"indexed": true,
"internalType": "address",
"name": "owner",
"type": "address"
},
{
"indexed": true,
"internalType": "address",
"name": "operator",
"type": "address"
},
{
"indexed": false,
"internalType": "bool",
"name": "approved",
"type": "bool"
}
],
"name": "ApprovalForAll",
"type": "event"
},
{
"anonymous": false,
"inputs": [
{
"indexed": false,
"internalType": "uint256",
"name": "id",
"type": "uint256"
},
{
"indexed": false,
"internalType": "address",
"name": "_sentTo",
"type": "address"
},
{
"indexed": false,
"internalType": "string",
"name": "tokenURI",
"type": "string"
}
],
"name": "Mint",
"type": "event"
},
{
"anonymous": false,
"inputs": [
{
"indexed": true,
"internalType": "uint256",
"name": "id",
"type": "uint256"
},
{
"indexed": true,
"internalType": "string",
"name": "str",
"type": "string"
}
],
"name": "Peter",
"type": "event"
},
{
"anonymous": false,
"inputs": [
{
"indexed": true,
"internalType": "address",
"name": "from",
"type": "address"
},
{
"indexed": true,
"internalType": "address",
"name": "to",
"type": "address"
},
{
"indexed": true,
"internalType": "uint256",
"name": "tokenId",
"type": "uint256"
}
],
"name": "Transfer",
"type": "event"
},
{
"inputs": [
{
"internalType": "address",
"name": "to",
"type": "address"
},
{
"internalType": "uint256",
"name": "tokenId",
"type": "uint256"
}
],
"name": "approve",
"outputs": [],
"stateMutability": "nonpayable",
"type": "function"
},
{
"inputs": [],
"name": "callPeter",
"outputs": [],
"stateMutability": "nonpayable",
"type": "function"
},
{
"inputs": [
{
"internalType": "address",
"name": "to",
"type": "address"
},
{
"internalType": "string",
"name": "tokenURI",
"type": "string"
},
{
"internalType": "uint256",
"name": "id",
"type": "uint256"
}
],
"name": "mintNFT",
"outputs": [
{
"internalType": "uint256",
"name": "",
"type": "uint256"
}
],
"stateMutability": "nonpayable",
"type": "function"
},
{
"inputs": [
{
"internalType": "address",
"name": "from",
"type": "address"
},
{
"internalType": "address",
"name": "to",
"type": "address"
},
{
"internalType": "uint256",
"name": "tokenId",
"type": "uint256"
}
],
"name": "safeTransferFrom",
"outputs": [],
"stateMutability": "nonpayable",
"type": "function"
},
{
"inputs": [
{
"internalType": "address",
"name": "from",
"type": "address"
},
{
"internalType": "address",
"name": "to",
"type": "address"
},
{
"internalType": "uint256",
"name": "tokenId",
"type": "uint256"
},
{
"internalType": "bytes",
"name": "_data",
"type": "bytes"
}
],
"name": "safeTransferFrom",
"outputs": [],
"stateMutability": "nonpayable",
"type": "function"
},
{
"inputs": [
{
"internalType": "address",
"name": "operator",
"type": "address"
},
{
"internalType": "bool",
"name": "approved",
"type": "bool"
}
],
"name": "setApprovalForAll",
"outputs": [],
"stateMutability": "nonpayable",
"type": "function"
},
{
"inputs": [
{
"internalType": "address",
"name": "from",
"type": "address"
},
{
"internalType": "address",
"name": "to",
"type": "address"
},
{
"internalType": "uint256",
"name": "tokenId",
"type": "uint256"
}
],
"name": "transferFrom",
"outputs": [],
"stateMutability": "nonpayable",
"type": "function"
},
{
"inputs": [],
"stateMutability": "nonpayable",
"type": "constructor"
},
{
"inputs": [
{
"internalType": "address",
"name": "owner",
"type": "address"
}
],
"name": "balanceOf",
"outputs": [
{
"internalType": "uint256",
"name": "",
"type": "uint256"
}
],
"stateMutability": "view",
"type": "function"
},
{
"inputs": [
{
"internalType": "uint256",
"name": "tokenId",
"type": "uint256"
}
],
"name": "getApproved",
"outputs": [
{
"internalType": "address",
"name": "",
"type": "address"
}
],
"stateMutability": "view",
"type": "function"
},
{
"inputs": [
{
"internalType": "address",
"name": "owner",
"type": "address"
},
{
"internalType": "address",
"name": "operator",
"type": "address"
}
],
"name": "isApprovedForAll",
"outputs": [
{
"internalType": "bool",
"name": "",
"type": "bool"
}
],
"stateMutability": "view",
"type": "function"
},
{
"inputs": [],
"name": "name",
"outputs": [
{
"internalType": "string",
"name": "",
"type": "string"
}
],
"stateMutability": "view",
"type": "function"
},
{
"inputs": [
{
"internalType": "uint256",
"name": "tokenId",
"type": "uint256"
}
],
"name": "ownerOf",
"outputs": [
{
"internalType": "address",
"name": "",
"type": "address"
}
],
"stateMutability": "view",
"type": "function"
},
{
"inputs": [
{
"internalType": "bytes4",
"name": "interfaceId",
"type": "bytes4"
}
],
"name": "supportsInterface",
"outputs": [
{
"internalType": "bool",
"name": "",
"type": "bool"
}
],
"stateMutability": "view",
"type": "function"
},
{
"inputs": [],
"name": "symbol",
"outputs": [
{
"internalType": "string",
"name": "",
"type": "string"
}
],
"stateMutability": "view",
"type": "function"
},
{
"inputs": [
{
"internalType": "uint256",
"name": "tokenId",
"type": "uint256"
}
],
"name": "tokenURI",
"outputs": [
{
"internalType": "string",
"name": "",
"type": "string"
}
],
"stateMutability": "view",
"type": "function"
}
]'''

    w3 = Web3(Web3.HTTPProvider(node))
    nft_contract = w3.eth.contract(abi=abi, address=nft_address)

    if not w3.isConnected():
        raise Exception('failed to connect to node: {}'.format(node))

    transfer_filter = nft_contract.events.Transfer.createFilter(fromBlock='latest')

    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(
            asyncio.gather(
                log_loop(transfer_filter, 'transfer', handle_transfer_event, 2),
            )
        )
    finally:
        loop.close()

if __name__ == '__main__':
    main()
```

If you just run this, it will fail each time. 

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by clanstyles** [comment]
Bug on our end. Sorry
