### ISSUE TITLE
Can't send a raw transaction: missing 4 required positional arguments: 'hash', 'r', 's', and 'v'

### ISSUE THREAD

**Issue by Nov1X** [ethereum/web3.py#2026]
Python: 3.9
OS: osx

pip freeze:
```
attrs==21.2.0\n
base58==2.1.0
bitarray==1.2.2
certifi==2021.5.30
chardet==4.0.0
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.4
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.1
idna==2.10
ipfshttpclient==0.7.0a1
jsonschema==3.2.0
lru-dict==1.1.7
multiaddr==0.0.9
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.17.3
pycryptodome==3.10.1
pyrsistent==0.17.3
requests==2.25.1
rlp==2.0.1
six==1.16.0
toolz==0.11.1
urllib3==1.26.5
varint==1.0.2
web3==5.19.0
websockets==8.1
```

I am trying to send raw transaction using infura node. There is a code:
```
t = w3.eth.account.sign_transaction(tr := contract.functions.edit("test").buildTransaction(
    {
        "nonce": w3.eth.get_transaction_count(w3.eth.default_account)
    }
), pkey)
```
And this error happening when im trying to run code above:
```
Traceback (most recent call last):
  File "***/main.py", line 64, in <module>
    w3.eth.send_raw_transaction(t)
  File "***/venv/lib/python3.9/site-packages/web3/module.py", line 53, in caller
    (method_str, params), response_formatters = method.process_params(module, *args, **kwargs)  # noqa: E501
  File "***/venv/lib/python3.9/site-packages/web3/method.py", line 194, in process_params
    _apply_request_formatters(params, self.request_formatters(method)))
  File "***/venv/lib/python3.9/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "***/venv/lib/python3.9/site-packages/web3/method.py", line 50, in _apply_request_formatters
    formatted_params = pipe(params, request_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "***/venv/lib/python3.9/site-packages/web3/_utils/abi.py", line 799, in map_abi_data
    return pipe(data, *pipeline)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "***/venv/lib/python3.9/site-packages/web3/_utils/abi.py", line 833, in data_tree_map
    return recursive_map(map_to_typed_data, data_tree)
  File "***/venv/lib/python3.9/site-packages/web3/_utils/decorators.py", line 30, in wrapped
    wrapped_val = to_wrap(*args)
  File "***/venv/lib/python3.9/site-packages/web3/_utils/formatters.py", line 89, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "***/venv/lib/python3.9/site-packages/web3/_utils/formatters.py", line 76, in map_collection
    return datatype(map(func, collection))
  File "***/venv/lib/python3.9/site-packages/web3/_utils/formatters.py", line 88, in recurse
    return recursive_map(func, item)
  File "***/venv/lib/python3.9/site-packages/web3/_utils/decorators.py", line 30, in wrapped
    wrapped_val = to_wrap(*args)
  File "***/venv/lib/python3.9/site-packages/web3/_utils/formatters.py", line 89, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "***/venv/lib/python3.9/site-packages/web3/_utils/formatters.py", line 76, in map_collection
    return datatype(map(func, collection))
  File "***/venv/lib/python3.9/site-packages/web3/_utils/abi.py", line 855, in __new__
    return super().__new__(cls, *iterable)
  File "***/venv/lib/python3.9/site-packages/web3/_utils/formatters.py", line 88, in recurse
    return recursive_map(func, item)
  File "***/venv/lib/python3.9/site-packages/web3/_utils/decorators.py", line 30, in wrapped
    wrapped_val = to_wrap(*args)
  File "***/venv/lib/python3.9/site-packages/web3/_utils/formatters.py", line 89, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "***/venv/lib/python3.9/site-packages/web3/_utils/formatters.py", line 76, in map_collection
    return datatype(map(func, collection))
TypeError: <lambda>() missing 4 required positional arguments: 'hash', 'r', 's', and 'v'
```

I dont't know what to do and how fix that. I am doing everything only after reading docs, and all code above is written only using docs. Help me.

**Comment by Nov1X** [comment]
Okay, fixed with t.rawTransaction().
