### ISSUE TITLE
The method eth_signTypedData does not exist/is not available

### ISSUE THREAD

**Issue by CongZhengithub** [ethereum/web3.py#2097]
Warning: Failed to derive default API key credentials: {'code': -32601, 'message': 'The method eth_signTypedData does not exist/is not available'}
Traceback (most recent call last):
  File "/Users/zhengcong/Documents/hkust/financial math/gitlab_py/apps/DataPlatform/MarketDataService/DYDX/dydxDataWss.py", line 25, in <module>
    onboarding_response = client.onboarding.create_user(
  File "/usr/local/lib/python3.9/site-packages/dydx3/modules/onboarding.py", line 98, in create_user
    return self._post(
  File "/usr/local/lib/python3.9/site-packages/dydx3/modules/onboarding.py", line 39, in _post
    signature = self.signer.sign(
  File "/usr/local/lib/python3.9/site-packages/dydx3/eth_signing/sign_off_chain_action.py", line 38, in sign
    typed_signature = self.signer.sign(
  File "/usr/local/lib/python3.9/site-packages/dydx3/eth_signing/signers.py", line 51, in sign
    raw_signature = self.web3.eth.signTypedData(
  File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 168, in formatted_response
    raise ValueError(response["error"])

When I run the code https://github.com/dydxprotocol/dydx-v3-python/blob/master/examples/onboard.py. I want to create the stack key.

**Comment by kclowes** [comment]
It looks like the node you're using doesn't have `eth_signTypedData` available. What kind of node are you connected to?

**Comment by CongZhengithub** [comment]
I am using infura node. Do I have any other choise? @kclowes  Thank you.

**Comment by kclowes** [comment]
> Do I have any other choise?

You have lots of choices :) Here are some [docs](https://web3py.readthedocs.io/en/stable/node.html) on choosing a node. 

After some digging, it looks like infura doesn't support eth_signTypedData even though their docs say they do. See this question: https://community.infura.io/t/eth-signtypeddata-is-currently-working/2626/3. From the dydx docs [here](https://community.infura.io/t/eth-signtypeddata-is-currently-working/2626/3), it looks like you can access some methods without a stark key, so you might start there. It looks like you can also generate your stark key on your own.  

I'm going to close since this isn't a problem with web3py, but hopefully that provides some direction.

**Comment by liavkoren** [comment]
@kclowes thank you for providing support for dydx's project !! This looks very helpful.

**Comment by spicyspyigo** [comment]
I am using local node working with Geth.
I got same error. 
`The method eth_signTypedData does not exist/is not available`

How can I resolve this?

**Comment by kclowes** [comment]
Last I checked, Geth doesn't support `eth_signTypedData`. You'll have to use another client.

**Comment by spicyspyigo** [comment]
@kclowes I see.
Thank you for your response!

**Comment by spicyspyigo** [comment]
@kclowes 
Do you have any clients you would recommend?
