### ISSUE TITLE
Issue using AsyncHTTPProvider

### ISSUE THREAD

**Issue by ramgos** [ethereum/web3.py#2121]
* Version: 5.23.0
* Python: 3.7.9
* OS: win
* `pip freeze` output

```
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==21.2.0
base58==2.1.0
bitarray==1.2.2
certifi==2021.5.30
chardet==4.0.0
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.5
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.1
idna==2.10
importlib-metadata==4.6.1
ipfshttpclient==0.7.0
jsonschema==3.2.0
lru-dict==1.1.7
multiaddr==0.0.9
multidict==5.1.0
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.17.3
psutil==5.8.0
pycryptodome==3.10.1
pyrsistent==0.18.0
pywin32==301
requests==2.25.1
rlp==2.0.1
six==1.16.0
toolz==0.11.1
typing-extensions==3.10.0.0
urllib3==1.26.6
varint==1.0.2
web3==5.23.0
websockets==9.1
yarl==1.6.3
zipp==3.5.0
```

I used Ganache CLI v6.12.2 (ganache-core: 2.13.2) for the local ethereum provider
Instantiation: `ganache-cli`

### What was wrong?

I was trying to make a simple program to print the coinbase:
```
import asyncio
from web3 import Web3

async def main():
    w3 = Web3(Web3.AsyncHTTPProvider("http://127.0.0.1:8545"))
    coinbase = await w3.eth.coinbase
    print(coinbase)

if __name__ == "__main__":
    asyncio.run(main())
```
When I run the code, I get the following error:
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "test.py", line 7, in main
    coinbase = await w3.eth.coinbase
  File "D:\Name\Ethereum\FirstProject\env\lib\site-packages\web3\eth.py", line 282, in coinbase
    return self.get_coinbase()
  File "D:\Name\Ethereum\ArbitrageMax\env\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "D:\Name\Ethereum\FirstProject\env\lib\site-packages\web3\manager.py", line 154, in request_blocking
    response = self._make_request(method, params)
  File "D:\Name\Ethereum\FirstProject\env\lib\site-packages\web3\manager.py", line 133, in _make_request
    return request_func(method, params)
TypeError: 'coroutine' object is not callable
sys:1: RuntimeWarning: coroutine 'AsyncBaseProvider.request_func' was never awaited
```
It seems despite using an async http provider, the manager still uses 'request_blocking'.
looking at tests added by merge requests regarding async issues led me to believe this is the correct syntax to call, I'll list one example: [issue #2056 - Async eth.get_balance, eth.get_code, eth.get_transaction_count](https://github.com/ethereum/web3.py/pull/2056/files)

```
# snippet from #2056's tests

class AsyncEthModuleTest:    
    #... other tests

    # test of get balance which involves awaiting coinbase
    @pytest.mark.asyncio
    async def test_eth_get_balance(self, async_w3: "Web3") -> None:
        coinbase = await async_w3.eth.coinbase  # type: ignore

        with pytest.raises(InvalidAddress):
            await async_w3.eth.get_balance(  # type: ignore
                ChecksumAddress(HexAddress(HexStr(coinbase.lower())))
            )

        balance = await async_w3.eth.get_balance(coinbase)  # type: ignore

        assert is_integer(balance)
        assert balance >= 0
```
I made sure the provider of the web3 object is actually an async provider by running the following code:
```
import asyncio
from web3 import Web3

async def main():
    w3 = Web3(Web3.AsyncHTTPProvider("http://127.0.0.1:8545"))
    print(type(w3.provider))
    # coinbase = await w3.eth.coinbase
    # print(coinbase)

if __name__ == "__main__":
    asyncio.run(main())
```
output:
```
<class 'web3.providers.async_rpc.AsyncHTTPProvider'>
```

**Comment by abo-take** [comment]
@kclowes, is it still in progress?
Should I use this:
w3 = Web3(Web3.AsyncHTTPProvider("http://127.0.0.1:8545"), modules={'eth': (AsyncEth,)}, middlewares=[]) 

Or this version mentioned in docs currently: w3 = AsyncWeb3(AsyncHTTPProvider(endpoint_uri))
