### ISSUE TITLE
web3.eth.get_block()

### ISSUE THREAD

**Issue by emrahsariboz** [ethereum/web3.py#2125]
* Version:5.23.1
* Python: 3.8.10
* OS: linux
* `pip freeze` output

### What was wrong?

I get the following error when I the following command

* The code which produced the error
`w3.eth.get_block(71)`
* The full output of the error

```
Traceback (most recent call last):
  File "get-status.py", line 24, in <module>
    print(w3.eth.get_block(1))
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/eth.py", line 561, in get_block
    return self._get_block(block_identifier, full_transactions)
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 83, in apply_formatters
    formatter(response["result"]),
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/emrsrb/.local/lib/python3.8/site-packages/eth_utils/applicators.py", line 72, in apply_formatter_if
    return formatter(value)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/emrsrb/.local/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/emrsrb/.local/lib/python3.8/site-packages/eth_utils/applicators.py", line 84, in apply_formatters_to_dict
    yield key, formatters[key](item)
  File "/home/emrsrb/.local/lib/python3.8/site-packages/web3/middleware/validation.py", line 71, in check_extradata_length
    raise ExtraDataLengthError(
web3.exceptions.ExtraDataLengthError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer to http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details. The full extraData is: HexBytes('0xd883010a09846765746888676f312e31362e37856c696e757800000000000000d383309cd18bc6ae34e3f02bb1de1727be8bef3460fa2886c98dc7cd1dcfe58a1cda7b851e274a114fb0218471f782043445ec98b8bcff002327c46060a50c5101')
```

* What type of node you were connecting to.

I am connecting local geth node through IPC. 

### How can it be fixed?

I am not sure how it can be fixed.

**Comment by emrahsariboz** [comment]
By the way, same error occurs even when I call `w3.eth.get_block('recent')`

**Comment by kclowes** [comment]
It looks like you're attached to a PoA chain. If so, the relevant part of the error message is here: 
`Refer to http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details`

> By the way, same error occurs even when I call w3.eth.get_block('recent')

Yeah, I would still expect the same error to be thrown if you don't have the middleware installed. Another thing to note is that `recent` isn't a valid block identifier. You'll want to use `latest` instead. 

If the middleware doesn't fix the issue, feel free to reopen.
