### ISSUE TITLE
string encoding of contract call

### ISSUE THREAD

**Issue by benjiqq** [ethereum/web3.py#2141]
* Version: 5.23.1
* Python: 3.9.6
* OS: osx

eth-abi==0.5.0
eth-account==0.5.4
eth-ape==0.1.0a22
eth-bloom==1.0.4
eth-brownie==1.15.2
eth-event==1.2.3
eth-hash==0.3.1
eth-keyfile==0.5.1
eth-keys==0.1.0b4
eth-rlp==0.2.1
eth-tester==0.1.0b11
eth-typing==2.2.2
eth-utils==0.7.4

freeze https://gist.github.com/benjyz/4e003f5cc310025abf19eec6c0b56d4a

### What was wrong?

```ctr.functions.someString().call()```

gives this error

`TypeError: decoding with 'utf8' codec failed (TypeError: a bytes-like object is required, not 'str')`

**Comment by kclowes** [comment]
@benjyz you're saying the error occurs when it's trying to decode the return value of the function?

**Comment by benjyz** [comment]
i call a contract and it fails. was working fine before, no idea where this comes from. it goes back to web3/_utils/normalizers.py

```
Traceback (most recent call last):
  File "/Users/user/foo/checks.py", line 104, in <module>
    bucket_info(some_contract, vega_token, log)
  File "/Users/user/foo/checks.py", line 53, in bucket_info
    log.info("-- name %s --" % some_contract.functions.name().call())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/contract.py", line 1536, in call_contract_function
    normalized_data = map_abi_data(_normalizers, output_types, output_data)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/abi.py", line 799, in map_abi_data
    return pipe(data, *pipeline)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/abi.py", line 833, in data_tree_map
    return recursive_map(map_to_typed_data, data_tree)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/decorators.py", line 30, in wrapped
    wrapped_val = to_wrap(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/formatters.py", line 89, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/formatters.py", line 76, in map_collection
    return datatype(map(func, collection))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/formatters.py", line 88, in recurse
    return recursive_map(func, item)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/decorators.py", line 30, in wrapped
    wrapped_val = to_wrap(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/formatters.py", line 90, in recursive_map
    return func(items_mapped)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/abi.py", line 830, in map_to_typed_data
    return ABITypedData(func(*elements))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/normalizers.py", line 78, in wrapper
    modified = to_wrap(type_str, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/web3-5.23.1-py3.9.egg/web3/_utils/normalizers.py", line 101, in decode_abi_strings
    return type_str, codecs.decode(data, 'utf8', 'backslashreplace')
TypeError: decoding with 'utf8' codec failed (TypeError: a bytes-like object is required, not 'str')
```

**Comment by benjyz** [comment]
If I replace 

`# return type_str, codecs.decode(data, 'utf8', 'backslashreplace')`

with this if works fine

`return type_str, data`

**Comment by kclowes** [comment]
Closing, stale
