### ISSUE TITLE
It is esoteric to get to use things from `web3.utils.events` as importing it fails..

### ISSUE THREAD

**Issue by tenuki** [ethereum/web3.py#2160]
* Version: 5.24.0
* Python: 3.7
* OS: linux
* `pip freeze` output

```
aiofiles==0.4.0
aiohttp==3.7.4.post0
asn1crypto==0.24.0
async-timeout==3.0.1
attrdict==2.0.1
attrs==19.3.0
base58==2.0.0
bitarray==1.2.2
bitcoin==1.1.42
boto3==1.16.28
botocore==1.19.63
certifi==2019.11.28
cffi==1.12.2
chardet==3.0.4
Click==7.0
coincurve==11.0.0
colorama==0.4.4
commonmark==0.9.1
cytoolz==0.10.1
eth-abi==2.1.0
eth-account==0.5.6
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-typing==2.2.1
eth-utils==1.10.0
fastapi==0.48.0
future==0.17.1
h11==0.9.0
hexbytes==0.2.0
httptools==0.0.13
idna==2.8
idna-ssl==1.1.0
importlib-metadata==1.5.0
iniconfig==1.1.1
ipfshttpclient==0.8.0a2
jmespath==0.10.0
jsonschema==3.2.0
lru-dict==1.1.6
moneyonchain==0.0.53
multiaddr==0.0.9
multidict==4.7.4
mypy-extensions==0.4.1
netaddr==0.7.19
nose==1.3.7
packaging==21.0
parsimonious==0.8.1
pbkdf2==1.3
peewee==3.13.1
pluggy==1.0.0
protobuf==3.11.3
py==1.10.0
pycparser==2.19
pycryptodome==3.9.6
pydantic==1.4
pyethash==0.1.27
Pygments==2.9.0
pymongo==3.11.4
pyparsing==2.4.7
pyrsistent==0.15.7
pysha3==1.0.2
pytest==6.2.5
python-dateutil==2.8.2
pytz==2019.3
PyYAML==5.1
qrcode==6.1
repoze.lru==0.7
requests==2.22.0
requirements==0.1
rich==9.2.0
rlp==1.2.0
s3transfer==0.3.7
sanic==18.12.0
scrypt==0.8.13
six==1.14.0
starlette==0.12.9
timeloop==1.0.2
toml==0.10.2
toolz==0.10.0
typing-extensions==3.7.4.1
ujson==1.35
urllib3==1.25.8
uvicorn==0.11.2
uvloop==0.14.0
varint==1.0.2
virtualenv==16.7.8
web3==5.24.0
websockets==9.1
yarl==1.4.2
zipp==2.2.0
```

### What was wrong?

Please include any of the following that are applicable:

#### code which produced the error

```python
from web3 import Web3
import json
from pprint import pprint
import web3.utils.events
```

#### The full output of the error

```
/home/user/local/bin/python3.7 /home/user/pycharm-2020.3.3/plugins/python/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 45935 --file /home/user/.config/JetBrains/PyCharm2021.2/scratches/scratch_26.py
Connected to pydev debugger (build 212.5284.44)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/local/lib/python3.7/site-packages/web3/utils/events.py", line 8, in <module>
    from eth_abi.abi import (
ImportError: cannot import name 'process_type' from 'eth_abi.abi' (/home/aweil/.local/lib/python3.7/site-packages/eth_abi/abi.py)

Process finished with exit code 1
```

# What type of node you were connecting to.

No node is involved.

#### Fill this section in if you know how this could or should be fixed.

```python
import datetime
import time
import logging
from abc import ABC, abstractmethod
from typing import Tuple, Optional, Callable, List, Iterable

from web3 import Web3
from web3.contract import Contract
from web3.datastructures import AttributeDict
from web3.exceptions import BlockNotFound
from eth_abi.codec import ABICodec

# Currently this method is not exposed over official web3 API,
# but we need it to construct eth_getLogs parameters
from web3._utils.filters import construct_event_filter_params
from web3._utils.events import get_event_data
```

**Comment by tenuki** [comment]
And.. after all, I mean, when you finally get your code "working" using the whole bunch of imports from above, what you get?

```python
Traceback (most recent call last):
  File "/home/user/pycharm-2020.3.3/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/pycharm-2020.3.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/user/.config/JetBrains/PyCharm2021.2/scratches/scratch_26.py", line 51, in <module>
    evt = getevdata(x)
  File "/home/user/.config/JetBrains/PyCharm2021.2/scratches/scratch_26.py", line 40, in getevdata
    return utils.events.get_event_data(w3.codec, abi, ev)
AttributeError: module 'web3.utils' has no attribute 'events'
```

**Comment by dbfreem** [comment]
What version are you using?

I tried the imports you have in your second code snippet and it seems to work. When trying your imports from the first code snippet I noticed the _ was missing when accessing the events module

was `web3.utils.events`
should be `web3._utils.events`

**Comment by fselmo** [comment]
I'm with @dbfreem here. Check your module path and give it another shot. This is not reproducible so I'm going to close it. If you feel like this is a bug and should be re-opened, please feel free to open it back up. Best of luck.

**Comment by tenuki** [comment]
I'm sorry for the late answer and providing not much more info. I understand and thank you the time you spent. I'll re check and if it still fails I'll re open, but maybe I was doing something wrong. Thanks again!!
