### ISSUE TITLE
Cannot attach to the ganache test network, 502 bad gateway error

### ISSUE THREAD

**Issue by miRemid** [ethereum/web3.py#2162]
* Version: 5.24.0
* Python: 3.9.5
* OS: linux
* `pip freeze` output

```
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==21.2.0
autopep8==1.5.7
base58==2.1.0
bitarray==1.2.2
certifi==2021.5.30
chardet==4.0.0
charset-normalizer==2.0.6
cytoolz==0.11.0
eth-abi==2.1.1
eth-account==0.5.6
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
hexbytes==0.2.2
idna==3.2
ipfshttpclient==0.8.0a2
jsonschema==3.2.0
lru-dict==1.1.7
multiaddr==0.0.9
multidict==5.1.0
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.18.0
py-solc-x==1.1.0
pycodestyle==2.7.0
pycryptodome==3.10.4
pyrsistent==0.18.0
requests==2.26.0
rlp==2.0.1
semantic-version==2.8.5
six==1.16.0
toml==0.10.2
toolz==0.11.1
typing-extensions==3.10.0.2
urllib3==1.26.7
varint==1.0.2
web3==5.24.0
websockets==9.1
yarl==1.6.3
```

### What was wrong?
cannot attach to the ganache-cli test network, 502 bad gateway error

Please include any of the following that are applicable:

* The code which produced the error
```python
from web3 import Web3
w3 = Web3(Web3.HTTPProvide("http://127.0.0.1:8545"))
address = "ganache account address"
nonce = w3.eth.getTransactionCount(address)
```
* The full output of the error
```shell
Traceback (most recent call last):
  File "/home/kamir/Documents/web3py/simple_storage/deploy.py", line 51, in <module>
    nonce = w3.eth.getTransactionCount(address)
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/providers/rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/web3/_utils/request.py", line 49, in make_post_request
    response.raise_for_status()
  File "/home/kamir/miniconda3/envs/web3/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://127.0.0.1:8545/
```
* What type of node you were connecting to.
Ganache-cli eth test network
> i already test ganache with web3js and geth

**Comment by kclowes** [comment]
Thanks for opening this @miRemid. I just tried this, and I'm not able to reproduce. Maybe try re-starting your `ganache-cli`?

**Comment by miRemid** [comment]
I have tried to restart ganache and setup ganache with docker but got same error.

I can't find a way to solve it, so I reinstalled my os in virtualbox and everything works well :)

**Comment by kclowes** [comment]
Great! Thanks for coming back to report your solution!
