### ISSUE TITLE
get_logs suddenly unable to handle inputs

### ISSUE THREAD

**Issue by tannishmango** [ethereum/web3.py#2165]
* Version: 5.24.0
* Python: 3.7
* OS: osx

Using Quicknode archive node, standard RPC

I have been using the get_logs function for a while, suddenly the inputs are not working for this example, nor many others I have tried. I input fromblock, toblock, address, topics, and did variations here. 

The only time i could get it to wrk was when i removed the blocks.

****CODE****
filter_params = {'fromBlock': 12000000, 'toBlock': 12150000, 'address': "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",'topics':["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]}

events = web3.eth.get_logs(filter_params)

****ERROR****

Traceback (most recent call last):

  File "<ipython-input-60-a683368c6b22>", line 1, in <module>
    events = web3.eth.get_logs(filter_params)

  File "/Users/ASUS/opt/anaconda3/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,

  File "/Users/ASUS/opt/anaconda3/lib/python3.8/site-packages/web3/manager.py", line 186, in request_blocking
    response = self._make_request(method, params)

  File "/Users/ASUS/opt/anaconda3/lib/python3.8/site-packages/web3/manager.py", line 147, in _make_request
    return request_func(method, params)

  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__

  File "/Users/ASUS/opt/anaconda3/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)

  File "/Users/ASUS/opt/anaconda3/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)

  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__

  File "/Users/ASUS/opt/anaconda3/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)

  File "/Users/ASUS/opt/anaconda3/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)

  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__

  File "/Users/ASUS/opt/anaconda3/lib/python3.8/site-packages/web3/middleware/formatting.py", line 83, in apply_formatters
    formatter(response["result"]),

  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__

  File "/Users/ASUS/opt/anaconda3/lib/python3.8/site-packages/eth_utils/applicators.py", line 116, in apply_one_of_formatters
    raise ValueError(

ValueError: The provided value did not satisfy any of the formatter conditions

**Comment by dino-rodriguez** [comment]
@tannishmango Any chance you remember what the issue you ran into here was?
