### ISSUE TITLE
Property adress not found on Contract class

### ISSUE THREAD

**Issue by LucasColas** [ethereum/web3.py#2166]
* Version: 5.24.0
* Python: 3.7.6
* OS: Win 10
* `pip freeze` output

```
absl-py==0.11.0
aiohttp==3.7.4.post0
altair==4.1.0
altgraph==0.17
argon2-cffi==20.1.0
asgiref==3.3.4
astor==0.8.1
astunparse==1.6.3
async-generator==1.10
async-timeout==3.0.1
atari-py==0.2.6
attrs==20.3.0
autobahn==20.12.3
Automat==20.2.0
backcall==0.2.0
base58==2.1.0
beautifulsoup4==4.10.0
bitarray==1.2.2
bleach==3.3.0
blinker==1.4
cached-property==1.5.2
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.4
chardet==3.0.4
click==7.1.2
cloudpickle==1.3.0
colorama==0.4.4
constantly==15.1.0
cryptography==3.3.1
cycler==0.10.0
cytoolz==0.11.0
dataclasses==0.6
dateparser==1.0.0
decorator==5.0.7
defusedxml==0.7.1
Django==3.2.4
entrypoints==0.3
eth-abi==2.1.1
eth-account==0.5.6
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.3
eth-rlp==0.2.1
eth-typing==2.2.2
eth-utils==1.10.0
Flask==1.1.2
flatbuffers==1.12
future==0.18.2
gast==0.3.3
gitdb==4.0.7
GitPython==3.1.15
google-auth==1.19.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.32.0
gym==0.17.2
gym-retro==0.8.0
h5py==2.10.0
hexbytes==0.2.2
hyperlink==20.0.1
idna==2.10
importlib-metadata==1.7.0
incremental==17.5.0
ipfshttpclient==0.8.0a2
ipykernel==5.5.3
ipython==7.22.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
itsdangerous==1.1.0
jedi==0.18.0
Jinja2==2.11.2
joblib==1.0.1
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
lru-dict==1.1.7
lxml==4.6.3
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.3.3
mistune==0.8.4
multiaddr==0.0.9
multidict==5.1.0
multitasking==0.0.9
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
neat-python==0.92
nest-asyncio==1.5.1
netaddr==0.8.0
notebook==6.3.0
numpy==1.19.5
oauthlib==3.1.0
opencv-python==4.4.0.42
opt-einsum==3.3.0
packaging==20.9
pandas==1.0.5
pandocfilters==1.4.3
parsimonious==0.8.1
parso==0.8.2
pefile==2019.4.18
pickleshare==0.7.5
Pillow==7.2.0
prometheus-client==0.10.1
prompt-toolkit==3.0.18
protobuf==3.12.2
pyarrow==3.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pycryptodome==3.10.4
pydeck==0.6.2
pygame==1.9.6
pyglet==1.5.0
Pygments==2.8.1
PyHamcrest==2.0.2
pyinstaller==4.2
pyinstaller-hooks-contrib==2021.1
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-binance==0.7.5
python-dateutil==2.8.1
pytz==2020.1
pywin32==300
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==5.3.1
pyzmq==22.0.3
regex==2020.11.13
requests==2.24.0
requests-oauthlib==1.3.0
rlp==2.0.1
rsa==4.6
scikit-learn==1.0
scipy==1.4.1
Send2Trash==1.5.0
service-identity==18.1.0
six==1.15.0
smmap==4.0.0
soupsieve==2.2.1
sqlparse==0.4.1
streamlit==0.80.0
tb-nightly==2.5.0a20210306
td-ameritrade-python-api==0.3.4
tensorboard==2.4.1
tensorboard-data-server==0.3.0
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-estimator==2.4.0
tensorflow-io==0.17.0
termcolor==1.1.0
terminado==0.9.4
testpath==0.4.4
threadpoolctl==2.2.0
toml==0.10.2
toolz==0.11.1
torch==1.7.0+cpu
torchaudio==0.7.0
torchvision==0.8.1+cpu
tornado==6.1
traitlets==5.0.5
Twisted==20.3.0
txaio==20.12.1
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.25.10
validators==0.18.2
varint==1.0.2
watchdog==2.0.2
wcwidth==0.2.5
web3==5.24.0
webencodings==0.5.1
websocket-client==0.57.0
websockets==9.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
yarl==1.6.3
yfinance==0.1.59
zipp==3.1.0
zope.interface==5.2.0
```

### What was wrong?

Here is the code :
```
from web3 import Web3
import json

Infura_URL = "https://mainnet.infura.io/v3/b456e7661afc4726a2be02f9635d1c60"

web3 = Web3(Web3.HTTPProvider(Infura_URL)) #Create a connection. Handle interactions with a server

#Check if we are connected
print(web3.isConnected())

#See the last block
print(web3.eth.blockNumber)

#Informations we need for a smart contract
abi = json.loads('[{"constant":true,"inputs":[],"name":"mintingFinished","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[],"name":"unpause","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_amount","type":"uint256"}],"name":"mint","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"paused","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[],"name":"finishMinting","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[],"name":"pause","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_amount","type":"uint256"},{"name":"_releaseTime","type":"uint256"}],"name":"mintTimelocked","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"remaining","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"payable":false,"type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Mint","type":"event"},{"anonymous":false,"inputs":[],"name":"MintFinished","type":"event"},{"anonymous":false,"inputs":[],"name":"Pause","type":"event"},{"anonymous":false,"inputs":[],"name":"Unpause","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"}]')
#Json array that describes what the smart contract looks like
adress = "0xd26114cd6EE289AccF82350c8d8487fedB8A0C07" #The Adress of the deployed smart contract on the Blockchain


#Get The Contract
contract = web3.eth.contract(adress=adress, abi=abi)


print(contract)
```

True
13344223
Traceback (most recent call last):
  File "C:\Users\lucas\github\Web3-Test\main.py", line 21, in <module>
    contract = web3.eth.contract(adress=adress, abi=abi)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\eth.py", line 822, in contract
    ContractFactory = ContractFactoryClass.factory(self.web3, **kwargs)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\contract.py", line 365, in factory
    normalizers=normalizers,
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\_utils\datatypes.py", line 51, in __new__
    verify_attr(name, key, all_keys)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\_utils\datatypes.py", line 23, in verify_attr
    "present on the {1} class".format(key, class_name)
AttributeError: Property adress not found on Contract class. `Contract.factory` only accepts keyword arguments which are present on the Contract class

I don't  know on what type of node I was connecting to.

**Comment by LucasColas** [comment]
I found the problem. 

The code should be like this :
```
address = "0xd26114cd6EE289AccF82350c8d8487fedB8A0C07" #The Adress of the deployed smart contract on the Blockchain


#Get The Contract
contract = web3.eth.contract(address=address, abi=abi)
```
address (not adress).
