### ISSUE TITLE
HTTP connection times out

### ISSUE THREAD

**Issue by userpasta** [ethereum/web3.py#217]
* Version: 3.9.0
* Python: 2.7
* OS: linux (ubuntu 16.04)

### What was wrong?
HTTP connection times out during contract method `transact()` execution.
 
* The code which produced the error
```
ReadTimeout: HTTPConnectionPool(host='localhost', port=8545): Read timed out. (read timeout=10)
```
* The full output of the error:
```
 Traceback (most recent call last):
  File "/home/szef/clone/prune/eth.py", line 131, in _real_trade
    int(amount),
  File "/home/szef/.local/lib/python2.7/site-packages/web3/contract.py", line 816, in transact_with_contract_function
    txn_hash = contract.web3.eth.sendTransaction(transact_transaction)
  File "/home/szef/.local/lib/python2.7/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/szef/.local/lib/python2.7/site-packages/web3/eth.py", line 246, in sendTransaction
    [formatters.input_transaction_formatter(self, formatted_transaction)],
  File "/home/szef/.local/lib/python2.7/site-packages/web3/providers/manager.py", line 27, in request_blocking
    response_raw = self.provider.make_request(method, params)
  File "/home/szef/.local/lib/python2.7/site-packages/web3/providers/rpc.py", line 52, in make_request
    **self.get_request_kwargs()
  File "/home/szef/.local/lib/python2.7/site-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/home/szef/.local/lib/python2.7/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/szef/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/szef/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/home/szef/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='localhost', port=8545): Read timed out. (read timeout=10)
```
* What type of node you were connecting to.
Local node

On my virtual machine first transaction was successfull and 2nd, 3rd and so one failed. There was 5-30 minutes difference between transactions (it happend 5 times in the row)
On local machine, sometimes it's failing immediatelly (1st transaction).

### How can it be fixed?
Unlocking account after every transaction seems to help.

**Comment by carver** [comment]
If I remember correctly, this was resolved in chat as needing to unlock the account after every usage (which parity requires). Please reopen if this issue is not addressed.
