### ISSUE TITLE
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff0a4462bb0>: Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by dexertos** [ethereum/web3.py#2195]
Hello. Everytime I try to connect to the host from a virtual machine using Ubuntu 20.04.3 LTS(64-bit) I get the following errors.

Traceback (most recent call last):
  File "urllib3/connection.py", line 174, in _new_conn
  File "urllib3/util/connection.py", line 96, in create_connection
  File "urllib3/util/connection.py", line 86, in create_connection
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 382, in _make_request
  File "urllib3/connectionpool.py", line 1010, in _validate_conn
  File "urllib3/connection.py", line 358, in connect
  File "urllib3/connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff0a4462bb0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=8588): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff0a4462bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "<frozen Frontrun>", line 22713, in <lambda>
  File "<frozen Frontrun>", line 12719, in latency
  File "requests/api.py", line 117, in post
  File "requests/api.py", line 61, in request
  File "requests/sessions.py", line 542, in request
  File "requests/sessions.py", line 655, in send
  File "requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=8588): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff0a4462bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by fselmo** [comment]
@dexertos What exactly are you trying to do here? I'm not sure I understand from the above. Are you still running into issues? Do you have more context?

**Comment by fselmo** [comment]
Closed due to inactivity and lack of context. Feel free to re-open if you have more details and believe this is a bug.
