### ISSUE TITLE
Error while trying contract.deploy() function

### ISSUE THREAD

**Issue by lakraj** [ethereum/web3.py#220]
* Python: 2.7/
* OS: Ubuntu 16.04

### What was wrong?
I am trying to deploy an instance of a sample contract I have in testrpc.
I have read in the abi and bytecodes of the sample contract into my .py file.
contract
```
pragma solidity ^0.4.11;

// This is a simple contract with a set and a get method

contract SampleContract {
  //Agent structure
  struct Agent {
    uint class;
  }
  //address owner;

  //Mapping each address to an agent
  mapping (address => Agent) agents;

  //No need of a constructor here I guess
  /*function SampleContract() {
    owner = msg.sender;
  }*/

  function set(uint _prediction) {
    agents[msg.sender].class = _prediction;
  }

  function get() constant returns (uint) {
    return agents[msg.sender].class;
  }
}
```

bytecode:
```
6060604052341561000f57600080fd5b5b6101558061001f6000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b1146100495780636d4ce63c1461006c575b600080fd5b341561005457600080fd5b61006a6004808035906020019091905050610095565b005b341561007757600080fd5b61007f6100df565b6040518082815260200191505060405180910390f35b806000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600001819055505b50565b60008060003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206000015490505b905600a165627a7a723058200ea7dbf36a18b368461448f4ca4942152b7986b12547a6cdcabd217330c5fbd30029
```

Please include any of the following that are applicable:

* The code which produced the error
```
betContract = web3.eth.contract(abi, bytecode=bytecode)
betContract.deploy(transaction={"from":web3.eth.accounts[0]}, )
```
* The full output of the error
```
Traceback (most recent call last):
  File "deployContract.py", line 154, in <module>
    main()
  File "deployContract.py", line 100, in main
    betContract.deploy(transaction={"from":web3.eth.accounts[0]}, )
  File "/usr/local/lib/python2.7/dist-packages/web3/contract.py", line 310, in deploy
    txn_hash = cls.web3.eth.sendTransaction(deploy_transaction)
  File "/usr/local/lib/python2.7/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/web3/eth.py", line 242, in sendTransaction
    transaction=formatted_transaction,
  File "/usr/local/lib/python2.7/dist-packages/web3/utils/transactions.py", line 28, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/usr/local/lib/python2.7/dist-packages/web3/utils/functional.py", line 14, in inner
    value = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/web3/eth.py", line 282, in estimateGas
    [formatted_transaction],
  File "/usr/local/lib/python2.7/dist-packages/web3/providers/manager.py", line 35, in request_blocking
    raise ValueError(response["error"])
ValueError: {u'message': u'Error: VM Exception while executing eth_estimateGas: out of gas\n 
at /.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:117:17\n    at /.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:59:5\n at /.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:3838:9\n    at /.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:421:16\n at replenish (/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:941:25)\n    at iterateeCallback (/.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:931:17)\n at /.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:906:16\n    at /.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/node_modules/async/dist/async.js:3835:13\n at /.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:55:9\n    at /.nvm/versions/node/v6.9.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/cache.js:107:7', u'code': -32000}
```

* What type of node you were connecting to.
testrpc --account="0x7c426a7b339c19f003ad3df1fde9404407d3c29d
c6efda6e6597c7964d16e85d,100000000000000 -u 0
version 3.0.5

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by sivachaitanya** [comment]
Did you try 
betContract = web3.eth.contract(abi=abi, bytecode=bytecode)
betContract.deploy(transaction={"from":web3.eth.accounts[0],"gas" : 3000000} )

**Comment by carver** [comment]
Please reopen if setting the gas limit higher did not resolve the issue for you.
