### ISSUE TITLE
Issue when try use AsyncHTTPProvider with geth_poa_middleware middleware

### ISSUE THREAD

**Issue by Andrei-Dolgolev** [ethereum/web3.py#2210]
### What was wrong?

Can't use middleware with asyncHttpProvider

it's return exception

```
Traceback (most recent call last):
  File "/crawler/import asyncio.py", line 30, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/crawler/import asyncio.py", line 24, in main
    coinbase = await w3.eth.get_block_number()
  File "/lib/python3.8/site-packages/web3/module.py", line 72, in caller
    result = await w3.manager.coro_request(method_str,
  File "/lib/python3.8/site-packages/web3/manager.py", line 202, in coro_request
    response = await self._coro_make_request(method, params)
  File "/lib/python3.8/site-packages/web3/manager.py", line 153, in _coro_make_request
    request_func = await self.provider.request_func(  # type: ignore
  File "y/lib/python3.8/site-packages/web3/providers/async_base.py", line 64, in request_func
    await self._generate_request_func(web3, all_middlewares)
  File "/lib/python3.8/site-packages/web3/providers/async_base.py", line 71, in _generate_request_func
    return await async_combine_middlewares(
  File "/lib/python3.8/site-packages/web3/middleware/__init__.py", line 106, in async_combine_middlewares
    accumulator_fn = await construct_middleware(middleware, accumulator_fn, web3)
  File "/lib/python3.8/site-packages/web3/middleware/__init__.py", line 115, in construct_middleware
    return await middleware(fn, w3)
TypeError: object cytoolz.functoolz.curry can't be used in 'await' expression
```
code for reproduce error.

```
import asyncio
from web3 import Web3
from web3.eth import AsyncEth
from web3.middleware import geth_poa_middleware

async def main():
    w3 = Web3(
        Web3.AsyncHTTPProvider(
            "http://127.0.0.1:8545"
        ),
        modules={"eth": (AsyncEth,)},
        middlewares=[geth_poa_middleware],
    )
    # w3.middleware_onion.inject(geth_poa_middleware, layer=0)

    block = await w3.eth.get_block_number()

    print(block)


if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by safor** [comment]
Please check potential solution at https://github.com/ethereum/web3.py/issues/2232#issuecomment-1158965622
