### ISSUE TITLE
web3.middleware.geth_poa_middleware doesn't work with asyncio

### ISSUE THREAD

**Issue by mzaprudin** [ethereum/web3.py#2232]
* Version: 5.25.0
* Python: 3.9.7
* OS: linux

### What was wrong?
I'm trying to get the lates block information from Binance Smart Chain node

```
import web3
import os
import asyncio

NODE_HTTP_ADDRESS_BSC = os.getenv('NODE_BSC_HTTP_ADDRESS')
NODE_HTTP_ADDRESS_ETH = os.getenv('NODE_ETH_HTTP_ADDRESS')

NODE_HTTP_ADDRESS = NODE_HTTP_ADDRESS_BSC

PAUSE_PERIOD = 0.2

async def get_block(w3: web3.Web3):
    block = await w3.eth.get_block('pending', full_transactions=True)
    return block

async def main():
    w3 = web3.Web3(
        web3.AsyncHTTPProvider(NODE_HTTP_ADDRESS),
        modules={ 'eth': (web3.eth.AsyncEth,), 'net': (web3.net.AsyncNet,)},
        middlewares=[]
        )
    # disable below for ETH node
    w3.middleware_onion.inject(web3.middleware.geth_poa_middleware, layer=0)

    tasks = []
    number = 0
    while True:
        tasks.append(asyncio.create_task(get_block(w3)))
        done = [t for t in tasks if t.done()]
        tasks = [t for t in tasks if not t.done()]

        for d in done:
            block = d.result()
            if block['number'] != number:
                print('')
                number = block['number']
                print(f'----- New block number: {number}')
            print(len(block['transactions']), end=' ')

        await asyncio.sleep(PAUSE_PERIOD)

if __name__ == '__main__':
    try:
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main())
    except KeyboardInterrupt:
        print('\nDone')
```

it works with ETH node as expected, but for BSC node I have to add
```
w3.middleware_onion.inject(web3.middleware.geth_poa_middleware, layer=0)
```
and after that I get the next error
```
Traceback (most recent call last):
  File "/home/m/dev/projects/xeon/bscscan/tx_count.py", line 46, in <module>
    loop.run_until_complete(main())
  File "/home/m/miniconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/m/dev/projects/xeon/bscscan/tx_count.py", line 34, in main
    block = d.result()
  File "/home/m/dev/projects/xeon/bscscan/tx_count.py", line 14, in get_block
    block = await w3.eth.get_block('pending', full_transactions=True)
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/eth.py", line 326, in get_block
    return await self._get_block(block_identifier, full_transactions)  # type: ignore
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/module.py", line 72, in caller
    result = await w3.manager.coro_request(method_str,
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/manager.py", line 213, in coro_request
    response = await self._coro_make_request(method, params)
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/manager.py", line 156, in _coro_make_request
    request_func = await self.provider.request_func(  # type: ignore
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/providers/async_base.py", line 64, in request_func
    await self._generate_request_func(web3, all_middlewares)
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/providers/async_base.py", line 71, in _generate_request_func
    return await async_combine_middlewares(
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/middleware/__init__.py", line 106, in async_combine_middlewares
    accumulator_fn = await construct_middleware(middleware, accumulator_fn, web3)
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/middleware/__init__.py", line 115, in construct_middleware
    return await middleware(fn, w3)
TypeError: object cytoolz.functoolz.curry can't be used in 'await' expression
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<get_block() done, defined at /home/m/dev/projects/xeon/bscscan/tx_count.py:13> exception=TypeError("object cytoolz.functoolz.curry can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/m/dev/projects/xeon/bscscan/tx_count.py", line 14, in get_block
    block = await w3.eth.get_block('pending', full_transactions=True)
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/eth.py", line 326, in get_block
    return await self._get_block(block_identifier, full_transactions)  # type: ignore
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/module.py", line 72, in caller
    result = await w3.manager.coro_request(method_str,
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/manager.py", line 213, in coro_request
    response = await self._coro_make_request(method, params)
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/manager.py", line 156, in _coro_make_request
    request_func = await self.provider.request_func(  # type: ignore
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/providers/async_base.py", line 64, in request_func
    await self._generate_request_func(web3, all_middlewares)
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/providers/async_base.py", line 71, in _generate_request_func
    return await async_combine_middlewares(
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/middleware/__init__.py", line 106, in async_combine_middlewares
    accumulator_fn = await construct_middleware(middleware, accumulator_fn, web3)
  File "/home/m/miniconda3/lib/python3.9/site-packages/web3/middleware/__init__.py", line 115, in construct_middleware
    return await middleware(fn, w3)
TypeError: object cytoolz.functoolz.curry can't be used in 'await' expression
```

**Comment by feedss** [comment]
Yes
I got the same exception.
How to fix it?

**Comment by kclowes** [comment]
The async provider is a work in progress, and this is definitely on the list to get done. Here is the list of currently supported methods and middlewares: https://web3py.readthedocs.io/en/stable/providers.html#supported-methods

**Comment by yuanhongda** [comment]
@kclowes   Would you please fix it?

**Comment by yuanhongda** [comment]
@kclowes  Is the problem fixed？

**Comment by yuanhongda** [comment]
@mzaprudin  Dear, do you have a solution? I also have this problem。

**Comment by yuanhongda** [comment]
Traceback (most recent call last):
  File "/Users/yuanhongda/CODE/mev-inspect-py/cli.py", line 221, in <module>
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/yuanhongda/CODE/mev-inspect-py/mev_inspect/concurrency.py", line 18, in wrapper
    loop.run_until_complete(f(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/yuanhongda/CODE/mev-inspect-py/cli.py", line 44, in inspect_block_command
    await inspector.inspect_single_block(
  File "/Users/yuanhongda/CODE/mev-inspect-py/mev_inspect/inspector.py", line 58, in inspect_single_block
    return await inspect_block(
  File "/Users/yuanhongda/CODE/mev-inspect-py/mev_inspect/inspect_block.py", line 68, in inspect_block
    await inspect_many_blocks(
  File "/Users/yuanhongda/CODE/mev-inspect-py/mev_inspect/inspect_block.py", line 105, in inspect_many_blocks
    block = await create_from_block_number(
  File "/Users/yuanhongda/CODE/mev-inspect-py/mev_inspect/block.py", line 31, in create_from_block_number
    block_timestamp, receipts, traces, base_fee_per_gas = await asyncio.gather(
  File "/Users/yuanhongda/CODE/mev-inspect-py/mev_inspect/block.py", line 60, in _find_or_fetch_block_timestamp
    return await _fetch_block_timestamp(w3, block_number)
  File "/Users/yuanhongda/CODE/mev-inspect-py/mev_inspect/block.py", line 105, in _fetch_block_timestamp
    block_json = await w3.eth.get_block(block_number)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/eth.py", line 447, in get_block
    return await self._get_block(block_identifier, full_transactions)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/module.py", line 72, in caller
    result = await w3.manager.coro_request(method_str,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 213, in coro_request
    response = await self._coro_make_request(method, params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 156, in _coro_make_request
    request_func = await self.provider.request_func(  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/providers/async_base.py", line 64, in request_func
    await self._generate_request_func(web3, all_middlewares)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/providers/async_base.py", line 71, in _generate_request_func
    return await async_combine_middlewares(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/middleware/__init__.py", line 108, in async_combine_middlewares
    accumulator_fn = await construct_middleware(middleware, accumulator_fn, web3)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/middleware/__init__.py", line 118, in construct_middleware
    return await middleware(fn, w3)
TypeError: object function can't be used in 'await' expression

@fselmo  How to solve this problem? Thank you.

**Comment by yuanhongda** [comment]
@pacrob  
Thanks for the guidance. Test passed.
