### ISSUE TITLE
ValueError: {'code': -32004, 'message': 'filter requests not supported'}

### ISSUE THREAD

**Issue by Zepps555** [ethereum/web3.py#2248]
* Version:5.25.0
* Python: 3.9.9
* OS: win

### while i was testing the code it didin't want to go through and showed me this error

ERROR: 2021-12-12 13:30:21,429 {'code': -32004, 'message': 'filter requests not supported'}
Traceback (most recent call last):
  File ".\test.py", line 953, in <module>
    run()
  File ".\test.py", line 944, in run
    scan(tokens)
  File ".\test.py", line 607, in scan
    filter = client.eth.filter({'address': routerAddress})
  File ".\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters, null_result_formatters)
  File ".\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File ".\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32004, 'message': 'filter requests not supported'}

in line 607 i ussed this as a filter 
filter = client.eth.filter({'address': routerAddress})

i did try changing it to web3.eth.filter but still didint work, please does anyone know how to fix this ?

**Comment by unparalleled-js** [comment]
What provider are you using? It appears that your provider does not support filtering.

**Comment by fselmo** [comment]
@Zepps555 this message is coming from your provider. I'm with @unparalleled-js on this one. I'm going to close this as this doesn't seem like an issue with the library but if you feel this was closed in error, please feel free to re-open.
