### ISSUE TITLE
Python3.10 pip install. Module not found: distutils.command.bdist_wininst

### ISSUE THREAD

**Issue by J0hn3ch** [ethereum/web3.py#2250]
* Version: latest
* Python: 3.10
* OS: linux
* `python3.10 -m pip install web3` output

``` Installing collected packages: netaddr, multidict, hexbytes, frozenlist, eth-keys, base58, yarl, pyrsistent, multiaddr, eth-rlp, eth-keyfile, eth-abi, bitarray, attrs, async-timeout, aiosignal, websockets, protobuf, lru-dict, jsonschema, ipfshttpclient, eth-account, aiohttp, web3
    Running setup.py install for bitarray ... error
    ERROR: Command errored out with exit status 1:
     command: /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nmi9tdi6/bitarray_f030e6aed3ba4144a754e84032dd3911/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nmi9tdi6/bitarray_f030e6aed3ba4144a754e84032dd3911/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2wqf9i2i/install-record.txt --single-version-externally-managed --compile --install-headers /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/include/site/python3.10/bitarray
         cwd: /tmp/pip-install-nmi9tdi6/bitarray_f030e6aed3ba4144a754e84032dd3911/
    Complete output (93 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.10
    creating build/lib.linux-x86_64-3.10/bitarray
    copying bitarray/util.py -> build/lib.linux-x86_64-3.10/bitarray
    copying bitarray/__init__.py -> build/lib.linux-x86_64-3.10/bitarray
    copying bitarray/test_util.py -> build/lib.linux-x86_64-3.10/bitarray
    copying bitarray/test_bitarray.py -> build/lib.linux-x86_64-3.10/bitarray
    running build_ext
    building 'bitarray._bitarray' extension
    creating build/temp.linux-x86_64-3.10
    creating build/temp.linux-x86_64-3.10/bitarray
    x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/include -I/usr/include/python3.10 -c bitarray/_bitarray.c -o build/temp.linux-x86_64-3.10/bitarray/_bitarray.o
    bitarray/_bitarray.c: In function ‘bitarray_fromfile’:
    bitarray/_bitarray.c:1429:5: warning: ‘PyEval_CallObjectWithKeywords’ is deprecated [-Wdeprecated-declarations]
     1429 |     result = PyEval_CallObject(reader, rargs);
          |     ^~~~~~
    In file included from /usr/include/python3.10/Python.h:144,
                     from bitarray/_bitarray.c:12:
    /usr/include/python3.10/ceval.h:17:43: note: declared here
       17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
          |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    bitarray/_bitarray.c: In function ‘bitarray_tofile’:
    bitarray/_bitarray.c:1568:5: warning: ‘PyEval_CallObjectWithKeywords’ is deprecated [-Wdeprecated-declarations]
     1568 |     result = PyEval_CallObject(writer, args);
          |     ^~~~~~
    In file included from /usr/include/python3.10/Python.h:144,
                     from bitarray/_bitarray.c:12:
    /usr/include/python3.10/ceval.h:17:43: note: declared here
       17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
          |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/bitarray/_bitarray.o -o build/lib.linux-x86_64-3.10/bitarray/_bitarray.cpython-310-x86_64-linux-gnu.so
    building 'bitarray._util' extension
    x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/include -I/usr/include/python3.10 -c bitarray/_util.c -o build/temp.linux-x86_64-3.10/bitarray/_util.o
    x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.10/bitarray/_util.o -o build/lib.linux-x86_64-3.10/bitarray/_util.cpython-310-x86_64-linux-gnu.so
    running install_lib
    creating /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray
    copying build/lib.linux-x86_64-3.10/bitarray/util.py -> /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray
    copying build/lib.linux-x86_64-3.10/bitarray/_util.cpython-310-x86_64-linux-gnu.so -> /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray
    copying build/lib.linux-x86_64-3.10/bitarray/__init__.py -> /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray
    copying build/lib.linux-x86_64-3.10/bitarray/test_util.py -> /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray
    copying build/lib.linux-x86_64-3.10/bitarray/test_bitarray.py -> /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray
    copying build/lib.linux-x86_64-3.10/bitarray/_bitarray.cpython-310-x86_64-linux-gnu.so -> /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray
    byte-compiling /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray/util.py to util.cpython-310.pyc
    byte-compiling /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray/__init__.py to __init__.cpython-310.pyc
    byte-compiling /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray/test_util.py to test_util.cpython-310.pyc
    byte-compiling /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray/test_bitarray.py to test_bitarray.cpython-310.pyc
    running install_egg_info
    running egg_info
    creating bitarray.egg-info
    writing bitarray.egg-info/PKG-INFO
    writing dependency_links to bitarray.egg-info/dependency_links.txt
    writing top-level names to bitarray.egg-info/top_level.txt
    writing manifest file 'bitarray.egg-info/SOURCES.txt'
    reading manifest file 'bitarray.egg-info/SOURCES.txt'
    writing manifest file 'bitarray.egg-info/SOURCES.txt'
    Copying bitarray.egg-info to /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/bitarray-1.2.2.egg-info
    running install_scripts
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nmi9tdi6/bitarray_f030e6aed3ba4144a754e84032dd3911/setup.py", line 18, in <module>
        setup(
      File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.10/distutils/command/install.py", line 634, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/setuptools/command/install_scripts.py", line 35, in run
        bw_cmd = self.get_finalized_command("bdist_wininst")
      File "/usr/lib/python3.10/distutils/cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/lib/python3.10/distutils/dist.py", line 857, in get_command_obj
        klass = self.get_command_class(command)
      File "/home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/setuptools/dist.py", line 834, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2449, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/lib/python3.10/site-packages/setuptools/command/bdist_wininst.py", line 1, in <module>
        import distutils.command.bdist_wininst as orig
    ModuleNotFoundError: No module named 'distutils.command.bdist_wininst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nmi9tdi6/bitarray_f030e6aed3ba4144a754e84032dd3911/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nmi9tdi6/bitarray_f030e6aed3ba4144a754e84032dd3911/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2wqf9i2i/install-record.txt --single-version-externally-managed --compile --install-headers /home/gianluca/Documenti/Tesi/Progetto/py-virtual-env/sec-iot-bc-venv/include/site/python3.10/bitarray Check the logs for full command output. 
```

### What was wrong?

```
On Python 3.10 console
>>> import distutils
<stdin>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```
The module bdist_wininst is not implemented.

I cannot install web3

How can I solve this problem?

**Comment by fselmo** [comment]
Hey @J0hn3ch, that's a good question. We don't currently have Python 3.10 support. It is coming up and there is a PR out for adding support [here](https://github.com/ethereum/web3.py/pull/2175). All are welcome to contribute.

I would recommend using a virtual environment with Python 3.9 for now for using `web3`. I'm going to close this for now as this is being tracked elsewhere. Feel free to open this back up if you feel like this stands out from that PR for any reason.
