### ISSUE TITLE
 'name': 'TXRejectedError'

### ISSUE THREAD

**Issue by recepsirin** [ethereum/web3.py#2282]
When write_to_eth method has been invoked, I am getting such an ambiguous error as below. Even tough, I've called .transact() with "From" key,value pairs, it didn't work out .
```
import json

from eth_typing import HexStr
from web3 import Web3


class SmartContractService(object):
    def __init__(self):
        self.ganache_url = "http://127.0.0.1:7545"
        self.web3 = Web3(Web3.HTTPProvider(self.ganache_url))

    @staticmethod
    def _read_smart_contract_file():
        # brownie init & brownie compile
        with open("product/contracts/build/contracts/createProduct.json") as file:
            contract = json.load(file)
        return contract

    @property
    def _abi(self):
        return self._read_smart_contract_file()['abi']

    @property
    def _bytecode(self):
        return self._read_smart_contract_file()['bytecode']

    def write_to_eth(self, product_id: str, product_name: str, category: str,
                     price: int,
                     description: str) -> HexStr:
        product = self.web3.eth.contract(abi=self._abi,
                                         address="0xEc0c8e81BDaB00a4A11D8955Ba7Aac69A29D98aa",
                                         bytecode=self._bytecode)

        result = product.functions.addProduct(product_id, product_name,
                                              category,
                                              price,
                                              description).transact()
        return self.web3.toHex(result)

    def read_from_contract(self, tx):
        return self.web3.eth.waitForTransactionReceipt(tx)

```

Stacktrace with the error:

>   File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/product/api/views.py", line 29, in post
    raise e
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/product/api/views.py", line 20, in post
    tx = self.service.write_to_eth(
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/product/api/service.py", line 35, in write_to_eth
    result = product.functions.addProduct(product_id, product_name,
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/web3/contract.py", line 997, in transact
    return transact_with_contract_function(
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/web3/contract.py", line 1590, in transact_with_contract_function
    txn_hash = web3.eth.send_transaction(transact_transaction)
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/web3/eth.py", line 719, in send_transaction
    return self._send_transaction(transaction)
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/recep/PycharmProjects/marketplace-eth-integrator/venv/lib/python3.8/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'message': 'from not found; is required', 'code': -32000, 'data': {'stack': 'TXRejectedError: from not found; is required\n    at StateManager.queueTransaction (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/lib/statemanager.js:345:14)\n    at GethApiDouble.eth_sendTransaction (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/lib/subproviders/geth_api_double.js:325:14)\n    at GethApiDouble.handleRequest (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/lib/subproviders/geth_api_double.js:109:10)\n    at next (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at GethDefaults.handleRequest (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/lib/subproviders/gethdefaults.js:15:12)\n    at next (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at SubscriptionSubprovider.FilterSubprovider.handleRequest (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/filters.js:89:7)\n    at SubscriptionSubprovider.handleRequest (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:137:49)\n    at next (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at DelayedBlockFilter.handleRequest (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/lib/subproviders/delayedblockfilter.js:31:3)\n    at next (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at RequestFunnel.handleRequest (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/lib/subproviders/requestfunnel.js:32:12)\n    at next (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at Web3ProviderEngine._handleAsync (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:123:3)\n    at Timeout._onTimeout (/tmp/.mount_ganachoqznnF/resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:107:12)\n    at listOnTimeout (internal/timers.js:531:17)', 'name': 'TXRejectedError'}}

**Comment by fselmo** [comment]
@recepsirin please consult the [docs on the transact method](https://web3py.readthedocs.io/en/latest/contracts.html?#web3.contract.ContractFunction.transact) and be sure to pass in a valid `transaction` dict with a `from` key and your sender address as the value.

This message is coming from your provider and does not appear to be an issue with the library. 
Please post usage questions to the [Discord](https://discord.com/invite/GHryRvPB84). There is a great community there that is always willing to help. I'm going to close this but if you feel there is still an issue with the library please feel free to reopen.
