### ISSUE TITLE
maxFeePerGas and gasPrice parameter

### ISSUE THREAD

**Issue by xmenycg** [ethereum/web3.py#2311]
* Version: web3-5.23.1
* Python: 3.8
* OS: osx
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

Please include any of the following that are applicable:
when i use web3.py to sign a message, it suggests the error below. I see web3.py import eth_account, but eth_account checks the parameters gasPrice but not maxFeePerGas. IN EIP 1559, maxFeePerGas replace the gasPrice, how can i do with this?

Traceback (most recent call last):
  File "infura.py", line 54, in <module>
    tx.sign_transaction("0x5e159d96818062227c9869ea3a53d5551e078157", 21000, GWEI*100, ETHER//100 * 16, GWEI*100)
  File "infura.py", line 40, in sign_transaction
    signed_txn = self.w3.eth.account.signTransaction(trans_dict, config.PRIVATE_KEY)
  File "/Library/Python/3.8/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Library/Python/3.8/site-packages/eth_account/account.py", line 616, in signTransaction
    return self.sign_transaction(transaction_dict, private_key)
  File "/Library/Python/3.8/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Library/Python/3.8/site-packages/eth_account/account.py", line 747, in sign_transaction
    ) = sign_transaction_dict(account._key_obj, sanitized_transaction)
  File "/Library/Python/3.8/site-packages/eth_account/_utils/signing.py", line 32, in sign_transaction_dict
    unsigned_transaction = serializable_unsigned_transaction_from_dict(transaction_dict)
  File "/Library/Python/3.8/site-packages/eth_account/_utils/legacy_transactions.py", line 44, in serializable_unsigned_transaction_from_dict
    assert_valid_fields(transaction_dict)
  File "/Library/Python/3.8/site-packages/eth_account/_utils/legacy_transactions.py", line 97, in assert_valid_fields
    raise TypeError("Transaction must include these fields: %r" % missing_keys)
TypeError: Transaction must include these fields: {'gasPrice'}
* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by fselmo** [comment]
We prefer to use issues to track issues with the library. Please refer to the [documentation](https://web3py.readthedocs.io/en/latest/) or feel free to ask usage questions on the [discord](https://discord.gg/GHryRvPB84). Be sure to use `maxFeePerGas` and `maxPriorityFeePerGas` fields to sign a dynamic fee transaction.
