### ISSUE TITLE
Cannot 

### ISSUE THREAD

**Issue by ymagoon** [ethereum/web3.py#2349]
* Version: 5.2.8
* Python: 3.9
* OS: linux (specifically on raspberry pi 4)
* `pip freeze` output

```
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
base58==2.1.1
bitarray==1.2.2
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
cryptography==36.0.1
cytoolz==0.11.2
eth-abi==2.1.1
eth-account==0.5.7
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.4
eth-rlp==0.2.1
eth-typing==2.3.0
eth-utils==1.10.0
frozenlist==1.3.0
hexbytes==0.2.2
idna==3.3
ipfshttpclient==0.8.0a2
jsonschema==3.2.0
lru-dict==1.1.7
multiaddr==0.0.9
multidict==6.0.2
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.19.4
pycparser==2.21
pycryptodome==3.14.1
pyrsistent==0.18.1
requests==2.27.1
rlp==2.0.1
six==1.16.0
toolz==0.11.2
urllib3==1.26.8
varint==1.0.2
web3==5.28.0
websockets==9.1
yarl==1.7.2

```
### What was wrong?

Spent about 2 hours uninstalling and reinstalling packages and continue to get errors that packages are not installed.

This is the output when running from web3 import Web3

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/Crypto/Util/_raw_api.py", line 81, in <module>
    ffi = FFI()
  File "/home/pi/.local/lib/python3.9/site-packages/cffi/api.py", line 48, in __init__
    import _cffi_backend as backend
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/web3/__init__.py", line 6, in <module>
    from eth_account import (
  File "/home/pi/.local/lib/python3.9/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import (
  File "/home/pi/.local/lib/python3.9/site-packages/eth_account/account.py", line 11, in <module>
    from eth_keyfile import (
  File "/home/pi/.local/lib/python3.9/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/home/pi/.local/lib/python3.9/site-packages/eth_keyfile/keyfile.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "/home/pi/.local/lib/python3.9/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/home/pi/.local/lib/python3.9/site-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/home/pi/.local/lib/python3.9/site-packages/Crypto/Util/_raw_api.py", line 164, in <module>
    import ctypes
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

**Comment by kclowes** [comment]
This looks similar to an issue that got raised in the python discord. And looks like it got resolved by downgrading to python 3.7? I suspect this is an issue with your `PATH`. I'm going to close because I don't think this is an issue with web3py, but feel free to reopen if you think that's wrong.
