### ISSUE TITLE
web3.eth.send_raw_transaction failed, cannot publish when tested locally

### ISSUE THREAD

**Issue by venom-d** [ethereum/web3.py#2400]
Traceback (most recent call last):
  File "/usr/src/pbb/py/pbb/test.py", line 115, in <module>
    sell_token(address, weth, token, _deadline, get_token_balance(token), gas, router, slippage)
  File "/usr/src/pbb/py/pbb/test.py", line 85, in sell_token
    _build_and_send_tx( func(qty, amount_out_min, [token, weth], address, _deadline,), _get_tx_params(address, qty, gas))
  File "/usr/src/pbb/py/pbb/test.py", line 46, in _build_and_send_tx
    return web3.eth.send_raw_transaction(signed_txn.rawTransaction)
  File "/usr/local/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32603, 'message': 'Error: Transaction reverted without a reason string', 'data': {'txHash': '0x50f150ef4f9767dc94290ce49762ee850b9d627f52da4b9ede3ce138d0572cd4'}}

**Comment by kclowes** [comment]
This is a response from your server, not a problem with web3.py. If you need usage help, please see [our discord](https://discord.com/invite/GHryRvPB84).
