### ISSUE TITLE
Can't send a raw transaction: "TypeError: SignedTransaction.__new__() missing 4 required positional arguments: 'hash', 'r', 's', and 'v'"

### ISSUE THREAD

**Issue by tenuki** [ethereum/web3.py#2415]
* Version: web3==5.28.0
* Python: Python 3.10.1
* OS: win
* `pip freeze` output  // see below

### What was wrong?

I build a transfer transaction call from a contract for an address of which I have the private-key.  then I sign it. Then I try to send that an it fails.

* The code which produced the error

```python
        tx = contract_instance.functions.transfer( 
                destination,
                amount,
        ).buildTransaction({
            'from': acc.address,
            'chainId': chain_id,
            'gas': 70000,
            'maxFeePerGas': w3.toWei('2', 'gwei'),
            'maxPriorityFeePerGas': w3.toWei('1', 'gwei'),
            'nonce': w3.eth.getTransactionCount(acc.address),
        })
        signed_txn = Account.sign_transaction(tx, private_key)
        # signed_txn = w3.eth.account.sign_transaction(tx, private_key)
        tx_hash = w3.eth.sendRawTransaction(signed_txn)
```

* The full output of the error

Yes sr! 

```cmd
Traceback (most recent call last):
  File "..\user\repos\my_repo\nft\mininft.py", line 188, in <module>
    mininft()
  File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "..\user\repos\my_repo\nft\mininft.py", line 174, in send
    tx_hash = w3.eth.sendRawTransaction(signed_txn)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\eth.py", line 818, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\module.py", line 53, in caller
    (method_str, params), response_formatters = method.process_params(module, *args, **kwargs)  # noqa: E501
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\method.py", line 202, in process_params
    _apply_request_formatters(params, self.request_formatters(method)))
  File "..\user\repos\my_repo\nft\env\lib\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\method.py", line 52, in _apply_request_formatters
    formatted_params = pipe(params, request_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
    return c_pipe(data, funcs)
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
    data = func(data)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
    raise
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\abi.py", line 811, in map_abi_data
    return pipe(data, *pipeline)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
    return c_pipe(data, funcs)
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
    data = func(data)
  File "cytoolz/functoolz.pyx", line 254, in cytoolz.functoolz.curry.__call__
    raise
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
    return self.func(*args, **kwargs)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\abi.py", line 845, in data_tree_map
    return recursive_map(map_to_typed_data, data_tree)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\decorators.py", line 30, in wrapped
    wrapped_val = to_wrap(*args)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\formatters.py", line 89, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\formatters.py", line 76, in map_collection
    return datatype(map(func, collection))
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\formatters.py", line 88, in recurse
    return recursive_map(func, item)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\decorators.py", line 30, in wrapped
    wrapped_val = to_wrap(*args)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\formatters.py", line 89, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\formatters.py", line 76, in map_collection
    return datatype(map(func, collection))
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\abi.py", line 867, in __new__
    return super().__new__(cls, *iterable)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\formatters.py", line 88, in recurse
    return recursive_map(func, item)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\decorators.py", line 30, in wrapped
    wrapped_val = to_wrap(*args)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\formatters.py", line 89, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\_utils\formatters.py", line 76, in map_collection
    return datatype(map(func, collection))
TypeError: SignedTransaction.__new__() missing 4 required positional arguments: 'hash', 'r', 's', and 'v'
```

(Honestly: I can't understand how it requires more than 30 layers of functions just to send an already signed transaction. )

* What type of node you were connecting to.

Private geth for BSC-testnet.

### How can it be fixed?

I have no clue.

Indeed, I think I shouldn't have reach this point at where I'm building the transaction and trying to sign and send manually. 

I think, there should and probably is a shorter and expected way to do this by letting web3py use an account created from a private_key:  `acc = w3.eth.account.from_key(private_key)`, but I couldn't either get that to work.  

I would appreciate help to get both ways to work or the link to the doc where I can do that, but I couldn't get that to work and can't find the exact way to do that either.

Thanks in advance.

---

### `pip freeze` output

```
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
base58==2.1.1
bitarray==1.2.2
bleach==4.1.0
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.1.2
colorama==0.4.4
commonmark==0.9.1
cytoolz==0.11.2
docutils==0.18.1
eth-abi==2.1.1
eth-account==0.5.7
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.4
eth-rlp==0.2.1
eth-typing==2.3.0
eth-utils==1.10.0
frozenlist==1.3.0
hexbytes==0.2.2
idna==3.3
importlib-metadata==4.11.3
ipfshttpclient==0.8.0a2
jsonschema==3.2.0
keyring==23.5.0
lru-dict==1.1.7
multiaddr==0.0.9
multidict==6.0.2
netaddr==0.8.0
packaging==21.3
parsimonious==0.8.1
pkginfo==1.8.2
protobuf==3.20.0
pycryptodome==3.14.1
Pygments==2.11.2
pyparsing==3.0.7
pyrsistent==0.18.1
pywin32==303
pywin32-ctypes==0.2.0
readme-renderer==34.0
requests==2.27.1
requests-toolbelt==0.9.1
rfc3986==2.0.0
rich==12.2.0
rlp==2.0.1
six==1.16.0
toolz==0.11.2
twine==4.0.0
urllib3==1.26.9
varint==1.0.2
web3==5.28.0
webencodings==0.5.1
websockets==9.1
yarl==1.7.2
zipp==3.8.0
```

**Comment by tenuki** [comment]
And if I try to: `tx_hash = w3.eth.sendRawTransaction(signed_txn.rawTransaction)`  I get:

```python
Traceback (most recent call last):
  File "..\user\repos\my_repo\nft\mininft.py", line 191, in <module>
    mininft()
  File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "..\user\repos\my_repo\nft\mininft.py", line 177, in send
    tx_hash = w3.eth.sendRawTransaction(t)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\eth.py", line 818, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'transaction type not supported'}
```

**Comment by fselmo** [comment]
@tenuki you're right to use `signed_txn.rawTransaction` as the docs state [here](https://web3py.readthedocs.io/en/latest/web3.eth.html?highlight=send_raw_transaction#web3.eth.Eth.send_raw_transaction). The reason you get an error with "transaction type not supported" is because BSC does not support dynamic fee transactions (type=2). The warning on [this page](https://web3py.readthedocs.io/en/latest/web3.eth.html?highlight=BSC#module-web3.eth) should help a bit with that. You need to set a `gasPrice` instead of `max*FeePerGas` values.

I'm going to close this as this doesn't seem to be an issue but please ask to reopen and post here if you are still having issues.

**Comment by tenuki** [comment]
> And if I try to: `tx_hash = w3.eth.sendRawTransaction(signed_txn.rawTransaction)` I get:
> 
> ```python
> Traceback (most recent call last):
>   File "..\user\repos\my_repo\nft\mininft.py", line 191, in <module>
>     mininft()
>   File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "..\user\repos\my_repo\nft\env\lib\site-packages\click\core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "..\user\repos\my_repo\nft\mininft.py", line 177, in send
>     tx_hash = w3.eth.sendRawTransaction(t)
>   File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\eth.py", line 818, in send_raw_transaction
>     return self._send_raw_transaction(transaction)
>   File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\module.py", line 57, in caller
>     result = w3.manager.request_blocking(method_str,
>   File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\manager.py", line 198, in request_blocking
>     return self.formatted_response(response,
>   File "..\user\repos\my_repo\nft\env\lib\site-packages\web3\manager.py", line 171, in formatted_response
>     raise ValueError(response["error"])
> ValueError: {'code': -32000, 'message': 'transaction type not supported'}
> ```

This failed because of this:

**Comment by tenuki** [comment]
> @tenuki you're right to use `signed_txn.rawTransaction` as the docs state [here](https://web3py.readthedocs.io/en/latest/web3.eth.html?highlight=send_raw_transaction#web3.eth.Eth.send_raw_transaction). The reason you get an error with "transaction type not supported" is because BSC does not support dynamic fee transactions (type=2). The warning on [this page](https://web3py.readthedocs.io/en/latest/web3.eth.html?highlight=BSC#module-web3.eth) should help a bit with that. You need to set a `gasPrice` instead of `max*FeePerGas` values.
> 
> I'm going to close this as this doesn't seem to be an issue but please ask to reopen and post here if you are still having issues.

I still have the doubt about if it is required to build and sign and send the tx by hand or if it is there a way to include an account created as specified by the documentation with "from_key(..)" and get it used automatically by: `contract.method.contract_func(params).transact({from: acc_created.address})`
?

**Comment by tenuki** [comment]
I think that it would be nice to also understand why I got: `TypeError: SignedTransaction.__new__() missing 4 required positional arguments: 'hash', 'r', 's', and 'v'`  at the first time...

**Comment by tenuki** [comment]
> 

Thanks for the links I'm checking again!

**Comment by tenuki** [comment]
> 



> I think that it would be nice to also understand why I got: `TypeError: SignedTransaction.__new__() missing 4 required positional arguments: 'hash', 'r', 's', and 'v'` at the first time...

Ok that was because of passing  ( signedtransaction )  instead of (  signedtransaction.rawTransaction ) to sendRawTransaction...  the error message was quite illustrative :-)

**Comment by tenuki** [comment]
> @tenuki you're right to use `signed_txn.rawTransaction` as the docs state [here](https://web3py.readthedocs.io/en/latest/web3.eth.html?highlight=send_raw_transaction#web3.eth.Eth.send_raw_transaction). The reason you get an error with "transaction type not supported" is because BSC does not support dynamic fee transactions (type=2). The warning on [this page](https://web3py.readthedocs.io/en/latest/web3.eth.html?highlight=BSC#module-web3.eth) should help a bit with that. You need to set a `gasPrice` instead of `max*FeePerGas` values.
> 
> I'm going to close this as this doesn't seem to be an issue but please ask to reopen and post here if you are still having issues.

Thank you

**Comment by fselmo** [comment]
> I still have the doubt about if it is required to build and sign and send the tx by hand or if it is there a way to include an account created as specified by the documentation with "from_key(..)" and get it used automatically by: `contract.method.contract_func(params).transact({from: acc_created.address})` ?

I think the [sign_and_send_raw_middleware](https://web3py.readthedocs.io/en/latest/middleware.html#signing) may prove helpful for you to be able to use `acct = Account.from_key(private_key)` and not have to sign everything all the time.

**Comment by tenuki** [comment]
> > I still have the doubt about if it is required to build and sign and send the tx by hand or if it is there a way to include an account created as specified by the documentation with "from_key(..)" and get it used automatically by: `contract.method.contract_func(params).transact({from: acc_created.address})` ?
> 
> I think the [construct_sign_and_send_raw_middleware](https://web3py.readthedocs.io/en/latest/middleware.html#signing) may prove helpful for you to be able to use `acct = Account.from_key(private_key)` and not have to sign everything all the time.

It really seems what I should be using!! Thank you so much!!!!
