### ISSUE TITLE
How do I stop a running filter?

### ISSUE THREAD

**Issue by mattvick** [ethereum/web3.py#242]
* Version: 3.11.1
* Python: 3.5.3
* OS: macOS 10.12.6

I'm connecting to the **Kovan** network using **Parity 1.7.0** on **localhost**

### How do I stop a running filter started with `Filter.watch(*callbacks)`?

When I try to stop a running filter, by calling `stop_watching()` inside it's callback, I receive a `RuntimeError: cannot join current thread.` error.

Some code to better explain:
```py
factory = web3.eth.contract(address=factory_address, abi=factory_abi)

def filter_callback(result, my_filter):
    print(result)
    my_filter.stop_watching()

instantiation_filter = factory.on('ContractInstantiation', filter_params=None)
instantiation_filter.watch(lambda x: filter_callback(x, instantiation_filter))

factory.transact({'from': web3.eth.coinbase}).create([user_address], 1)

>>> {'address': '0xf93586f3d3bae44782151803ac52b0b54c5b9f1f', 'transactionHash': '0x97cc60667d2f71096f47464d58a3fc00690f40291868689b4257ae1bb7cf6859', 'logIndex': 19, 'blockHash': '0x688b461b47142efdc9812b89e730f4255e876e6b485731bc9cd7f6df5f71a0cc', 'args': {'instantiation': '0x484c6852a28c1990b703f913f394be0d4a718435', 'sender': '0x72d0609e2cfed6568cc5a42d09310f1d2fcf412f'}, 'transactionIndex': 2, 'blockNumber': 3360629, 'event': 'ContractInstantiation'}
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/matthew/.pyenv/versions/3.5.3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/matthew/.pyenv/versions/3.5.3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/matthew/webapp/env/lib/python3.5/site-packages/web3/utils/filters.py", line 89, in _run
    callback_fn(self.format_entry(entry))
  File "<console>", line 1, in <lambda>
  File "<console>", line 3, in filter_callback
  File "/Users/matthew/webapp/env/lib/python3.5/site-packages/web3/utils/filters.py", line 121, in stop_watching
    self.join(timeout)
  File "/Users/matthew/.pyenv/versions/3.5.3/lib/python3.5/threading.py", line 1051, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

**Comment by carver** [comment]
#294 should include an example of how to deal with this.

**Comment by djrtwo** [comment]
Are we keeping a very similar API, but removing all GreenletThread related code? 

Example keeping call to `watch` but removing `stop_watching`. 
Having `watch` explicitly call `_run`, etc.

**Comment by pipermerriam** [comment]
closing this as the filter API has been reworked. Please re-open or re-submit a new issue if you are still having issues.
