### ISSUE TITLE
cant deploy solidity contract with python

### ISSUE THREAD

**Issue by sadath-12** [ethereum/web3.py#2430]
error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\blockchain\deploy.py", line 42, in <module>
    nonce =w3.eth.getTransactionCount(my_address)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\manager.py", line 150, in _make_request
    return request_func(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\gas_price_strategy.py", line 90, in middleware   
    return make_request(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\buffered_gas_estimate.py", line 40, in middleware    return make_request(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\middleware\exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\providers\rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\_utils\request.py", line 102, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\SYED SADATH ULLA\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=7545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000206A69F8D90>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))

**Comment by fselmo** [comment]
This looks an issue with your provider setup. The issue seems like it's coming from the very first call it tries to make which is getting the `nonce` for your transaction with `w3.eth.get_transaction_count(from_address)`. I'm going to close this as it's unrelated to deploying a contract.

Please check your provider setup and feel free to ask questions on [Discord](https://discord.gg/GHryRvPB84). That's the best place to ask usage and setup questions.
