### ISSUE TITLE
WebsocketProvider constructor is not thread-safe

### ISSUE THREAD

**Issue by afedotov89** [ethereum/web3.py#2445]
* Version: 5.28.0
* Python: 3.8
* OS: osx

### What was wrong?
Exception when using WebsocketProvider in multiple threads.
The code which produced the error (with a high probability):
```
import threading
from web3 import Web3, WebsocketProvider

def fn():
    w3 = Web3(WebsocketProvider())
    w3.eth.chain_id
    w3.eth.chain_id

threading.Thread(target=fn).start()
threading.Thread(target=fn).start()
```
The full output of the error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "web3_test.py", line 7, in fn
    w3.eth.chain_id
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/eth.py", line 609, in chain_id
    return self._chain_id()
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/providers/websocket.py", line 144, in make_request
    return future.result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/providers/websocket.py", line 130, in coro_make_request
    await asyncio.wait_for(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 404, in recv
    await asyncio.wait(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 424, in wait
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 424, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 667, in ensure_future
    raise ValueError('The future belongs to a different loop than '
ValueError: The future belongs to a different loop than the one specified as the loop argument
```
Node type probably doesn't matter. Produced with hardhat, infura mainnet, xdai.
In more complex code, this error also occurs:
```
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/eth.py", line 609, in chain_id
    return self._chain_id()
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/providers/websocket.py", line 144, in make_request
    return future.result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/providers/websocket.py", line 124, in coro_make_request
    async with self.conn as conn:
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/providers/websocket.py", line 72, in __aenter__
    self.ws = await connect(
  File "/Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 986, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1365, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
RuntimeError: Task <Task pending name='Task-6' coro=<WebsocketProvider.coro_make_request() running at /Users/sasha/Library/Caches/pypoetry/virtualenvs/metadata-w3rui5rF-py3.8/lib/python3.8/site-packages/web3/providers/websocket.py:124> cb=[_chain_future.<locals>._call_set_state() at /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py:367]> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/futures.py:360]> attached to a different loop
```

### How can it be fixed?

I think the problem is race condition in provider WebsocketProvider constructor: https://github.com/ethereum/web3.py/blob/v5.28.0/web3/providers/websocket.py#L102
Lock is needed

**Comment by svija** [comment]
I have same problem as you met sadly :(

**Comment by fselmo** [comment]
@afedotov89 I hope you were able to get around that. We have been on a course to deprecate the `WebsocketProvider` altogether and hope to make `WebsocketProviderV2` the default websocket provider for the library. It is an asynchronous provider so if there are any issues with async compatibility for your use case, that would be helpful to know. Otherwise, a similar example can be successfully run with this new websocket provider.

```py
async def fn():
    async with AsyncWeb3.persistent_websocket(
        WebsocketProviderV2(f"wss://mainnet.infura.io/ws/v3/{INFURA_PROJECT_ID}")
    ) as w3:
        await w3.eth.chain_id
        await w3.eth.chain_id
        await w3.eth.chain_id


def run_fn():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(fn())
    loop.close()


threading.Thread(target=run_fn).start()
threading.Thread(target=run_fn).start()
threading.Thread(target=run_fn).start()
time.sleep(1)  # give enough time for futures to finish before closing loop
```

@svija  I hope the above example can serve as a guide for your case as well.

---

If async alone would help satisfy your use case, rather than multithreading, the following code snippet might be of some use as well.

```py
async def fn():
    async with AsyncWeb3.persistent_websocket(
        WebsocketProviderV2(f"wss://mainnet.infura.io/ws/v3/{INFURA_PROJECT_ID}")
    ) as w3:
        await w3.eth.chain_id
        await w3.eth.chain_id
        await w3.eth.chain_id
        await w3.eth.chain_id


async def run_example():
    await asyncio.gather(*[fn() for _ in range(3)])

asyncio.run(run_example())
```

**Comment by fselmo** [comment]
Closing for now. If you have any issues with `WebsocketProviderV2` please ask to re-open. Best of luck.
