### ISSUE TITLE
ContractFunction.call may fail as args and kwargs properties may be None

### ISSUE THREAD

**Issue by iwiwi** [ethereum/web3.py#2541]
* Version: 5.29.2
* Python: 3.10.4
* OS: linux

### What was wrong?

Depending on the way how a `ContractFunction` is instantiated, its `args` and `kwargs` may be `None`, which occurs errors when invoking `call`.

#### Example code

```python
import json
from web3.auto.infura import w3

USDC = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
EIP20_ABI = json.loads('[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_from","type":"address"},{"indexed":true,"name":"_to","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"_owner","type":"address"},{"indexed":true,"name":"_spender","type":"address"},{"indexed":false,"name":"_value","type":"uint256"}],"name":"Approval","type":"event"}]')

contract = w3.eth.contract(USDC, abi=EIP20_ABI)
f = contract.get_function_by_signature("decimals()")
f.call()
```

#### Result
```
Traceback (most recent call last):
  File "...", line 14, in <module>
    f.call()
  File ".../venv/lib/python3.10/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
TypeError: Value after * must be an iterable, not NoneType

```

### How can it be fixed?

The minimal fix may be changing `*self.args` and  `**self.kwargs` to `*(self.args or [])` and `**(self.kwargs or {})` in the following lines: 

https://github.com/ethereum/web3.py/blob/c68f6564ef85c17c5162ce2493d6db16e755516c/web3/contract.py#L1222-L1223

I can work on creating a PR.

**Comment by kclowes** [comment]
Sure, a PR would be great. Thanks!

**Comment by iwiwi** [comment]
Thanks for your response! Created a PR: #2545
