### ISSUE TITLE
KeyError: 'baseFeePerGas': while sending a simple contract transaction

### ISSUE THREAD

**Issue by tenuki** [ethereum/web3.py#2552]
* Version: 5.29.2
* Python: 3.8.10
* OS: linux
* `pip freeze` output

```
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
base58==2.1.1
bitarray==2.5.1
certifi==2022.6.15
charset-normalizer==2.1.0
cytoolz==0.11.2
eth-abi==2.1.1
eth-account==0.5.8
eth-hash==0.3.3
eth-keyfile==0.5.1
eth-keys==0.3.4
eth-rlp==0.2.1
eth-typing==2.3.0
eth-utils==1.10.0
frozenlist==1.3.0
hexbytes==0.2.2
idna==3.3
importlib-resources==5.8.0
ipfshttpclient==0.8.0a2
jsonschema==4.6.1
lru-dict==1.1.7
multiaddr==0.0.9
multidict==6.0.2
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.20.1
pycryptodome==3.15.0
pyrsistent==0.18.1
requests==2.28.1
rlp==2.0.1
six==1.16.0
toolz==0.11.2
urllib3==1.26.9
varint==1.0.2
web3==5.29.2
websockets==9.1
yarl==1.7.2
zipp==3.8.0
```

### What was wrong?

* The code which produced the error

```py
import os
from eth_account import Account
from web3 import Web3
from web3.middleware import geth_poa_middleware, \
    construct_sign_and_send_raw_middleware

from abis import RouterAddress, Router, FactoryAddress, Factory, ERC20

w3 = Web3(Web3.HTTPProvider('https://data-seed-prebsc-1-s3.binance.org:8545/'))
acct = Account.create(os.environ['PRIVATE_KEY'])
w3.middleware_onion.add(construct_sign_and_send_raw_middleware(acct))
w3.eth.default_account = acct.address
w3.middleware_onion.inject(geth_poa_middleware, layer=0)

router = w3.eth.contract(address=RouterAddress, abi=Router)
factory = w3.eth.contract(address=FactoryAddress, abi=Factory)

print('ADDRESS:', acct.address)

latest = w3.eth.get_block('latest')
print(repr(latest))

erc20 = w3.eth.contract(address=Web3.toChecksumAddress(
                            '0x20e64f051aA846A1B556E2686357D50B8f6D230a'),
                        abi=ERC20)
r = erc20.functions.approve(RouterAddress, 10_000_000).transact({
#    'baseFeePerGas': '5000000000',
#    'gasLimit': '1000000',
 #'maxFeePerGas': '5000000000',  # 5gw
 #'baseFeePerGas': '5000000000',  # 5gw
# 'gas': '1000000',
# 'limit': '1000000',
})
print(repr(r))

# # --- test2 ---
# tx = erc20.functions.approve(RouterAddress, 10_000_000).buildTransaction({
#     'from': acct.address,
#     #'chainId': chain_id,
#     #'gasPrice': _gas_price,
#    # 'nonce': w3.eth.getTransactionCount(acc.address),
# })
# signed_txn = w3.eth.account.sign_transaction(tx, os.environ['PRIVATE_KEY'])
# tx_hash = w3.eth.send_raw_transaction(signed_txn.rawTransaction)
# print('tx hash:',tx_hash)
```

* The full output of the error

Part1:
Whatever the settings I put or remove from transaction options, including no extra options, and also trying the manual sign tx and send, what I get is:

```
/home/user/repos/whatever/venv/bin/python /home/user/repos/whatever/maxfeerror.py
ADDRESS: 0x92987Ee266BfB8Ce3384C8a512524eE83a3D8AcA
AttributeDict({'difficulty': 2, 'proofOfAuthorityData': HexBytes('0xd98301010a846765746889676f312e31362e3135856c696e75780000de3b3a0480c76456371b93df6259faa1eb407f890a3acb8fc0061e3e21c26af4dd3bb45835058018713bbf645869c907a94ac13328c51b44cc7789a1a18b20bee0b08d9b00'), 'gasLimit': 30000000, 'gasUsed': 313133, 'hash': HexBytes('0xac032059b126bfdd9a9636c8d66dc77e6243d5e0e7fd8ba351fdf1bb21e15037'), 'logsBloom': HexBytes('0x0000000000000002000000000020000000000000000000000004000000000000000040000400000200000000000000010000000000800000000020000000000000000000000000040020000800000000201008000002000000000000040000000000802000020000004000000000800008000000000400000000001220000000000000000000000000000000008000001000040000200000000000000000002000020000000000000004000000000000000000000000000000004000000000002000000a000000000000000002000000200000000080000100000002001000000000000000000000030000000000000000000000001000000000000000000004'), 'miner': '0x980A75eCd1309eA12fa2ED87A8744fBfc9b863D5', 'mixHash': HexBytes('0x0000000000000000000000000000000000000000000000000000000000000000'), 'nonce': HexBytes('0x0000000000000000'), 'number': 20690380, 'parentHash': HexBytes('0xc9197dd890343021013d440075f120f3db5f9c92bd7734a540abf3639074b052'), 'receiptsRoot': HexBytes('0x965c92f62189b7ffde2cbf4d511e2c2248b8ab563b820d02828cf38b9ac8267d'), 'sha3Uncles': HexBytes('0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'), 'size': 1336, 'stateRoot': HexBytes('0xd1d44f3a88977387eb8efb281baef007990428f5d53b8d92e9d3a2b59bf41e4f'), 'timestamp': 1656714330, 'totalDifficulty': 41227990, 'transactions': [HexBytes('0xcf8a4fc58415cdb97d641e6c6af8a2060fc44fab35c4129f4879d173cab94ff3'), HexBytes('0x2ff6fcf86d802742e4691a6e36bbd771fabc899f877659171be208882f4ab178'), HexBytes('0x69a9731b8cbb65ca1af2e9a6ed7a3b305905bc36b552d857e71da064ee14fe5d'), HexBytes('0x0697e2262ffb91b76a90de111094c1f6735d347f2d0e6ec7ece9d2d60a2a8aca'), HexBytes('0x2252558c103913000be9a69ca616b4c545cb320b149301c65a65df22e56049ae')], 'transactionsRoot': HexBytes('0x90f6e34c7a5f994931619ba6886098e3cbaddaac8470eb5209e343db3a3a1ea6'), 'uncles': []})
Traceback (most recent call last):
  File "/home/user/repos/whatever/maxfeerror.py", line 39, in <module>
    r = erc20.functions.approve(RouterAddress, 10_000_000).transact({
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/contract.py", line 997, in transact
    return transact_with_contract_function(
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/contract.py", line 1590, in transact_with_contract_function
    txn_hash = web3.eth.send_transaction(transact_transaction)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/eth.py", line 828, in send_transaction
    return self._send_transaction(transaction)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/middleware/signing.py", line 151, in middleware
    transaction = format_and_fill_tx(params[0])
  File "cytoolz/functoolz.pyx", line 505, in cytoolz.functoolz.Compose.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/_utils/transactions.py", line 114, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/_utils/transactions.py", line 64, in <lambda>
    web3.eth.max_priority_fee + (2 * web3.eth.get_block('latest')['baseFeePerGas'])
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/datastructures.py", line 51, in __getitem__
    return self.__dict__[key]  # type: ignore
KeyError: 'baseFeePerGas'
```

But if I try against other node ( `https://data-seed-prebsc-1-s1.binance.org:8545/` ) what I get is: 

```
ADDRESS: 0x1AEB21FE38060312586021d314e59C4d6A740556
AttributeDict({'difficulty': 2, 'proofOfAuthorityData': HexBytes('0xd98301010b846765746889676f312e31362e3130856c696e75780000de3b3a041e73acf7cc0605b209a054a1c9219110288a0bad9aed7e15bdf0777d047b03f01db8b4c4cbeaccb657ab4604daa44bd28a414bd2d4e5605889dcd5e08eb2032d00'), 'gasLimit': 30000000, 'gasUsed': 96068, 'hash': HexBytes('0xc139c58ef494bbf6ad2cfdd98819e2c3f267aeeb45f1e0515cbb3b08c110cf1b'), 'logsBloom': HexBytes('0x00000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000080000000002010000000000000000000000000000000000020000200200100000000000000080000000000000000000000001000000000000000000000000000000000000000000400000000000000000000000020020000001000000000000000400000000000000020000000000000000008000000000000000000000000020000010000000000000000000000000002000000000010000000000000010000000000000000000000000000000000000000000000'), 'miner': '0x049153b8DAe0a232Ac90D20C78f1a5D1dE7B7dc5', 'mixHash': HexBytes('0x0000000000000000000000000000000000000000000000000000000000000000'), 'nonce': HexBytes('0x0000000000000000'), 'number': 20690621, 'parentHash': HexBytes('0xde58c81131289f8ee00d1d332f42b16cde2b2d8f26cd8933b42594fb5d788685'), 'receiptsRoot': HexBytes('0xd135482c800ea54732ffc6e62144d8ba3ec2635041c84f625b971f5d34051850'), 'sha3Uncles': HexBytes('0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'), 'size': 1048, 'stateRoot': HexBytes('0xc9a7848afa10d816ace716b1608dd3879458e37a3f4df7041199aef6c94acf2c'), 'timestamp': 1656715053, 'totalDifficulty': 41228472, 'transactions': [HexBytes('0xadcb4ec065f6f14259ed23ec29057cd8409797c8de37998fa2ff1589cdcd8291'), HexBytes('0xe4108c3c953c7ac6ff61301a1f2149045f0a85b6b16eaa118d6e38460f3abb2c'), HexBytes('0xa4714b1f54ccf3ad27d99bf4cd937a9c9d87f3cae07f65c51c390b3b8d4590fa')], 'transactionsRoot': HexBytes('0xd04f59510ce4c85c9ef575bdba527c835be92f575e815941b03c104cc85c04ac'), 'uncles': []})
/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/eth.py:656: UserWarning: There was an issue with the method eth_maxPriorityFeePerGas. Calculating using eth_feeHistory.
  warnings.warn(
Traceback (most recent call last):
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/eth.py", line 654, in max_priority_fee
    return self._max_priority_fee()
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'the method eth_maxPriorityFeePerGas does not exist/is not available'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maxfeerror.py", line 28, in <module>
    r = erc20.functions.approve(RouterAddress, 10_000_000).transact({
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/contract.py", line 997, in transact
    return transact_with_contract_function(
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/contract.py", line 1590, in transact_with_contract_function
    txn_hash = web3.eth.send_transaction(transact_transaction)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/eth.py", line 828, in send_transaction
    return self._send_transaction(transaction)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/middleware/signing.py", line 151, in middleware
    transaction = format_and_fill_tx(params[0])
  File "cytoolz/functoolz.pyx", line 505, in cytoolz.functoolz.Compose.__call__
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/_utils/transactions.py", line 114, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/_utils/transactions.py", line 64, in <lambda>
    web3.eth.max_priority_fee + (2 * web3.eth.get_block('latest')['baseFeePerGas'])
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/eth.py", line 660, in max_priority_fee
    return fee_history_priority_fee(self)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/_utils/fee_utils.py", line 45, in fee_history_priority_fee
    fee_history = eth.fee_history(*PRIORITY_FEE_HISTORY_PARAMS)  # type: ignore
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/eth.py", line 876, in fee_history
    return self._fee_history(block_count, newest_block, reward_percentiles)
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/user/repos/whatever/venv/lib/python3.8/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'the method eth_feeHistory does not exist/is not available'}
```

* What type of node you were connecting to.

Bsc smartchain testnet public nodes. Presumably geth as that is what they give you to install.

---

**Comment by tenuki** [comment]
Adding: {'maxFeePerGas': '5000000000'} what I get is (using first node) :

```
File "..//venv/lib/python3.8/site-packages/eth_account/_utils/typed_transactions.py", line 428, in assert_valid_fields
    raise TypeError("Transaction had invalid fields: %r" % invalid)
TypeError: Transaction had invalid fields: {'maxFeePerGas': '5000000000'}

```

**Comment by fselmo** [comment]
Hey @tenuki... `web3.py` exists in the `/ethereum` repos and, as such, is built with Ethereum in mind. Refer to the note at the top of [this section](https://web3py.readthedocs.io/en/latest/web3.eth.html?highlight=binance#module-web3.eth) in the docs for a quick explanation and answer.

Best of luck.
