### ISSUE TITLE
encode_structured_data

### ISSUE THREAD

**Issue by DvScripts** [ethereum/web3.py#2696]
Hello
I tried to reproduce this code :
https://github.com/ethereum/web3.py/issues/2661

So my code looks like this 👍 

```python
import eth_account
from eth_account import Account
from eth_account.messages import encode_structured_data

data2 = {
    "types": {
        "EIP712Domain": [{
                "name": "name",
                "type": "string"
            }, {
                "name": "version",
                "type": "string"
            }, {
                "name": "chainId",
                "type": "uint256"
            }, {
                "name": "verifyingContract",
                "type": "address"
            }
        ],
        "OrderComponents": [{
                "name": "offerer",
                "type": "address"
            }, {
                "name": "zone",
                "type": "address"
            }, {
                "name": "offer",
                "type": "OfferItem[]"
            }, {
                "name": "consideration",
                "type": "ConsiderationItem[]"
            }, {
                "name": "orderType",
                "type": "uint8"
            }, {
                "name": "startTime",
                "type": "uint256"
            }, {
                "name": "endTime",
                "type": "uint256"
            }, {
                "name": "zoneHash",
                "type": "bytes32"
            }, {
                "name": "salt",
                "type": "uint256"
            }, {
                "name": "conduitKey",
                "type": "bytes32"
            }, {
                "name": "counter",
                "type": "uint256"
            }
        ],
        "OfferItem": [{
                "name": "itemType",
                "type": "uint8"
            }, {
                "name": "token",
                "type": "address"
            }, {
                "name": "identifierOrCriteria",
                "type": "uint256"
            }, {
                "name": "startAmount",
                "type": "uint256"
            }, {
                "name": "endAmount",
                "type": "uint256"
            }
        ],
        "ConsiderationItem": [{
                "name": "itemType",
                "type": "uint8"
            }, {
                "name": "token",
                "type": "address"
            }, {
                "name": "identifierOrCriteria",
                "type": "uint256"
            }, {
                "name": "startAmount",
                "type": "uint256"
            }, {
                "name": "endAmount",
                "type": "uint256"
            }, {
                "name": "recipient",
                "type": "address"
            }
        ]
    },
    "primaryType": "OrderComponents",
    "domain": {
        "name": "Seaport",
        "version": "1.1",
        "chainId": 1,
        "verifyingContract": "0x00000000006c3852cbEf3e08E8dF289169EdE581"
    },
    "message": {
        "offerer": "0x51663AE5742164944D1bb6cb2785Fdf839666Ed4",
        "offer": [{
                "itemType": 1,
                "token": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
                "identifierOrCriteria": 0,
                "startAmount": 5000000000000000,
                "endAmount": 5000000000000000
            }
        ],
        "consideration": [{
                "itemType": 4,
                "token": "0x458aed4f6f2Af40De88856e414Cf5b49514cbD78",
                "identifierOrCriteria": 0,
                "startAmount": 1,
                "endAmount": 1,
                "recipient": "0x51663AE5742164944D1bb6cb2785Fdf839666Ed4"
            }, {
                "itemType": 1,
                "token": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
                "identifierOrCriteria": 0,
                "startAmount": 125000000000000,
                "endAmount": 125000000000000,
                "recipient": "0x0000a26b00c1F0DF003000390027140000fAa719"
            }, {
                "itemType": 1,
                "token": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
                "identifierOrCriteria": 0,
                "startAmount": 500000000000000,
                "endAmount": 500000000000000,
                "recipient": "0x769c11a5a8Eb2032F149D3B70798a4eEA59C79aA"
            }
        ],
        "startTime": 1665431940,
        "endTime": 1665433736,
        "orderType": 2,
        "zone": "0x004C00500000aD104D7DBd00e3ae0A5C00560C00",
        "zoneHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "salt": "244468603027617",
        "conduitKey": "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000",
        "totalOriginalConsiderationItems": 3,
        "counter": 0
    }
}

data2['message']['zoneHash'] = bytes.fromhex(data2['message']['zoneHash'][2:])
data2['message']['conduitKey'] = bytes.fromhex(data2['message']['conduitKey'][2:])
account = Account.from_key("xxxx")
structured_msg = encode_structured_data(data)
signed = Account.sign_message(structured_msg, account.key)
recovered_address = Account.recover_message(structured_msg, signature=signed.signature)
assert recovered_address == account.address
```

error

```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    structured_msg = encode_structured_data(data2)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\messages.py", line 156, in encode_structured_data
    hash_eip712_message(structured_data),
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 260, in hash_message
    encode_data(
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 230, in encode_data
    type, value = encode_field(
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\eth_account\_utils\structured_data\hashing.py", line 218, in encode_field
    raise TypeError(
TypeError: Value of `salt` (24446860302761739304752683030156737591518664810215442929817238635507136356392) is not encodable as type `uint256`. If the base type is correct, verify that the value does not exceed the specified size for the type.
```

if i dont do this

data2['message']['zoneHash'] = bytes.fromhex(data2['message']['zoneHash'][2:])
data2['message']['conduitKey'] = bytes.fromhex(data2['message']['conduitKey'][2:])

then it crash on those 2 too

how to make signature for this

**Comment by kclowes** [comment]
The error message is telling you that your salt value is expected to be an integer, but you're passing it as a string. Closing, as it doesn't look like this is a bug.
