### ISSUE TITLE
TypeError: Transaction had invalid fields: {'to': '0x0d8ce2a99bb6e3b7db580ed848240e4a0f9ae153'}

### ISSUE THREAD

**Issue by woshidama323** [ethereum/web3.py#2728]
* Version: 3.51.2
* Python: 3.9
* OS: linux
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

Please include any of the following that are applicable:

description:
      when trying to sign with sign_transaction offline, I got such errors bellow:
      ```
      TypeError: Transaction had invalid fields: {'to': '0x0d8ce2a99bb6e3b7db580ed848240e4a0f9ae153'}
      ```

Here is the whole output
```shell
>>> stx = {'gasPrice': 5000000000, 'nonce': 431, 'to': '0x0d8ce2a99bb6e3b7db580ed848240e4a0f9ae153', 'value': 0, 'data': '0xa9059cbb0000000000000000000000002ff22e41447be8acadbfab0c95968263da15dd1a000000000000000000000000000000000000000000000000c3e3df74074f3f51', 'gas': 200000, 'chainId': 56}
>>> 
>>> import web3
>>> from web3.auto import w3
>>> w3.eth.account.sign_transaction(transaction_dict, "0x189bd618eea3d8aa9bd0f5f7ea20da73ff3a511a1adf2805c2d887a2ce82465a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'transaction_dict' is not defined
>>> w3.eth.account.sign_transaction(stx, "0x189bd618eea3d8aa9bd0f5f7ea20da73ff3a511a1adf2805c2d887a2ce82465a")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eth_account/account.py", line 748, in sign_transaction
    ) = sign_transaction_dict(account._key_obj, sanitized_transaction)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eth_account/_utils/signing.py", line 32, in sign_transaction_dict
    unsigned_transaction = serializable_unsigned_transaction_from_dict(transaction_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eth_account/_utils/legacy_transactions.py", line 44, in serializable_unsigned_transaction_from_dict
    assert_valid_fields(transaction_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/eth_account/_utils/legacy_transactions.py", line 114, in assert_valid_fields
    raise TypeError("Transaction had invalid fields: %r" % invalid)
TypeError: Transaction had invalid fields: {'to': '0x0d8ce2a99bb6e3b7db580ed848240e4a0f9ae153'}
```

But if i change the to field with "0xdd8ce2a99bb6e3b7db580ed848240e4a0f9ae153" (here i changed 0x0 to 0xd) 
It works well 

Guess the web3.py cannot handle such 0x0 prefix address well ?

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.
None
---
**Note:** We prefer to use issues to track our work. If you think you've encountered a bug in web3py or 
have a feature request, you're in the right place. If you have implementation or usage questions, 
please refer to our [documentation](https://web3py.readthedocs.io/en/latest/) and/or join the conversation 
on [discord](https://discord.gg/GHryRvPB84).

**Comment by kclowes** [comment]
Thanks for the report @woshidama323. We changed the private key you listed to `<private key>`, even though it doesn't look like the address associated with the PK has any assets. Don't use the address associated with that PK in the future.

It does look like this is a bug, but you can work around it by converting the to address to HexBytes before sending it:

```
>>> from hexbytes import HexBytes
>>> stx = {'gasPrice': 5000000000, 'nonce': 431, 'to': HexBytes(0x0d8ce2a99bb6e3b7db580ed848240e4a0f9ae153), ... }
```

I'm going to transfer this issue to the `eth-account` repo because I think that's where the actual issue is.
