### ISSUE TITLE
connection closed abnormally [internal]

### ISSUE THREAD

**Issue by danielpetrato** [ethereum/web3.py#2757]
Versão: 5.31.3
Python: 3.7.9
SO: windows
Blockchain: BNB

After a certain time my program returns this error and closes the connection, this happens with python, I did a test with javascript and this error does not occur

`Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 750, in transfer_data
    message = await self.read_message()
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 819, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 895, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 975, in read_frame
    extensions=self.extensions,
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\framing.py", line 55, in read
    data = await reader(2)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "teste_web3.py", line 370, in <module>
    main()
  File "teste_web3.py", line 363, in main
    log_loop(tx_filter, 2)))
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "teste_web3.py", line 351, in log_loop
    for event in event_filter.get_new_entries():
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\_utils\filters.py", line 160, in get_new_entries
    log_entries = self._filter_valid_entries(self.eth_module.get_filter_changes(self.filter_id))
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\module.py", line 60, in caller
    null_result_formatters)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\manager.py", line 150, in _make_request
    return request_func(method, params)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\middleware\gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\middleware\attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\middleware\formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\middleware\buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\providers\websocket.py", line 144, in make_request
    return future.result()
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\web3\providers\websocket.py", line 127, in coro_make_request
    timeout=self.websocket_timeout
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 442, in wait_for
    return fut.result()
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 471, in send
    await self.ensure_open()
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 726, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason`

**Comment by danielpetrato** [comment]
I'm trying to run this code and I want my program not to exit.

`async def log_loop(event_filter, poll_interval):
    while True:
        for event in event_filter.get_new_entries():
            handle_event(event)
        await asyncio.sleep(poll_interval)


def main():
    # filter for pending transactions
    tx_filter = web3.eth.filter({'fromBlock':'latest', 'address':'0x18B2A687610328590Bc8F2e5fEdDe3b582A49cdA'})
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(
            asyncio.gather(
                log_loop(tx_filter, 2)))
    finally:
        loop.close()


if __name__ == '__main__':
   
    main()`

**Comment by fselmo** [comment]
@danielpetrato, would be happy to re-open this issue if we see some improvements we can make. I think our websockets connection **can** use some improvements but we have prioritized the async providers as of late. Happy to review any PRs aimed at better handling of the websockets connection / re-connecting when dropped, otherwise we will try to get to this asap when we have more bandwidth.

One thing I'm curious about is trying to pass in ``ping_interval=None`` kwarg when setting up the `WebsocketProvider`.

```py
w3 = WebsocketProvider(provider_url, ping_interval=None)
```

Does this help the connection not time out in any way?
