### ISSUE TITLE
Error while using tkinter with web3.py

### ISSUE THREAD

**Issue by Jyo561Python** [ethereum/web3.py#2809]
* Version: x.x.x
* Python: 2.7/3.4/3.5
* OS: osx/linux/win
* `pip freeze` output

```
<put the output from running pip freeze here>
```

### What was wrong?

(((
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/web3/contract.py", line 1537, in call_contract_function
    output_data = web3.codec.decode(output_types, return_data)
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/eth_abi/codec.py", line 210, in decode
    return decoder(stream)
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/eth_abi/decoding.py", line 142, in decode
    start_pos = decode_uint_256(stream)
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/eth_abi/decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/loser34/pyne-projects/new-app/hello.py", line 9, in get_mood
    mood = contract.functions.getMood().call()
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/web3/contract.py", line 970, in call
    return call_contract_function(
  File "/home/loser34/pyne-projects/pynecone/lib/python3.9/site-packages/web3/contract.py", line 1554, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
)))

how to fix this error

**Comment by pacrob** [comment]
From the last line:

`web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?`

it appears that the issue is with your node or your connection to it, not with web3.py
We prefer to use issues for problems with the library itself, but you can check our our [Discord](https://discord.gg/GHryRvPB84) for help with usage questions.

**Comment by fselmo** [comment]
This actually looks like an error from an attempt to decode the contract call result. This doesn't seem like an issue with the library but if you have any more context I would try to post it on the Discord linked above. Best of luck.
