### ISSUE TITLE
Web3.py should return a exception if `trace_` endpoints are not available

### ISSUE THREAD

**Issue by Uxio0** [ethereum/web3.py#2914]
* Version: 6.1.0
* Python: 3.10
* OS: linux

### What was wrong?

When calling `w3.tracing.trace_filter()` on a node not supporting `trace_` methods (like Ganache), on versions `< 6` it was returning `ValueError("The method trace_filter does not exist/is not available")`, but currently is raising a not controlled exception on parsing the result.

For example `w3.tracing.trace_filter({"fromAddress": "0xEdC763b3e418cD14767b3Be02b667619a6374076"})`:
```
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/abi.py:769: in data_tree_map
    return recursive_map(map_to_typed_data, data_tree)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/decorators.py:30: in wrapped
    wrapped_val = to_wrap(*args)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/formatters.py:84: in recursive_map
    items_mapped = map_collection(recurse, data)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/formatters.py:68: in map_collection
    return datatype(map(func, collection))
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/formatters.py:82: in recurse
    return recursive_map(func, item)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/decorators.py:30: in wrapped
    wrapped_val = to_wrap(*args)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/formatters.py:84: in recursive_map
    items_mapped = map_collection(recurse, data)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/formatters.py:68: in map_collection
    return datatype(map(func, collection))
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/abi.py:792: in __new__
    return super().__new__(cls, *iterable)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/formatters.py:82: in recurse
    return recursive_map(func, item)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/decorators.py:30: in wrapped
    wrapped_val = to_wrap(*args)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/formatters.py:84: in recursive_map
    items_mapped = map_collection(recurse, data)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/formatters.py:68: in map_collection
    return datatype(map(func, collection))
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/formatters.py:82: in recurse
    return recursive_map(func, item)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/decorators.py:30: in wrapped
    wrapped_val = to_wrap(*args)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/formatters.py:85: in recursive_map
    return func(items_mapped)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/abi.py:765: in map_to_typed_data
    return ABITypedData(func(*elements))
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/normalizers.py:74: in wrapper
    modified = to_wrap(type_str, data)
../../../.virtualenvs/safe-eth-py/lib/python3.10/site-packages/web3/_utils/normalizers.py:197: in abi_address_to_hex
    validate_address(data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def validate_address(value: Any) -> None:
        """
        Helper function for validating an address
        """
        if is_not_address_string(value):
            if not is_valid_ens_name(value):
>               raise InvalidAddress(f"ENS name: '{value}' is invalid.")
E               web3.exceptions.InvalidAddress: ENS name: '0' is invalid.
```

The issue can be tested with Ganache, with this request:
```
{
   "method":"trace_filter",
   "params":[
      {
         "fromBlock":"0xccb943",
         "toBlock":"0xccb943",
         "fromAddress":[
            "0xEdC763b3e418cD14767b3Be02b667619a6374076"
         ]
      }
   ],
   "id":1,
   "jsonrpc":"2.0"
}
```

You get:
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "error": {
        "message": "The method trace_filter does not exist/is not available",
        "stack": "Error: The method trace_filter does not exist/is not available\n    at Executor.execute (/home/uxio/.config/yarn/global/node_modules/ganache/dist/node/1.js:2:164730)\n    at EthereumProvider._requestRaw (/home/uxio/.config/yarn/global/node_modules/ganache/dist/node/1.js:2:131539)\n    at Connector.<anonymous> (/home/uxio/.config/yarn/global/node_modules/ganache/dist/node/1.js:2:126027)\n    at Connector.handle (/home/uxio/.config/yarn/global/node_modules/ganache/dist/node/1.js:2:126511)\n    at /home/uxio/.config/yarn/global/node_modules/ganache/dist/node/1.js:2:154453",
        "code": -32700
    }
}
```

### How can it be fixed?

If RPC is not supporting trace methods, return the `ValueError` as previously

**Comment by kclowes** [comment]
Thanks for the report @Uxio0. I see what you mean. It looks to me like web3py is expecting the address(es) as a list, so a workaround for now might be to put the address in a list: 

`w3.tracing.trace_filter({"fromAddress": ["0xEdC763b3e418cD14767b3Be02b667619a6374076"]})`

But we'll try and fix this in the next few weeks.

**Comment by Uxio0** [comment]
Hi @kclowes , I didn't realize. It looks like a list would be the expected type so I guess implementation is correct: https://www.quicknode.com/docs/ethereum/trace_filter

We have a test for checking if tracing was not supported where we were using an address instead of a list, and as we were not parsing the inputs previously everything was working.

Feel free to close this if you think it's alright, sorry

**Comment by Uxio0** [comment]
@kclowes As I don't know where to ask, how could I easily use web3.py `result formatters` to parse a raw query? (We have a method for batching `trace_block` and I would like to refactor my code to stop using my formatter and use yours)

**Comment by kclowes** [comment]
> It looks like a list would be the expected type...Feel free to close this

It's still an error that doesn't make sense, so I'll leave it open. 

>  As I don't know where to ask, how could I easily use web3.py result formatters to parse a raw query?

It depends on how you're doing it, but we have the ability to add custom methods to the different modules. Check out Section 2. "Custom Methods" of [this blog post](https://snakecharmers.ethereum.org/web3-py-patterns-customizations/). You can add a new method to the tracing module and then pass in whatever result formatters you want. Otherwise, you could use some custom middleware, or a combination of the two. We all hang around the web3py [discord channel](https://discord.gg/GHryRvPB84) too if you have other usage questions!

**Comment by Uxio0** [comment]
Thanks for the feedback. My question was more on the line of reusing your formatters for our custom RPC Batch calls, but I will figure out a way 😉 

Also there's an error on the result formatter. For `reward` type of traces `author` is not ERC55 encoded, e.g.

`AttributeDict({'action': AttributeDict({'author': '0x5a0b54d5dc17e0aadc383d2db43b0a0d3e029c4c', 'rewardType': 'block', 'value': 2000000000000000000}), 'blockHash': HexBytes('0x8f9809f6012f85803956a419e2e54914dfdebba33e4f7a0d1574b12e92499c0e'), 'blockNumber': 13191781, 'result': None, 'subtraces': 0, 'traceAddress': [], 'type': 'reward'})`
