### ISSUE TITLE
IPCProvider timeout paramater

### ISSUE THREAD

**Issue by userpasta** [ethereum/web3.py#309]
* Version: 3.13.5
* Python: 2.7
* OS: Ubuntu 16.04

### What was wrong?
A request has timed out.

Please include any of the following that are applicable:
* The code which produced the error
`web3.manager.request_blocking('parity_pendingTransactions', [])`
* The full output of the error
`
Traceback (most recent call last):
  File "/home/user/clone/mempool/eth.py", line 78, in get_mempool
    'parity_pendingTransactions', []
  File "/home/user/.virtualenvs/prune/local/lib/python2.7/site-packages/web3/manager.py", line 112, in request_blocking
    response = self._make_request(method, params)
  File "/home/user/.virtualenvs/prune/local/lib/python2.7/site-packages/web3/manager.py", line 95, in _make_request
    return make_request_fn(method, params)
  File "/home/user/.virtualenvs/prune/local/lib/python2.7/site-packages/web3/middleware/attrdict.py", line 20, in middleware
    response = make_request(method, params)
  File "/home/user/.virtualenvs/prune/local/lib/python2.7/site-packages/web3/middleware/formatting.py", line 25, in middleware
    response = make_request(method, params)
  File "/home/user/.virtualenvs/prune/local/lib/python2.7/site-packages/web3/providers/ipc.py", line 103, in make_request
    timeout.sleep(0)
  File "/home/user/.virtualenvs/prune/local/lib/python2.7/site-packages/web3/utils/compat/compat_stdlib.py", line 74, in sleep
    self.check()
  File "/home/user/.virtualenvs/prune/local/lib/python2.7/site-packages/web3/utils/compat/compat_stdlib.py", line 67, in check
    raise self
Timeout: 10 seconds`
* What type of node you were connecting to
Parity

### How can it be fixed?
Add timeout parameter to IPCProvider class to be able to retry sooner, when a timeout occurs. Right know 10 seconds timeout is hardcoded:  https://github.com/pipermerriam/web3.py/blob/master/web3/providers/ipc.py

**Comment by carver** [comment]
Are you seeing 10s timeouts followed by successful lookups on retry?

**Comment by userpasta** [comment]
I have no way to verify as, but will check it, if it happens again.

**Comment by sbaks0820** [comment]
Is there already a pull request or a specific branch that has the timeout included?

**Comment by pipermerriam** [comment]
@sbaks0820 no, this hasn't been done but it should be a small change if you'd like to give it a go.
