### ISSUE TITLE
UnicodeDecodeError when importing web3 to python

### ISSUE THREAD

**Issue by choesy** [ethereum/web3.py#3142]
* Version: 6.11.2
* Python: 3.10.11
* OS: win 11
* `pip freeze` output

```
aiohttp==3.8.6
aiosignal==1.3.1
async-timeout==4.0.3
attrs==23.1.0
bitarray==2.8.2
certifi==2023.7.22
charset-normalizer==3.3.2
cytoolz==0.12.2
eth-abi==4.2.1
eth-account==0.10.0
eth-hash==0.5.2
eth-keyfile==0.6.1
eth-keys==0.4.0
eth-rlp==0.3.0
eth-typing==3.5.1
eth-utils==2.3.0
frozenlist==1.4.0
hexbytes==0.3.1
idna==3.4
jsonschema==4.19.2
jsonschema-specifications==2023.7.1
lru-dict==1.3.0
multidict==6.0.4
parsimonious==0.9.0
protobuf==4.25.0
pycryptodome==3.19.0
pyunormalize==15.0.0
pywin32==306
referencing==0.30.2
regex==2023.10.3
requests==2.31.0
rlp==3.0.0
rpds-py==0.12.0
toolz==0.12.0
typing_extensions==4.8.0
urllib3==2.0.7
web3==6.11.2
websockets==12.0
yarl==1.9.2
```

### What was wrong?
The code wont run, it produces an error when just importing web3 library in main.py, i am using virtualenv on windows.
* The code which produced the error
When calling import web3
```
import web3
```
* The full output of the error
```
(.venv) PS C:\Users\aleks\Desktop\TestMlblockchain\gym_states> python .\main.py
Traceback (most recent call last):
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\main.py", line 1, in <module>
    from web3 import Web3
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\.venv\lib\site-packages\web3\__init__.py", line 1, in <module>
    from eth_account import Account  # noqa: E402,
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\.venv\lib\site-packages\eth_account\__init__.py", line 1, in <module>
    from eth_account.account import (
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\.venv\lib\site-packages\eth_account\account.py", line 20, in <module>
    from eth_keyfile import (
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\.venv\lib\site-packages\eth_keyfile\__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\.venv\lib\site-packages\eth_keyfile\keyfile.py", line 11, in <module>
    from eth_keys import keys
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\.venv\lib\site-packages\eth_keys\__init__.py", line 15, in <module>
    from .main import (  # noqa: F401
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\.venv\lib\site-packages\eth_keys\main.py", line 3, in <module>
    from eth_utils import (
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\.venv\lib\site-packages\eth_utils\__init__.py", line 86, in <module>
    from .network import (
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\.venv\lib\site-packages\eth_utils\network.py", line 49, in <module>
    networks = initialize_network_objects()
  File "C:\Users\aleks\Desktop\TestMlblockchain\gym_states\.venv\lib\site-packages\eth_utils\network.py", line 27, in initialize_network_objects
    network_data = json.load(open_file)
  File "C:\Users\aleks\.pyenv\pyenv-win\versions\3.10.11\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\aleks\.pyenv\pyenv-win\versions\3.10.11\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 247555: character maps to <undefined>

```
* What type of node you were connecting to.
None

---

**Comment by choesy** [comment]
I tryed to uninstall web3, then using "pip purge cache" and installing web3 again. But not working

**Comment by fselmo** [comment]
Thanks for reporting @choesy. This was stemming from another library which just had a patch release to attempt to fix this issue. Uninstalling web3.py and re-installing now would work. Or, please attempt to update *eth-utils* via `pip install -U eth-utils` (and, if you'd like to also silence some related warnings, `pip install -U eth-typing`).

Please report back whether that fixed the issue for you or not if you can 😃 .

**Comment by choesy** [comment]
Thank you, now it works :)

**Comment by fselmo** [comment]
Happy to hear it. Thanks for reporting back! 👍🏼
