### ISSUE TITLE
Watch contract events by given contract addr

### ISSUE THREAD

**Issue by msoedov** [ethereum/web3.py#377]
* Version: web3==3.16.1
* Python: 3.5
* OS: osx

Is there a good way to init contract from address and subscribe to it's events? 

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
```
def tranfer(*a, **kw):
    print("T>: {0}".format(a, kw)

con = web3.eth.contract(address="0x60d8c3f099468e46591f8947a7515600a590e877").on('Transfer', {}, tranfer)

con.watch(tranfer)

```
* The full output of the error

```
Traceback (most recent call last):
  File "app.py", line 27, in <module>
    filter_params={})
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/utils/decorators.py", line 13, in _wrapper
    return self.method(obj, *args, **kwargs)
           │           │     │       └ {'filter_params': {}}
           │           │     └ ('Transfer',)
           │           └ <web3.contract.Contract object at 0x10a0d8fd0>
           └ <web3.utils.decorators.combomethod object at 0x10a049d30>
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/contract.py", line 299, in on
    argument_filter_names,
    └ []
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/contract.py", line 597, in _find_matching_event_abi
    event_abi_candidates = filter_fn(cls.abi)
                           │         └ <class 'web3.contract.Contract'>
                           └ <toolz.functoolz.Compose object at 0x10a0ef240>
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/toolz/functoolz.py", line 466, in __call__
    ret = self.first(*args, **kwargs)
          │           │       └ {}
          │           └ (None,)
          └ <toolz.functoolz.Compose object at 0x10a0ef240>
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/utils/abi.py", line 97, in filter_by_argument_name
    for abi in contract_abi
TypeError: 'NoneType' object is not iterable
```

* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by carver** [comment]
We're looking forward to filters becoming more reliable with: #346 which is a work in progress implementation of #294 .

Several issues have been linked to that one now, for an idea of what other people have tried and come up with as workarounds. In particular, see #230

**Comment by pipermerriam** [comment]
closing this as the filter API has been reworked.  Please re-open or re-submit a new issue if you are still having issues.
