### ISSUE TITLE
Example code failed to run

### ISSUE THREAD

**Issue by tam0202** [ethereum/web3.py#467]
* Version: web3@3.6.13, py-solc@2.0.0
* Python: 3.6.3
* OS: linux

### What was wrong?
Example code given in README resulted in "no such file" error on compile_source
* The full output of the error:
`Traceback (most recent call last):
File "example.py", line 29, in <module>
    compiled_sol = compile_source(contract_source_code) # Compiled source code
  File "/usr/local/lib/python3.6/site-packages/solc/main.py", line 106, in compile_source
    stdoutdata, stderrdata, command, proc = solc_wrapper(**compiler_kwargs)
  File "/usr/local/lib/python3.6/site-packages/solc/utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/solc/wrapper.py", line 155, in solc_wrapper
    stderr=subprocess.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'solc': 'solc'`

**Comment by carver** [comment]
Thanks. You must install `solc` for `py-solc` to work.  I opened an issue to clarify the error message in py-solc.

To install solc, try `python -m solc.install v0.4.17` or see http://solidity.readthedocs.io/en/latest/installing-solidity.html
