### ISSUE TITLE
eth-keyfile/ethereum-keyfile dependency issue?

### ISSUE THREAD

**Issue by rishflab** [ethereum/web3.py#509]
* Version: 4.0.0b4
* Python: 3.6
* OS: osx

code:
`from web3.auto import w3
acct = w3.eth.account.create()`

error:
`/Users/rishabintern/db3/bin/python /Users/rishabintern/PycharmProjects/db3py/blockchain.py
Traceback (most recent call last):
  File "/Users/rishabintern/PycharmProjects/db3py/blockchain.py", line 5, in <module>
    from web3.auto import w3
  File "/Users/rishabintern/db3/lib/python3.6/site-packages/web3/__init__.py", line 7, in <module>
    from web3.account import Account  # noqa: E402
  File "/Users/rishabintern/db3/lib/python3.6/site-packages/web3/account.py", line 11, in <module>
    from eth_keyfile import (
  File "/Users/rishabintern/db3/lib/python3.6/site-packages/eth_keyfile/__init__.py", line 2, in <module>
    "This library has been renamed to `eth-keyfile`.  The `ethereum-keyfile` "
DeprecationWarning: This library has been renamed to `eth-keyfile`.  The `ethereum-keyfile` package will no longer recieve updates.  Please update your dependencies accordingly.

Process finished with exit code 1
`

Is this due to something I have done wrong?

**Comment by ChrisRut** [comment]
I am also seeing this, I think the issue is `eth-keyfile` is not properly pinned to a specific version: https://github.com/ethereum/web3.py/blob/master/setup.py#L22

So it changed out from underneath this project.

**Comment by pipermerriam** [comment]
@rishflab try:

```
pip uninstall ethereum-keyfile
pip install eth-keyfile
```

@ChrisRut I don't believe that's related.  This appears to be due to the renaming of the python module.

@rishflab re-open if you're still having this issue.

**Comment by ChrisRut** [comment]
I confirmed pinning the version of eth-keyfile in setup.py fixed it for me: https://github.com/ChrisRut/web3.py/commit/a6634c565f7f5f5cfa06b50a0bd58525d785b3a3

**Comment by shawnpringle** [comment]
2018, September.  I can install web3.py but when I import web3, I get the following exception:
```
Python 3.6.0 (default, Jul  7 2018, 17:42:42) 
[GCC 4.8.5] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import web3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alumno/development/web3.py/web3/__init__.py", line 16, in <module>
    from eth_account import Account  # noqa: E402
  File "/usr/local/lib/python3.6/site-packages/eth_account-0.3.0-py3.6.egg/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/eth_account-0.3.0-py3.6.egg/eth_account/account.py", line 10, in <module>
    from eth_keyfile import (
  File "/usr/local/lib/python3.6/site-packages/eth_keyfile-0.5.1-py3.6.egg/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/eth_keyfile-0.5.1-py3.6.egg/eth_keyfile/keyfile.py", line 7, in <module>
    from Crypto.Protocol.KDF import scrypt
ImportError: cannot import name 'scrypt'
>>> quit();
```
