### ISSUE TITLE
Could not decode contract function call transfer return data 0x for output_types ['bool']

### ISSUE THREAD

**Issue by aaronluoq** [ethereum/web3.py#518]
* Version: 3.16.4
* Python: Python 3.6.3
* OS: osx
* geth:1.7.2-stable-1db4ecdc

### What was wrong?

in local chain:
```
c = web3.eth.contract(address='0xBF523Cb09b67540d2B06a3E376624122e7649c63',abi=json.loads(abi_js))

>>> c.call().transfer('0xD9B8B44Cc2D153A0052Ce7D0A7a450DFe893e066',100000)
Traceback (most recent call last):
  File "/Users/aaronluo/test/blockchain/ethereum/py36/lib/python3.6/site-packages/web3/contract.py", line 844, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/Users/aaronluo/test/blockchain/ethereum/py36/lib/python3.6/site-packages/eth_abi/abi.py", line 109, in decode_abi
    return decoder(stream)
  File "/Users/aaronluo/test/blockchain/ethereum/py36/lib/python3.6/site-packages/eth_abi/decoding.py", line 102, in __call__
    return self.decode(stream)
  File "/Users/aaronluo/test/blockchain/ethereum/py36/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/aaronluo/test/blockchain/ethereum/py36/lib/python3.6/site-packages/eth_abi/decoding.py", line 140, in decode
    yield decoder(stream)
  File "/Users/aaronluo/test/blockchain/ethereum/py36/lib/python3.6/site-packages/eth_abi/decoding.py", line 102, in __call__
    return self.decode(stream)
  File "/Users/aaronluo/test/blockchain/ethereum/py36/lib/python3.6/site-packages/eth_abi/decoding.py", line 165, in decode
    raw_data = cls.read_data_from_stream(stream)
  File "/Users/aaronluo/test/blockchain/ethereum/py36/lib/python3.6/site-packages/eth_abi/decoding.py", line 247, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronluo/test/blockchain/ethereum/py36/lib/python3.6/site-packages/web3/contract.py", line 866, in call_contract_function
    raise_from(BadFunctionCallOutput(msg), e)
  File "/Users/aaronluo/test/blockchain/ethereum/py36/lib/python3.6/site-packages/web3/utils/exception_py3.py", line 2, in raise_from
    raise my_exception from other_exception
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call transfer return data 0x for output_types ['bool']
```

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.
thx

**Comment by carver** [comment]
Sometimes this can happen when your contract throws an exception during the call.

- Maybe '0xD9B8B44Cc2D153A0052Ce7D0A7a450DFe893e066' doesn't have 100000 tokens to send? - It could also happen if you have the wrong ABI

Most times we get a report like this, it means that someone's contract isn't behaving like they expected.

**Comment by jasonrhaas** [comment]
I am also seeing this error message, but only on Ropsten.  The contract code works fine on the testrpc, but as soon as I switch to the contract deployed on Ropsten, everything returns `b''`

**Comment by adamyala** [comment]
I'm encountering the same issue on Rinkeby. Testing on Remix works fine, but the contract calls on the testnet are acting up.

**Comment by jasonrhaas** [comment]
@adamyala Check that you have the right contract address, as defined in your contract json file under the `networks` section.

**Comment by adamyala** [comment]
@jasonrhaas I figured out my issue.

For anyone else who was brought here via google, it's possible that your contract is failing when generating the data to send in the transaction.

For example, my smart contract is:
```
pragma solidity ^0.4.25;

contract Points {

  address public owner = msg.sender;
  mapping (bytes32 => uint8) public pointsEarned;

  function isOwner() public view returns (bool) {
      return msg.sender == owner;
  }

  function getPoints(bytes32 username) public view returns (uint8) {
    return pointsEarned[username];
  }

  function setPoints(bytes32 username, uint8 points) public returns (uint8) {
    assert(isOwner());
    pointsEarned[username] = points;
    return pointsEarned[username];
  }

}
```

When I triggered the error, I was using:
```
        contract_function = contract_instance.functions.setPoints(username, points)
        transaction_details = contract_function.buildTransaction()
```
`buildTransaction` has no params so the contract assumes I am not the owner. This also returns no bytes and I saw the above error.

If I use
```
        contract_function = contract_instance.functions.setPoints(username, points)
        # wallet_address is the owner of the contract
        transaction_details = contract_function.buildTransaction({'from': wallet_address})
```
instead, then the `isOwner` assertion passes the function call works well.

**Comment by agatsoh** [comment]
Any news on whether someone is assigned on this issue or working on it !!!

**Comment by kclowes** [comment]
Closing - Looks like this was resolved and it's very old.
