### ISSUE TITLE
ConciseContract does not allow interfacing with methods through standard API

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#521]
* Version: 0.3.x and 0.4.x

### What was wrong?

```python
# This works:
print(gnt.balanceOf(GNT_ADDR))
# This does not:
print(gnt.call({'from': web3.eth.coinbase}).balanceOf(GNT_ADDR))
```

The later produces this error:

```python
Traceback (most recent call last):
  File "./check.py", line 20, in <module>
    print(gnt.call({'from': web3.eth.coinbase}).balanceOf(GNT_ADDR))
  File ".../lib/python3.5/site-packages/web3/contract.py", line 805, in __call__
    return self.__prepared_function(**kwargs)(*args)
  File ".../lib/python3.5/site-packages/web3/contract.py", line 834, in call_contract_function
    transaction=transaction,
  File ".../lib/python3.5/site-packages/web3/utils/decorators.py", line 17, in _wrapper
    return self.method(obj, *args, **kwargs)
  File ".../lib/python3.5/site-packages/web3/contract.py", line 695, in _prepare_transaction
    fn_kwargs,
  File ".../lib/python3.5/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File ".../lib/python3.5/site-packages/web3/contract.py", line 734, in _encode_transaction_data
    fn_name, args, kwargs,
  File ".../lib/python3.5/site-packages/web3/contract.py", line 663, in _get_function_info
    fn_abi = cls._find_matching_fn_abi(fn_name, args, kwargs)
  File ".../lib/python3.5/site-packages/web3/contract.py", line 627, in _find_matching_fn_abi
    raise ValueError("No matching functions found")
ValueError: No matching functions found
```

The error occurs because `ConciseContract` tries to lookup a function named `call`.

### How can it be fixed?

The `ConciseContract` class should be augmented such that the `__getattr__` method will return the existing attribute on the contract class if present, only falling back to the contract method if no attribute by the requested name exists.

**Comment by carver** [comment]
Hm, I don't like the idea of introducing namespace conflicts to the API.

It is possible to accomplish this in the current API. The intended way to specify call values in `ConciseContract` is:

```py
gnt.balanceOf(GNT_ADDR, call={'from': web3.eth.coinbase})
```

So my first preference is to close as won't fix. Thoughts?
