### ISSUE TITLE
Warn on specific missing fields from w3.eth.account.signTransaction

### ISSUE THREAD

**Issue by HenryHoggard** [ethereum/web3.py#560]
* Version: v4.0.0-beta5
*  Python: 3.5
*  OS: linux

I'm trying to test the new API to build, sign and broadcast a raw transaction, could anyone have a look at this error? 

### Code

```
from web3 import Web3
import json
import web3
from web3.providers.rpc import HTTPProvider
contractAddress = '0xaddress'
web3 = Web3(HTTPProvider('https://mainnet.infura.io/metamask'))
key = b'\x00'


with open('test.abi', 'r') as abi_definition:
    abi = json.load(abi_definition)
print (web3.eth.blockNumber)

address = web3.toChecksumAddress("0xaddress")
fContract = web3.eth.contract(address=contractAddress, abi=abi)
tx = fContract.buildTransaction({'gasPrice': 2000000000, 'gas':200000}).test(_value=20000000000)
signed = web3.eth.account.signTransaction(tx,key)
#signed = web3.eth.account.signTransaction(transaction_dict=tx,private_key=key)

print (signed)
final = web3.eth.sendRawTransaction(signed.rawTransaction)
print (final)
```

### Error

```
    signed = web3.eth.account.signTransaction(tx,key)
  File "/usr/local/lib/python3.5/dist-packages/web3-4.0.0b5-py3.5.egg/web3/utils/decorators.py", line 14, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3-4.0.0b5-py3.5.egg/web3/account.py", line 167, in signTransaction
    ) = sign_transaction_dict(account._key_obj, transaction_dict)
  File "/usr/local/lib/python3.5/dist-packages/web3-4.0.0b5-py3.5.egg/web3/utils/signing.py", line 28, in sign_transaction_dict
    unsigned_transaction = serializable_unsigned_transaction_from_dict(web3, transaction_dict)
  File "/usr/local/lib/python3.5/dist-packages/web3-4.0.0b5-py3.5.egg/web3/utils/transactions.py", line 51, in serializable_unsigned_transaction_from_dict
    return serializer.from_dict(filled_transaction)
  File "/usr/local/lib/python3.5/dist-packages/web3-4.0.0b5-py3.5.egg/web3/utils/encoding.py", line 276, in from_dict
    return cls(**field_dict)
  File "/usr/local/lib/python3.5/dist-packages/rlp-0.6.0-py3.5.egg/rlp/sedes/lists.py", line 181, in __init__
    raise TypeError('Not all fields initialized')
TypeError: Not all fields initialized
```

**Comment by HenryHoggard** [comment]
Solved, I didn't include the "nonce" value in the tx dict.

**Comment by carver** [comment]
Reopening as a reminder to check for and list the missing fields, at the beginning of `signTransaction`.

**Comment by wong2** [comment]
maybe the error could include info about which fields are missing?

**Comment by cryptomental** [comment]
Hi! I was looking around what is inside this project and found this issue.
I experimented yesterday with schemas and this is what I came up with:

```
from schema import Schema, And, Use, Regex, SchemaError


transaction_schema = Schema({'to': And(Regex('^0x\w{40}$'),
                                       error='Invalid address. Use 0x... 42-character string'),
                             'value': And(Use(int), lambda n: n > 0),
                             'gas': And(Use(int), lambda n: n > 0),
                             'gasPrice': And(Use(int), lambda n: n > 0),
                             'nonce': And(Use(int), lambda n: n >= 0),
                             'chainId': And(Use(int), lambda n: n > 0)})

transaction_complete = {
                'to': '0xF0109fC8DF283027b6285cc889F5aA624EaC1F55',
                'value': 1000000000,
                'gas': 2000000,
                'gasPrice': 234567897654321,
                'nonce': 0,
                'chainId': 1
            }

transaction_incomplete = {
                'to': '0xF0109fC8DF283027b6285cc889F5aA624EaC1F55',
                'value': 1000000000,
                'gas': 2000000,
                'gasPrice': 234567897654321,
                'chainId': 1
            }

transaction_bad_address = {
                'to': '0iF0109fC8DF283027b6285cc889F5aA624EaC1F55',
                'value': 1000000000,
                'gas': 2000000,
                'gasPrice': 234567897654321,
                'nonce': 0,
                'chainId': 1
            }

transaction_negative_gas = {
                'to': '0xF0109fC8DF283027b6285cc889F5aA624EaC1F55',
                'value': 1000000000,
                'gas': 2000000,
                'gasPrice': 234567897654321,
                'nonce': 0,
                'chainId': 1
            }

transaction_bad_value_type = {
                'to': '0xF0109fC8DF283027b6285cc889F5aA624EaC1F55',
                'value': [1000000000],
                'gas': 2000000,
                'gasPrice': 234567897654321,
                'nonce': 0,
                'chainId': 1
            }

transactions = [transaction_complete,
                transaction_incomplete,
                transaction_bad_address,
                transaction_negative_gas,
                transaction_bad_value_type]

for transaction in transactions:
    try:
        transaction_schema.validate(transaction)
    except SchemaError as e:
        # error handling here
        print("Transaction validation error: %s" % e)

assert transaction_schema == transaction_incomplete
```

There are two ways to use schemas, either call validate() or assert. Out of the five transactions above, four are not valid and this is detected:

```
Transaction validation error: Missing keys: 'nonce'
Transaction validation error: Invalid address. Use 0x... 42-character string
Transaction validation error: Key 'value' error:
int([1000000000]) raised TypeError("int() argument must be a string, a bytes-like object or a number, not 'list'",)
Traceback (most recent call last):
  File "schemas.py", line 69, in <module>
    assert transaction_schema == transaction_incomplete
AssertionError
```

I think that this solution could be applied not only to transaction dict but to other types as well.
Please let me know if this approach would work here and if so where to put schema definitions, likely a new schemas.py or perhaps an already existing file.

**Comment by pipermerriam** [comment]
I'm not sure that we need a full dependency for this.  The validators that we need are mostly either already written or very easy to write.

- to: `eth_utils.is_checksum_address`
- nonce, gas, gas_price, value: `eth_utils.is_integer`, `0 <= value < 2**256 - 1`
- data: `eth_utils.is_hex`
- chainid: ??? but should be simple integer validation.

**Comment by cryptomental** [comment]
@pipermerriam that was just a proposal. About the library dependency, according to https://pypi.python.org/pypi/schema/ "you can just drop schema.py file into your project—it is self-contained.". But anyway if validators are available in the eth_utils already, then indeed schema may not be needed.

**Comment by carver** [comment]
In the process of moving the Account module to another repo, so removing the [Good First Issue] tag. This issue should be ported there once the move is complete.

**Comment by marcgarreau** [comment]
Quick test shows this has been implemented.
