### ISSUE TITLE
Function returns 0x when I want  to read a larger amount of data

### ISSUE THREAD

**Issue by pseudogelb** [ethereum/web3.py#607]
* Version:4.0.0
* Python: 3.6
* OS: win

I have some issues to read out a larger amount of data with web3.py. I made a test contract, which has functions that return array of different sizes, one a uint8 250'000 array and one a 1'000'000 sized array. Both functions work fine in remix.ethereum.org, but when I use web3.py, I can only read out the 250'000 uint8 sized array, the other returns always a 0x error. I also tried to increase the gas limit, but this didn't solve it either. Any ideas/suggestions what could be done here? In the end I need to read out a array of size 10Mio uint8 values.

#My Python Code:
```
import json
from web3 import Web3, HTTPProvider

w3 = Web3(HTTPProvider('https://ropsten.infura.io'))

contractAddress = '0x90c892a89daf937dd4c150120469c4eb146f164c'

with open('testfactory.json', 'r') as abi_definition:
    abi = json.load(abi_definition)

transaction = {'gas': 0x1000000000000}

contract_inst=w3.eth.contract(contractAddress, abi=abi)

print(contract_inst.call(transaction).getValue2()) # works fine
print(contract_inst.call(transaction).getValue1()) #returns 0x`
```

#My testfactory.json:
```
[
	{
		"constant": true,
		"inputs": [],
		"name": "getValue1",
		"outputs": [
			{
				"name": "",
				"type": "uint8[1000000]"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"constant": true,
		"inputs": [],
		"name": "getValue2",
		"outputs": [
			{
				"name": "",
				"type": "uint8[250000]"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "constructor"
	}
]
```

#My solidity contract:
```
pragma solidity ^0.4.19;


contract TestContract {

   uint8 [1000000] val;
   uint8 [250000] val2;


   function TestContract(){

   }

   function getValue1()  external view returns(uint8 [1000000]){
         return val;
   }
   
   function getValue2()  external view returns(uint8 [250000]){
         return val2;
   }

}
```
#Error code in python:
```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\web3\contract.py", line 844, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "C:\Python36\lib\site-packages\eth_abi\abi.py", line 109, in decode_abi
    return decoder(stream)
  File "C:\Python36\lib\site-packages\eth_abi\decoding.py", line 102, in __call__
    return self.decode(stream)
  File "C:\Python36\lib\site-packages\eth_utils\functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "C:\Python36\lib\site-packages\eth_abi\decoding.py", line 140, in decode
    yield decoder(stream)
  File "C:\Python36\lib\site-packages\eth_abi\decoding.py", line 102, in __call__
    return self.decode(stream)
  File "C:\Python36\lib\site-packages\eth_utils\functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "C:\Python36\lib\site-packages\eth_abi\decoding.py", line 198, in decode
    yield cls.item_decoder(stream)
  File "C:\Python36\lib\site-packages\eth_abi\decoding.py", line 102, in __call__
    return self.decode(stream)
  File "C:\Python36\lib\site-packages\eth_abi\decoding.py", line 165, in decode
    raw_data = cls.read_data_from_stream(stream)
  File "C:\Python36\lib\site-packages\eth_abi\decoding.py", line 247, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/Sebi/PycharmProjects/web3/test.py", line 18, in <module>
    print(contract_inst.call(transaction).getValue1()) #returns 0x
  File "C:\Python36\lib\site-packages\web3\contract.py", line 866, in call_contract_function
    raise_from(BadFunctionCallOutput(msg), e)
  File "C:\Python36\lib\site-packages\web3\utils\exception_py3.py", line 2, in raise_from
    raise my_exception from other_exception
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call getValue1 return data 0x for output_types ['uint8[1000000]']
```

**Comment by dylanjw** [comment]
The gas cost of your arrays are extremely high.

The memory cost function is ((memory fee * word size + (word size**2/512)) where the memory fee is 3 gas, and the word size for your 8uint array is 1,000,000.

3 * 1,000,000 + 1,000,000**2 / 512 = 1,956,125,000 gas

with an average gas price of 22gwei, creating that array will cost roughly 42 ether.

It looks like you are testing on the ropstein network.  I would hazard a guess that you are either exceeding the sender account balance or the gas limit.

**Comment by pipermerriam** [comment]
I suspect this is due to exceeding the gas limit for the `eth_call` but my intuition says you should have received an error during execution rather than getting a `0x` as your return data.  Will need to do some further investigating to see what's going on.  @dylanjw if you get a chance, can you try making the raw `eth_call` using `web3.manager.request_blocking('eth_call', [{<the-prepared-transaction-for-making-the-call>}])` and seeing what the raw return value is?  Alternatively, I'd be curious to see what web3.js does, assuming infura is actually returning `0x`.

**Comment by dylanjw** [comment]
Im getting a "missing value" error.  Is something missing from the transaction json?

```
>>> contract.functions.getValue1().buildTransaction(){'value': 0, 'gas': 4712388, 'gasPrice': 20000000000, 'chainId': 3, 'to': '0x90C892a89daf937dD4c150120469c4EB146F164c', 'data': '0x60d586f8'}
>>> w3.manager.request_blocking('eth_call', [{'value': 0, 'gas': 4712388, 'gasPrice': 20000000000, 'chainId': 3, 'to': '0x90C892a89daf937dD4c150120469c4EB146F164c', 'data': '0x60d586f8'}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dwilson/Develop/Projects/ethereum/web3.py/web3/manager.py", line 102, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32602, 'message': 'missing value for required argument 1'}
>>> 
```

**Comment by pseudogelb** [comment]
I don't know what should be missing here, I posted all the code and also the .json I used for this test project. Can you call getValue2(), the function that works fine with web3.py?

**Comment by dylanjw** [comment]
@pseudogelb the call to getValue2() over infura with web3.py works as you have stated.  In my previous comment, I was trying to build and send the call to getValue1() as raw transaction to get more information.  The error is likely due to a mistake Im making, and not related to the primary issue.

Following @pipermerriam suggestion of trying this in web3.js, getValue1() returns `0x` just as in the web3.py implementation.  Here is the code I used:

```javascript
var Web3 = require('web3');
const solc = require('solc');
const fs = require('fs');


var source = {"array.sol": 
"pragma solidity ^0.4.19; contract TestContract { uint8 [1000000] val; uint8 [250000] val2; function TestContract(){ } function getValue1()  external view returns(uint8 [1000000]){ return val; } function getValue2()  external view returns(uint8 [250000]){ return val2; } }"};


var web3 = new Web3(Web3.givenProvider || "https://ropsten.infura.io");

const output = solc.compile({sources: source}, 1);
const abi = JSON.parse(output.contracts['array.sol:TestContract'].interface);

contractAddress = '0x90C892a89daf937dD4c150120469c4EB146F164c';
contract = new web3.eth.Contract(abi, contractAddress);

contract.methods.getValue2().call();
contract.methods.getValue1().call();
```

And the resulting error:

```
Unhandled rejection Error: Couldn't decode uint8 from ABI: 0x
    at SolidityTypeUInt.formatOutputUInt [as _outputFormatter] (/home/dwilson/Develop/Eth/contract_testing/node_modules/web3-eth-abi/src/formatters.js:174:15)
    at SolidityTypeUInt.SolidityType.decode (/home/dwilson/Develop/Eth/contract_testing/node_modules/web3-eth-abi/src/type.js:252:17)
    at /home/dwilson/Develop/Eth/contract_testing/node_modules/web3-eth-abi/src/type.js:234:34
    at SolidityTypeUInt.SolidityType.decode (/home/dwilson/Develop/Eth/contract_testing/node_modules/web3-eth-abi/src/type.js:238:11)
    at /home/dwilson/Develop/Eth/contract_testing/node_modules/web3-eth-abi/src/index.js:327:49
    at Array.forEach (<anonymous>)
    at ABICoder.decodeParameters (/home/dwilson/Develop/Eth/contract_testing/node_modules/web3-eth-abi/src/index.js:326:13)
    at Contract._decodeMethodReturn (/home/dwilson/Develop/Eth/contract_testing/node_modules/web3-eth-contract/src/index.js:459:22)
    at Method.outputFormatter (/home/dwilson/Develop/Eth/contract_testing/node_modules/web3-eth-contract/src/index.js:811:46)
    at Method.formatOutput (/home/dwilson/Develop/Eth/contract_testing/node_modules/web3-core-method/src/index.js:162:54)
    at sendTxCallback (/home/dwilson/Develop/Eth/contract_testing/node_modules/web3-core-method/src/index.js:453:33)
    at /home/dwilson/Develop/Eth/contract_testing/node_modules/web3-core-requestmanager/src/index.js:144:9
    at XMLHttpRequest.request.onreadystatechange (/home/dwilson/Develop/Eth/contract_testing/node_modules/web3-providers-http/src/index.js:77:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/dwilson/Develop/Eth/contract_testing/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/dwilson/Develop/Eth/contract_testing/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/dwilson/Develop/Eth/contract_testing/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/dwilson/Develop/Eth/contract_testing/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

My best guess is that infura puts limitations on what can be run on the client EVM with eth_call, and upon hitting that limit returns 0x instead of a more descriptive error.

**Comment by dylanjw** [comment]
@pseudogelb There is a new issue open on INFURA similar to your situation:  https://github.com/INFURA/infura/issues/70.  I would be interested in what they say.  Im closing this because I see no actionable way to detect when a call with large return values will fail.
