### ISSUE TITLE
Traceback when sending transaction without nonce

### ISSUE THREAD

**Issue by palango** [ethereum/web3.py#613]
* Version: 4.0.0b7
* Python: 3.6
* OS: osx

### What was wrong?

When trying to send a transaction without a nonce on the `eth_tester` `PyEVMBackend` I get the following error. However, `nonce` is marked as optional in the docs: https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.sendTransaction

```
python test_web3_nonces.py        
Traceback (most recent call last):
  File "test_web3_nonces.py", line 39, in <module>
    'from': web3.eth.coinbase
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/eth.py", line 212, in sendTransaction
    get_buffered_gas_estimate(self.web3, transaction),
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/utils/transactions.py", line 158, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/eth.py", line 254, in estimateGas
    [transaction],
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/manager.py", line 99, in request_blocking
    response = self._make_request(method, params)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/manager.py", line 82, in _make_request
    return request_func(method, params)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 21, in middleware
    response = make_request(method, formatted_params)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 21, in middleware
    response = make_request(method, formatted_params)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/providers/eth_tester/middleware.py", line 308, in middleware
    return make_request(method, [filled_transaction] + params[1:])
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/middleware/fixture.py", line 12, in middleware
    return make_request(method, params)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 21, in middleware
    response = make_request(method, formatted_params)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/providers/eth_tester/main.py", line 383, in make_request
    response = delegator(self.ethereum_tester, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/web3/providers/eth_tester/main.py", line 48, in call_eth_tester
    return getattr(eth_tester, fn_name)(*fn_args, **fn_kwargs)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/eth_tester/main.py", line 419, in estimate_gas
    raw_gas_estimate = self.backend.estimate_gas(raw_transaction)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/eth_tester/backends/pyevm/main.py", line 428, in estimate_gas
    computation = _execute_and_revert_transaction(self.chain, signed_evm_transaction, 'pending')
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/eth_tester/backends/pyevm/main.py", line 194, in _execute_and_revert_transaction
    computation = state.execute_transaction(transaction)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/evm/vm/forks/spurious_dragon/vm_state.py", line 22, in execute_transaction
    computation = _execute_frontier_transaction(self, transaction)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/evm/vm/forks/frontier/vm_state.py", line 50, in _execute_frontier_transaction
    vm_state.validate_transaction(transaction)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/evm/vm/forks/homestead/vm_state.py", line 13, in validate_transaction
    validate_homestead_transaction(self, transaction)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/evm/vm/forks/homestead/validation.py", line 17, in validate_homestead_transaction
    validate_frontier_transaction(evm, transaction)
  File "/Users/test/venvs/test-venv/lib/python3.6/site-packages/evm/vm/forks/frontier/validation.py", line 26, in validate_frontier_transaction
    raise ValidationError("Invalid transaction nonce")
evm.exceptions.ValidationError: Invalid transaction nonce
```

The code is the following:
```python
from web3 import Web3
from web3.providers.eth_tester import EthereumTesterProvider
from eth_tester import EthereumTester

from eth_tester.backends.pyevm import PyEVMBackend
t = EthereumTester(backend=PyEVMBackend())

web3 = Web3(EthereumTesterProvider(t))

target = web3.toChecksumAddress('0xd3cda913deb6f67967b99d67acdfa1712c293601')

for _ in range(10):
    web3.eth.sendTransaction({
        'to': target,
        'from': web3.eth.coinbase
    })

print(f'tx count: {web3.eth.getTransactionCount(web3.eth.coinbase)}')

```

**Comment by carver** [comment]
Thanks for the detailed report!

The best solution I see is to:
1. add a simple test that sends a transaction, without a nonce. Much like: tests/core/eth-module/test_defaultAccount_api.py
2. add a new `fill_default_nonce` to this pipeline: https://github.com/ethereum/web3.py/blob/master/web3/providers/eth_tester/middleware.py#L307

Side note @palango -- since you're on v4-beta, you should be using the beta version of the docs instead:  https://web3py.readthedocs.io/en/latest/

**Comment by ynouri** [comment]
Hi @palango ,
I've not been able to reproduce your issue with the following versions of web3, eth-tester and pyevm:
```
$ pip freeze | grep -E 'web3|eth-tester|py-evm'
eth-tester==0.1.0b13
py-evm==0.2.0a9
web3==4.0.0b7
```
When executing your script, it looks like the transactions go through:
```
$ python test_web3_nonces.py
tx count: 10
```
(Note: there is a bunch of `DeprecationWarning` thrown by eth-utils but those are not related and seem to be fixed with eth-utils release v1.0.0-beta.1)

Are you using the same version of eth-tester and py-evm? Also, is there any code in your script that you didn't include (your error message mentions a line 39)? Please let me know if I missed anything.

**Comment by palango** [comment]
@ynouri 
my version are the following:
```
pip freeze | grep -E 'web3|eth-tester|py-evm'
eth-tester==0.1.0b15
py-evm==0.2.0a10
web3==4.0.0b7
```

**Comment by ynouri** [comment]
Hi @palango ,
Can't reproduce either. Would you mind providing the full script you're running? Or are you able to reproduce with only the code you provided above?
Thanks

**Comment by palango** [comment]
@ynouri You're right, I just removed stuff that I didn't deem important.

The example above runs fine for me as well. The following code crashes. The problem seems to be in the `disable_auto_mine_transactions` function.
```
from web3 import Web3
from web3.providers.eth_tester import EthereumTesterProvider

from eth_tester import EthereumTester

from eth_tester.backends.pyevm import PyEVMBackend
t = EthereumTester(backend=PyEVMBackend())

web3 = Web3(EthereumTesterProvider(t))

print("Testing nonces in web3")

t.disable_auto_mine_transactions()

privkey = '0x58d23b55bc9cdce1f18c2500f40aa4ab7245df9a89505e9b1fa4851f623d24d1'
address = t.add_account(privkey)

target = web3.toChecksumAddress('0xd3cda913deb6f67967b99d67acdfa1712c293601')


# import rlp
# from ethereum.transactions import Transaction
# tx = Transaction(
#     nonce=web3.eth.getTransactionCount(web3.eth.coinbase),
#     gasprice=web3.eth.gasPrice,
#     startgas=100000,
#     to=target,
#     value=12345,
#     data=b'',
# )
# tx.sign(privkey)
# raw_tx = rlp.encode(tx)
# raw_tx_hex = web3.toHex(raw_tx)
# web3.eth.sendRawTransaction(raw_tx_hex)

for _ in range(10):
    web3.eth.sendTransaction({
        'to': target,
        'from': web3.eth.coinbase
    })

print(f'tx cont {web3.eth.getTransactionCount(web3.eth.coinbase)}')

print(web3.eth.blockNumber)
```

**Comment by palango** [comment]
Thanks for investigating @ynouri 

It works now. Originally I wanted to find out if the nonces are increased automatically if I schedule multiple transactions. I guess I can look deeper into that now.
