### ISSUE TITLE
ConciseContract cleanup

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/web3.py#675]
### What was wrong?

The `web3.contract.ConciseContract` has some cleanup that could be done to improve the class in small ways.

### How can it be fixed?

1. Update the documentation to make it very clear that `ConciseContract` **only** exposes contract functions and that **all** other `Contract` class methods and properties are not available with the `ConciseContract` API.  This includes `c.address`, `c.abi`, `c.deploy()`, etc.
2. The `_none_addr`  method on the `ConciseContract` class should be moved to a stand-alone function.  This is to remove the potential for collisions between actual methods on the `ConciseContract` and contract ABI function names.
3. In the `__init__` we should check for name collisions between contract methods and class methods.  In the event we find a collision I think we should insert an `@property` method onto the class which raises an `AttributeError` indicating that there was a name collision, the name that collided, and instructions that they should access the function on the primary contract object.

**Comment by pipermerriam** [comment]
@carver thoughts on these cleanups?

**Comment by carver** [comment]
Yeah, this all seems good. I also like the idea of changing the examples away from using it as a `ContractFactoryClass` since it changes the API so dramatically. Instead, we would recommend in the docs that you invoke it as a separate thing:

```py
contract = w3.eth.contract(...)
concise = ConciseContract(contract)
```

**Comment by boneyard93501** [comment]
to 3: 
something like that will do ?
```python
class ConciseContract:
    ALLOWED_MODIFIERS = set(['call', 'estimateGas', 'transact', 'buildTransaction'])

    EX_NS = [_ for _ in dir(Contract) if not _.endswith('__')]

    def __init__(self,contract,function):
        if function.__name__ in self.EX_NS:
        # or
        # if getattr(function,'__name__') in self.EX_NS:
            raise AttributeError(f'namespace collision for {function.__name__} with Contract.')
        self.__contract = contract
        self.__function = function
```

**Comment by pipermerriam** [comment]
@boneyard93501 not quite.  We don't actually care about NS collisions with `Contract`, only with the very limited API that `ConciseContract` exposes.  I think you could do something simpler like:

```python
from cytoolz import curry

def mk_collision_prop(fn_name):
    def collision_fn(self):
        raise AttributeError("Namespace collision for function name {0} with existing API for ConciseContract".format(fn_name))
    collision_fn.__name__ = fn_name
    return collision_fn

class ConciseContract:
    def __init__(self, ...):
        for fn_name in the_abi_function_names:
            if hasattr(self, fn_name):
                setattr(self, fn_name, property(mk_collision_prop(fn_name)))
```

**Comment by boneyard93501** [comment]
duh. yet another instance supporting a much-needed "reading comprehension required" label. sorry. i got some time tomorrow evening if you're not in hurry.

**Comment by pipermerriam** [comment]
> yet another instance supporting a much-needed "reading comprehension required"

@carver can attest to my inability to read the actual PR text where he's regularly laid out the answers to questions he knows I'll have, yet I still ask them.

**Comment by boneyard93501** [comment]
to 2: will that work?  

```bash
diff --git a/web3/contract.py b/web3/contract.py
index d0b53d6..6f35151 100644
--- a/web3/contract.py
+++ b/web3/contract.py
@@ -664,16 +664,16 @@ class ConciseContract:
         contract_function = getattr(self._classic_contract.functions, attr)
         return ConciseMethod(contract_function, self._classic_contract._return_data_normalizers)

-    @staticmethod
-    def _none_addr(datatype, data):
-        if datatype == 'address' and int(data, base=16) == 0:
-            return (datatype, None)
-        else:
-            return (datatype, data)
+
+def _none_addr(datatype, data):
+    if datatype == 'address' and int(data, base=16) == 0:
+        return (datatype, None)
+    else:
+        return (datatype, data)


 CONCISE_NORMALIZERS = (
-    ConciseContract._none_addr,
+    _none_addr,
 )
```

since _CONCISE_NORMALIZERS is used in all the tests and it's a tuple, seems preferable to leave it.



to 3:

below is based on your suggested approach but i dropped the property() so the AttributeError actually pops when you call the function.  

```bash
+def mk_collision_prop(fn_name):
+    def collision_fn():
+        msg = "Namespace collision for function name {0} with ConciseContract API.".format(fn_name)
+        raise AttributeError(msg)
+    collision_fn.__name__ = fn_name
+    return functools.partial(collision_fn)
+
+
 class ConciseContract:
     '''
     An alternative Contract Factory which invokes all methods as `call()`,
@@ -652,10 +660,30 @@ class ConciseContract:
     > contract.functions.withdraw(amount).transact({'from': eth.accounts[1], 'gas': 100000, ...})
     '''
     def __init__(self, classic_contract):
+        import inspect
+        d = set([d['name'] for d in classic_contract.abi if d.get('name') is not None])
+        print("Concise Contract __init__ called by: ", inspect.currentframe().f_back.f_locals['self'])
+   
+        protected_fn_names = [fn for fn in dir(self) if not fn.endswith('__')]
+        for fn_name in d:
+            if fn_name in protected_fn_names:
+                print(fn_name,  property(mk_collision_prop(fn_name)))
+                setattr(self, fn_name, mk_collision_prop(fn_name))
+
         classic_contract._return_data_normalizers += CONCISE_NORMALIZERS
         self._classic_contract = classic_contract
         self.address = self._classic_contract.address

+    def topUp(self,):
+        ''' for local test only. this is a function on the abi i used '''
+        print("nothing to see here.")
+
```

and  

```python
abi = '...'
address = '...'

w3 = Web3(HTTPProvider('http://127.0.0.1:8545'))
concise = w3.eth.contract(address=address, abi=abi_str, ContractFactoryClass=ConciseContract)

# calling ns colliion test function
concise.topUp()
```  
gets you:   

```bash
(web3patch) booyah@iMac27 ~/localdev/source-code/web3.py (lilpatch) $ python bb-test/patch_tester.py
ENS init
ens:  <class 'ens.main.ENS'>
Concise Contract __init__ called by:  <toolz.functoolz.Compose object at 0x10da81a20>
ENS init
ens:  <class 'ens.main.ENS'>
Concise Contract __init__ called by:  <toolz.functoolz.Compose object at 0x10daa7668>
Concise Contract __init__ called by:  <toolz.functoolz.Compose object at 0x10da81748>
topUp <property object at 0x10daa9c28>
Traceback (most recent call last):
  File "bb-test/patch_tester.py", line 20, in <module>
    concise.topUp()
  File "/Users/booyah/localDev/source-code/web3.py/web3/contract.py", line 644, in collision_fn
    raise AttributeError(msg)
AttributeError: Namespace collision for function name topUp with ConciseContract API.
(web3patch) booyah@iMac27 ~/localdev/source-code/web3.py (lilpatch) $
```

as a side node, one thing i still haven't been able to figure out is why the contracts, well Web3 really, is called three times. i traced it back to <class 'ens.main.ENS'> but why that's happening is still eluding me.

thoughts? thanks.
