### ISSUE TITLE
Unable to get return data from getter functions when using the `call` method

### ISSUE THREAD

**Issue by postables** [ethereum/web3.py#688]
I'm using the latest version of web3py fetched from pip (4.0.0b11), on a private PoA network.

`>>>contract.call().numPeers()` produces the following output

```
/home/solidity/.local/lib/python3.6/site-packages/eth_utils/string.py:22: DeprecationWarning: The `force_bytes` function has been deprecated and will be removed in a subsequent release of the eth-utils library. UTF8 cannot encode some byte values in the 0-255 range which makes naive coersion between bytes and text representations impossible without explicitly declared encodings.
  "declared encodings.".format(fn.__name__)
/home/solidity/.local/lib/python3.6/site-packages/eth_utils/string.py:22: DeprecationWarning: The `force_obj_to_bytes` function has been deprecated and will be removed in a subsequent release of the eth-utils library. UTF8 cannot encode some byte values in the 0-255 range which makes naive coersion between bytes and text representations impossible without explicitly declared encodings.
  "declared encodings.".format(fn.__name__)
/home/solidity/.local/lib/python3.6/site-packages/eth_utils/formatting.py:20: DeprecationWarning: The `is_prefixed` function has been deprecated and will be removed in a subsequent release of the eth-utils library. Now that eth-utils is compatible with Python3, we encourage developers to use stdlib functions where possible.
  "functions where possible.".format(fn.__name__)
/home/solidity/.local/lib/python3.6/site-packages/eth_utils/string.py:22: DeprecationWarning: The `force_obj_to_text` function has been deprecated and will be removed in a subsequent release of the eth-utils library. UTF8 cannot encode some byte values in the 0-255 range which makes naive coersion between bytes and text representations impossible without explicitly declared encodings.
  "declared encodings.".format(fn.__name__)
/home/solidity/.local/lib/python3.6/site-packages/eth_utils/string.py:22: DeprecationWarning: The `force_text` function has been deprecated and will be removed in a subsequent release of the eth-utils library. UTF8 cannot encode some byte values in the 0-255 range which makes naive coersion between bytes and text representations impossible without explicitly declared encodings.
  "declared encodings.".format(fn.__name__)
/home/solidity/.local/lib/python3.6/site-packages/eth_abi/abi.py:92: DeprecationWarning: Automatic inference of hex encoded data has been deprecated. Please adjust your code to ensure that the data argument for `decode_single` is a byte string
  "Automatic inference of hex encoded data has been deprecated. "
Traceback (most recent call last):
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/contract.py", line 844, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/home/solidity/.local/lib/python3.6/site-packages/eth_abi/abi.py", line 109, in decode_abi
    return decoder(stream)
  File "/home/solidity/.local/lib/python3.6/site-packages/eth_abi/decoding.py", line 102, in __call__
    return self.decode(stream)
  File "/home/solidity/.local/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/home/solidity/.local/lib/python3.6/site-packages/eth_abi/decoding.py", line 140, in decode
    yield decoder(stream)
  File "/home/solidity/.local/lib/python3.6/site-packages/eth_abi/decoding.py", line 102, in __call__
    return self.decode(stream)
  File "/home/solidity/.local/lib/python3.6/site-packages/eth_abi/decoding.py", line 165, in decode
    raw_data = cls.read_data_from_stream(stream)
  File "/home/solidity/.local/lib/python3.6/site-packages/eth_abi/decoding.py", line 247, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/contract.py", line 866, in call_contract_function
    raise_from(BadFunctionCallOutput(msg), e)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/utils/exception_py3.py", line 2, in raise_from
    raise my_exception from other_exception
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call numPeers return data 0x for output_types ['uint256']
```

**Comment by pipermerriam** [comment]
This looks like trying to talk to a contract which doesn't exist, *or* that the ABI you're using doesn't match the return types.  To debug this any further we'll need full information to reproduce this locally.

- contract address
- contract abi
- ideally contract source too

**Comment by postables** [comment]
Thanks Piper! After reading your post I re-did my workflow gathering the data you required and everything worked. Not sure what I missed but I clearly missed something last night. Thank you :D
