### ISSUE TITLE
IPC connection patch not found on random occasions when using python scripts

### ISSUE THREAD

**Issue by postables** [ethereum/web3.py#689]
I don't seem to have this problem when using web3py from the terminal, and it only appears to happen intermittently with my python scripts. I'm not quite sure what the problem is, since the path to the IPC file is a soft link in the same directory as my python code.
```
solidity@pop-os:~/Documents/Code/Postables/Sidechain-Bridge/python$ ls -l geth.ipc && ls $(pwd)/IpfsNode.py
lrwxrwxrwx 1 solidity solidity 75 Mar  8 02:18 geth.ipc -> /home/solidity/Documents/Code/Postables/Sidechain-Bridge/poa/node1/geth.ipc
/home/solidity/Documents/Code/Postables/Sidechain-Bridge/python/IpfsNode.py
```

Traceback
```
Traceback (most recent call last):
  File "IpfsNode.py", line 65, in <module>
    print("Number of peers", peerRegistryContract.call().numPeers())
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/contract.py", line 837, in call_contract_function
    return_data = contract.web3.eth.call(call_transaction)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/eth.py", line 253, in call
    [transaction, block_identifier],
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/manager.py", line 93, in request_blocking
    response = self._make_request(method, params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/manager.py", line 76, in _make_request
    return request_func(method, params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 20, in middleware
    response = make_request(method, params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, formatted_params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/providers/ipc.py", line 108, in make_request
    with self._lock, self._socket as sock:
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/providers/ipc.py", line 41, in __enter__
    self.sock = self._open()
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/providers/ipc.py", line 54, in _open
    return get_ipc_socket(self.ipc_path)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/providers/ipc.py", line 28, in get_ipc_socket
    sock.connect(ipc_path)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by pipermerriam** [comment]
This doesn't look like a web3 error.  Have you checked that the file at `ipc_path` exists?

**Comment by postables** [comment]
@pipermerriam  Yes I'm 100% sure the file at ipc_path exists, the output of the `ls` command is the first code snippet showing that the ipc path exists.

**Comment by pipermerriam** [comment]
I understand that it exists when you ls, but there may be a race condition at play.  I would recommend trying something like the following.

```python
try:
    # web3 code that causes the error
except FileNotFoundError:
    import os
    print('File exists?:', os.path.exists(w3.providers[0].ipc_path))
```

Another issue could be if you're using relative paths?

**Comment by postables** [comment]
@pipermerriam  Here's the code:

```python
config = 'configs/settings_test.yml'
with open(config, 'r') as ymlFile:
	cfg = yaml.load(ymlFile)
pDataBridgeAddress = cfg['private']['dataBridgeAddress']
pDataBridgeAbiFile = cfg['private']['dataBridgeAbi']
pConnectionMethod = cfg['private']['connectionMethod']
if pConnectionMethod == 'rpc':
	pConnectionPath = cfg['private']['rpcUrl']
elif pConnectionMethod == 'ipc':
	pConnectionPath = cfg['private']['ipcPath']
else:
	exit()
pNet = Listener.Listener(pDataBridgeAddress, pDataBridgeAbiFile)
if pConnectionMethod == 'rpc':
	# connect to the network
	pNet.establishRpcConnection(pConnectionPath)
elif pConnectionMethod == 'ipc':
	# connect to the network
	pNet.establishIpcConnection(pConnectionPath)
else:
	exit()
```

The yaml file that the information is loaded from
```yaml
main:
  dataBridgeAddress: '0x0D69c4d2423A2708f18202B302559A0A3c7c9172'
  dataBridgeAbi: 'abi/DataBridge.abi'
  adminAddress: '0x124' # thsi is the address of the designated bridge admin 
  adminPassword: '1234'
  connectionMethod: 'ipc'
  rpcUrl: 'http://127.0.0.1:8546'
  ipcPath: '/home/soliidty/.ethereum/geth.ipc'
```

The library that is called which connects to the network
```python
	# if we're not using test rpc, connect via ipc
	def establishIpcConnection(self, ipcPath):
		self.w3 = Web3(IPCProvider(ipcPath))
	# if we're not using test rpc, connect via specified rpc url
	def establishRpcConnection(self, rpcUrl):
		self.w3 = Web3(HTTPProvider(rpcUrl))
```

Error that is triggered when a function is called
```python
Traceback (most recent call last):
  File "Relayer.py", line 116, in <module>
    payloadSubmission(mContract, mAddress, payload, file)
  File "Relayer.py", line 79, in payloadSubmission
    payloadContract.functions.submitPayload(mAddress, mContract, payload, fileHash).transact({'from': accountAddress})
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/contract.py", line 883, in transact
    **self.kwargs)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/contract.py", line 1098, in transact_with_contract_function
    txn_hash = web3.eth.sendTransaction(transact_transaction)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/eth.py", line 228, in sendTransaction
    get_buffered_gas_estimate(self.web3, transaction),
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/utils/transactions.py", line 73, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/eth.py", line 270, in estimateGas
    [transaction],
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/manager.py", line 101, in request_blocking
    response = self._make_request(method, params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/manager.py", line 84, in _make_request
    return request_func(method, params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/middleware/formatting.py", line 21, in middleware
    response = make_request(method, formatted_params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/middleware/formatting.py", line 21, in middleware
    response = make_request(method, formatted_params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/middleware/validation.py", line 44, in middleware
    return make_request(method, post_validated_params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/middleware/formatting.py", line 21, in middleware
    response = make_request(method, formatted_params)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/providers/ipc.py", line 155, in make_request
    with self._lock, self._socket as sock:
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/providers/ipc.py", line 44, in __enter__
    self.sock = self._open()
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/providers/ipc.py", line 57, in _open
    return get_ipc_socket(self.ipc_path)
  File "/home/solidity/.local/lib/python3.6/site-packages/web3/providers/ipc.py", line 28, in get_ipc_socket
    sock.connect(ipc_path)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by pipermerriam** [comment]
Did you try my suggested code for verifying that the `ipc_path` does indeed exist prior to interacting with web3?  This really doesn't look like a web3 bug so I would suggest trying my suggestion above and reporting back.  If you can verify that there is a valid IPC socket at that location just prior to the call that fails (and maybe also just after), then we can start digging deeper into this.
