### ISSUE TITLE
Cannot import web3 

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#736]
* pip 9.0.3
* Python: 3.5
* OS: linux (ubuntu)

```
### pip install:
$ sudo apt-get install python3-pip
$ sudo pip3 install virtualenv
#once
$ virtualenv -p python3 ~/.venv-py3
# each session:
$ source ~/.venv-py3/bin/activate
```
Current session is: `(.venv-py3) user$`

When I use following line on my python file:
`from web3.auto import w3`

I receive the following error:

```
Traceback (most recent call last):
  File "getClusterAddresses.py", line 5, in <module>
    from web3.auto import w3
  File "/home/alper/.venv-py3/lib/python3.5/site-packages/web3/__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "/home/alper/.venv-py3/lib/python3.5/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/home/alper/.venv-py3/lib/python3.5/site-packages/eth_account/account.py", line 10, in <module>
    from eth_keyfile import (
  File "/home/alper/.venv-py3/lib/python3.5/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/home/alper/.venv-py3/lib/python3.5/site-packages/eth_keyfile/keyfile.py", line 10, in <module>
    from eth_keys import keys
  File "/home/alper/.venv-py3/lib/python3.5/site-packages/eth_keys/__init__.py", line 15, in <module>
    from .main import (  # noqa: F401
  File "/home/alper/.venv-py3/lib/python3.5/site-packages/eth_keys/main.py", line 1, in <module>
    from typing import (Any, Union, Type)  # noqa: F401
ImportError: cannot import name 'Type'
```

**Comment by carver** [comment]
What's the result of `python --version` while in the virtualenv?

`typing.Type` was introduced in version 3.5.2 according to https://docs.python.org/3/library/typing.html

**Comment by avatar-lavventura** [comment]
Any version >= than `3.5.2 `will work? such as `3.6`? 
This line `sudo apt-get install python3` installs python 3.5.0, I was not able to upgrade it. @carver

**Comment by redserpent7** [comment]
I'm on python 3.7 and I am getting this error.

**Comment by carver** [comment]
@redserpent7 please open a new ticket, with the full traceback, the result of `python -V`, and your installed libraries (`pip list`).
