### ISSUE TITLE
Contract interaction always raising "gas required exceeds allowance or always failing transaction"

### ISSUE THREAD

**Issue by ScriptProdigy** [ethereum/web3.py#769]
* Version: 4.1.0
* Python: 3.6
* OS: linux

### What was wrong?
Using the code below, the error below ALWAYS appears, no matter the ERC20 token.

```
>>> from web3 import Web3
>>> web3i = Web3(Web3.HTTPProvider("wallet here")
>>> contracti = web3i.eth.contract(address=web3i.toChecksumAddress("0x9992ec3cf6a55b00978cddf2b27bc6882d88d1ec"), abi='[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_subtractedValue","type":"uint256"}],"name":"decreaseApproval","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimalFactor","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_addedValue","type":"uint256"}],"name":"increaseApproval","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"_polyDistributionContractAddress","type":"address"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Approval","type":"event"}]')
move = contracti.functions.transferFrom("0xB6856aD7c30ED8e8447357DE835165a78CfBdebB", "0x1261dd2f410550160E98685d1E9E0272AAf09AA0", 7000000000000000000)


>>> move.estimateGas()
ValueError: {'code': -32000, 'message': 'gas required exceeds allowance or always failing transaction'}

OR

>>> move.call()
Traceback (most recent call last):
  File "/vagrant/virt/lib/python3.6/site-packages/web3/contract.py", line 1233, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/vagrant/virt/lib/python3.6/site-packages/eth_abi/abi.py", line 63, in decode_abi
    return decoder(stream)
  File "/vagrant/virt/lib/python3.6/site-packages/eth_abi/decoding.py", line 99, in __call__
    return self.decode(stream)
  File "/vagrant/virt/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/vagrant/virt/lib/python3.6/site-packages/eth_abi/decoding.py", line 137, in decode
    yield decoder(stream)
  File "/vagrant/virt/lib/python3.6/site-packages/eth_abi/decoding.py", line 99, in __call__
    return self.decode(stream)
  File "/vagrant/virt/lib/python3.6/site-packages/eth_abi/decoding.py", line 162, in decode
    raw_data = cls.read_data_from_stream(stream)
  File "/vagrant/virt/lib/python3.6/site-packages/eth_abi/decoding.py", line 244, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/vagrant/virt/lib/python3.6/site-packages/web3/contract.py", line 995, in call
    **self.kwargs)
  File "/vagrant/virt/lib/python3.6/site-packages/web3/contract.py", line 1255, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call transferFrom return data b'' for output_types ['bool']
```

I have ether as well as poly on the from address. I've tested this with ebtc contract as well. Same result.
https://etherscan.io/address/0xB6856aD7c30ED8e8447357DE835165a78CfBdebB

**Comment by ScriptProdigy** [comment]
Im using a fully synced geth node

**Comment by ScriptProdigy** [comment]
Oddly enough this 'sort of' works

```
>>> move = contracti.functions.transferFrom("0xB6856aD7c30ED8e8447357DE835165a78CfBdebB", "0x1261dd2f410550160E98685d1E9E0272AAf09AA0", 0)
>>> move.estimateGas()
44068
```

clearly doesnt work though as Im sending 0 tokens..

**Comment by ScriptProdigy** [comment]
Woo, turns out I wasnt supplying enough gas to the above. All is well now!

**Comment by zidzid1234** [comment]
Give more gas value during transaction building
txn0 = {'gas': 48000}
txn = ctrtInst.functions.functionName(arg1, arg2).buildTransaction(txn0)
