### ISSUE TITLE
 Working with Local Private Keys, module 'web3' has no attribute 'utils'

### ISSUE THREAD

**Issue by agz1990** [ethereum/web3.py#780]
* Version:  4.1.0
* Python: 3.6
* OS: linux/win

### What was wrong?
Traceback (most recent call last):
  File "<ipython-input-260-69766ce4d393>", line 2, in <module>
    w3.eth.contract(address="0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359", abi=EI
P20_ABI)
  File "f:\python36\lib\site-packages\web3\eth.py", line 351, in contract
    ContractFactory = ContractFactoryClass.factory(self.web3, **kwargs)
  File "f:\python36\lib\site-packages\web3\contract.py", line 216, in factory
    'address': partial(normalize_address, kwargs['web3'].ens),
  File "f:\python36\lib\site-packages\web3\main.py", line 184, in ens
    return ENS.fromWeb3(self)
  File "f:\python36\lib\site-packages\ens\main.py", line 72, in fromWeb3
    return cls(web3.manager.providers, addr=addr)
  File "f:\python36\lib\site-packages\ens\main.py", line 60, in __init__
    self.ens = self.web3.eth.contract(abi=abis.ENS, address=ens_addr)
  File "f:\python36\lib\site-packages\web3\eth.py", line 351, in contract
    ContractFactory = ContractFactoryClass.factory(self.web3, **kwargs)
  File "f:\python36\lib\site-packages\web3\contract.py", line 834, in factory
    return compose(cls, Contract.factory(*args, **kwargs))
  File "f:\python36\lib\site-packages\web3\contract.py", line 225, in factory
    normalizers=normalizers)
  File "f:\python36\lib\site-packages\web3\utils\datatypes.py", line 34, in __ne
w__
    processed_namespace = web3.utils.formatters.apply_formatters_to_dict(
AttributeError: module 'web3' has no attribute 'utils'
None

![_20180421011344](https://user-images.githubusercontent.com/5153919/39064507-58689592-4501-11e8-875b-b8f17a9373f9.png)
![image](https://user-images.githubusercontent.com/5153919/39064592-a421ac76-4501-11e8-87ed-494147b1d51d.png)

HI: 
   i follow  web3py readthedocs, try  Sign a Contract Transaction, Get that error. pls help. 
   document url: http://web3py.readthedocs.io/en/stable/web3.eth.account.html

**Comment by carver** [comment]
It kind of sounds like you have a borked environment. I would start in a fresh virtualenv. However you do it, you'll want to uninstall web3utils. It is an old package that only supports web3 v3, as you pointed out. There shouldn't be anything that depends on web3utils anymore. (all the good stuff from it has been imported into web3 v4, anyway)

**Comment by agz1990** [comment]
hi carver ,  I clean the development environment adn reinstall web3 , now the problem has been solved. Thank you!
