### ISSUE TITLE
Whisper - TypeError: Object of type 'ShhFilter' is not JSON serializable

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/web3.py#798]
* Version: 4.2.0
* Python: 3.6.5
* OS: linux
* geth v1.8.7 (`geth --shh --syncmode "fast"`)

### What was wrong?
Trying the new Whisper v6 integration. Let me know if I did not set it up correctly, basically trying to figure it out for the first time.

I got one error that didn't seem right to me, it looks like the `ShhFilter` doesn't implement serializable for pretty-printing or something.

Code and the error:
```python
>>> from web3.auto import w3
>>> from web3.shh import Shh
>>> shh = Shh(w3)
>>> kp = shh.newKeyPair()
>>> pubkey = shh.getPublicKey(kp)
>>> privkey = shh.getPrivateKey(kp)
>>> flt = shh.newMessageFilter({'topic': '0x12345678', 'privateKeyID': kp})
>>> shh.post({'payload': w3.toHex(text="This is a test!"), 'pubkey': pubkey, 'topic': '0x12345678', 'powTarget': 2.5, 'powTime': 2})
>>> shh.getMessages(flt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/shh.py", line 79, in getMessages
    return self.web3.manager.request_blocking("shh_getFilterMessages", [filter_id])
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/manager.py", line 103, in request_blocking
    response = self._make_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/manager.py", line 86, in _make_request
    return request_func(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/middleware/validation.py", line 45, in middleware
    return make_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/providers/auto.py", line 63, in make_request
    return self._proxy_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/providers/auto.py", line 76, in _proxy_request
    return provider.make_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/providers/ipc.py", line 153, in make_request
    request = self.encode_rpc_request(method, params)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/site-packages/web3/providers/base.py", line 67, in encode_rpc_request
    "id": next(self.request_counter),
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/bryant/.pyenv/versions/3.6.5/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ShhFilter' is not JSON serializable
```

**Comment by ConnorChristie** [comment]
Unfortunately, it does not. It should, however, be updated to handle serialization to support use cases like this.

**Comment by fubuloubu** [comment]
@ConnorChristie I was trying it out. Is there another way to use the API to try basic messaging?

**Comment by fubuloubu** [comment]
Ah, I see now! For usabilities sake, the middleware sounds nice.

I will give this a try!

**Comment by fubuloubu** [comment]
Works!

```python
>>> shh.getMessages(flt.filter_id)                 
[{'ttl': 50, 'timestamp': 1525131074, 'topic': HexBytes('0x12345678'), 'payload': HexBytes('0x546869732069732061207465737421'), 'padding': HexBytes('0x03345b12c13e2322ea3c4ff239fbca73470f2d355e4136e333f9bcff27facf88e441c988d0bbe79b90e2b8f7dfe8144f222a8ca25ba700a2cf338ee044d91ecb6c94c150db7e6787dd73e557794d614381116c67c3821404456d3279eb0748a9179aa54a0c8ee5dac589150049dbee842fb0987ae28466e96f925509cd22ba3695124b97a302e3c43f01e84866cb1577d190e9d0b1e7e6b14a3bbd0c1c34d7c036a4c82cb2f2b3c1c021f6318e7dbf9c94c347abe5fb38ed7ecdb12e4dd3b11c6f969074d555fd8a8df9ea0224a6a49a70456c26796c9609a65572dc0a88e0f45324672983d5d82aa5360ce88b6fa6'), 'pow': 3.369460154241645, 'hash': HexBytes('0x61e2225a9d4d13db68760c3f078f8af29d5eeae16cc24ac7e50dae4dc6f360b3'), 'recipientPublicKey': HexBytes('0x0409d7cdadef4d8f6173beef14838505eac63f1823d1cbd1ad1eee6be61a12e76703001e90e27138f9f4787b8614f81acacad88d582dfc2289a2a3b76b593fac14')}]   
```
