### ISSUE TITLE
get error when run README example

### ISSUE THREAD

**Issue by thomaszdxsn** [ethereum/web3.py#799]
* Version: latest
* Python: 3.6
* OS: osx

### What was wrong?

* The code which produced the error

I install all dependency and run the README's example, but can't complete, may be API changed error.
 
* The full output of the error

```
 Traceback (most recent call last):
  File "test.py", line 33, in <module>
    w3 = Web3(TestRPCProvider())
  File ".../.virtualenvs/eth/lib/python3.6/site-packages/web3/utils/decorators.py", line 57, in wrapper
    return to_wrap(*args, **kwargs)
  File ".../.virtualenvs/eth/lib/python3.6/site-packages/web3/providers/tester.py", line 152, in __init__
    from testrpc.server import get_application
  File ".../.virtualenvs/eth/lib/python3.6/site-packages/testrpc/server.py", line 8, in <module>
    from .rpc import RPCMethods
  File ".../.virtualenvs/eth/lib/python3.6/site-packages/testrpc/rpc.py", line 11, in <module>
    from ethereum import blocks
  File ".../.virtualenvs/eth/lib/python3.6/site-packages/ethereum/__init__.py", line 8, in <module>
    from . import slogging  # noqa
  File ".../.virtualenvs/eth/lib/python3.6/site-packages/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, isnumeric
  File ".../.virtualenvs/eth/lib/python3.6/site-packages/ethereum/utils.py", line 11, in <module>
    from rlp.utils import decode_hex, encode_hex as _encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'
```

* What type of node you were connecting to.
 
   just testrpc, not connecting real node

### How can it be fixed?

I'am a newbie, don't now how to fix it.

**Comment by voith** [comment]
can you post your version of rlp?
```
pip freeze | grep ^rlp 
```
In any case try to pin your `rlp` version to `0.6.0` and see if it works.
```
pip install rlp==0.6.0
```

**Comment by thomaszdxsn** [comment]
It work, thank you very much.

but still stranger. it's previous version is latest(1.0.1), but don't work. 

is it testrpc error?

**Comment by voith** [comment]
@thomaszdxsn The latest `rlp 1.0.1` release has done some refactoring. This is a known issue.
Other packages that are dependent on this are yet to be made compatible. 
This should be fixed in [eth-testrpc](https://github.com/pipermerriam/eth-testrpc/blob/cbb22ff2bebc9f12098b0bb7f2a245f3510522b4/setup.py#L41)

**Comment by thomaszdxsn** [comment]
thanks, please close this issue
