### ISSUE TITLE
deploy contract example is broken ? TypeError: Incorrect argument count.  Expected '1'.  Got '0'

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/web3.py#808]
Your [own example](http://web3py.readthedocs.io/en/stable/examples.html#working-with-contracts) has stopped working?
```
web3 version 4.2.0, python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

~/py3/site-packages/eth_tester/backends/__init__.py:48: UserWarning: Ethereum Tester: No backend was explicitely set, and no *full* backends were available.  Falling back to the `MockBackend` which does not support all EVM functionality.  Please refer to the `eth-tester` documentation for information on what backends are available and how to set them.
  "Ethereum Tester: No backend was explicitely set, and no *full* "
~/DeployContractExample.py:20: DeprecationWarning: deploy is deprecated in favor of contract.constructor.transact
  bytecode=contract_interface['bin']).deploy()

Traceback (most recent call last):
  File "~/DeployContractExample.py", line 41, in <module>
    address = deploy_contract(w3, contract_interface)
  File "~/DeployContractExample.py", line 20, in deploy_contract
    bytecode=contract_interface['bin']).deploy()
  File "~/py3/site-packages/web3/utils/decorators.py", line 57, in wrapper
    return to_wrap(*args, **kwargs)
  File "~/py3/site-packages/web3/contract.py", line 289, in deploy
    deploy_transaction['data'] = cls._encode_constructor_data(args, kwargs)
  File "~/py3/site-packages/web3/utils/decorators.py", line 16, in _wrapper
    return self.method(objtype, *args, **kwargs)
  File "~/py3/site-packages/web3/contract.py", line 667, in _encode_constructor_data
    arguments = merge_args_and_kwargs(constructor_abi, args, kwargs)
  File "~/py3/site-packages/web3/utils/abi.py", line 204, in merge_args_and_kwargs
    len(args) + len(kwargs),

TypeError: Incorrect argument count.  Expected '1'.  Got '0'
```

### What was wrong?

Please see
* [DeployContractExample.py](https://gitlab.com/electronDLT/chainhammer/blob/master/DeployContractExample.py)
* tested both contracts in [contract.sol](https://gitlab.com/electronDLT/chainhammer/blob/master/contract.sol), both fail with the same error message.

### How can it be fixed?

Repair example code.

**Comment by drandreaskrueger** [comment]
Actually, now I chose to deploy not their, but your example contract.sol ... and now I get a different error:

```
web3 version 4.2.0, python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
~/py3/site-packages/eth_tester/backends/__init__.py:48: UserWarning: Ethereum Tester: No backend was explicitely set, and no *full* backends were available.  Falling back to the `MockBackend` which does not support all EVM functionality.  Please refer to the `eth-tester` documentation for information on what backends are available and how to set them.
  "Ethereum Tester: No backend was explicitely set, and no *full* "
~/DeployContractExample.py:25: DeprecationWarning: deploy is deprecated in favor of contract.constructor.transact
  bytecode=contract_interface['bin']).deploy()
Traceback (most recent call last):
  File "~/DeployContractExample.py", line 46, in <module>
    address = deploy_contract(w3, contract_interface)
  File "~/DeployContractExample.py", line 25, in deploy_contract
    bytecode=contract_interface['bin']).deploy()
  File "~/py3/site-packages/web3/utils/decorators.py", line 57, in wrapper
    return to_wrap(*args, **kwargs)
  File "~/py3/site-packages/web3/contract.py", line 291, in deploy
    txn_hash = cls.web3.eth.sendTransaction(deploy_transaction)
  File "~/py3/site-packages/web3/eth.py", line 239, in sendTransaction
    get_buffered_gas_estimate(self.web3, transaction),
  File "~/py3/site-packages/web3/utils/transactions.py", line 72, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "~/py3/site-packages/web3/eth.py", line 280, in estimateGas
    [transaction],
  File "~/py3/site-packages/web3/manager.py", line 106, in request_blocking
    raise ValueError(response["error"])

ValueError: RPC Endpoint has not been implemented: eth_estimateGas
```

**Comment by drandreaskrueger** [comment]
> The sandbox node provided by eth-tester. You can install it with pip install -U web3[tester].

in spite of 

    pip3 install py-solc web3 web3[tester]

I get a

```
versions: web3 4.2.0, solc 0.4.23+commit.124ca40d.Linux.gpp, python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
Traceback (most recent call last):
  File "/home/akrueger/Documents/Code/gitlab/electronDLT/chainhammer/DeployContractExample.py", line 42, in <module>
    w3 = Web3(Web3.EthereumTesterProvider())
  File "/home/akrueger/Documents/Code/envs/py3eth/lib/python3.5/site-packages/web3/utils/decorators.py", line 57, in wrapper
    return to_wrap(*args, **kwargs)
  File "/home/akrueger/Documents/Code/envs/py3eth/lib/python3.5/site-packages/web3/providers/tester.py", line 121, in __init__
    raise Exception("`TestRPCProvider` requires the `eth-testrpc` package to be installed")
Exception: `TestRPCProvider` requires the `eth-testrpc` package to be installed
```

**Comment by drandreaskrueger** [comment]
So ... now ...

This code, which is the exact copy of your example in the `latest` manual
https://gitlab.com/electronDLT/chainhammer/blob/1c87749345d04a474b243e7b3ccd97a8dc3358e3/DeployContractExample.py

does still fail:

```
versions: web3 4.2.0, solc 0.4.23+commit.124ca40d.Linux.gpp, python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

Traceback (most recent call last):
  File "~/DeployContractExample.py", line 45, in <module>
    print (w3.eth.accounts)
  File "~/py3/site-packages/web3/eth.py", line 97, in accounts
    return self.web3.manager.request_blocking("eth_accounts", [])
  File "~/py3/site-packages/web3/manager.py", line 103, in request_blocking
    response = self._make_request(method, params)
  File "~/py3/site-packages/web3/manager.py", line 86, in _make_request
    return request_func(method, params)
  File "~/py3/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "~/py3/site-packages/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "~/py3/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "~/py3/site-packages/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "~/py3/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "~/py3/site-packages/web3/middleware/validation.py", line 45, in middleware
    return make_request(method, params)
  File "~/py3/site-packages/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "~/py3/site-packages/web3/middleware/formatting.py", line 23, in middleware
    response = make_request(method, params)
  File "~/py3/site-packages/web3/providers/tester.py", line 67, in middleware
    return valmap(to_text, make_request(method, params))
  File "cytoolz/dicttoolz.pyx", line 165, in cytoolz.dicttoolz.valmap
  File "cytoolz/dicttoolz.pyx", line 190, in cytoolz.dicttoolz.valmap
  File "~/py3/site-packages/eth_utils/decorators.py", line 73, in wrapper
    return to_wrap(*args, **kwargs)
  File "~/py3/site-packages/eth_utils/conversions.py", line 115, in to_text
    raise TypeError("Expected an int, bytes, bytearray or hexstr.")

TypeError: Expected an int, bytes, bytearray or hexstr.

```

**Comment by drandreaskrueger** [comment]
Your 
```
@validate_conversion_arguments
def to_text(primitive=None, hexstr=None, text=None):
    if hexstr is not None:
        return to_bytes(hexstr=hexstr).decode('utf-8')
    elif text is not None:
        return text
    elif isinstance(primitive, str):
        return to_text(hexstr=primitive)
    elif isinstance(primitive, (bytes, bytearray)):
        return primitive.decode('utf-8')
    elif is_integer(primitive):
        byte_encoding = int_to_big_endian(primitive)
        return to_text(byte_encoding)
    print (type(primitive))
    raise TypeError("Expected an int, bytes, bytearray or hexstr.")
```
is incomplete?

because the `print (type(primitive))` gives me:

    <class 'list'>

for a

    print (w3.eth.accounts)


-----------

should I perhaps NOT use the `latest` version?

http://web3py.readthedocs.io/en/latest/releases.html says last stable is 4.0.0   
do you still trust that version?

**Comment by drandreaskrueger** [comment]
I have now also tried `web3 4.0.0`, and deleted the `w3.eth.defaultAccount = w3.eth.accounts[0]` but then it runs into the exact same problem at  `tx_hash = Greeter.constructor().transact()` --> `TypeError: Expected an int, bytes, bytearray or hexstr.`

Web3.py is broken.

**Comment by drandreaskrueger** [comment]
In short:

Please update your `latest` [contracts.html#contract-deployment-example](http://web3py.readthedocs.io/en/latest/contracts.html#contract-deployment-example) into something that actually works with your 'latest' code, and don't forget to give the exact dependency versioning: `pip3 install web3[tester]==4.0.0 py-solc==x.y.z web3==x.y.z eth-testrpc==x.y.z`

Thanks a lot!

**Comment by dangell7** [comment]
@drandreaskrueger 

change the line 

```
w3 = Web3(Web3.EthereumTesterProvider())
```

to 

```
w3 = Web3(TestRPCProvider())
```

This will fix your problem. 

@carver Can you change the docs to reflect this? Seems that the `EthereumTesterProvider()` is being imported, however, the docs are pointing the user to use the TestRPC at the top...

**Comment by dangell7** [comment]
Also, @drandreaskrueger fyi

```
mkvirtualenv samypubnet
pip install web3
pip install py-solc
pip install eth-testrpc
pip install rlp==0.6.0
pip freeze > requirements.txt
```

**Comment by drandreaskrueger** [comment]
Fantastic, thanks a lot, @dangell7 and @carver 

[This version](https://gitlab.com/electronDLT/chainhammer/blob/a9e38d137444986c822bc621ae9cd5bb01a9cfa8/DeployContractExample.py) is now working perfectly.

Thanks!

**Comment by drandreaskrueger** [comment]
Is there an easy way to link to a matching version of the readthedocs

https://web3py.readthedocs.io/en/v4.2.0/

instead of linking to 

http://web3py.readthedocs.io/en/latest/contracts.html#contract-deployment-example

because `latest` will be a moving target ;-)

---

To prevent such problems in the future, I have now fixed the `pip install ...` [versions like this](https://gitlab.com/electronDLT/chainhammer/blob/a9e38d137444986c822bc621ae9cd5bb01a9cfa8/README.md#virtualenv-for-py3-dependencies-mostly-ethereum).

**Comment by drandreaskrueger** [comment]
> > Is there an easy way to link to a matching version v4.2.0 of the readthedocs  
> > https://web3py.readthedocs.io/en/v4.2.0/    
> > instead of linking to  
> > http://web3py.readthedocs.io/en/latest/contracts.html#contract-deployment-example  
> > because latest will be a moving target ;-)  

Your suggestion of moving from `latest` to `stable` doesn't help that at all:

> Once it's released, you can update to use  
> http://web3py.readthedocs.io/en/stable/contracts.html#contract-deployment-example

no, @carver that won't help 

because `/stable/` will also keep moving one day, and that will then break something new.

My experience tells me: In Ethereum, nothing is ever stable; interfaces keep on changing, examples stop working, etc.

---

The only way out is to use precise version numbers, e.g. 

http://web3py.readthedocs.io/en/v4.2.0/contracts.html#contract-deployment-example

or

http://web3py.readthedocs.io/en/v3.16.5/examples.html#looking-up-receipts

I do think it is easy, just configure your readthedocs differently, so that it keeps EACH version number.

**Comment by drandreaskrueger** [comment]
> glad to hear it!

yes, me too. Thanks for your bugfix!
