### ISSUE TITLE
AttributeError: module 'web3.manager' has no attribute 'request_blocking'

### ISSUE THREAD

**Issue by r0fls** [ethereum/web3.py#811]
* Version: 4.1.0
* Python: 3.6
* OS: osx

I received the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/raphael.deem/code/fig-lotto/drawing.py", line 119, in run_lotto
    lotto.distribute()
  File "/Users/raphael.deem/code/fig-lotto/drawing.py", line 97, in distribute
    Eth.sendTransaction({"from": OWNER_ADDRESS, "to": wallet, "value": 1_000_000_000_000_000_000*amount/rate, "gas": 420000})
  File "/usr/local/lib/python3.6/site-packages/web3/eth.py", line 250, in sendTransaction
    return self.web3.manager.request_blocking(
AttributeError: module 'web3.manager' has no attribute 'request_blocking'
```

When executing the below code:

```python
Eth = web3.eth.Eth(web3)
Eth.sendTransaction({"from": OWNER_ADDRESS, "to": wallet, "value": 1_000_000_000_000_000_000*amount/rate, "gas": 420000})
```

I was connecting to a test node on the Ropsten network.

**Comment by voith** [comment]
You need to create a web3 instance:
```
from web3 import Web3
# choose any provider of your choice
web3 = Web3(Web3.IPCProvider())
web3.eth.sendTransaction({"from": OWNER_ADDRESS, "to": wallet, "value": 1_000_000_000_000_000_000*amount/rate, "gas": 420000})
```

**Comment by pipermerriam** [comment]
@voith FYI: We've been using the convention `w3` as the variable name for a web3 instance to reduce the likelyhood of confustion between the python module and an instance of the `Web3` object.

**Comment by pipermerriam** [comment]
@r0fls you should consider using `w3.toWei('1', 'ether')` for currency conversions.  Well tested to do the proper conversion and easier to read.
