### ISSUE TITLE
ImportError: cannot import name 'decode_hex' when import ethereum

### ISSUE THREAD

**Issue by FrancisJen** [ethereum/web3.py#813]
(py3interface-rXFxZXWO) bash-3.2$ python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ethereum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/renyiguang/.local/share/virtualenvs/py3interface-rXFxZXWO/lib/python3.6/site-packages/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/Users/renyiguang/.local/share/virtualenvs/py3interface-rXFxZXWO/lib/python3.6/site-packages/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/Users/renyiguang/.local/share/virtualenvs/py3interface-rXFxZXWO/lib/python3.6/site-packages/ethereum/utils.py", line 13, in <module>
    from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'

**Comment by ckcollab** [comment]
NOTE: fix is `pip install 'rlp==0.6.0'`
