### ISSUE TITLE
No module named web3.__main__; 'web3' is a package and cannot be directly executed`

### ISSUE THREAD

**Issue by Lvenkin2** [ethereum/web3.py#822]
* Version: 4.0.0
* Python: 3.6
* OS: linux Ubuntu 16.04
Im run
`python3 -m web3`
error

`/usr/local/bin/python3: No module named web3.__main__; 'web3' is a package and cannot be directly executed`

and 

` python3 /var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py`
Traceback (most recent call last):
 ```
 File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/usr/local/lib/python3.6/site-packages/web3/__init__.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/usr/local/lib/python3.6/zipfile.py", line 13, in <module>
    import shutil
  File "/usr/local/lib/python3.6/shutil.py", line 22, in <module>
    import bz2
  File "/usr/local/lib/python3.6/bz2.py", line 19, in <module>
    from threading import RLock
  File "/usr/local/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/local/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.6/tokenize.py", line 35, in <module>
    from token import *
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/usr/local/lib/python3.6/site-packages/web3/providers/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/web3/providers/base.py", line 4, in <module>
    from eth_utils import (
  File "/usr/local/lib/python3.6/site-packages/eth_utils/__init__.py", line 97, in <module>
    __version__ = pkg_resources.get_distribution("eth-utils").version
AttributeError: module 'pkg_resources' has no attribute 'get_distribution'
```
I can not do 10 days. Once it happened, but after a few hours it stopped working. help me please

**Comment by voith** [comment]
@Lvenkin2 AFAIU,  web3 is not meant to used as command line utility. Hence there is no `__main__.py` file. 

I'm not very sure about your second error, but seems more likely an issue with your version. Can you  check if upgrading your web3 version solves the issue for you? `pip install 'web3==4.2.0'`

**Comment by Lvenkin2** [comment]
im run 
`pip3 iinstall --upgrade web3==4.2.0`
after
`
python3 /var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py 0xB8aAc54a27d40e5D71A43f114e3E5ad53071735d 1`

but 

```
Traceback (most recent call last):
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/usr/local/lib/python3.6/site-packages/web3/__init__.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/usr/local/lib/python3.6/zipfile.py", line 13, in <module>
    import shutil
  File "/usr/local/lib/python3.6/shutil.py", line 22, in <module>
    import bz2
  File "/usr/local/lib/python3.6/bz2.py", line 19, in <module>
    from threading import RLock
  File "/usr/local/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/local/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.6/tokenize.py", line 35, in <module>
    from token import *
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/usr/local/lib/python3.6/site-packages/web3/providers/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/web3/providers/base.py", line 4, in <module>
    from eth_utils import (
  File "/usr/local/lib/python3.6/site-packages/eth_utils/__init__.py", line 97, in <module>
    __version__ = pkg_resources.get_distribution("eth-utils").version
AttributeError: module 'pkg_resources' has no attribute 'get_distribution'
```

**Comment by Lvenkin2** [comment]
error I have on 3 computers ... maybe I'm missing something?
im install 
python3.6
pip3

**Comment by voith** [comment]
just taking a random guess here:
Are you using the latest version of pip and setuptools?
`pip3 install --upgrade pip3`
`pip3 install --upgrade setuptools`
Try the above listed commands and then retry installing web3

**Comment by Lvenkin2** [comment]
```
root@1:/home/ubuntu/web3.py# pip3 install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1

```

and 

```
root@1:/home/ubuntu/web3.py# pip3 install --upgrade setuptools
Requirement already up-to-date: setuptools in /usr/local/lib/python3.6/site-packages (39.1.0)
ethereum-tester 0.1.0b2 requires ethereum-keys>=0.1.0-alpha.7, which is not installed.
erc20token 0.1.8 requires ethereum-keys==0.1.0a7, which is not installed.
two1 3.10.9 has requirement base58==0.2.2, but you'll have base58 0.2.1 which is incompatible.
two1 3.10.9 has requirement requests<=2.11.1, but you'll have requests 2.18.4 which is incompatible.
py-evm 0.2.0a16 has requirement web3<5.0.0,>=4.1.0, but you'll have web3 3.11.1 which is incompatible.
ethtoken 0.0.1a3 has requirement web3~=4.0b7, but you'll have web3 3.11.1 which is incompatible.
ethereum-tester 0.1.0b2 has requirement cytoolz==0.8.2, but you'll have cytoolz 0.9.0.1 which is incompatible.
erc20token 0.1.8 has requirement ethereum-utils==0.6.0, but you'll have ethereum-utils 0.6.2 which is incompatible.
erc20token 0.1.8 has requirement web3>=3.16.3, but you'll have web3 3.11.1 which is incompatible.
```
when I start to install the dependencies, they are restored and so in a circle. For example, I set base58 == 0.2.2 after which requests <= 2.11.1 and base58 == 0.2.1 will become ...

**Comment by Lvenkin2** [comment]
new error

```
root@1:/home/ubuntu/web3.py# python3 /var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py 0xB8aAc54a27d40e5D71A43f114e3E5ad53071735d 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/zipfile.py", line 18, in <module>
    import threading
  File "/usr/local/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/local/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.6/tokenize.py", line 35, in <module>
    from token import *
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/usr/local/lib/python3.6/site-packages/web3/providers/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/web3/providers/base.py", line 4, in <module>
    from eth_utils import (
ImportError: cannot import name 'to_bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/usr/local/lib/python3.6/site-packages/web3/__init__.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/usr/local/lib/python3.6/zipfile.py", line 20, in <module>
    import dummy_threading as threading
  File "/usr/local/lib/python3.6/dummy_threading.py", line 45, in <module>
    import threading
  File "/usr/local/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/local/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.6/tokenize.py", line 35, in <module>
    from token import *
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/usr/local/lib/python3.6/site-packages/web3/providers/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/web3/providers/base.py", line 4, in <module>
    from eth_utils import (
ImportError: cannot import name 'to_bytes'

```

**Comment by voith** [comment]
Now you seem to be on a older version of `eth-utils`. 
`pip install --upgrade eth-utils`.
I think you're having this  problem because you installed an older version  of `web3.py` previously. 
Can you create a new `virtualenv` and install web3 in it?

**Comment by carver** [comment]
Ah, it seems your OS is managing your setuptools version, so the pip upgrade may not have an effect. What OS are you on? Also, what is the result of `pip list | grep setuptools`?

**Comment by Lvenkin2** [comment]
`setuptools        39.1.0`

**Comment by Lvenkin2** [comment]
@carver any idea?

**Comment by pipermerriam** [comment]
@Lvenkin2 It's not clear to me what you are trying to do, however, in the code snippets you've pasted I see a mix of `pip` and `pip3` invocations indicating that you might be mixing between different python environments.

I would suggest the following workflow.

1. create a new virtual environment and activate it.
2. verify that the `pip` or `pip3` that you are using is from the virtual environment with `which pip` or `which pip3` depending on which one you are using.
3. verify that `setuptools` and `pip` are updated with `pip install --upgrade setuptools pip` (or with `pip3` if that's what you are using)
4. run the fresh install of web3 (or whatever it is that you're installing)
5. see if it worked?

**Comment by Lvenkin2** [comment]
@pipermerriam 

```
 virtualenv venvnew
Using base prefix '/usr/local'
New python executable in /home/ubuntu/venvnew/bin/python3.6
Also creating executable in /home/ubuntu/venvnew/bin/python
Installing setuptools, pip, wheel...done.
ubuntu@1:~$ . venvnew/bin/activate
(venvnew) ubuntu@1:~$ which pip
/home/ubuntu/venvnew/bin/pip
(venvnew) ubuntu@1:~$ python -V
Python 3.6.5
(venvnew) ubuntu@1:~$
(venvnew) ubuntu@1:~$ pip install web3

(venvnew) ubuntu@1:~$ python /var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py 0xB8aAc54a27d40e5D71A43f114e3E5ad53071735d 1


(venvnew) ubuntu@1:~$ python /var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py 0xB8aAc54a27d40e5D71A43f114e3E5ad53071735d 1
Traceback (most recent call last):
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/web3/__init__.py", line 1, in <module>
    import pkg_resources
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/usr/local/lib/python3.6/zipfile.py", line 13, in <module>
    import shutil
  File "/home/ubuntu/venvnew/lib/python3.6/shutil.py", line 22, in <module>
    import bz2
  File "/usr/local/lib/python3.6/bz2.py", line 19, in <module>
    from threading import RLock
  File "/usr/local/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/local/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/home/ubuntu/venvnew/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/home/ubuntu/venvnew/lib/python3.6/tokenize.py", line 35, in <module>
    from token import *
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/web3/providers/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/web3/providers/base.py", line 4, in <module>
    from eth_utils import (
  File "/home/ubuntu/venvnew/lib/python3.6/site-packages/eth_utils/__init__.py", line 97, in <module>
    __version__ = pkg_resources.get_distribution("eth-utils").version
AttributeError: module 'pkg_resources' has no attribute 'get_distribution'

```

**Comment by pipermerriam** [comment]
that's a bash error.  you should be running that in a python repl.

```
$ python -c "import pkg_resources; print(pkg_resources.__dict__.keys())
```

**Comment by Lvenkin2** [comment]
first instance ubuntu 16.04 - ec2 amazon
```
root@1:/home/ubuntu# python3 python -c "import pkg_resources; print(pkg_resources.__dict__.keys())
>

```
second instance ubuntu 18.04
```
root@sd-122416:/home/ubuntu# python -c "import pkg_resources; print(pkg_resources.__dict__.keys())
>

```

**Comment by Lvenkin2** [comment]
first
```

```
(venvnew) ubuntu@1:~$ python -c "import pkg_resources; print(pkg_resources.__dict__.keys())"
dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', 'absolute_import', 'sys', 'os', 'io', 'time', 're', 'types', 'zipfile', 'zipimport', 'warnings', 'stat', 'functools', 'pkgutil', 'operator', 'platform', 'collections', 'plistlib', 'email', 'errno', 'tempfile', 'textwrap', 'itertools', 'inspect', 'get_importer', '_imp', 'extern', '_vendor', 'six', 'urllib', 'map', 'filter', 'utime', 'mkdir', 'rename', 'unlink', 'WRITE_SUPPORT', 'os_open', 'isdir', 'split', 'importlib_machinery', 'py31compat', 'appdirs', 'packaging', 'require', 'working_set', 'add_activation_listener', 'resources_stream', 'cleanup_resources', 'resource_dir', 'resource_stream', 'set_extraction_path', 'resource_isdir', 'resource_string', 'iter_entry_points', 'resource_listdir', 'resource_filename', 'resource_exists', '_distribution_finders', '_namespace_handlers', '_namespace_packages', 'PEP440Warning', 'parse_version', '_state_vars', '_declare_state', '__getstate__', '__setstate__', '_sget_dict', '_sset_dict', '_sget_object', '_sset_object', '_sget_none', '_sset_none', 'get_supported_platform', '__all__', 'ResolutionError', 'VersionConflict', 'ContextualVersionConflict', 'DistributionNotFound', 'UnknownExtra', '_provider_factories', 'PY_MAJOR', 'EGG_DIST', 'BINARY_DIST', 'SOURCE_DIST', 'CHECKOUT_DIST', 'DEVELOP_DIST', 'register_loader_type', 'get_provider', '_macosx_vers', '_macosx_arch', 'get_build_platform', 'macosVersionString', 'darwinVersionString', 'get_platform', 'compatible_platforms', 'run_script', 'run_main', 'get_distribution', 'load_entry_point', 'get_entry_map', 'get_entry_info', 'IMetadataProvider', 'IResourceProvider', 'WorkingSet', '_ReqExtras', 'Environment', 'AvailableDistributions', 'ExtractionError', 'ResourceManager', 'get_default_cache', 'safe_name', 'safe_version', 'safe_extra', 'to_filename', 'invalid_marker', 'evaluate_marker', 'NullProvider', 'EggProvider', 'DefaultProvider', 'EmptyProvider', 'empty_provider', 'ZipManifests', 'MemoizedZipManifests', 'ZipProvider', 'FileMetadata', 'PathMetadata', 'EggMetadata', 'register_finder', 'find_distributions', 'find_eggs_in_zip', 'find_nothing', '_by_version_descending', 'find_on_path', 'dist_factory', 'NoDists', 'safe_listdir', 'distributions_from_metadata', 'non_empty_lines', 'resolve_egg_link', 'register_namespace_handler', '_handle_ns', '_rebuild_mod_path', 'declare_namespace', 'fixup_namespace_packages', 'file_ns_handler', 'null_ns_handler', 'normalize_path', '_normalize_cached', '_is_egg_path', '_is_unpacked_egg', '_set_parent_ns', 'yield_lines', 'MODULE', 'EGG_NAME', 'EntryPoint', '_remove_md5_fragment', '_version_from_file', 'Distribution', 'EggInfoDistribution', 'DistInfoDistribution', '_distributionImpl', 'issue_warning', 'RequirementParseError', 'parse_requirements', 'Requirement', '_always_object', '_find_adapter', 'ensure_directory', '_bypass_ensure_directory', 'split_sections', '_mkstemp', '_call_aside', '_manager', 'cached_files', 'extraction_error', 'extraction_path', 'get_cache_path', 'postprocess', '_initialize', '_initialize_master_working_set'])

second

root@sd-122416:/home/ubuntu# python3 -c "import pkg_resources; print(pkg_resources.__dict__.keys())"
dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', 'absolute_import', 'sys', 'os', 'io', 'time', 're', 'types', 'zipfile', 'zipimport', 'warnings', 'stat', 'functools', 'pkgutil', 'operator', 'platform', 'collections', 'plistlib', 'email', 'errno', 'tempfile', 'textwrap', 'itertools', 'inspect', 'get_importer', '_imp', 'extern', '_vendor', 'six', 'urllib', 'map', 'filter', 'utime', 'mkdir', 'rename', 'unlink', 'WRITE_SUPPORT', 'os_open', 'isdir', 'split', 'importlib_machinery', 'py31compat', 'appdirs', 'packaging', 'require', 'working_set', 'add_activation_listener', 'resources_stream', 'cleanup_resources', 'resource_dir', 'resource_stream', 'set_extraction_path', 'resource_isdir', 'resource_string', 'iter_entry_points', 'resource_listdir', 'resource_filename', 'resource_exists', '_distribution_finders', '_namespace_handlers', '_namespace_packages', 'PEP440Warning', 'parse_version', '_state_vars', '_declare_state', '__getstate__', '__setstate__', '_sget_dict', '_sset_dict', '_sget_object', '_sset_object', '_sget_none', '_sset_none', 'get_supported_platform', '__all__', 'ResolutionError', 'VersionConflict', 'ContextualVersionConflict', 'DistributionNotFound', 'UnknownExtra', '_provider_factories', 'PY_MAJOR', 'EGG_DIST', 'BINARY_DIST', 'SOURCE_DIST', 'CHECKOUT_DIST', 'DEVELOP_DIST', 'register_loader_type', 'get_provider', '_macosx_vers', '_macosx_arch', 'get_build_platform', 'macosVersionString', 'darwinVersionString', 'get_platform', 'compatible_platforms', 'run_script', 'run_main', 'get_distribution', 'load_entry_point', 'get_entry_map', 'get_entry_info', 'IMetadataProvider', 'IResourceProvider', 'WorkingSet', '_ReqExtras', 'Environment', 'AvailableDistributions', 'ExtractionError', 'ResourceManager', 'get_default_cache', 'safe_name', 'safe_version', 'safe_extra', 'to_filename', 'invalid_marker', 'evaluate_marker', 'NullProvider', 'EggProvider', 'DefaultProvider', 'EmptyProvider', 'empty_provider', 'ZipManifests', 'MemoizedZipManifests', 'ZipProvider', 'FileMetadata', 'PathMetadata', 'EggMetadata', 'register_finder', 'find_distributions', 'find_eggs_in_zip', 'find_nothing', '_by_version_descending', 'find_on_path', 'dist_factory', 'NoDists', 'safe_listdir', 'distributions_from_metadata', 'non_empty_lines', 'resolve_egg_link', 'register_namespace_handler', '_handle_ns', '_rebuild_mod_path', 'declare_namespace', 'fixup_namespace_packages', 'file_ns_handler', 'null_ns_handler', 'normalize_path', '_normalize_cached', '_is_egg_path', '_is_unpacked_egg', '_set_parent_ns', 'yield_lines', 'MODULE', 'EGG_NAME', 'EntryPoint', '_remove_md5_fragment', '_version_from_file', 'Distribution', 'EggInfoDistribution', 'DistInfoDistribution', '_distributionImpl', 'issue_warning', 'RequirementParseError', 'parse_requirements', 'Requirement', '_always_object', '_find_adapter', 'ensure_directory', '_bypass_ensure_directory', 'split_sections', '_mkstemp', '_call_aside', '_manager', 'cached_files', 'extraction_error', 'extraction_path', 'get_cache_path', 'postprocess', '_initialize', '_initialize_master_working_set'])

```
```

**Comment by pipermerriam** [comment]
Both of those have a `get_distribution`.  You've got something wrong with your python install, modules, or something, but this looks very unlikely to be a bug with web3.py.
