### ISSUE TITLE
please help configure python/server for web3

### ISSUE THREAD

**Issue by Lvenkin2** [ethereum/web3.py#833]
* Version: 4.2
* Python: 3.6
* OS: linux

im run
`python3 -m web3`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/site-packages/web3/__init__.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/usr/local/lib/python3.6/zipfile.py", line 13, in <module>
    import shutil
  File "/usr/local/lib/python3.6/shutil.py", line 22, in <module>
    import bz2
  File "/usr/local/lib/python3.6/bz2.py", line 19, in <module>
    from threading import RLock
  File "/usr/local/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/local/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.6/tokenize.py", line 35, in <module>
    from token import *
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/usr/local/lib/python3.6/site-packages/web3/providers/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/web3/providers/base.py", line 4, in <module>
    from eth_utils import (
  File "/usr/local/lib/python3.6/site-packages/eth_utils/__init__.py", line 97, in <module>
    __version__ = pkg_resources.get_distribution("eth-utils").version
AttributeError: module 'pkg_resources' has no attribute 'get_distribution'

```

**Comment by Lvenkin2** [comment]
pip3 freeze
```

aiohttp==2.3.10
alabaster==0.7.10
anyconfig==0.9.4
apipkg==1.4
appdirs==1.4.3
argh==0.26.2
arrow==0.12.1
asn1crypto==0.24.0
async-lru==0.1.0
async-timeout==3.0.0
attrdict==2.0.0
attrs==18.1.0
Babel==2.5.3
backcall==0.1.0
backoff==1.5.0
base58==0.2.2
bitcoin==1.1.42
bumpversion==0.5.3
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.6
coincurve==7.1.0
colorama==0.3.9
configparser==3.5.0
contextlib2==0.5.5
coverage==4.5.1
cryptography==2.2.2
Cython==0.28.2
cytoolz==0.9.0.1
decorator==4.3.0
docker-py==1.8.0
docopt==0.6.2
docutils==0.14
ecdsa==0.11
entrypoints==0.2.3
eth-abi==1.0.0
eth-account==0.2.2
eth-bloom==1.0.0
eth-hash==0.1.2
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b24
eth-utils==1.0.2
ethereum==2.3.1
execnet==1.5.0
flake8==3.5.0
flaky==3.4.0
funcsigs==1.0.2
future==0.16.0
gevent==1.2.2
geventhttpclient==1.3.1
greenlet==0.4.13
hexbytes==0.1.0
httplib2==0.11.3
hypothesis==3.53.0
idna==2.6
idna-ssl==1.0.1
imagesize==1.0.0
ipython==6.3.1
ipython-genutils==0.2.0
jedi==0.12.0
jeepney==0.3.1
Jinja2==2.10
json-rpc==1.11.0
jsonrpcclient==2.0.1
jsonrpcserver==3.1.1
jsonschema==2.6.0
keyring==12.2.0
keyrings.alt==2.2
launchpadlib==1.10.5
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
mccabe==0.6.1
mnemonic==0.13
mock==2.0.0
more-itertools==4.1.0
multidict==4.3.1
numpy==1.14.3
oauth==1.0.1
olefile==0.45.1
packaging==17.1
parsimonious==0.8.0
parso==0.2.0
path.py==11.0.1
pathtools==0.1.2
pbkdf2==1.3
pbr==4.0.2
pexpect==4.5.0
pickleshare==0.7.4
Pillow==5.1.0
pluggy==0.6.0
plyvel==1.0.4
prompt-toolkit==1.0.15
protobuf==3.0.0a3
ptyprocess==0.5.2
pusherclient==0.3.0
py==1.5.3
py-ecc==1.4.2
py-geth==2.0.1
py-solc==2.1.0
pyaes==1.6.1
pycodestyle==2.3.1
pycparser==2.18
pycrypto==2.6.1
pycryptodome==3.6.1
pyethash==0.1.27
pyflakes==1.6.0
Pygments==2.2.0
pylru==1.0.9
PyMySQL==0.8.1
pyparsing==2.2.0
pysha3==1.0.2
pystan==2.17.1.0
pytest==3.2.5
pytest-forked==0.2
pytest-mock==1.10.0
pytest-pythonpath==0.7.2
pytest-watch==4.1.0
pytest-xdist==1.22.2
python-dateutil==2.7.2
python-debian==0.1.30
pytz==2018.4
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
scrypt==0.8.6
SecretStorage==2.3.1
semantic-version==2.6.0
sha256==0.1
simplegeneric==0.8.1
simplejson==3.11.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.7.4
sphinx-better-theme==0.1.5
sphinx-rtd-theme==0.3.1
sphinxcontrib-websupport==1.0.1
tabulate==0.8.2
testresources==2.0.1
toolz==0.9.0
toposort==1.5
tox==3.0.0
tqdm==4.23.2
traitlets==4.3.2
trie==1.3.6
typing==3.6.4
urllib3==1.22
virtualenv==15.2.0
wadllib==1.3.2
watchdog==0.8.3
wcwidth==0.1.7
web3==4.2.0
websocket==0.2.1
websocket-client==0.47.0
websockets==4.0.1
Werkzeug==0.14.1
when-changed==0.3.0
yarl==1.2.4
zipfile2==0.0.12
zipfile36==0.1.3
zope.interface==4.3.2
root@1:/home/ubuntu/Desktop/ico# pip3 freeze
aiohttp==2.3.10
alabaster==0.7.10
anyconfig==0.9.4
apipkg==1.4
appdirs==1.4.3
argh==0.26.2
arrow==0.12.1
asn1crypto==0.24.0
async-lru==0.1.0
async-timeout==3.0.0
attrdict==2.0.0
attrs==18.1.0
Babel==2.5.3
backcall==0.1.0
backoff==1.5.0
base58==0.2.2
bitcoin==1.1.42
bumpversion==0.5.3
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.6
coincurve==7.1.0
colorama==0.3.9
configparser==3.5.0
contextlib2==0.5.5
coverage==4.5.1
cryptography==2.2.2
Cython==0.28.2
cytoolz==0.9.0.1
decorator==4.3.0
docker-py==1.8.0
docopt==0.6.2
docutils==0.14
ecdsa==0.11
entrypoints==0.2.3
eth-abi==1.0.0
eth-account==0.2.2
eth-bloom==1.0.0
eth-hash==0.1.2
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b24
eth-utils==1.0.2
ethereum==2.3.1
execnet==1.5.0
flake8==3.5.0
flaky==3.4.0
funcsigs==1.0.2
future==0.16.0
gevent==1.2.2
geventhttpclient==1.3.1
greenlet==0.4.13
hexbytes==0.1.0
httplib2==0.11.3
hypothesis==3.53.0
idna==2.6
idna-ssl==1.0.1
imagesize==1.0.0
ipython==6.3.1
ipython-genutils==0.2.0
jedi==0.12.0
jeepney==0.3.1
Jinja2==2.10
json-rpc==1.11.0
jsonrpcclient==2.0.1
jsonrpcserver==3.1.1
jsonschema==2.6.0
keyring==12.2.0
keyrings.alt==2.2
launchpadlib==1.10.5
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
mccabe==0.6.1
mnemonic==0.13
mock==2.0.0
more-itertools==4.1.0
multidict==4.3.1
numpy==1.14.3
oauth==1.0.1
olefile==0.45.1
packaging==17.1
parsimonious==0.8.0
parso==0.2.0
path.py==11.0.1
pathtools==0.1.2
pbkdf2==1.3
pbr==4.0.2
pexpect==4.5.0
pickleshare==0.7.4
Pillow==5.1.0
pluggy==0.6.0
plyvel==1.0.4
prompt-toolkit==1.0.15
protobuf==3.0.0a3
ptyprocess==0.5.2
pusherclient==0.3.0
py==1.5.3
py-ecc==1.4.2
py-geth==2.0.1
py-solc==2.1.0
pyaes==1.6.1
pycodestyle==2.3.1
pycparser==2.18
pycrypto==2.6.1
pycryptodome==3.6.1
pyethash==0.1.27
pyflakes==1.6.0
Pygments==2.2.0
pylru==1.0.9
PyMySQL==0.8.1
pyparsing==2.2.0
pysha3==1.0.2
pystan==2.17.1.0
pytest==3.2.5
pytest-forked==0.2
pytest-mock==1.10.0
pytest-pythonpath==0.7.2
pytest-watch==4.1.0
pytest-xdist==1.22.2
python-dateutil==2.7.2
python-debian==0.1.30
pytz==2018.4
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
scrypt==0.8.6
SecretStorage==2.3.1
semantic-version==2.6.0
sha256==0.1
simplegeneric==0.8.1
simplejson==3.11.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.7.4
sphinx-better-theme==0.1.5
sphinx-rtd-theme==0.3.1
sphinxcontrib-websupport==1.0.1
tabulate==0.8.2
testresources==2.0.1
toolz==0.9.0
toposort==1.5
tox==3.0.0
tqdm==4.23.2
traitlets==4.3.2
trie==1.3.6
typing==3.6.4
urllib3==1.22
virtualenv==15.2.0
wadllib==1.3.2
watchdog==0.8.3
wcwidth==0.1.7
web3==4.2.0
websocket==0.2.1
websocket-client==0.47.0
websockets==4.0.1
Werkzeug==0.14.1
when-changed==0.3.0
yarl==1.2.4
zipfile2==0.0.12
zipfile36==0.1.3
zope.interface==4.3.2
```

**Comment by Lvenkin2** [comment]
` python3 -c "import pkg_resources; print(pkg_resources.__dict__.keys())"`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/zipfile.py", line 18, in <module>
    import threading
  File "/usr/local/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/local/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.6/tokenize.py", line 35, in <module>
    from token import *
  File "/home/ubuntu/Desktop/ico/token.py", line 8, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/usr/local/lib/python3.6/site-packages/web3/__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "/usr/local/lib/python3.6/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/eth_account/account.py", line 10, in <module>
    from eth_keyfile import (
  File "/usr/local/lib/python3.6/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/eth_keyfile/keyfile.py", line 10, in <module>
    from eth_keys import keys
ImportError: cannot import name 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/usr/local/lib/python3.6/zipfile.py", line 20, in <module>
    import dummy_threading as threading
  File "/usr/local/lib/python3.6/dummy_threading.py", line 45, in <module>
    import threading
  File "/usr/local/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/local/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/lib/python3.6/tokenize.py", line 35, in <module>
    from token import *
  File "/home/ubuntu/Desktop/ico/token.py", line 8, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/usr/local/lib/python3.6/site-packages/web3/__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "/usr/local/lib/python3.6/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/eth_account/account.py", line 10, in <module>
    from eth_keyfile import (
  File "/usr/local/lib/python3.6/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/eth_keyfile/keyfile.py", line 10, in <module>
    from eth_keys import keys
ImportError: cannot import name 'keys'
```

**Comment by Lvenkin2** [comment]
fix python3 -c "import pkg_resources; print(pkg_resources.__dict__.keys())" and update post

**Comment by pipermerriam** [comment]
Web3 is a library intended to be used from python.  It has no API for use directly from the command line, thus invoking `python -m web3` isn't intended to be a supported feature or functionality.

**Comment by Lvenkin2** [comment]
please help

**Comment by carver** [comment]
Somehow your python environment is borked. You need to find a way to get setuptools & pip installed correctly.

This command must work before even worrying about anything ethereum-related (run it in your terminal):

```sh
python -c "import pkg_resources; pkg_resources.get_distribution; print('hooray!')"
```

This isn't exactly your problem, but some resources for debugging a broken environment:
https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

> `sudo apt-get install --reinstall python-pkg-resources`

Seems like something worth trying ^
