### ISSUE TITLE
Problem with from web3 import Web3

### ISSUE THREAD

**Issue by Park-jeong-seop** [ethereum/web3.py#837]
* Version: 4.2.1
* Python: 3.5
* OS: linux

### What was wrong?
```
from web3 import Web3
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pjs/bp_core_eth/venv/lib/python3.5/site-packages/web3/__init__.py", line 7, in <module>
    from eth_account import Account  # noqa: E402
  File "/home/pjs/bp_core_eth/venv/lib/python3.5/site-packages/eth_account/__init__.py", line 1, in <module>
    from eth_account.account import Account  # noqa: F401
  File "/home/pjs/bp_core_eth/venv/lib/python3.5/site-packages/eth_account/account.py", line 10, in <module>
    from eth_keyfile import (
  File "/home/pjs/bp_core_eth/venv/lib/python3.5/site-packages/eth_keyfile/__init__.py", line 7, in <module>
    from eth_keyfile.keyfile import (  # noqa: F401
  File "/home/pjs/bp_core_eth/venv/lib/python3.5/site-packages/eth_keyfile/keyfile.py", line 10, in <module>
    from eth_keys import keys
  File "/home/pjs/bp_core_eth/venv/lib/python3.5/site-packages/eth_keys/__init__.py", line 15, in <module>
    from .main import (  # noqa: F401
  File "/home/pjs/bp_core_eth/venv/lib/python3.5/site-packages/eth_keys/main.py", line 1, in <module>
    from typing import (Any, Union, Type)  # noqa: F401
ImportError: cannot import name 'Type'
```

**Comment by carver** [comment]
What is the full python version? I'll assume it is <3.5.2

`typing.Type` was added in 3.5.2 https://docs.python.org/3/library/typing.html#typing.Type

So you can either upgrade to a later python3.5 runtime (which you should anyway, bugfixes and such).

Or, you can use the backported typing library: https://pypi.org/project/typing/ Note that because it's a builtin library, you would have to play games to use the pip version instead of the builtin one, like: https://github.com/python/mypy/issues/1838#issuecomment-231539460

**Comment by Park-jeong-seop** [comment]
Thank you. this problem is solved.
my pyhon version is 3.5.1
I solved this problem by using module 'typing' in 'pip' instead of using module 'python 3.5.1'.
