### ISSUE TITLE
Retrieve Token Name And Decimals From Contract

### ISSUE THREAD

**Issue by webjunkie01** [ethereum/web3.py#843]
* Version: 4.0.2
* Python: 3.5
* OS: Linux

### What was wrong?

Hi, I would like to know if it's possible to retrieve the decimals, name and symbol from a contract. From the docs I can see you can get the address, but no decimals, name or symbol. I remember this was possible in version 3.13 and below.

Currently I can't with the following code

`token_contract =  web3.eth.contract(abi=token_abi,address=checksum_token_address)
 token_contract.functions.symbol() or token_contract.symbol()`

The node is fully synced but still I get this error. Even if I try with an infura node. eth-abi==1.0.0 (https://ropsten.infura.io/kXyhAH9YiDtxmZqFX3zS)

> Traceback (most recent call last):
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/web3/contract.py", line 1239, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/eth_abi/abi.py", line 63, in decode_abi
    return decoder(stream)
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/eth_abi/decoding.py", line 99, in __call__
    return self.decode(stream)
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/eth_abi/decoding.py", line 137, in decode
    yield decoder(stream)
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/eth_abi/decoding.py", line 99, in __call__
    return self.decode(stream)
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/eth_abi/decoding.py", line 162, in decode
    raw_data = cls.read_data_from_stream(stream)
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/eth_abi/decoding.py", line 244, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes
 The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
  File "top_tokens.py", line 90, in <module>
    get_tokens(URL)
  File "top_tokens.py", line 57, in get_tokens
    print(TokenContract.decimals())
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/web3/contract.py", line 783, in __call__
    return self.__prepared_function(*args, **kwargs)
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/web3/contract.py", line 796, in __prepared_function
    return getattr(self._function(*args), modifier)(modifier_dict)
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/web3/contract.py", line 1001, in call
    **self.kwargs)
  File "/Users/g/www/wallet-env-api35/lib/python3.5/site-packages/web3/contract.py", line 1261, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

**Comment by carver** [comment]
Since you closed the issue, I assume you've got it figured out :+1: 

There have been a lot of improvements since 4.0.2. I highly recommend an update to the latest: v4.2.1.
