### ISSUE TITLE
ENS error when using filters in private blockchain

### ISSUE THREAD

**Issue by artemistomaras** [ethereum/web3.py#870]
* Version: 4.2.1
* Python: 3.6
* OS: Ubuntu 17.10
* Private network: started with ``ganache-cli -d -p 7545 -i 999``

### What was wrong?
I've deployed the [ClaimsRegistry](https://github.com/uport-project/ethereum-claims-registry) contract and send some transactions to it.

When I try to get the events that fired using filters I get the following error:
```
claims_registry_address="0x59d3631c86BbE35EF041872d502F218A39FBa150"
claim_set_topic=b'\x8c\x9f\x895H\xe8B\x9f\x93R\xab\xa6i\x8eoM\xca.9\x06\x04\xf6\xe8\xc5\x88\x1azP]\x94\xaeP'

f = web3.eth.filter({'from': "1", "to": "11", "address": claims_registry_address, "topics": [claim_set_topic]})

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/eth.py", line 308, in filter
    [filter_params],
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/manager.py", line 103, in request_blocking
    response = self._make_request(method, params)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/manager.py", line 86, in _make_request
    return request_func(method, params)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/middleware/formatting.py", line 47, in apply_formatters
    formatted_params = formatter(params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/formatters.py", line 41, in apply_formatter_at_index
    yield formatter(item)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/rpc_abi.py", line 59, in apply_abi_formatters_to_dict
    [data[field] for field in fields],
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/abi.py", line 442, in map_abi_data
    return pipe(data, *pipeline)
  File "cytoolz/functoolz.pyx", line 589, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 565, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/abi.py", line 474, in data_tree_map
    return recursive_map(map_to_typed_data, data_tree)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/decorators.py", line 35, in wrapped
    wrapped_val = to_wrap(*args)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/formatters.py", line 115, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/formatters.py", line 102, in map_collection
    return datatype(map(func, collection))
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/formatters.py", line 114, in recurse
    return recursive_map(func, item)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/decorators.py", line 35, in wrapped
    wrapped_val = to_wrap(*args)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/formatters.py", line 116, in recursive_map
    return func(items_mapped)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/abi.py", line 471, in map_to_typed_data
    return ABITypedData(func(*elements))
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/normalizers.py", line 132, in abi_ens_resolver
    return (abi_type, validate_name_has_address(w3.ens, val))
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/utils/ens.py", line 29, in validate_name_has_address
    addr = ens.address(name, guess_tld=False)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/ens/main.py", line 86, in address
    return self.resolve(expanded, 'addr')
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/ens/main.py", line 178, in resolve
    resolver = self.resolver(normal_name)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/ens/main.py", line 187, in resolver
    resolver_addr = self.ens.resolver(name_to_hash(normal_name))
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/contract.py", line 813, in __call__
    return self.__prepared_function(*args, **kwargs)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/contract.py", line 826, in __prepared_function
    return getattr(self._function(*args), modifier)(modifier_dict)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/contract.py", line 1031, in call
    **self.kwargs)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/contract.py", line 1262, in call_contract_function
    return_data = web3.eth.call(call_transaction, block_identifier=block_id)
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/eth.py", line 270, in call
    [transaction, block_identifier],
  File "/home/artemis/.virtualenvs/uport_relay_server/lib/python3.6/site-packages/web3/manager.py", line 106, in request_blocking
    raise ValueError(response["error"])
ValueError: {'message': 'Attempting to run transaction which calls a contract function, but recipient address 0x314159265dD8dbb310642f98f50C066173C1259b is not a contract address', 'code': -32000, 'data': {'stack': 'n: Attempting to run transaction which calls a contract function, but recipient address 0x314159265dD8dbb310642f98f50C066173C1259b is not a contract address\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:4080983\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:4072923\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:542986\n    at e.exports.c.getCode (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:120503)\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:542936\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:4050262\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:4053941\n    at Object.return (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:4053600)\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:4051925\n    at e (/usr/lib/node_modules/ganache-cli/build/cli.node.js:2:4053889)\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:4053874\n    at /usr/lib/node_modules/ganache-cli/build/cli.node.js:2:4051064\n    at process._tickCallback (internal/process/next_tick.js:176:11)', 'name': 'n'}}

```

After reading the docs, it seems that the address ``0x314159265dD8dbb310642f98f50C066173C1259b`` is the address of the ENS on the ``mainnet``.

The question is why is this getting invoked when I am using a private blockchain?

**Comment by carver** [comment]
Which addresses are you hoping to see included in this filter for `from` and `to`?

`f = web3.eth.filter({'from': "1", "to": "11"...`

`"1"` and `"11"` don't look like addresses, so Web3.py is interpreting them as ENS names.

**Comment by artemistomaras** [comment]
It appears that I had a typo in my code,

the [correct](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter) arguments are ``fromBlock`` and ``toBlock``. Setting the correct argument names everything works as intended.

Thank you for your time!
