### ISSUE TITLE
JSON decoding some parity results using IPCProvider gives delimiter error

### ISSUE THREAD

**Issue by ankitchiplunkar** [ethereum/web3.py#881]
* Version: 4.2.1, fresh installed today from master branch
* Python: 3.6.5
* OS: ubuntu 18.04

### What was wrong?
web3.py was not able to decode result from parity.

```
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 36865 (char 36864)
```

Please include any of the following that are applicable:

* The code which produced the error
```
>>> from web3.auto import w3
>>> w3.eth.getBlock(3000090, True)
```

* The full output of the error

```
Traceback (most recent call last):
  File "/home/ankit/ether_sql/venv/src/web3/web3/utils/encoding.py", line 254, in json_decode
    decoded = json.loads(json_str)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 36865 (char 36864)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ankit/ether_sql/venv/src/web3/web3/eth.py", line 141, in getBlock
    [block_identifier, full_transactions],
  File "/home/ankit/ether_sql/venv/src/web3/web3/manager.py", line 107, in request_blocking
    response = self._make_request(method, params)
  File "/home/ankit/ether_sql/venv/src/web3/web3/manager.py", line 90, in _make_request
    return request_func(method, params)
  File "/home/ankit/ether_sql/venv/src/web3/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/ankit/ether_sql/venv/src/web3/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/home/ankit/ether_sql/venv/src/web3/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/ankit/ether_sql/venv/src/web3/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/ankit/ether_sql/venv/src/web3/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/ankit/ether_sql/venv/src/web3/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/ankit/ether_sql/venv/src/web3/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/home/ankit/ether_sql/venv/src/web3/web3/providers/auto.py", line 63, in make_request
    return self._proxy_request(method, params)
  File "/home/ankit/ether_sql/venv/src/web3/web3/providers/auto.py", line 76, in _proxy_request
    return provider.make_request(method, params)
  File "/home/ankit/ether_sql/venv/src/web3/web3/providers/ipc.py", line 179, in make_request
    response = self.decode_rpc_response(raw_response)
  File "/home/ankit/ether_sql/venv/src/web3/web3/providers/base.py", line 63, in decode_rpc_response
    return FriendlyJsonSerde().json_decode(text_response)
  File "/home/ankit/ether_sql/venv/src/web3/web3/utils/encoding.py", line 258, in json_decode
    raise ValueError(err_msg)

```

* What type of node you were connecting to.
Parity

### How can it be fixed?
?

Fill this section in if you know how this could or should be fixed.

**Comment by ankitchiplunkar** [comment]
I did some more testing and found that this error occurs only if I use the IPCProvider, does not occur with HTTP or WS providers.

```
>>> from web3 import Web3
>>> web3HTTP = Web3(Web3.HTTPProvider("http://127.0.0.1:8545"))
>>> web3IPC = Web3(Web3.IPCProvider())
>>> web3WS = Web3(Web3.WebsocketProvider("ws://127.0.0.1:8546"))
>>> 
>>> t = web3HTTP.eth.getBlock(3000090, True)
>>> t = web3WS.eth.getBlock(3000090, True)
>>> t = web3IPC.eth.getBlock(3000090, True)
Traceback (most recent call last):
  File "/home/ankit/ether_sql/venv/src/web3/web3/utils/encoding.py", line 254, in json_decode
    decoded = json.loads(json_str)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 36865 (char 36864)

During handling of the above exception, another exception occurred:
```

**Comment by ankitchiplunkar** [comment]
Upon more digging I found this Issue similar to 
Issue: https://github.com/ethereum/web3.py/issues/862
Pull request: https://github.com/ethereum/web3.py/pull/864

I will close this issue and move the discussion to earlier above posts.
