### ISSUE TITLE
Web3py with Ganache, sendTransaction error with data

### ISSUE THREAD

**Issue by PaulSka** [ethereum/web3.py#896]
* Version: 4.3.0
* Python: 3.6.2
* OS: linux

### What was wrong?

I use web3py with ganache docker (https://hub.docker.com/r/trufflesuite/ganache-cli/)

Using web3.eth.sendTransaction do some strange error with data

#### Example 1 GOOD
```
transact = web3.eth.sendTransaction({
   "from" : web3.eth.accounts[0],
    "data": web3.toHex(text="hello")
})
transact
HexBytes('0x8e6df4e5e1ae68bea789a453744ea0ee2a22949ef0fbea7ee279b3c2bd2dfd2c')
```

#### Example 2 GOOD
```
transact = web3.eth.sendTransaction({
   "from" : web3.eth.accounts[0],
    "data": web3.toHex(text="hEllo")
})
transact
HexBytes('0xf5dfeaa706f5c56bc1a501f1f9d58277995d52f62235e9104769b58055ae6c5e')
```
#### Example 3 ERROR
```
transact = web3.eth.sendTransaction({
   "from" : web3.eth.accounts[0],
    "data": web3.toHex(text="Hello")
})
transact
ValueError: {'message': 'VM Exception while processing transaction: invalid opcode', 'code': -32000, 'data': {'stack': 'c: VM Exception while processing transaction: invalid opcode\n    at Function.c.fromResults (/src/build/cli.node.js:2:349615)\n    at /src/build/cli.node.js:2:560937\n    at /src/build/cli.node.js:2:2029868\n    at /src/build/cli.node.js:2:125701\n    at /src/build/cli.node.js:2:111208\n    at o (/src/build/cli.node.js:2:114308)\n    at f (/src/build/cli.node.js:2:114230)\n    at /src/build/cli.node.js:2:114032\n    at /src/build/cli.node.js:2:125681\n    at /src/build/cli.node.js:2:2819698\n    at l (/src/build/cli.node.js:2:2820121)\n    at /src/build/cli.node.js:2:2820170\n    at t.default (/src/build/cli.node.js:2:2820438)\n    at /src/build/cli.node.js:2:2816635\n    at g.n.emit (/src/build/cli.node.js:2:2821138)\n    at /src/build/cli.node.js:2:2029834\n    at /src/build/cli.node.js:2:125620\n    at o (/src/build/cli.node.js:2:114322)\n    at f (/src/build/cli.node.js:2:114230)\n    at /src/build/cli.node.js:2:114032\n    at /src/build/cli.node.js:2:125681\n    at /src/build/cli.node.js:2:2029813\n    at /src/build/cli.node.js:2:2823920\n    at /src/build/cli.node.js:2:111208\n    at o (/src/build/cli.node.js:2:114308)\n    at /src/build/cli.node.js:2:114346\n    at Ut (/src/build/cli.node.js:2:123715)\n    at Object.<anonymous> (/src/build/cli.node.js:2:114435)\n    at /src/build/cli.node.js:2:2823841\n    at /src/build/cli.node.js:2:114032\n    at c (/src/build/cli.node.js:2:129079)\n    at /src/build/cli.node.js:2:2823793\n    at /src/build/cli.node.js:2:163697\n    at /src/build/cli.node.js:2:267232', 'name': 'c'}}
```

**Comment by dylanjw** [comment]
Sending a transaction with no "to" address is understood to be a contract creation transaction.  The data field is the contract initialization bytecode, so in the above three examples you are telling the EVM to create contracts using the following initialization bytecode:
```
>>> w3.toHex(text="hello")
'0x68656c6c6f'
>>> w3.toHex(text="hEllo")
'0x68456c6c6f'
>>> w3.toHex(text="Hello")
'0x48656c6c6f'
>>> 
```

The error is essentially saying that there is no such thing as opcode `0x48`, because it is trying to interpret your hex encoded text as evm bytecode.

**Comment by dylanjw** [comment]
Feel free to ask any questions or continue this discussion here, but I am going to close this issue because there is no bug.
