### ISSUE TITLE
Timeout Sending 50Transactions parallel to private network node

### ISSUE THREAD

**Issue by TimRi91** [ethereum/web3.py#916]
* Version: geth 1.8.11, go 1.10.2
* Python: 3.6
* OS: win

Due to some Latency-Measurements i send 50 Txs via python multiprocessing simultaneously to one of my three nodes, which are my private network.
After i get some results some error occurs and i don't know how to fix this timeout issue.

My Pythoncode:

```
import multiprocessing as mp
import time
import os
import socket
socket.timeout(100000)
from web3 import Web3
web3 = Web3(Web3.HTTPProvider("http://127.0.0.1:8545", request_kwargs={'timeout': 60}))

#Get Access to Coinbase-Account
web3.personal.unlockAccount(web3.eth.coinbase, 'xxxx')

#Testsetgröße
n = 50
output = mp.Queue()

#Function to transfer Token and measure Latency for each
def measure_Latency(output):
    tStart = time.time()
    hTx = web3.eth.sendTransaction({
        'from': web3.toChecksumAddress(web3.eth.coinbase),
        'to': web3.toChecksumAddress('0x4e3913e7fdaa548fbe60ebf330169ccc576ba1df'),
        'value': web3.toWei(1, 'ether')
        })
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
    tEnd = time.time()
    tResult = tEnd - tStart
    output.put(tResult)
    print("Latenz:",tResult, "Sekunden")

if __name__ == '__main__':
    for x in range(n):
        #init each transactionprocess
        MeasureInstances= mp.Process(target=measure_Latency, args=(output,))
        MeasureInstances.start()
    for x in range(n):
        #wait until each transaction is done
        MeasureInstances.join()
    results = [output.get() for x in range(n)]
    #write results in .txt-file
    filename = 'Latency_Testset'+str(n)+'_'+str(time.strftime("%d-%m-%Y_%H-%M-%S"))+'.txt'
    pathname = os.path.join('results', filename)
    file = open(pathname,'w')
    for x in range(len(results)):
        file.write('{:.9f}'.format(results[x]) + '\n')
    file.close()
```

My **geth** node command:
`geth --datadir "./node1" --networkid 2061 --port 30304 --nodiscover --rpc --rpcaddr 127.0.0.1 --rpcport 8545 --rpcapi="db,eth,net,web3,personal,web3" --ipcpath "./node1/geth.ipc" --mine --minerthreads 1 --gasprice "10000" --etherbase 0x6102b28607f48d8a07e720681f5b29d3efe86f64 --verbosity 3`

and the error in the console (after some latency outputs, the errors come up):

```
Latenz: 8.44599986076355 Sekunden
Latenz: 11.190999984741211 Sekunden
Latenz: 12.21500015258789 Sekunden
Latenz: 9.924000024795532 Sekunden
Latenz: 10.337000131607056 Sekunden
Latenz: 9.849999904632568 Sekunden
Latenz: 3.562000036239624 Sekunden
Latenz: 3.552000045776367 Sekunden
Latenz: 3.482999801635742 Sekunden
Latenz: 3.7960000038146973 Sekunden
Latenz: 4.638999700546265 Sekunden
Latenz: 3.865999937057495 Sekunden
Latenz: 3.318000078201294 Sekunden
Latenz: 1.763000249862671 Sekunden
Latenz: 1.38100004196167 Sekunden
Latenz: 0.8949997425079346 Sekunden
Latenz: 0.8599998950958252 Sekunden
Latenz: 6.541999816894531 Sekunden
Latenz: 4.79200005531311 Sekunden
Latenz: 11.622999906539917 Sekunden
Latenz: 8.452999830245972 Sekunden
Latenz: 6.266999959945679 Sekunden
Latenz: 8.97599983215332 Sekunden
Latenz: 15.140000104904175 Sekunden
Latenz: 10.835000038146973 Sekunden
Latenz: 16.598999977111816 Sekunden
Latenz: 10.031999826431274 Sekunden
Latenz: 11.551000118255615 Sekunden
Latenz: 15.663999795913696 Sekunden
Latenz: 14.134000301361084 Sekunden
Process Process-42:
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 67, in w
ait_for_transaction_receipt
    txn_receipt = web3.eth.getTransactionReceipt(txn_hash)
  File "C:\Python36\lib\site-packages\web3\eth.py", line 227, in getTransactionR
eceipt
    [transaction_hash],
  File "C:\Python36\lib\site-packages\web3\manager.py", line 110, in request_blo
cking
    raise ValueError(response["error"])
ValueError: {'code': -32600, 'message': 'read tcp 127.0.0.1:8545->127.0.0.1:5739
3: i/o timeout'}
Latenz: 42.62299966812134 Sekunden
Latenz: 44.347999811172485 Sekunden
Process Process-41:
Process Process-40:
Process Process-39:
Process Process-43:
Process Process-38:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
web3.utils.threads.Timeout: 120 seconds
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
web3.utils.threads.Timeout: 120 seconds
web3.utils.threads.Timeout: 120 seconds
web3.utils.threads.Timeout: 120 seconds
web3.utils.threads.Timeout: 120 seconds
Process Process-44:
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 67, in w
ait_for_transaction_receipt
    txn_receipt = web3.eth.getTransactionReceipt(txn_hash)
  File "C:\Python36\lib\site-packages\web3\eth.py", line 227, in getTransactionR
eceipt
    [transaction_hash],
  File "C:\Python36\lib\site-packages\web3\manager.py", line 110, in request_blo
cking
    raise ValueError(response["error"])
ValueError: {'code': -32600, 'message': 'read tcp 127.0.0.1:8545->127.0.0.1:5740
5: i/o timeout'}
Process Process-47:
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
web3.utils.threads.Timeout: 120 seconds
Process Process-46:
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
web3.utils.threads.Timeout: 120 seconds
Process Process-45:
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
web3.utils.threads.Timeout: 120 seconds
Process Process-48:
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
web3.utils.threads.Timeout: 120 seconds
Process Process-50:
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
web3.utils.threads.Timeout: 120 seconds
Process Process-49:
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\tmp\latency-v1.3.py", line 28, in measure_Latency
    web3.eth.waitForTransactionReceipt(web3.toHex(hTx))
  File "C:\Python36\lib\site-packages\web3\eth.py", line 222, in waitForTransact
ionReceipt
    return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
  File "C:\Python36\lib\site-packages\web3\utils\transactions.py", line 70, in w
ait_for_transaction_receipt
    _timeout.sleep(poll_latency)
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 68, in sleep
    self.check()
  File "C:\Python36\lib\site-packages\web3\utils\threads.py", line 61, in check
    raise self
web3.utils.threads.Timeout: 120 seconds
Traceback (most recent call last):
  File "latency-v1.3.py", line 44, in <module>
    results = [output.get() for x in range(n)]
  File "latency-v1.3.py", line 44, in <listcomp>
    results = [output.get() for x in range(n)]
  File "C:\Python36\lib\multiprocessing\queues.py", line 94, in get
    res = self._recv_bytes()
  File "C:\Python36\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "C:\Python36\lib\multiprocessing\connection.py", line 306, in _recv_bytes

    [ov.event], False, INFINITE)
KeyboardInterrupt

```

How can it be fixed?

**Comment by pipermerriam** [comment]
Web3.py is not threadsafe and will likely cause you problems if used in an async environment.

I recommend the ethereum stack exchange site if you're looking for more information on how you might accomplish this.  It looks like you may just be genuinely maxing out your node's capacity.

http://ethereum.stackexchange.com/questions
