### ISSUE TITLE
AttributeError: 'Web3' object has no attribute 'shh'

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/web3.py#933]
* Web3.py version: 4.2.1
* Python: 3.5.2
* OS: linux
* geth version: `1.8.0-unstable`
* I am running `geth` with `--shh` flag and `--rpcapi "admin,eth,net,web3,debug,shh"`

---------

    from web3 import Web3, HTTPProvider
    web3 = Web3(HTTPProvider('http://localhost:8545'))          
    
    print ("web3 =", web3.version.api) #4.2.1
    print(web3.shh) #error occurs

When I try to run following code above, I am having following error: 

    Traceback (most recent call last):
      File "dd.py", line 11, in <module>
        print(web3.shh)
    AttributeError: 'Web3' object has no attribute 'shh'

=> How could I fix this error?

**Comment by avatar-lavventura** [comment]
I am sorry to re-open this issue. With web3 version: `4.4.1`, I have started to have the same error. @voith 

My code:

```
from web3 import Web3, HTTPProvider
web3 = Web3(HTTPProvider('http://localhost:8545'))
from web3.shh import Shh
Shh.attach(web3, "shh")

# import time
print ("web3 =", web3.version.api)
print(web3.shh.info)
print(web3.shh)
```

Error I am having:

```
Traceback (most recent call last):
  File "whisper.py", line 8, in <module>
    print(web3.shh.info)
  File "/home/alper/eBlocBroker/venv/lib/python3.5/site-packages/web3/shh.py", line 16, in info
    return self.web3.manager.request_blocking("shh_info", [])
  File "/home/alper/eBlocBroker/venv/lib/python3.5/site-packages/web3/manager.py", line 110, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32601, 'message': 'The method shh_info does not exist/is not available'}
```
