### ISSUE TITLE
Traceback on Py 3 with missing provider and behavior 3.7+

### ISSUE THREAD

**Issue by oberstet** [ethereum/web3.py#980]
# traceback

I am interested in getting web3 running and usable from within a Twisted application, and ran into sth you might wanna investigate. when no provider is available, the auto detection bails out:

* python 3.7.0

```
(cpy370_1) oberstet@thinkpad-t430s:~/scm/oberstet/scratchbox/python/web3$ python test2.py 
Traceback (most recent call last):
  File "test2.py", line 4, in <module>
    print(w3.isConnected())
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/web3/main.py", line 178, in isConnected
    if provider.isConnected():
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/web3/providers/auto.py", line 70, in isConnected
    provider = self._get_active_provider(use_cache=True)
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/web3/providers/auto.py", line 86, in _get_active_provider
    if provider is not None and provider.isConnected():
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/web3/providers/base.py", line 77, in isConnected
    response = self.make_request('web3_clientVersion', [])
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/web3/providers/websocket.py", line 104, in make_request
    return future.result()
  File "/home/oberstet/cpy370/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/oberstet/cpy370/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/web3/providers/websocket.py", line 92, in coro_make_request
    async with self.conn as conn:
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/web3/providers/websocket.py", line 49, in __aenter__
    uri=self.endpoint_uri, loop=self.loop, **self.websocket_kwargs
  File "/home/oberstet/cpy370_1/lib/python3.7/site-packages/websockets/client.py", line 397, in __await__
    transport, protocol = yield from self._creating_connection
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_connection' was never awaited
(cpy370_1) oberstet@thinkpad-t430s:~/scm/oberstet/scratchbox/python/web3$ python -V
Python 3.7.0
```

* python 3.6.5

```
(cpy365_14) oberstet@thinkpad-t430s:~/scm/oberstet/scratchbox/python/web3$ python test2.py 
False
Traceback (most recent call last):
  File "test2.py", line 5, in <module>
    print(w3.eth.getBlock('latest'))
  File "/home/oberstet/cpy365_14/lib/python3.6/site-packages/web3/eth.py", line 141, in getBlock
    [block_identifier, full_transactions],
  File "/home/oberstet/cpy365_14/lib/python3.6/site-packages/web3/manager.py", line 107, in request_blocking
    response = self._make_request(method, params)
  File "/home/oberstet/cpy365_14/lib/python3.6/site-packages/web3/manager.py", line 99, in _make_request
    params,
web3.exceptions.UnhandledRequest: No providers responded to the RPC request:
method:eth_getBlockByNumber
params:['latest', False]

(cpy365_14) oberstet@thinkpad-t430s:~/scm/oberstet/scratchbox/python/web3$ python -V
Python 3.6.5
```

# behavior

I also noticed the different behavior on Py 3.7 and <3.7: on 3.7, it seems to use asyncio machinery and websocket under the hood. not on < 3.7

---

**Comment by oberstet** [comment]
test program used to trigger the traceback abvoe:

```python
#from web3.auto.infura import w3
from web3.auto import w3

print(w3.isConnected())
print(w3.eth.getBlock('latest'))
```

**Comment by voith** [comment]
@oberstet Firstly, web3 is not yet compatible with python3.7. The `websockets` error that you're getting with python3.7 is well known.

Looking at your second error I feel that you are not able to connect to the node. Since `auto` is getting connected to `websockets` before `http`, please check that you've enabled the correct settings on the node.

Also check if you're able to make a request through curl.

**Comment by oberstet** [comment]
sure I can connect. I posted the issue just to let you know where the traceback comes from on py37 ..

rgd `websockets`: sure, I want to use Autobahn anyways ..

**Comment by oberstet** [comment]
sure!

> this specific traceback might result from an unhandled initial connect error .. the connect future lacks an errback. no clue, best bet for this specific issue ..
