### ISSUE TITLE
Issue with filtering events without contract address

### ISSUE THREAD

**Issue by palango** [ethereum/web3.py#987]
* Version: 4.5.0, also happens on 4.2.0
* Python: 3.6
* OS: osx

### What was wrong?

I'm filtering events with a given ABI, independent of the emitting contract. The code is below. This worked but recently a new contract popped up (this is on ropsten testchain) whose events match but which cannot be decoded.

```
python test-event.py                                                                        18:05:22
filter for TokenNetworkCreated
{'fromBlock': 0, 'toBlock': 'latest'}
{'topics': ['0xf11a7558a113d9627989c5edf26cbd19143b7375248e621c8e30ac9e0847dc3f'], 'fromBlock': 0, 'toBlock': 'latest'}
Traceback (most recent call last):
  File "test-event.py", line 99, in <module>
    'TokenNetworkCreated',
  File "test-event.py", line 89, in get_events
    events = filter.get_all_entries()
  File "/Users/paul/Work/venv/lib/python3.6/site-packages/web3/utils/filters.py", line 110, in get_all_entries
    return self._format_log_entries(log_entries)
  File "/Users/paul/Work/venv/lib/python3.6/site-packages/web3/utils/filters.py", line 117, in _format_log_entries
    self.format_entry(log_entry) for log_entry in log_entries
  File "/Users/paul/Work/venv/lib/python3.6/site-packages/web3/utils/filters.py", line 117, in <listcomp>
    self.format_entry(log_entry) for log_entry in log_entries
  File "/Users/paul/Work/venv/lib/python3.6/site-packages/web3/utils/filters.py", line 162, in format_entry
    return self.log_entry_formatter(entry)
  File "/Users/paul/Work/venv/lib/python3.6/site-packages/web3/utils/events.py", line 171, in get_event_data
    len(log_topics),
ValueError: Expected 2 log topics.  Got 0
```

The code for which this happens is the following. I'm not sure if I'm doing something wrong with the filters or if this is an issue in web3.

```py
import functools
from typing import Dict, Union, List

from web3 import Web3, HTTPProvider
from web3.contract import get_event_data
from web3.utils.filters import construct_event_filter_params, LogFilter

# this is the problematic transaction
# tx_hash = '0x30601c175598a8182c49ba076d0edf09e508ff3e289874ccf7835379306f32b6'
# 
web3 = Web3(HTTPProvider('http://localhost:8545'))
# tx = web3.eth.getTransaction(tx_hash)
# print(tx)
# logs = web3.eth.getLogs({'fromBlock': 0, 'toBlock': 3755955, 'address': '0x598A3898Bd2764e649A7AcC3e59D37Dc794bFc0F'})
# print(logs)


def create_event_filter(
        web3: Web3,
        event_name: str,
        event_abi: Dict,
        filter_params: Dict = None,
) -> LogFilter:
    """Create filter object that tracks events emitted.

    Args:
        web3: A web3 client
        event_name: The name of the event to track
        event_abi: The ABI of the event to track
        filter_params: Other parameters to limit the events

    Returns:
        A LogFilter instance"""
    if filter_params is None:
        filter_params = {}
    filter_meta_params = dict(filter_params)

    print(filter_meta_params)

    data_filter_set, event_filter_params = construct_event_filter_params(
        event_abi,
        **filter_meta_params,
    )

    log_data_extract_fn = functools.partial(get_event_data, event_abi)

    print(event_filter_params)
    log_filter = web3.eth.filter(event_filter_params)

    log_filter.set_data_filters(data_filter_set)
    log_filter.log_entry_formatter = log_data_extract_fn
    log_filter.filter_params = event_filter_params

    return log_filter


def get_events(
        w3: Web3,
        abi,
        event_name: str,
        from_block: Union[int, str] = 0,
        to_block: Union[int, str] = 'latest',
) -> List:
    """Returns events emmitted by a contract for a given event name, within a certain range.

    Args:
        w3: A Web3 instance
        contract_manager: A contract manager
        contract_name: The name of the contract
        event_name: The name of the event
        from_block: The block to start search events
        to_block: The block to stop searching for events

    Returns:
        All matching events"""
    print('filter for', event_name)
    filter = create_event_filter(
        web3=w3,
        event_name=event_name,
        event_abi=abi,
        filter_params={
            'fromBlock': from_block,
            'toBlock': to_block,
        },
    )
    events = filter.get_all_entries()

    w3.eth.uninstallFilter(filter.filter_id)
    return events

ABI = {'anonymous': False, 'inputs': [{'indexed': True, 'name': 'token_address', 'type': 'address'}, {'indexed': True, 'name': 'token_network_address', 'type': 'address'}], 'name': 'TokenNetworkCreated', 'type': 'event'}

events = get_events(
    web3,
    ABI,
    'TokenNetworkCreated',  
)
```

### How can it be fixed?

All events that match the filters should be decoded.

**Comment by dylanjw** [comment]
We could add a try, catch when a matched event can't be decoded using the provided ABI.  Im not sure if it would be better in the case of an undecodable event to include it in the results or not.  Is there a reason you are not including the address?  Matching on just the event signature topic means you'll get results from any contract that used that event name, and there is no way to divine what the abi required to decode those entries is.

**Comment by palango** [comment]
>  Matching on just the event signature topic means you'll get results from any contract that used that event name, and there is no way to divine what the abi required to decode those entries would be.

Is that true? From what I see in the code internally `event_abi_to_log_topic` is called with the events ABI. This creates the `event_signature` from the ABI and includes the inputs to the event. So from my understanding events with the same name and same ABI of the inputs should always be decodeable.

**Comment by dylanjw** [comment]
You are correct.  I misspoke.  The event signature does include the arguments, but it does not include which arguments are indexed.  The error output seems to indicate that the event from the other contract differs in that the arguments are not indexed, even though the event signatures match.

**Comment by palango** [comment]
That makes sense. Thanks!
